README.md
Update to versions of PHP 5.5.1 have PCRE 8.34, which changes prep_ pattern matching, causing a Bug where Charts do not display.
See Bug report
I have replaced the pattern in JsCharts.php correcting a compilation error
I also added Kdevelop IDE files to .gitignore ( .kdev4 ), for my own convenience, but if others wish to use Kdevelop this might be useful.
Contributors agreement is in your inbox.
Hope this is useful
Thanks
Rick
=> Bug Fix for 1934

custom/include/MySugar/javascript/AddRemoveDashboardPages.js
The page was refreshed before the ajax POST request had the change to complete. Now the dialog waits till it succeeded it's request and then refreshes the page.
=> Fix for bug #122 Adding / removing tabs

include/utils/autoloader.php, include/utils/file_utils.php, modules/Administration/views/view.globalsearchsettings.php, modules/UpgradeWizard/end.php, modules/UpgradeWizard/silentUpgrade_step2.php
#103
AFAICT, the Sugar Search Engine is part of SugarCRM 7.x.  Either way, the CE lacks the necessary files.
Removing these references then stop the constant spam in the errorlog, caused by the creation of a logic hook that doesn't exist.
This PR just removes/comments out the references; it does not fix existing installations or hooks.
=> remove Sugar search engine references

custom/include/MySugar/MySugar.php
Full credit to this fix goes to adesimone from suiteforge.org:
https://suitecrm.com/forum/developer-help/1823-unable-to-add-dashlet-at-home-page-screen
Applied fix to my build and it works.
=> Update MySugar.php - fix for cannot add dashlets

modules/AOR_Reports/controller.php, modules/AOW_WorkFlow/controller.php
Dynamic Dropdown field type does not work the same in Workflow or AOR_Reports.
User should be allowed to select multiple values like the Dropdown field type.
See Bug 222:  Workflow doesn't work correctly with dynamic dropdowns bug
=> Dynamic Dropdown does not behave like Dropdown in Workflow or AOR_Reports

themes/SuiteR/tpls/login.tpl
If you login with incorrect details, it displays two error messages instead of one.
=> Remove double warning

include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php, include/generic/SugarWidgets/SugarWidgetSubPanelTopArchiveEmailButton.php, include/generic/SugarWidgets/SugarWidgetSubPanelTopButton.php, include/utils/file_utils.php, modules/Import/controller.php
Includes 2 commits that concern the compatibility to PHP 5.5
- Issue with strtolower for non-latin characters: they lead to characters that cannot be parsed by JSON. JSON doesn't accept non UTF-8 since PHP 5.5
- Issue with Module Builder/Studio concerning the creation of fields: Vardefs are being written and reread. The Zend op-cache causes the cached version to be read, instead of the newly written file
Please ignore the first two commits.
=> PHP 5.5 compatibility

modules/Administration/templates/themeConfigSettings.tpl
#410 
This issue has been fixed.
The problem was that php could not tell the difference between the save button or the button for the colour to be switched. 
simple fix was to rename the save/cancel button to something that php could understand
=> bug fix #410

modules/AOS_PDF_Templates/generatePdf.php
Tinymce places< p > tags around page breaks which can cause blank pages when generating a pdf
=> Update generatePdf.php to avoid blank pages

include/InlineEditing/inlineEditing.js
Proposed fix for issue #364 (click X icon to close redirects to bad url /undefined causing a 404 http error.
=> Fix for #364 Click X redirects to undefined 404

modules/UpgradeWizard/systemCheck.php
.git folder does not need to be checked for Upgrades.
=> Skip .git folder on file system checks

include/InlineEditing/inlineEditing.js
Inline editing does not respect link target attribute.
https://github.com/salesagility/SuiteCRM/issues/446
=> Fix for issue 446

modules/AOS_PDF_Templates/templateParser.php
The parse_template_bean method call only checks for enum and multi-enum. This causes the pdf template to show the enum key instead of value from the language . Added check for radio enum to translate the enum key.
=> PDF Template shows the key of the radio enum instead of the value

modules/Emails/EditViewArchive.html
There was an extra comma in the object that was causing the issue.  This has been removed and the calendar popup is now appearing without issue.
=> Closes bug #632

custom/Extension/modules/Cases/Ext/Vardefs/cases_aop_case_updates.php, modules/AOP_Case_Updates/Case_Updates.php
The change in cases_aop_case_updates.php stops the inline editing of the update (as advised by Jim).  The change to case_update.php stops the loading of call updates if the call id is null.  This was causing the system to retrieve any updates with a null case id to be returned.
=> This closes #625.  

include/database/DBManager.php, include/database/DBManagerFactory.php, include/database/MssqlManager.php, include/database/MysqlManager.php, include/database/MysqliManager.php, include/database/SqlsrvManager.php, include/utils.php
As per bug #130, this adds a generic function for strlen, substr, strtoupper, strtolower, strpos, strrpos which will call the mb_* equivalent when available, else it will default back to the general version. This has updated all of the references to either the generic or mb_* calls to the new version in utils.php.
=> Closes bug #130

modules/Tasks/metadata/detailviewdefs.php
In Tasks Module there's a bug, even if the task is completed the button "close" is still showing up in the options in detail view, this is a fix for it.
=> Fix "Close" button still showing

custom/modules/Connectors/controller.php, include/connectors/formatters/default/company_detail.js, jssource/src_files/include/connectors/formatters/default/company_detail.js
Correctly extended the custom Connectors controller to include functions from original controller. Fixed Connectors to display properly on all themes by adding a check for the destroy function on the display object (necessary because theme SuiteR return a display object of html code causing js error)
=> fixed Connectors: Modify Mapping and Connectors to work across all themes

include/language/en_us.lang.php
Avoid versions statements for public interface as its not useful.
Any version update will break translations!
=> Removing versions references from public strings

include/Dashlets/DashletGenericAutoRefresh.tpl, include/Dashlets/DashletGenericAutoRefreshDynamic.tpl
This fix adds a check for a null item before calling ".value".  This closes bug #774.
=> closes bug 774

modules/Administration/index.php
Default web dashlet as installed on a secure secure gives mixed context warning and blocks content from loading
=> correct http to https

themes/SuiteR/css/style.css
Fix for github issue: "SuiteR Responsive Theme navigation bar #569"
Added media query and css to show the nav bar correctly
=> css fix for github issue 569

modules/Home/Dashlets/iFrameDashlet/configure.tpl
As per http://stackoverflow.com/a/417184/3894683, setting to 2000 characters is a sensible upper bound.  I have tested this and it saves / loads the url at this length.
=> Closes  #805 by upping the limit the url limit from 255 to 2000

modules/Administration/language/en_us.lang.php, modules/Schedulers/_AddJobsHere.php, themes/SuiteR/css/colourSelector.php, themes/SuiteR/themedef.php
- This should fix the notification & search btn background, and the dashlet icons color.
- This removes the references to "custom" for #903
- Added the option "dashlet header text" to theme settings for #928
=> Fixed #739, #903, #928

include/InlineEditing/InlineEditing.php
This fixes the 500 error when rname is null and in tandem with commit 6b600b5e76bcdb5a6af018fa36f776bf54242354 closes bug #880
=> This stops the 500 error when a rname is null and closes bug #880

data/SugarBean.php
Fall back to the max_per_page value. These two values differing would cause broken pagination.
=> Closes #834.

modules/jjwg_Maps/language/en_us.lang.php
Duplicated lines: 
$mod_strings['LBL_CRON_URL'] = 'Cron URL:';
$mod_strings['LBL_CRON_URL'] = 'CRON URL';
Also Long lines turned into a single line to not break translation
=> Duplicated lines 'LBL_CRON_URL

modules/Home/quicksearchQuery.php
The quicksearchQuery::CONDITION_EQUAL dies if you are using a custom file as it is named quicksearchQueryCustom::CONDITION_EQUAL
=> Modify quick Search Query

modules/Schedulers/language/en_us.lang.php
global $sugar_config key moved to the end. This fix issue 748
Schedulers language file - global $sugar_config key removal · Issue #748 · salesagility/SuiteCRM - https://github.com/salesagility/SuiteCRM/issues/748
=> Schedulers - global key - Fix issue #748

modules/Import/language/en_us.lang.php
global $sugar_config key moved to the end. This fix issue 748
This is related with issue
https://github.com/salesagility/SuiteCRM/issues/748
=> Import - global key fix

modules/AOR_Reports/tpls/EditViewFooter.tpl
This will list the fields for the selected report module on edit page load.  This will always selected the first tree item (which is always the selected report module as per the getModuleTreeData method of aow_utils.php
=> Closes #951.  This will select the appropriate report module on edit page load.

modules/Calendar/CalendarDisplay.php, modules/Calendar/language/en_us.lang.php
This closes #409 as per the OP's suggestion of replacing the hard-coded values with the mod_strings value.
=> Closes #409 by removing the hard-coding of the labels

themes/SuiteR/css/colourSelector.php, themes/SuiteR/css/style.css
Fix for issue 585: #mobile_menu now gets its styles from colourSelector.php instead of style.css . Closes #585 .
=> Fix for issue 585: #mobile_menu now gets its styles from colourSelector.php instead of style.css . Closes #585 .

include/database/MssqlManager.php
This adjusts the pattern finder to include the string length and correctly adjusts the SQL Query and eliminating the Syntax Error for ORDER BY queries (main area affected was the Meetings Sub Panels).
=> Fixes Issue #946 - MSSQL ORDER BY Query Incorrect Syntax

jssource/src_files/modules/Calendar/Cal.js
This closes #973 by checking for null on the variable before setting properties.
=> Closes #973 by adding a check around the variable for null before caling the properties.

modules/AOS_Products_Quotes/Line_Items.php
The original code was stripping off the zero part of 10, 100, 1000, ... of the list item quantity when the currency significant digits field was set to 0.  This update will only remove the fractional part and the decimal point (whatever it has been specified to be in the locale settings) if the fractional part is composed purely of zeros.
=> This closes #598.

themes/Suite7/tpls/_head.tpl
In stock modules the title shows the object you are watching, not in custom modules. This fixes this.
Reference: http://forums.sugarcrm.com/f3/module-name-record-name-browser-title-87820/
=> Browser title not correct for custom modules - from gunnicom

modules/Administration/language/en_us.lang.php
modules/Administration/language
missing </strong> ending tag.
Long line enclosed in single quotes
=> missing </strong> - modules/Administration/language

modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.php
Fixed #1076.  This changes the click through value from the label to the key.  Fixed as per @emcrobert's suggestion.
=> Fixed #1076.  This changes the click through value from the label to the key.

include/SearchForm/tpls/header.tpl
Fixes #1050.  This allows for the enter key to cause a carriage return rather than posting the form for textareas within the search screen.
=> Fixes #1050.  This allows for enter to move the carriage return rather than activating the form for textareas within the search form

modules/Users/tpls/wizard.tpl
This update changes the documentation link in the wizard to point to the SuiteCRM userguides and it removes the Knowledge Base item.  These were both previously 404'ing by pointing to https://suitecrm.com/suitecrm-the-sugarcrm-fork.
=> Closes #1040.  Updates the documentation url and removes the knowledge base item to stop 404.

modules/SugarFeed/views/view.adminsettings.php
$currModule['label'] = $module was being overridden if $module is Facebook or Twitter.
Re-arranged the conditional to ensure it was set earlier if condition is met and avoid the Undefined Index in $currModule['label'] = $GLOBALS['app_list_strings']['moduleList'][$module];
=> Fix undefined index for Facebook and Twittter issue#1080

modules/Charts/Dashlets/OpportunitiesByLeadSourceByOutcomeDashlet/OpportunitiesByLeadSourceByOutcomeDashlet.php
Change tool tip to use the actual value rather than the label for the link (still displays label correctly).
=> fixes #1073 Issue with clicking through to data on Opportunities By Lead Source By Outcome Dashlet

modules/Calendar/CalendarGrid.php
Closes #1010.  This error was because it was expecting the time in h:ia format (e.g. 10:50am) but it was getting passed through as simply "10:50".  I have also modified the returned format to match that of the start time.
=> Closes #1010. The mobile calendar was 500'ing due to the $start_time variable not being created from DateTime::createFromFormat.

modules/Reminders/Reminder.php
Reminders for Calls and Meetings do not work correctly unless the user’s time zone is set to UTC. If the user’s time zone is set to say Europe (UTC+1) the reminder will trigger 1 hour later.
This was introduced as part of the Reminder enhancements for 7.4.3. It looks like code was copied from include/javascript/jsAlerts.php to modules/Reminders/Reminder.php, however the code in jsAlerts queried Call reminder datetime directly from the database using a query and thus the datetime returned was in UTC, whereas in Reminder.php the query was changed to use the Bean which returns time in the user’s time zone.
The checks performed against the current time were using nowDb() which returns UTC times. This fix changes to check against current time in the user’s time zone.
Originally found this …
=> Fix user time zone issue with reminder datetime. Fix for #766.

include/Smarty/plugins/function.sugar_button.php
Fixes #1057.  If the redirect view is the detailview but the id is empty, then redirect to the listview for the module.
=> Fixes #1057.  This will not redirect to the detail view if the id is empty.  It will go to the list view instead.

include/SugarObjects/forms/PersonFormBase.php
Fixed #1074.  This will only show the detailview link upon cancelling if the id is present.  Else it will go to the listview.
=> Fixed #1074.  This will only show the detailview link upon cancelling if the id is present.  Else it will go to the listview.

modules/AOR_Reports/AOR_Report.php, suitecrm_version.php
Issue #1065
Adding require_once reference "modules/AOR_Reports/aor_utils.php" into the constructor of AOR_Report()
After testing, There seems to have no signification implications as AOR_Report depends on this util package and there are no naming collisions.
=> Issue #1065: Hotfix

include/database/MysqliManager.php
MysqliManager.php replaced deprecated mysqli_client_encoding with mysqli_character_set_name
mysqli_character_set_name exists in both version 5 and 7
=> Fixed #816

include/InlineEditing/inlineEditing.js
Fixed #1105 In case of a link inline editing if(user_value != output_value) { would always be true as output_value contained HTML+value, even though user_value gets just textbox value without HTML
=> Fixed #1105 - link field editing confirmation message.

modules/Schedulers/Save.php
Fixed #1142 - basic Scheduler settings do not allow to specify  day_of_month or which month it should run on, so both of these options should be set to '*'; . These is especially important in case user moves from advanced to basic settings.
=> Fixed #1142 - set day_of_month and months to *

modules/Administration/language/en_us.lang.php, themes/SuiteR/css/colourSelector.php, themes/SuiteR/themedef.php
The Action menu buttons and the icons should actually be two separate issues. This fixes the action menu drop colour selection issues. Suggest opening a separate bug for the icon colour issues.
=> Fixed #682 Theme settings for supbanels menu + icons

modules/AOS_PDF_Templates/templateParser.php
If you use a quote or invoice templates that included the product image you have to have a product image for every product otherwise it will show an image load error since the URL in the img-tag is invalid.
This code change checks if there is an image for the product before creating the img-tag.
=> Avoid creating img tag if there is no product image

download.php
Fixed #1195 - because the module was created using Module Builder and it does not create any _cstm table, there is a need to check whether the field has _c extension.
=> Fixed #1195 - because the module was created using Module Builder and it does not create any _cstm table

include/InlineEditing/inlineEditing.js, include/language/en_us.lang.php
In relation to issue #1160. Making alert and confirm strings in inlineEditing.js translatable.
Added two labels:
* LBL_CONFIRM_CANCEL_INLINE_EDITING
* LBL_LOADING_ERROR_INLINE_EDITING
=> Fixed #1160: Translatable strings in Inline Editing

modules/DynamicFields/templates/Fields/TemplateField.php
Fixed #1170 - replaced htmlentities with htmlspecialchars in order to allow users to enter special language characters.
=> Fixed #1170 - replaced htmlentities with htmlspecialchars.

include/SugarFields/Fields/Bool/DetailView.tpl, include/SugarFields/Fields/Bool/EditView.tpl, include/SugarFields/Fields/Bool/InlineEdit.tpl, include/SugarFields/Fields/Bool/InlineEditView.tpl, include/SugarFields/Fields/Bool/ListView.tpl
The root cause of this is in the core sugarfield Bool. Where it sets the value="CHECKED" where as it should be: checked="checked". Tested it in a few random places and does not seem to have any negative effects on checkbox fields.
=> Fixed #123 Checkbox not displayed when exported to PDF

include/InlineEditing/InlineEditing.php
This checks if the vardef name is "assigned_user_name", if that is the case, it does not create a link for it.
=> Fixed #817 - Inline Editing: Relationship always displayed as link after inline editing

modules/ProjectTask/updateProject.php
Related to issue #1203.
Re-factored code. 
Rule:
if the task's "end date" is after the project's "end date", extend the related project to fit the new task "end date".
=> Fixed#1203

modules/Meetings/metadata/editviewdefs.php
Fixed #1178 - in Firefox if a form has some POST data setup and a button has type=button it will not submit the form. Solution: change the button type to type=submit instead of type=button
=> Fixed #1178 - change the button type to type=submit instead of type=button

modules/Schedulers/_AddJobsHere.php
According to the docs at the top of the file (and proven by how no scheduling works *at all* at the moment) you have to return a boolean indicating success or failure.  Since this function had no return, it was returning null which the caller tests and treats as false.  Hence, no report schedules.  "return true" might not be the brightest thing to do here, but it beats "return null" until someone smarter than me can sort it out.
(Resubmitted to hotfix as requested)
=> Add missing return

include/database/DBManager.php, tests/tests/include/MVC/Controller/SugarControllerTest.php, tests/tests/include/MVC/SugarApplicationTest.php, tests/tests/include/MVC/View/SugarViewTest.php, tests/tests/include/MVC/View/views/view.classicTest.php, tests/tests/modules/Users/UserTest.php, tests/tests/modules/iCals/iCalTest.php
This is reverting back to original function as MSSQL instances are unable to upgrade.
=> Fixed #1398 - checkConnection ping() causes failure on MSSQL

include/SugarEmailAddress/SugarEmailAddress.php
Fixed #1120 - fixed email validation for: Accounts -> Contacts subpanel -> Select -> Create Contact -> Save. If email is required it should highlight this field and show an error message.
Cannot just replace 
$form = 'form_DC'.$this->view .''.$module; 
with 
$form = 'form'.$this->view .'_'.$module; 
as form_DC... still being used in many other places.
Instead I added some conditional statements to make this replacement environment specific.
=> Fixed #1120 - fixed email validation for: Accounts -> Contacts subpanel -> Select -> Create Contact -> Save.

download.php
Fixed #1506 Fixed #1304 - IE11 and Microsoft Edge cannot display generic 'application/octet-stream' (which is defined as "arbitrary binary data" in RFC 2046).
=> Fixed #1506 Fixed #1304

modules/Leads/language/en_us.lang.php
Fixed #1512.  This removes "en_us" from the body of the label.
=> Fixed #1512.  This removes "en_us" from the body of the label.

modules/SugarFeed/metadata/dashletviewdefs.php
Fixed #1420.  As per OP's suggestion, the created_by_name has been removed.  As per Matt's comment, the assigned_user_id has been set to $current_user->name.
=> Fixed #1420.

themes/SuiteR/js/style.js
Like this you can start typing right after touching the search symbol. Otherwise you will need one more click in the search field.
=> Give focus to search field saves one click on mobile

include/database/DBManager.php
If you create a record, and the field type is numeric, empty fields get saved as "0" or "0.00".
If you update them and delete the 0 you can get NULL, but you should also be able to save NULLs on create.
By only cleaning values that are longer than 0 chars, you are able to save them as NULL or the default value for that field.
=> Allow NULL values to be inserted on new record

modules/Emails/EmailUI.php
Single quote used in translation file will lead to JS error and make e-mail module unusable
=> Modify EmailsUI.php to escape strings containing single quote

modules/Emails/Email.php
Fixes #1742 by preventing the overzealous join onto the contacts table.
Fixes #1742
Create a new case
Add a contact with an email address to the case
Add a case update
Check the history subpanel - the contact section should now correctly show the contact name.
=> Fixed #1742: Prevents the contact name from being incorrectly loaded

install/installConfig.php
datef value wasn't found on $sugarConfigDefaults array
There's no issue number I fix it when installing an instance I was customizing.
I was customizing a SuiteCRM installation and the default_date_format value was ignored.
include/utils.php value for default_date_format is ignored during installation.
Try change it to:
```'default_date_format' => 'd/m/Y',```
It is going to be ignored on the installer.
=> fix: Wrong key 'datef' changed to 'default_date_format'

include/InlineEditing/inlineEditing.js
In-Line Editing Issues
"After Inline editing a Field, (And Saving changes), You are unable to expand the Action Menu.
Also, refreshing the page after inline editing redirects to the Homepage."
=> Suitep inline edit

themes/SuiteP/css/style.css
In Firefox 47 (and chrome) can not add project task to project via ghantt chart navigate to Project Add a Task via the Project detail view. Click Save - nothing happens Then Click Cancel - screen freezes.
I believe the issue is cause by the zindex of the dialog overlay being more than the dialog it self causing the page to appear to crash, as you can't select anything in the tab.
So I have change the z-index of the overlay
This makes adding a project task in the ghantt chart impossible with  out this fix.
navigate to Project Add a Task via the Project detail view. Open the task up again.
=> Fixed  Screen freezes add a Project Task via Projects (css issue)

themes/SuiteP/tpls/_headerModuleList.tpl
I modified the SuiteP template to translate the label LBL_CREATE_BUTTON_LABEL for the quick create button on the global navigation
Allows the label to be translated into other languages.
- Install an other language pack.
- Check that the button to ensure that it has been translated
=> Fixed #1867 - Making the quick create menu translatable.

include/SubPanel/SubPanelTiles.php, themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
config values 'hide_subpanels' and 'hide_subpanels_on_login' do not work, and it just defaults to hide_subpanels always in SuiteP. The defult should be to show the the subpanel, On install of a new install it should set the hide_subpanels to true if this should be the new default
In some cases it is appropriate to display the subpanels as expanded. 
You have to edit the config.php file.
=> Fixed hide_subpanels config option with SuiteP

themes/SuiteP/js/style.js
SuiteP Theme – User Profile, All options on one screen (Regardless of Current Tab)
Edit user profile. (Can be done in SuiteP theme by hovering over Top-right and clicking “Profile”) All of the tab's Content is displayed in one long run-on page. This makes the tabs fairly redundant, and the page very long.
This can also be seen when on the Detailview for a user profile.
Check tab contents on User Profile / EditView and DetailView
…reen (Regardless of Current Tab)
=> Hotfix user profile 196

themes/SuiteP/include/DetailView/DetailView.tpl
In SuiteP when you updated a case your update wouldn't appear as the javascript was looking for an ID in the HTML that no longer existed. I've updated Suite P's detailview template to fix this.
Updating cases was broken in Suite P
Set your theme to Suite P then try to update a case.
=> Fixed #1826 where cases wouldn't update with Suite P theme

modules/DynamicFields/templates/Fields/Forms/enum.tpl
Original problem:
An issue occurs when a user adds a new drop down field with a new drop down list for the field. For example, if a user adds a new 'employees' field with a drop down list 'employees_list' and saves this, the existing core 'employees' field is modified, instead of a new 'employees_c' field being generated. This could have further implications on existing functionality/data.
Solution:
added some JavaScript to prevent user from adding or editing field if the filds name already exists.
=> Fixed #1029 - prevent user from adding or editing field if the filds name already exists.

jssource/src_files/include/javascript/sugar_3.js, modules/ModuleBuilder/controller.php
Fixed #1029 - prevent user from adding or editing field if the fields name already exists. This fix also works for custom fields.
Go to admin -> Studio -> Add field -> change Data Type to dropdown, Radio or MultiSelect -> Edit -> if the field name already exists, then it should prevent you from editing and display an error message.
=> Fixed #1029 - prevent user from adding or editing field if the fields name already exists. This fix also works for custom fields.

themes/SuiteP/css/style.css
Issue 1628 - Users are having trouble seeing the whole dialog and are not able to scroll through the form.
Relates to issue #1928 
Allows the user to fill in the email settings dialog.
- Activities
- Emails
- Settings
- Ensure that you can scroll through the dialog.
=> Fixed #1928 - restyling the email settings dialog box.

modules/Calendar/CalendarDisplay.php
A number of users in the forums have been unable to see the Calendar on php5.3 - this was due to a parsing error (works on PHP 5.4+)
Made the code suitable for PHP5.3
Unable to view Calendar in PHP 5.3 environments
1. Be on a php5.3 environment
2. log in as any user
3. navigate to Calendar
4. you should now be able to use and navigate the calendar as expected.
=> Fixed #1903 - Unable to load Calendar in PHP5.3

modules/Calendar/Cal.js, modules/Calendar/CalendarDisplay.php, modules/Calendar/index.php
Reference to issue #1938
Issues caused by start and end dates in the users preferences being undefined.
Ensures that calendar displays correctly.
Open the calendar from for the first time by a user.
You should see the time slots in the calendar.
=> Fixed #1938 - Calendar not showing time slots

modules/Spots/controller.php
Error loading Spots module on PHP 5.3 due to array syntax
Updated array syntax to suit older PHP versions
Module is unusable for PHP 5.3 environments
On a PHP 5.3 environment test Spots module - should lead to fatal error
After fix, on PHP 5.3 should be able to navigate and create Spot records as expected on other supported PHP evironments
=> PHP5.3 code syntax for Spots module

themes/SuiteP/include/DetailView/DetailView.tpl
white space after primary object in detailview: seems to be a large block of white space between module and first subpanel
related to task (251)
=> white space after primary object in detailview

include/ListView/ListViewSmarty.php, install/install_utils.php, modules/Configurator/Configurator.php, modules/Configurator/language/en_us.lang.php, modules/Configurator/tpls/EditView.tpl
this PR able to users to set default collapsed/expanded settings for subpanels
collapsed subpanels by default - we need that string in config_override (task 249)
- quick repair and rebuild needed
- check/un-check the new one collapsed subpanels checkbox on system settings on admin panel
- you should see the different on edit view subpanels collapsed state by default
=> add 'collapsed subpanles' checkbox to system settings

themes/SuiteP/images/FP_Event_Locations.svg
In the add dashlet modal dialog (dashboard). The location icon is missing. This pr is to add it back in. This could be missing because the change i made to get the my calendar to show.
- Missing icon
1. Home
2. Actions -> add dashlet
3. Check the location icon is there.
4.
=> Add dashlet locations icon missing

themes/SuiteP/css/bootstrap.min.css, themes/SuiteP/css/style.css, themes/SuiteP/js/style.js, themes/SuiteP/tpls/_headerModuleList.tpl
SuiteP: Adding Support for No Module Filters
If a user doesn't use 'Module Menu Filters' the top menu on desktop doesn't display well.
1. Admin
2. Profile
3. Advance
4. check Module Menu Filters
5. Click save
Pass condition: if you are in the desktop view the right nav items should stay inline with the items.
=> SuiteP: Adding Support for No Module Filters

modules/Calendar/Calendar.php, modules/Calendar/CalendarDisplay.php
Changed the hard coded array of colours in CalendarDisplay.php as Cal.js appends a # before them so the # before the hex color in the array was redundant and preventing it from using correct default colours. Related to Kanboard task 259
Also updated code so default shared calendar seperate setting is respected.
The initial default calendar settings were being ignored
If you go to view a shared calendar without setting any user preferences it should show a separate calendar for each user and use the default colours that are used in the settings menu.
=> fix calendar ignoring initial default values

modules/AOS_PDF_Templates/templateParser.php, modules/AOS_Products_Quotes/Line_Items.php, modules/AOS_Products_Quotes/vardefs.php
Conversion of Quotes to PDF show (NOW) 0 in right side.
Solve problem with conversion to PDF.
The CRM did not show 0 when Quantity is 10, 100, 1000 or highest
Only show 1, 100 or 1000.
this has occurs only when my local settings have "0" on "Currency Significant Digits"
References issue #791
Fix has been made by  @CaptainChainsaw   
thanks for contribution.
Make Conversion of Quotes to PDF fully functioning
=> Fixed #791 Conversion of Quotes to PDF not show 0 in right side.

modules/Meetings/MeetingFormBase.php
Changed the code that deletes leads or contacts from a meeting to use the bean rather than SQL.
After relationship delete logic hooks weren't getting called when you removed a lead or contact from a meeting using the link with the text rem on the meetings editview.
relates to issue #1559 
Add an after relationship delete logic hook to the meetings module. Create a meeting and add contacts and leads to it. Edit meeting and use the link that says rem next to a contact/leads name to remove them and check if the logic hook gets called.
=> Fixed #1559. Deleting a contact from a meeting doesn't call the logic hook

themes/SuiteP/css/style.css
css fix for minimised subpanels so they aren't spaced out
css fix for minimised subpanels so they aren't spaced out
Go to detail view of any module, minimise the subpanels and make sure there aren't massive gaps between them.
=> css fix for minimised subpanels so they aren't spaced out

themes/SuiteP/css/style.css
Made sure selectLinkBottom had the same styles applied to it as selectLinkTop so the select all checkbox at the bottom of list view looks the same as the one at the top of list view.
Select all checkbox at bottom of list view looked broken in SuiteP.
Check the checkbox at the top and bottom of any list view in SuiteP for selecting all items looks the same
=> Fix appearance of Select All checkbox in Footer for SuiteP theme.

themes/SuiteP/js/style.js, themes/SuiteP/tpls/footer.tpl
fix for issue #2128 
task 264
click on "© Supercharged by SuiteCRM" and "© Powered By SugarCRM " in footer area
(quick repair and rebuild needed)
=> Fixed #2128 - Footer Licence popups Missing in SuiteP

modules/Calendar/CalendarDisplay.php
Changed calendar from being a fixed height to auto.
Stops displaying an extra row at the bottom which made it look broken
View calendar in either the day, week or shared week view and check it looks ok.
=> Calendar day & week view shows an extra row

themes/SuiteP/css/style.css
this pull request contains a fix for Hotfix footer task 212 (2) and issue #2125
the early change broken the listview on mobile (width:600px-)
=> early change broke the listview on mobile

themes/SuiteP/css/style.css
CSS change to fix menu in List View
The options in the menu couldn't be seen.
Go to any list view, click the checkbox next to an item to select it, then click the button that says Delete. Before this fix the menu went of the left hand side of the screen and you couldn't read the options. It should now display so all the menu options can be read correctly.
=> fix List view menu going off screen in SuiteP

themes/SuiteP/css/style.css
Minor css fix. for the progression navigation. The border that make the elements look like arrows are set to the wrong color for suitep.
Makes the progression links look more inline with the SuiteP Theme
Create a new campaign
=> Fixed campaign wizard progress items background

themes/SuiteP/tpls/_headerModuleList.tpl
this PR for task 215 - Action menu text too big [updated!]
The dropdown action menu text it too big and need reformatted
better in menu when Module Menu Filters is disabled but Favourites displays in line with Recent item
pref don't show favourites / Recent Items if there isn't any, especially on administration
task 215
=> don't show favourites / Recent Items if there isn't any

themes/SuiteP/css/style.css
task 215
doesn't fix the actual issue - Action menu text too big, and now if Module Menu Filters is disable the menus all show the just the recently viewed for every module should be consistent, accross the board and the text for "Recent Viewed" etc should be smaller/ fit in
=> the text for 'Recent Viewed' etc should be smaller/ fit in

themes/SuiteP/css/style.css
This fix corrects the width of the duration field in the edit view of the calls module. 
When user edits a call the duration field task up the entire horizontal area.
- Go to calls
- Edit / Create A Call
- Check the width of the duration field
=> SuiteP: fixing duration field in calls

include/InlineEditing/inlineEditing.js
I changed the GET request to a POST. To reproduce bug, inline edit description field and enter a large description.
This change solves the problem of updating textboxes with a lot of text via inline editing.
#1849 
Use a large description field and inline edit.
=> Fixed  #1849 - Quick edit sends AJAX request via GET

themes/SuiteP/include/DetailView/DetailView.tpl, themes/SuiteP/js/style.js
sub panels can go behind sidebar
Daniel @ 08/09/2016 16:49
link
Issue:
When you create a new panel in the detail view. The subpanel ul no longer reside in the #content div. The #content div is what helps to set the width of the content area.
I am still trying to work out why the ul is in the wrong place.
AFAIK there are not issues with closing tags. I can't see any javascript that is moving it out of the content div. It might be somthing to do with smarty.
task/270
=> remove an extra div closure

include/SubPanel/SubPanel.php
bugfix for External Account page load.  first bad commit was 6bc114b978b050f6899505a1ef95fa93a840bd01 so it's may related for an other issue thereat
External Accounts tab page contents didn't loaded on User EditView (profile page)
External Accounts tab page contents didn't loaded on User EditView (profile page) so try to click on the "External Accounts" tab
=> External Account page load fix on User EditView

themes/SuiteP/css/style.css
Relate fields extra long
Fixes to line items have broken relate fields which now show extra long
task/292
=> wrap text in line items

modules/Emails/EmailUIAjax.php
Use the sugar_unserialize method rather than the PHP unserialize to prevent issues when unserialising user supplied data.
Changed the EmailUIAjax file to use  sugar_unserialize rather than the core unserialize method.
Prevents issues caused when unserializing user supplied data.
This change should only affect malicious use - the existing EmailUIAjax functionality should remain unchanged so testing that this works correctly should be sufficient.
=> Use sugar_unserialize instead of unserialize. 

modules/InboundEmail/InboundEmail.php
Quote the uid parameter when creating SQL queries as this value can come from the user.
Since the uid parameter can come from the user it's possible for this value to be malformed or malicious. This change escapes the uid parameter to prevent SQL injection or broken SQL.
=> Quote the uid when doing SQL queries to prevent malformed/malicious SQL.

modules/AOR_Reports/AOR_Report.php
When a user selects a date field to use in a report, then selects the group by with a format. The query fails on the MS SQL due to the group by requirements specified in ANSI SQL 3. This is due to the module id not being included in the group by. This change fixes the issue.
Fixes the group by function for ANSI SQL 3.
See description
=> Adding module id to second group by

modules/Campaigns/TrackDetailView.php
In a Campaign's Status View you should be able to select a Email Marketing Record to filter the graph, however there is a undefined label for the null value.
Fixes value on select option
- Create campaign
- go into the status view
- check that the filter chart type is has none.
=> Fixed: Campaign Email Record Graph dropdown displays undefined label

themes/SuiteP/css/style.css, themes/SuiteP/include/EditView/SugarVCR.tpl
Edit view buttons do display in line with the design (/task/283)
and
SuiteP on mobile - Save&Continue or Pagination button is pushing others on one left site (issue #2338 )
This PR contains fix for task 283 and issue #2338 (focused on EditView)
=> Hotfix task 283 edit buttons

data/SugarBean.php, include/language/en_us.notify_template.html
Fixes several problems with the notification Email templates:
- translated languages were showing tags in Email subjects, like `<p>`
- translation process had to be manual because extra HTML tags needed to be added in templates, but couldn't, because they would render incorrectly in emails
- HTML was being removed from Emails, unnecessarily reducing the ability to make better looking templates
- links in emails weren't showing as links, but as visible URL's
- solves a problem visible to every user of translated languages
- makes translation management easier (minus one manual step multiplied by 53 languages). Horus68 is waiting for this since January...
- as a positive side-effect, this change opens up new possibilities of future embellishing emails with some more HTML
- Try the actions …
=> HTML notification Emails fix

themes/SuiteP/css/style.css
My Pipeline dashlet issues
If you add the my pipeline or pipeline dashet to the view and open the settings panel, select date and then close the panel, reopening the panel again causes the overlay to appear infront of everything else stopping the user from interacting with the system.
task/328
=> pipeline dashlet popup and calendar popup fix

themes/SuiteP/include/ListView/ListViewPagination.tpl, themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl, themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
Enabling Sprites causes extra images to appear
if 'use_sprites' => true, is set in the config (add to config then go to repair and 'Rebuild Sprites') extra images can appear on top of other images @see the list view pagination in the the screenshot attached in task/323
task/323
=> Enabling Sprites causes extra images to appear

include/InlineEditing/inlineEditing.js
Fixed  #543  -inline editing on text area - cannot create line breaks
Adds the ability to press shift and enter to get a new line when inline editing
Allows users to press shift and enter to get a new line.
Inline edit a field such as the description field in accounts, press shift and enter and you will then be able to go to a newline
=> Fixed  #543 -inline editing on text area - cannot create line breaks

themes/SuiteP/css/style.css
This pull request contains a simple fix for issue #2430 does not change the bgcolour of search input when it's autofilled by browser
=> Fixed #2430 - global search autofilled background colour

include/language/en_us.lang.php, modules/Reminders/Reminders.js
This PR contains a popup confirmation for ask user to delete Remainder when the user deleted the last one invitee too because if the reminder is empty then the remainder could be useless (without invitees..) it cause a Validation error why the form 'Save' failed and the original problem still there (see issue #1178)
Reminder invitees validation was not clear
Remove all invitees from a reminder on Meetings or Calls
=> Fixed #1178 - Confirm popup for delete empty reminders

modules/AOS_PDF_Templates/templateParser.php
references issue #2153
Added a conditional statement which checks whether field is of type image. 
If the field is of type image then a link pointing to the location of the image is generated.
PDF images showing up in templates are not created when PDF is generated.
1. Create a new field on invoice of type image
2. Add the new field to the edit screen of invoice
3. Create an invoice record and upload a jpg image to the new field.
4. Create a pdf template on invoice and add the image field to it.
5. Select Print as PDF on the created invoice record.
6. Select the PDF template that you added the image field to.
7. Examine the generated PDF.
=> Fixed #2153 - added image generating link to the template parser.

themes/SuiteP/css/style.css
Removed the important from style.css when searching in list view.
Fix to provide consistent padding on list view.
View the list view after a search before and after the merge (may require a repair/rebuild to rebuild cache).  The padding between the rows should match that when not searching.
=> Fixed incorrect height for list view after search

modules/Home/UnifiedSearchAdvanced.php
Couple changes in modules/Home/UnifiedSearchAdvanced.php - relates to issue #99 
Modified $where_clauses
- create number of contacts
- open SuiteCRM
- in global search type some record with apostrophe
- click search
- the output displays searched record
- click on basic search
- after apostrophe apear slash symbol
- after search again another slashes were added 
Remove "/" appearience in record
=> Fixed #99 Issue with apostrophes in search

include/MySugar/tpls/addDashletsDialog.tpl, themes/SuiteP/include/MySugar/tpls/addDashletsDialog.tpl
This is related to issue #2124 and Pull request #2376
The labels are missing in the web tab of the add dashlets dialog. 
This change corrects the issue.
Add a web dashlet to the dashboard. You should see the following:
=> Add labels to the fields in Add dashlet - Web Tab

modules/Cases/language/en_us.lang.php
There is a missing string in language file for Modules / Cases /  line 165
`    'LBL_CONTACT_CREATED_BY' => 'Created by',`
this is called from \modules\Cases\vardefs.php
`                'vname' => 'LBL_CONTACT_CREATED_BY',`
Note: The language file string was removed on an previous PR but should be reverted 
https://github.com/shogunpol/SuiteCRM/commit/a52a93b372c7117b4c4dda55ae0c4389acc17bd3
=> Cases module - Missing string LBL_CONTACT_CREATED_BY

modules/AOS_PDF_Templates/templateParser.php
Emails which are based on Email Templates with some fields that have variables representing Dynamic DropDowns have keys inserted instead of values (e.g americas_bolivia instead of Bolivia).
This can be fixed by changing line 63 to make sure that it applies special formatting if the type of $field_def is dynamicenum .
references issue #2642
1. Created a dropdown called ARC_Sub_Region in Admin -> Dropdown Editor
2. Created a field for the Contact module called 'Test Dropdown'. This field is a Dynamic Dropdown type field and has ARC_Sub_Region as its dropdown. Added this field to the EditView and DetailsView of the Contact module.
3. Went to the Contacts record for Britney Walraven (example user) and set the 'Test Dropdown' to Bolivia.
4. Created an Email template for testing the dropdown …
=> Fixed #2642 - changed line 63 to make sure that it applies special formatting if the type of $field_def is dynamicenum

include/Smarty/plugins/function.sugar_button.php
Delete confirmation ignores "Cancel" and deletes anyway - fixed
Delete confirmation ignores "Cancel" and deletes anyway - fixed
References isue #2862
=> Fixed #2862 - Delete confirmation ignores "Cancel" and deletes anyway

install/suite_install/suite_install.php
When a user installs suitecrm the enable_action_menu is not set, which causes issues with some views in SuiteCRM eg. Meetings/Calls. 
* Fixes bug
1. Install the SuiteCRM
2. Check config.php for 'enable_action_menu'
3. Also check the detail views for each module to ensure that you see the action menu
=> Adding 'enable_action_menu' to config during install

include/utils.php, modules/Administration/PasswordManager.tpl, modules/Administration/language/en_us.lang.php, modules/Configurator/Configurator.php, modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php, modules/Users/controller.php, modules/Users/language/en_us.lang.php, modules/Users/views/view.detail.php
Provides admin settings for automatically locking users after a configurable amount of failed logins. Also provides admin users the ability to unlock locked users.
Also provides an admin setting for automatically unlocking users after a configurable amount of time.
Currently there is no limit to the number of login attempts that a user can make, this could in theory allow brute force attacks on the login screen. This PR allows an automated way of preventing this.
Setting the new maxfailedlogins config setting and deliberately failing to login, say, 3 times will prevent future logins until the user is unlocked on the user screen by an admin.
Setting the automaticunlocktime config setting however will unlock users x minutes after they are locked.
=> Add User lockout and user unlock options 

jssource/src_files/include/javascript/sugar_3.js, modules/ModuleBuilder/tpls/MBModule/field.tpl, modules/ModuleBuilder/views/view.modulefield.php
references issue #2183
The following file - modules/ModuleBuilder/tpls/MBModule/field.tpl had this input field with a value always true - <input type='hidden' name='is_update' value='true'>
So the form could not differentiate whether it was creating a new field or just updating an existing field.
This caused a problem with saving already existing fields - it tried to check whether the field name already exists (this check is only required if the user creates a new field, if the user updates an already existing field, then there is no need to check for duplicate field name as the user cannot change the field name anyway it will always stay the same in case of an update).
The following changes were applied: 
1. modules/ModuleBuilder/views/view.modulefield.php
if($field_name == '') { …
=> Fixed #2183 - only check for duplicate field names if it is not an update

themes/SuiteP/css/navbar.scss, themes/SuiteP/tpls/_headerModuleList.tpl
This prevents the toolbar on the right hand side from wrapping to the next line.
When a user access a module that has a name which is very long. The toolbar on the right hand side wraps to the next line. This is due to a change I made the the spacing of the home button.
So to ensure that this doesn't happen again I have implemented a script which is similar the one we used for non filter menus; where it hides the menu item. However this implementation doesn't put the element in the All menu.
* prevents the nav bar style from breaking.
* Compile style.css from sass
* Access a user that utilises the filter menus
* Access a module like MAP ADDRESS CACHE
=> Hiding nav menus when the current module text is too large.

include/InlineEditing/inlineEditing.js
Quick Search population when using inline-editing would not populate after the first inline-edit on any page. (Referenced in issues #2344 and #2499 which both contain steps for reproduction.)
Resolving a bug that was raised in two seperate issues regarding the same functionality.
As described in Issue #2344 the following steps could be used to replicate the bug, when following these steps now, it's resolved:
1. Open list view of any module
2. Double click on Assigned to field in any row to inline edit selected record.
3. When typing, suggestion items show up.
4. Save row by clicking on tick icon.
5. Double click on Assigned to once again, this time suggestions do not show after typing.
Issue #2499 also lists a scenario on a different page which has since been resolved with this change, …
=> Fix #2344/#2499 - Quicksearch not populating after first inline edit.

include/InlineEditing/inlineEditing.js
Fixing issue #2545 - Often times the warning loss of changes dialogue window would appear when entering an inline edit box (upon double click). The Window would also be prompted if there were no changes made.
A potential frustrating (from user interface point of view, user experience) bug that shouldn't have been present. Removal of the dialogue window appearing upon entering (sometimes) and clicking away without changes to the window should result in some less frustrating in-line editing experience.
In issue #2545 the user provided a note for reproduction:
"When i mark some field for inline editing and click ouside the message show
up. I click cancel on message and second message popup immediatlety. When I
click cancel second time focus goes back to edited field."
=> Fix #2545 - Warning about loss of changes appears multiple times

themes/SuiteP/js/style.js
When a administrator/developer changes the layout of a detail view in studio, so that the panel types are mixed between "tab" and "panel" eg Tab, Tab, Panel, Tab, Panel. This causes and issue with the javascript for the first tab in the mobile detail view. Where as a User: after selecting a tab in the dropdown menu in the first tab, the contents of the tab displays as none / blank. 
Example
The reason is because the index of the dropdown menu and the tab contents are out off by 1. This fixe selects the correct tab content number. 
* In studio add panels and set the type (Tab/Panel) in a random order.
* Check that you can see those tabs in the mobile view.
=> DetailView(mobile): Fixed issue when the panels and tabs are in a mixed order in studio.

modules/ACLRoles/DetailView.tpl, themes/SuiteP/css/forms.scss
Sugar Action Menu seems broken across all themes for Roles admin panel. I have made this flat menu instead.
Allows users to edit, duplicated and delete roles
See roles admin
* rebuild sass for testing SuiteP
=> Making sugarmenu flat

themes/SuiteP/css/forms.scss
Regression issue. The testOutboundDialog_c in the email settings is behind the mask when a user selects send test email.
* Bug Fix
* Go to admin -> email settings
* Click send test email
=> Fixed testOutboundDialog_c zindex

modules/Calendar/CalendarActivity.php
Fixed provided by @adamjakab 
Correcting a typo which stops Meetings being filtered correctly on Calendar
1. Set Calendar Settings to 'Show Completed Meetings,Calls and Tasks' to false.
2. Confirm that the Meetings, Calls and Tasks are not displayed if Held/completed.
3.  Ensure existing functionality is maintained.
=> Fixed - Calendar is displaying Closed (HELD|NOT HELD) Meetings when $show_completed is false

modules/EmailMan/EmailManDelivery.php
When creating a new outbound email, or updating system settings and using SMTP it is saved in the field mail_sendtype as "SMTP". When checking before sending a campaign it is checking for "smtp" and then when this fails it is using sendmail. This means you can never send a campaign using smtp.
It solves the issue of not being able to use smtp to send emails.
Test sending a campaign and see that the system email settings have not been used to send an email. Apply fix and see that it has.
=> Fix campaign email issue

modules/Studio/language/en_us.lang.php
missing closing tag `</b>`
Note: no issue created for this PR
Found a related duplicated issue: https://github.com/salesagility/SuiteCRM/issues/2676
So this string must be removed or fixed!
=> Missing closing tag </b>

themes/SuiteP/tpls/_headerModuleList.tpl
This is a second attempt to fix #2936. Using the height of the desktop toolbar to detect if the navigation menus are wrapping to the next line, instead of the width of the desktop toolbar.
* Fixes bug with the navigation bar in the large desktop view
* Add many menu filters
* Resize browser width to around 1605px
* Access a module who name is longer the 17 characters
The navigation elements should not wrap. However this hides some navigation menus:
Menu items should not wrap to the next line
=> Fixed Desktop Toolbar visual overflow issue

themes/Suite7/css/style.css, themes/SuiteR/css/style.css
- Fixed #3012 - break lines in searchform fields label
please see related issue: #3012
=> Fixed #3012 - break lines in searchform fields label

themes/SuiteP/include/EditView/EditView.tpl
Same is as #2988 but in the edit view.
When a administrator/developer changes the layout of a detail view in studio, so that the panel types are mixed between "tab" and "panel" eg Tab, Tab, Panel, Tab, Panel. This causes and issue with the javascript for the first tab in the mobile edit view. Where as a User: after selecting a tab in the dropdown menu in the first tab, the contents of the tab displays as none / blank.
* fixes the bug
* includes the fix in #3073 (in order to prevent merge conflicts)
* In studio add panels and set the type (Tab/Panel) in a random order.
* Check that you can see those tabs in the mobile view.
=> Fixed - Edit View Tabs for mobile (SuiteP)

themes/SuiteP/css/admin.scss, themes/SuiteP/modules/Studio/TabGroups/EditViewTabs.tpl
When the user has a display which is less than 1500px in width, the module filters on the right hand side overflow.
* This change corrects the issue
- [] My change requires a change to the documentation.
=> Module Menu Filters: Overflow issue (SuiteP)

modules/EmailMan/testOutboundEmail.php
- Fix Email Settings test with differents admin user
(ref: case 7148)
When the admin user changed to the difference one admin user the test Email Setting function failed,
Email Settings at testOutboundEmail action tried to get an Outbound Email record by current user id however the user id of 'system' typed Outbound Email is always 1.
login with admin user
set Email Settings in Admin menu
test email => ok
add a second admin user
Logout and log in with second admin user
select Email Settings in Admin menu
test email => failed (which is bad)
retype the password
test email => ok
=> Fix Email Settings test with differents admin user

modules/AOR_Reports/AOR_Report.php, modules/ProspectLists/ProspectList.php
The issue was related to #1525, #856 and #875.
**Prospect Lists:**
Quoting the column 'type' because it is a keyword in MySQL is bug.
The responsibility should be in the database manager. I have
removed the quotes and the query seems to work without them.
I can't see why it was added in the first place as both engines on
MySQL and SQL seem to process the query without the need for
quotations or brackets. Perhaps it was just as a precaution.
**Reports:**
I have added the quoteIdentifier to reports, because the table alias is quoted and the quotation should be handled by the database manager.
* Provides a more correct solution
* Retest the issues I have linked.
This change has been tested on:
* Ubuntu 14.04 PHP 5.6 / MySQL 5.6
* Ubuntu 16.04 PHP 7 / MySQL 5.7
* Windows Server 2008 R2 / SQL …
=> Removing "`" from db query.

include/ListView/ListViewSearchLink.tpl, include/ListView/ListViewSmarty.php, include/SearchForm/SearchForm2.php, modules/MySettings/StoreQuery.php, themes/SuiteP/css/editview.scss, themes/SuiteP/css/listview.scss
This change shows search form at list view area only if $sugar_config['save_query'] set to 'populate_only' so that the user able to set search parameters when the list view is empty
- needs to rebuild style.css
- for next steps, please see related issue: #3072
=> Fixed #3072 - show search form for save query if popuplate only

include/InlineEditing/inlineEditing.js
Issue #3148 was raised by a community member regarding entering a Relate/QS field, closing it then clicking on a hyperlink would result in the hyperlink not following to the url.
The community member who opened up the issue raised it as a frustrating issue. Frustrating user experience is a priority to resolve where/if possible.
The bug is that the clicks would increment to 2 instead of 1 where a URL is not followed unless the clicks are 1. The function for buildEditField() is called twice or a part of the function is executed twice to increment clicks one click higher than it should be. This is a bigger issue at scale though and this resolves the issue for the time until time can be made to look into addressing this further.
In a vanilla installation, do the following:
* Enter an Accounts …
=> Fix #3148 - Hyperlinks not followed after entering Relate/QS field

include/database/MysqliManager.php
Bug fix related to issue #3119. It was a simple fix, just had to add the call to the dump_slow_queries() function.
Functionality is there, just wasn't working for MySQL.
Simply enable log slow queries from system settings.
=> Log slow queries for MySQL

modules/Calendar/CalendarDisplay.php
Issue raised via Issue 3225 - https://github.com/salesagility/SuiteCRM/issues/3225
Calendar not displaying on PHP 7.1
Enables users on PHP 7.x to view Calendar display
Test on PHP 7.x environment.
Access Calendar module it should display as expected in older PHP environments.
=> Fixed #3225 - Calendar body is not shown after PHP 7.x update

include/MassUpdate.php
Fix for Issue #2277 - Dynamic dropdowns didn't show up when performing a mass update, even if the mass update checkbox was checked in Studio when editing the field.
Inclusion of the type within the MassUpdate.php class for dynamicenum within two case statements where dynamicenum was missing from the type of inputs. With this change, dynamic dropdowns now show up in mass editing when the checkbox is checked in studio.
The issue raises broken functionality within Studio - a checkbox which is supposed to allow functionality didn't work. The issue was raised back in September and can be seen as a user frustration if they require to have this functionality for any mass-changes to information.
Without the applied changes in the MassUpdate.php file, within Issue #2277, there are steps listed to …
=> Fix #2277 - Mass Update with Dynamic Dropdowns

modules/Emails/javascript/Email.js
When you insert an image in tinyMCE - it also attaches it. As it links to a URL in the public folder it does not need to attach it. 
It allows you to insert an image without it being attached.
Create template and insert image - see that it's attached. Apply fix and clear browser cache and see that it does not anymore.
=> Fix - Insert image also attaches it in tinymce

README.md, include/ListView/ListViewGeneric.tpl
Combines the two class tags into one to resolve issue #3247
Two classes were introduced, this fix reduces the number of class tags to 1, so that inline editing works on the list view
=> Fixed #3247 - Suite7 inline editing does not work

modules/Campaigns/SubPanelViewer.php
Changes to be committed:
modified:   modules/Campaigns/SubPanelViewer.php
Use .tpl instead of .html
One liner to fix bug from issue #3108
Pager on Campaigns result returned error.
Described in issue 
- [X ] Bug fix (non-breaking change which fixes an issue)
=> Fix for #3108 - Campaigns results not using smarty template.

data/SugarBean.php, include/database/MssqlManager.php, include/database/MysqlManager.php
This pull request is in relation to issue #1719 and pull request #2454.
The issue is that as of MySQL 5.7 strict mode is enabled by default. This means that you must pass the correct data type into each field of a SQL query. SuiteCRM historically used "0000-00-00" and "0000-00-00 00:00:00" to define null values, instead of passing in NULL. Older versions of MySQL and MS SQL both support use NULL for dates and times.  As do other database engines like SQLite.
So I have updated the DB Manager to pass a NULL instead. To ensure that we have support for legacy code bases, I have also added an empty check in the SugarBean so that date and time fields are set to '' instead of NULL. This is because most codes bases check for  '', however they really should use the empty() function in PHP.
* …
=> Fixed MySQL/MS SQL Strict Mode

include/InlineEditing/inlineEditing.js
Fix for Issue #3250 - Whenever clicking into an inline edit field with the value matching up to be an area telephone number, such as, "(00000) 000000" - the field will populate as expected, but when trying to close (click away) or save, an exception will be thrown due to not parsing the area code brackets properly.
Inline Edit doesn't work for Telephone Numbers when it should... it can prove to be a frustrating user experience.
* Install SuiteCRM
* Go to a module with a telephone field in list view, e.g: Accounts
* Double click the field
* Try to either click away or close it (save).
=> Fix #3250 - Resolving Telephone Number Inline Edit

modules/UpgradeWizard/systemCheck.php
When checking the modules/AOD_Index/Index/Index directory, if the lucene index process is running, files are being created and deleted very quickly.  The uwFindAllFiles call takes long enough that files may be deleted before they can be checked for permissions.  This change checks to see if the found file still exists before checking permissions.
https://github.com/salesagility/SuiteCRM/issues/3212
The AOD_Index process can quickly create and delete a large number of files. If it is running when an upgrade check is performed, some files can be reported as being owned by root. Upon checking for the files manually, users find that they do not exist.
Have an AOD_Index process currently running
Perform an upgrade/system check
See files in the AOD_Index directory and not flagged as having bad …
=> Fix #3212 Update systemCheck.php to confirm file exists before permission check

include/InlineEditing/inlineEditing.js
Fix for Issue #3136 - Translates the newline ```\n``` and carriage return character ```\r``` to line break  ```<br />``` for the save/closure of inline editing fields where new lines can be taken (mainly textareas).
User within the community was experiencing data being presented wrong to them upon saving unless they refreshed. As it can be annoying feedback to not see the information as you've specified it upon saving unless you do a page refresh, I looked into this alongside of the other inline editing changes I'm currently working on.
* Go into a detail view that has a textarea.
* Insert some information, taking new lines after writing text with <kbd>shift</kbd> + <kbd>enter</kbd>
* Save process and view output.
_This also corrects the issue if you open content with already existing …
=> Fix #3136 - Correct newline in textarea when save/close to line breaks

modules/AOS_Products/tpls/EditViewHeader.tpl
references issue #2917
Even though the relationship between Product and Product Category is created correctly, the following file modules/AOS_Products/tpls/EditViewHeader.tpl was trying to save is as a return_module instead of return_relationship.
The products created in the "Products" subpanel of "Product Categories“ are not related to the category. A product can be created but not shown in the subpanel unless you select the product category in the full form.
1. Navigate to Product Categories -> Products subpanel -> Create
2. Enter the details of the product and click Save.
3. The new Product is created, and is linked to the Product Category (displayed under the Products subpanel).
=> Fixed #2917 - template should save a relationship name in the relate_to input

modules/AOS_PDF_Templates/formLetterPdf.php
On some browsers, if the header is not generated first then it doesn't appear on the first page.
To fix this, the order of the generation is changed.
=> Fix for Missing Header

include/language/en_us.lang.php, modules/AOP_Case_Updates/Case_Updates.php
There are 2 internal update labels on cases. I suggest removing one and keeping the bold one that says 'Internal Update'
- Go into the detail view of a case
- View that there is now only 1 internal update label
=> Removes duplicate Internal label on cases

modules/ModuleBuilder/parsers/relationships/DeployedRelationships.php, modules/ModuleBuilder/parsers/relationships/UndeployedRelationships.php
When trying to deploy a new relationship via studio in PHP 7.1 the relationship does not deploy and returns an error. This is due to the argument count for user defined functions being upgraded from a warning to an error with in PHP7.1.
Try to deploy a relationship via studio.
=> Fixed #3299 - Module builder and adding relationship fails in PHP 7.1

include/php-sql-parser.php
An uninitialized array will lead to the error of the subject line as PHP > 7.1 will assume it to be a string.
Adding 
$expr = array();
will stop that error appearing!
The detail supplied above is enough,
This is one major part of to get the REST interface to work with PHP 7.1
You need to run a "get_entry_list" query, "login" and "get_server_info" will just work fine but as soon as you need to work with data the above problem will stop the interface to work!
=> Fatal error: Uncaught Error: [] operator not supported in PHP 7.1.0

include/EditView/SubpanelQuickCreate.php
Original PR ( #3284 ) was compared off of a community member's branch - instead of opening a PR against his branch to then add to the open PR and also removing the view change, this PR will be for any further adjustments.
-- Original Description --
A fix provided by @imtg-suitecrm in relation to Issue #3238 - Sub panel when you are in quick create shows Save and Continue button at the bottom when it should not as this functionality does nothing currently.
UI indicates functionality that does not belong/does not work, removing this from the view would enhance user experience and not frustrate users when it does not work as they think it would.
* Open Contacts module
* Go into the Edit View on a contact
* Scroll down to the sub panel
* Create a new record
* Save and Continue button is …
=> Fix #3238 - Hide save and continue button on contacts subpanel

include/utils.php, install/performSetup.php
When installing on PHP5.3 environment the instance would fail due to syntax error only visible on PHP 5.3 (does not affect PHP 5.4+)
Installation (and Upgrades probably) fails on PHP 5.3 environments.
Failure of installation (biggie)
1. Set up PHP 5.3 
2. Clone hotfix branch (with fix)
3. Install SuiteCRM instance - should be successful - else a blank screen will appear.
=> Fixed issue on PHP5.3 with syntax error for getRunningUser

modules/Emails/include/ListView/ListViewDataEmails.php, modules/InboundEmail/InboundEmail.php
Resolves issue when clicking sort by Date Created and showing default with emails appearing newest at the top.
=> Resolving sorting by unformatted date and default sort by date created

modules/AM_ProjectTemplates/controller.php, modules/Project/Project.php
Requirements.
As a User when I create a Project based on a Template (either via the Project Template's Action Button > Created Project, or from a project's Edit View Related To field to Projects and Save) and copy the Template's Tasks over that the Tasks that follow a preceding task will begin on the next available working day.
Currently these tasks are created with a start date of the same finish date of a preceding tasks - this is incorrect.
=> Gantt Chart - following tasks should be created the next available working day

include/SugarObjects/templates/person/Person.php
Issue #3470 
Removed extra `=` sign from if clause, where it compares `$where` to blank.
Because of this PR, now we can export all records from leads module.
1. Go to `Leads` module.
2. Select all the records.
3. Click on `Export'.
=> Fixed #3470 - Export fails when trying to export all records (DB error)

modules/AOS_Quotes/language/en_us.lang.php
Language value edited for consistency and clarity:
`'LBL_SUBTOTAL_TAX_AMOUNT_USDOLLAR' => 'Subtotal + Tax (Default Currency)',`
See issue details: Subtotal Tax - language #3477 
Translation issues
=> Fixed #3477 - Subtotal Tax

modules/AOR_Reports/AOR_Report.php
At AOR_Report, when exist a condition "Equal_To" and empty, the system
add extra condition " OR XXX is null", but this condition has no
parenthesis.
=> Report. The errors caused by the conditions of type "field = ''"

download.php
A photo uploaded to the users profile (edit view / detail view) into the 'photo' field of the 'users' table is visible in the users module only. Within the employees detail view the photo is not found. This fix makes the photo correctly display in both the user profile and employee detail view.
Issue reference: #2483 
1. Add photo in user profile.
2. Add photo to employee detail view layout in studio.
=> Fixed #2483 - User profile image not visible on Employee detail page

modules/Campaigns/WizardMarketing.php
Fixes an error I found while customizing the code, #3404 
Without the full path, the reference works because PHP ends up picking up the file from the local directory. However, if you move this `WizardMarketing.php` to `custom` to customize it, the reference will break.
Just use the Marketing Wizard to see if it works.
Then copy `WizardMarketing.php` into the custom dir and use the Wizard again.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
=> Fix #3404 local reference in include in WizardMarketing.php

data/SugarBean.php
Added strict parameter to array_search function call to include strict type comparison of field def value
Issue raised when trying to create WorkFlow with Send Email action where TO field was a Related Field and there wasn't expected related field in the dropdown list. The field was skipped because it's checked as Required - since array_search was used without the $strict parameter it would compare string value and boolean true value.
1. In studio mark Relate field to Users module as Required
2. Create WorkFlow with Send Email action.  Set TO as Related Field and in dropdown list of fields there should now be this field.
=> Fixed #3499 - SugarBean - array_seach function doesn't use strict parameter

include/SugarEmailAddress/SugarEmailAddress.php
Implements the change proposed in #3295
SugarEmailAddress->addresses will only have the last added primary address marked as such, all previous address will have primary_address set to 0, as the code's original intention was.
Add several primary email addresses to a bean via $bean->emailAddress->addAddress
Check if only the last added address is marked as primary, either in the address array, or in the email_addr_bean_rel table after $bean->save
=> Fixed #3295 - SugarEmailAddress->addAddress does not set other addresses to non-primary if $primary parameter is true 

modules/Spots/controller.php
This works for MySql and I have also changed the SQL for MSSQL but not able to test it.
Change SQL to use UNION ALL when selecting data.
Spots pivot table only shows unique values and the counts are all 1. The pivot table needs the 'duplicates' for the counts to be correct.
Create pivot table on Activities with many calls in various states. Notice that the count correctly reflects the number of calls in the various states.
MSSQL version not tested but MSSQL syntax seems to require the same UNION ALL.
- [x ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) …
=> Spots needs UNION ALL when selecting data #3304

jssource/Minifier.php, modules/Emails/include/ComposeView/ComposeView.tpl, modules/Emails/include/ComposeView/EmailsComposeView.js
Task: scrm-8
When the user types in the related to field they are not presented with the auto-completion box.
The issue is due to the id of the compose view being randomised. SQS expects the id of the form to be the name of the view like "EditView", as the sqs_objects array stores each filed by the form id + the name of the field.
Also in this change:
I have added an if statement to the minifier so that when you are in development mode the minifier simply returns the javascript unminified. This helps developers debug client side issues faster, and also speeds up the JS rebuild processes. This will only effect developers and not users.
This change corrects the issue.
* Repair JS Grouping
* Compose an email
* Type in the relate to field
You should be able to see the …
=> Fixing Compose View Related To

modules/Emails/include/ListView/ListViewHeader.js
When the user first clicks on emails with out any settings i have added a glyphicon in the folder button to mark that there is an issue.
=> Adding glyphicon when user email settings are missing

include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Updated SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php to use the new email composer function populateComposeViewFields().
1. Go into account detailview
2. Open activities subpanel
3. Open create task submenu
4. Compose Email
- [] Bug fix (non-breaking change which fixes an issue)
=> Fixed - Subpanels using old email composer popup

modules/InboundEmail/InboundEmail.php
The regex used to check if the date from the imap server has the timezone string is incorrect.
This change corrects the issue.
View emails.
=> Fixing regex for date created

modules/AOP_Case_Updates/Case_Updates.php, modules/Emails/views/view.detail.php, modules/InboundEmail/InboundEmail.php
Task: SCRM-581
Issue: #3617
When user imports email, they are unable to see the body. Updated populate fields to support the newer 
InboundEmail::getMessageTextWithUid method.
Fixes bug
* Import email
* View imported email
=> Fixed #3617 - Imported emails body field

modules/Home/Dashlets/RSSDashlet/RSSDashlet.php
This fixes certain rss feeds displaying HTML tags. Some rss feeds break the way the rss dashlet parses the xml causing it to display incorrectly.
Issue reference: #1855
1. Repair and rebuild.
2. Add a web dashlet.
3. Enter https://community.sugarcrm.com/community/feeds/allcontent?community=2017 as news feed.
=> Fixed #1855 - RSS dashlet formatting

modules/UpgradeWizard/systemCheck.php, modules/UpgradeWizard/uw_utils.php
UpgradeWizard shows deprecated php version but able to upload the upgrade packs
UpgradeWizard doesn't able to upload any upgrade on php 5.5.9 and stop the upgrade process
Upgrade SuiteCRM on php 5.5.9
=> do not broke the upgrade process

modules/Emails/include/ComposeView/EmailsComposeView.js
When the users selects an email template in the compose view, the validation prevents them from sending an email. This change corrects this by populating the change into the hidden description field.
Fixes bug
* Repair js
* compose email with a email template
=> Fixed Email Templates In Compose View

include/SugarObjects/templates/file/views/view.edit.php, modules/ModuleBuilder/MB/MBPackage.php
This change fixes modules returning a 500 error when attempting to export on PHP 7.1. This change also fixes modules created with the file template not allowing the user to create a record.
Issue ref: #3684 
Issue ref: #3676 
1. Create a module in module builder based of file template.
2. Attempt to create a record inside this module.
3. Attempt to export a module in module builder on PHP 7.1
=> Fixed #3676 - Module builder export and file template.	

include/EditView/EditView2.php
A typo in a method name was preventing creation of security groups, through the administration interface. The problem was introduced in PR #3596.
Fixes issue #3707.
=> Fix typo preventing creation of security groups

include/SugarFolders/SugarFolders.php
This changes fixes the issue where a user can see the folders of other users in the email settings dialog.
* Fixes issue
* Create a personal email account in one user
* Go into the email settings of an other user.
* Under folder management ensure that it says "none"
=> Fixed #3719 - Every user can select all private email folders

modules/Emails/Compose.php, modules/Emails/EmailsController.php, modules/InboundEmail/InboundEmail.php
This change fixes the issue with signatures when unsupported UTF-8 characters break the json_encode method, causing the user to not see their signature.
* Fixes the issue
* Use a PHP 5.3 environment
* Create a signature
* Set the signature up
* Compose an email
=> Fixed #3725 - Email Signature UTF8

modules/Emails/templates/displaySubjectField.tpl
Task: SCRM-590
Issue: n/a
In the list view of the emails module, users cannot select emails which do not have a subject.
* Fixes bug
* As a user Given that I am viewing my emails When an email has no subject i Expect to see a (no subject) link.
=> Fixed SCRM-590 - Cannot select emails with no subject (list view)

modules/Emails/include/ComposeView/EmailsComposeView.js
When user composes email in firefox, and then attaches a document (not a file), it causes the form to submit.
This change fixes the issue by adding the missing event into the method arguments
* Repair js grouping
* Compose email in firefox
* Attach a document
=> Fixed scrm-613 - Attach Doc submits form on firefox

modules/Emails/EmailUIAjax.php
User cannot set the signature in the email account settings to none.
This change fixes the issue
*  Navigate to user profile
*  Click "Settings"
*  Switch to the "Mail Accounts" tab and edit a Mail Account
*  Set the signature as something other than --none–
*  Edit it again and try to set it as --none–
=> Allow email signature to set to none

modules/AOS_PDF_Templates/sendEmail.php, modules/AOS_Quotes/templates/showPopupWithTemplates.tpl, modules/Emails/include/ComposeView/ComposeView.tpl, modules/Emails/include/ComposeView/EmailsComposeView.js, modules/Emails/views/view.compose.php
Task: scrm-604
Issue: #3654 
When user send an email after selecting "email quotation", they are presented with a blank screen due to the handling of return_id.
This corrects the issue
- Repair JS minified
- Repair JS groupings
- select a quote
- select email quotation in the action menu
- Send email
You should be redirected back to quote
=> Adding better handling for return_{field}} in url

modules/Emails/Email.php, modules/Emails/include/ComposeView/ComposeView.tpl, modules/Emails/include/ComposeView/EmailsComposeView.js, modules/Emails/metadata/composeviewdefs.php, modules/Emails/vardefs.php
User cannot force emails to send in plain text format.
Note: that selecting Send Plain Text Emails Only in the email settings will override the checkbox in the compose view.
This change fixes the issue.
- Compose Email
- Check send in plain text only
=> Fixed #3730 - Email: No way to send plain-text emails

modules/EmailMan/EmailMan.php, modules/EmailTemplates/EmailTemplate.php, modules/EmailTemplates/Save.php, modules/Emails/EmailUI.php, modules/Emails/EmailUIAjax.php, modules/InboundEmail/InboundEmail.php, modules/Schedulers/_AddJobsHere.php, tests/tests/modules/InboundEmail/InboundEmailTest.php
- This PR contains some fox for PHP errors (Email Template variables did not handle the variables correctly after html entity cleanup)
- Also contains a fix for Inbound email duplication check: related to bounced messages in campaign stat (related issue #3766)
Campaign stat doesn't shows the bounced messages after the scheduled jobs run
- create a new campaign with some bounced email address in target list
- check campaign stat after scheduled jobs
=> Hotfix scrm 569 bounce email handling broken

include/OutboundEmail/OutboundEmail.php, modules/Emails/templates/emailOptions.tpl, modules/Users/UserEmailOptions.tpl, modules/Users/UserViewHelper.php, modules/Users/tpls/EditViewFooter.tpl, modules/Users/tpls/wizard.tpl, modules/Users/views/view.wizard.php
Users are able to change the system outbound email account by editing it in their user profile.
* This change removes there ability to change the password in the user profile.
* Access user profile
* Attempt to change the system email accounts password
=> Fixed #3841 - Saving profile deletes SMTP password

include/SuiteEditor/SuiteEditorConnector.php, include/SuiteEditor/SuiteEditorDirectHTML.php, include/SuiteEditor/SuiteEditorMozaik.php, include/SuiteEditor/SuiteEditorSettings.php, include/SuiteEditor/SuiteEditorSettingsForMozaik.php, include/SuiteEditor/SuiteEditorSettingsForTinyMCE.php, include/SuiteEditor/SuiteEditorTinyMCE.php
In this PR able to customize code templates and settings of Suite Editors and added some plugin into TinyMCE by default: plugins: ['code', 'table', 'link']
ref: SCRM-608
please see in related issue #3671 - When editing an email template with TinyMCE it is not possible to edit the html
=> Fixed #3671 - able to customize suite editors

include/SugarTheme/SugarTheme.php
This is the minimal fix, just a better message. It would be nice to handle this better in upgrades to 7.9 where SuiteP is disabled.
See issue #3753 
Disable all themes through config_override.php, for example.
Or disable SuiteP on a 7.8 instance, then upgrade to 7.9
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
=> Fix #3753 no available themes

include/SugarFolders/SugarFolders.php, modules/InboundEmail/InboundEmail.php
This PR contains a fix for Compose Email Popup.
'From' field failed when trying to retrieve options for drop-drown select.
ref: SCRMBT-21
Error log shows up a message: [FATAL] Exception in Controller: Cannot tell if the inbound email account is a personal account or a group account.
@daniel-samson: Can you please look at your two new function in https://github.com/salesagility/SuiteCRM/commit/73d21ca5ffde14256dcda033afdff4b269d3637a#diff-2aadc7f50e2480defbfecef7a0295a66
Problem was the database doesn't store string values in a bool field or mssql driver doesn't retrieve strings when the value is bool in this field: 'inbound_email.is_personal' but the IF condition with '===' check for strings and it's failed in each possible case.
In same time, these function returns are bool typed values …
=> Fix scrmbt 21 email check mssql

modules/ModuleBuilder/parsers/relationships/ManyToOneRelationship.php
No issue raised. PHP warnings in module builder due to method declarations not matching the abstract.
```
Warning: Declaration of ManyToOneRelationship::setReadonly() should be compatible with AbstractRelationship::setReadonly($set = true) in /.../modules/ModuleBuilder/parsers/relationships/ManyToOneRelationship.php on line 0
Warning: Declaration of ManyToOneRelationship::buildLabels() should be compatible with AbstractRelationship::buildLabels($update = false) in /.../modules/ModuleBuilder/parsers/relationships/ManyToOneRelationship.php on line 0
```
Go to ModuleBuilder and create a module.
There are many nasty code formatting issues in this file and this module as a whole. I have not attempted to fix those as there are other PRs that deal with code formatting.
=> Fix non-matching delaration of relationship methods in ModuleBuilder

include/generic/DeleteRelationship.php, include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
This change removes the "Remove" button from the roles sub-panel in user profile when a user does not have access to roles. It also ensures that a user cannot remove a role relationship if they do not have access to aclroles.
1. As a non-admin user go to user profile
2. Click cancel
3. Check that the "Remove" button does not appear in the roles sub-panel
=> Fixed - Relationship removal access issue

modules/Emails/Email.php, modules/Emails/include/ListView/ListViewDataEmails.php
Task: SCRM-663
Display names with umlauts are broken in the latest sCRM email-client:
The Array "$this->to_addrs_arr" contains:
[0] => Array ( [email] => xyz@abc.de [display] => nig )
Where it should be "König". Strings are broken off after the Umlaut.
Issue reference: #3791
1. Receive an email with an umlaut containing name
=> Fixed #3791 - Problems with Umlauts in E-Mail-Client

modules/Emails/Email.php
Task: SCRM-692
Both imported and archived emails do not have the "From" field populated.
Issue reference: #4033
1. Import an email and check that the "From" field has been populated in the detailview
2. Open an archived email and check that the "From" field has been populated
=> Fixed #4033 - Email DetailView does not show recipient/sender-data

modules/Alerts/templates/default.tpl
"SuiteR+" is creating the error.
I have changed this to SuiteP so that it works for me. However, shouldn't this be a function that determines what theme is active for user and returns the correct theme name?
Thoughts?
This fixes bug described in Issue #4104 4104
It stops unnecessary errors from being logged.
SuiteCRM is trying to look for an image in a theme that does not exist anymore
- [X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
=> Fix for Issue #4104 - Incorrect reference to Suite R+ 

modules/AOS_PDF_Templates/templateParser.php
Fix  - #2247 MultiSelect field issue in PDF
Issue: Multi select displays key instead of value. To recreate create a multiselect with different keys and values, then create a pdf template which uses this field. 
It solves the bug of multi selects displaying the key instead of value.
Create a multiselect field(or use existing) where the key is different to the value. Then create a pdf template with this field in it, and print to pdf.
=> Fix  - #2247 MultiSelect field issue in PDF

README.md, modules/Import/views/view.step3.php
When you are importing, on Step 3 you can click "< Default Value". After clicking this the option to hide it again should be shown with "> Default Value". It is not currently shown and is just blank.
This Fixes that issue
Allow you to hide the default value entry.
Try importing and clicking default value and see that it is blank. Apply fix and see that you can now hide it again.
=> Fix Default Value in Importer

modules/AOS_PDF_Templates/language/en_us.lang.php
Fixed #4290 - Reinstate strings for PDF templates  - "Samples" dropdown 
Without the fix it contains empty options, though these option actually work well if you select them.
Menu ALL / PDF templates
Before fix: "empty" Load Sample drop-down menu:
====== After fix: fields are visible
Note 1: A quick repair (or a logout) is required to make strings visible
Note 2: Crowdin project already fixed
=> Fixed #4290 : Unresolved labels in PDF Template samples

.gitignore
Microsoft Visual Studio is a free IDE that can be used for PHP projects, including SuiteCRM.
This makes the generated project files be excluded from Git, similarly to what is already there for other IDE's.
Note: this was previously done in #3221 where it was already labeled `Assessed` and `Ready to Merge`
=> Add Visual Studio exclusions to .gitignore

modules/Cases/language/en_us.lang.php
English edits to avoid issues on translations.
"Update Text" to "Updates - Text" - this is a field for Case updates with text only
the english wording causes translations as an "action to update some text"
"Update attachment form" to "Updates - Attachment form" - Form for attachments on case updates
the english wording causes translations as an "action to update the attachment form itself"
Wrong context translation
Note: no GIT issue created.
=> Attachment form translation

jssource/src_files/modules/Users/DetailView.js
#4301 
Replaced
jssource/src_files/modules/Users/DetailView.js
with 
modules/Users/DetailView.js
On repairing js DetailView.js gets overwritten with old version from jssource. This breaks User module modal functionality
Repair js in stock 7.8.6 
Try to change users password from drop down in detail view this throws javascript error
=> Fixed #4301 : Repair JS Files Overwrites DetailView.js with old version

themes/SuiteP/css/editview.scss
Addressing Issue #2203 regarding overflow of text.
Changed ```white-space: no-wrap``` on line 609 to ```white-space: inherit``` within editview.scss
Reasoning behind this is to stop the overflow (escaping) of text from the containing div when a long string is entered into a field in a detail view.
To resolve a bug flagged by the users where the display would become messed up if they exceeded the space of the div with the input into the fields to enhance user experience should they require to input long information.
* Go to Accounts or Contacts
* From the list view and click on the name to enter the detail view.
* In the address inline edit, apply a long name such as:
```
THIS IS A REALLY REALLY LONG DESCRIPTION OF A LATIN AMERICAN STREET ADDRESS WITH MULTIPLE  DETAILS ON NEIGHBOURS …
```
=> Fix #2203 - Overflowing text from div container

themes/SuiteP/modules/ModuleBuilder/tpls/layoutView.tpl
Due to a missing {assign}, the label was not being assigned properly, causing the layout slots to show the wrong title.
Add missing {assign} as per the default template.
Edit a layout of a custom module while using no translations and the SuiteP theme.
=> Fixed #4220 -- Layout editor showing incorrect labels in SuiteP.

modules/AOW_Actions/actionLines.js
Fixes an issue with workflows not displaying actions properly.
Issue reference: #4401 
1. Create new workflow with almost one action.
2. Save the workflow.
3. Edit the previously created workflow.
4. Check that the action is displayed correctly.
=> Fixed #4401 - On 7.8.7 LTS Workflow actions are not displayed on Edit View

include/ListView/ListViewSubPanel.php
Fixes an issue with PHP Fatal error:  Can't use method return value in write context when using a PHP version lower than 5.5.
Issue reference: #4380 
1. Enter a list-view like accounts.
2. Click on a record to enter detail-view.
=> Fixed #4380 - 7.9.6 Cannot view account details

themes/SuiteP/css/navbar.scss
Sub-panel quick create form is not visible while using SuiteP with a mobile browser.
Issue reference: #4180
1. Repair & Rebuild.
2. Rebuild SASS.
3. Enter an accounts detail-view.
4. Open the opportunities sub-panel.
5. While in mobile view with a width less than 750px, click "Create".
=> Fixed #4180 - SuiteP quickcreate forms not visible in mobile

modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php
Fix UndeployedMetaDataImplementation::getFileName() to match the signature of the base class.
The getFileName function in UndeployedMetaDataImplementation is
different from the other implementations, since it allows using
alternate packages. Since it is no longer a static function, separate it
into getFileNameInPackage and change getFileName to assume the
instance's package, so it is compatible with the base class.
This should bring it into line with the usage of getFileName in the
other implementations.
Also, repair the broken phpdoc on getFileName.
I was unable to add one-to-many relationships in the Module Builder because PHP was generating fatal errors.
In the module builder, create a package and create a module in the package. Attempt to add a one-to-many or many-to-one relationship …
=> Fixed #4213 - Cannot edit Layouts in Module Builder

themes/Suite7/tpls/header.tpl
Typo: Triple quotes instead of only two
=> Typo: Triple quotes instead of only two

include/language/en_us.lang.php
TinyMCE editor name should be written without a space as in TinyMCE
Fix https://github.com/salesagility/SuiteCRM/issues/4328
Proper brand name for a 3rd party software
Actual format: Tiny MCE
Brand name, see: https://www.tinymce.com/
=> Fixed #4328 - TinyMCE brand name

include/SugarFields/Fields/Html/SugarFieldHtml.php
This change corrects an issue with display encoded html inside the tinymce editor, while respecting the security issues.
Fixes the issue.
* Install SuiteCRM / Run Repair And Rebuild
* Create a PDF template or use a field which has an html field.
* Save the PDF template
* Edit the PDF template again
Test Fails if you see encoded html tags in the description.
=> Fixed #4375  - PDF Template Editor Shows Only HTML

modules/EmailMarketing/EmailMarketing.php
User time zone was not being set for TimeDate object and was defaulting to UTC. This was then being converted to UTC for database storage assuming the correct timezone had been set resulting in the wrong time being written to the database.
Created DateTimeZone from user preferences then used this when creating DateTime object from date string
The email campaign was not saving time correctly
create a newsletter marketing campaign, when adding date and time for campaign use xdebug to follow code through on save function for EmailMarketing.php. Check that DateTime being passed to TimeDate->asDB has correct timezone set from user preference.
Check that correct time has been created for email campaign
=> Fix #4088 Campaign Scheduler Changes Date/Time

.github/CONTRIBUTING.md, suitecrm_version.php
The link for the forum in CONTRIBUTING.md is incorrectly formatted leading to a 404 page
People who would like to contribute may click on this link and it goes to a 404 page
Try clicking on the link in master versus this branch
=> Link for forum in CONTRIBUTING.md is wrong

themes/SuiteP/include/MySugar/javascript/retrievePage.js
We apply the fix sugested in [here](https://github.com/salesagility/SuiteCRM/issues/4272#issue-258447993)
It's not possible to Add Tabs to Home Page of SuiteCRM using Firefox
Open SuiteCRM with Firefox, and try to add a new Tab to Home Page
=> Fixed #4157 / #4272 - Adding new tab on dashboard using Firefox is not possible

modules/AOR_Reports/tpls/EditViewFooter.tpl, suitecrm_version.php
Fixes issue #1532
Originally seemed fine on Chrome, but resulted in broken functionality in Firefox.
Resulted in broken functionality in FireFox on certain scenarios - corrected to enable a fully working experience.
Taken from the comments on the issue:
* Begin Creating a report by clicking the "Create" button on the right of the screen. On the report, you are unable to change tabs. (i.e, Fields, Conditions, Charts)
* If you have a report in the "Recently Viewed" panel, (Either on the Left of the CRM, or the one found by hovering over "Reports" on the Navigation bar), Click the Pencil icon to go straight to the Editview for this report. Then, you are unable to change tabs. (resolved with provided fix)
=> Fix #1532 - Adjusted JS for Condition Line Views

include/MassUpdate.php
Fix mass update of int fields.
generated HTML was 
<input name="Array" size="12" id="Array" maxlength="10" value="" type="text">
instead of 
<input name="FIELD_NAME" size="12" id="FIELD_NAME" maxlength="10" value="" type="text">
int fields can be added to Mass Update but changes were not saved.
=> Fix MassUpdate for int type fields

modules/ModuleBuilder/javascript/SimpleList.js, modules/ModuleBuilder/parsers/parser.dropdown.php
#1456 - Dropdown Editor: Display Label with single quotes is cut to save
=> Fixed - #1456 - Dropdown Editor: Display Label with single quotes is cut to save

data/SugarBean.php
Audit does not record the changes when setting value on a related field that was empty.
When a related field is not informed, is not pushed to `$fetched_rel_row` array. My change pushes this related field to `$fetched_rel_row` as empty.
See issue #4607
=> Fix #4607 - Audit does not record the changes when setting value on a related field that was empty

modules/ACL/ACLController.php
A lot of PHP Notice:  Undefined index: module when using REST API
Not sure in which branch this PR should be merged.
Added isset($_REQUEST['module']) in CheckAccess function.
Minor issue with PHP notices
=> Fix notices in REST API

themes/SuiteP/include/DetailView/DetailView.tpl, themes/SuiteP/include/EditView/EditView.tpl
When a User upgrades from SugarCRM, any JavaScript customisation break on the panels. This is due the change after SuiteCRM 7.7.x, where the panels in the editview and the detail view were changed from tables to divs.
This change adds the old class and a data-id attribute to allow these scripts either continue to work or at least be easy to update.
=> Fix detail panels on upgrade

lib/SuiteCRM/API/v8/Controller/ModuleController.php, lib/SuiteCRM/API/v8/container/ApplicationLanguage.php, lib/SuiteCRM/API/v8/route/moduleRoutes.php, lib/SuiteCRM/Utility/ApplicationLanguage.php
Added a route for retrieving the application language strings.
Adds one new route at /api/v8/modules/meta/languages which returns all the application language strings.
=> Feature/restapi - Application language strings

modules/AOS_Products_Quotes/AOS_Utils.php
To unformat_number()  is passed only variable name instead of the variable value from object.
This results that  *_usdollar fields of invoices and quotes don't have values.
Copy of PR #4454
=> Fix variable assignment in AOS_Utils::perform_aos_save()

modules/AOR_Charts/AOR_Chart.php
render('') generates an error with imagepng function for PHP 5.4 and higher.
Must be replaced by render(NULL)
See http://php.net/manual/fr/function.imagepng.php
Copy of PR: #3819
=> Fix error with PHP 5.4 and higher

modules/AOS_Quotes/converToInvoice.php
Previously, when creating an invoice, it would create new line items for each item in the quote but use the existing group. This meant that if you modified a quote then the totals on the invoice would be wrong. To reproduce bug:
1. Create a quote
2. Convert to invoice
3. Modify quote so that the total is different
4. Look at invoice and see the totals are now wrong
Copy of PR: #3907
=> Fixed Bug in Quote to Invoice Conversion

data/Relationships/One2MRelationship.php
One2MRelationship::add() functions last command is to call parent::add() function but it does not return value which is returned from parent::add(). 
Documentation states that it should return boolean value:
`@return boolean true if successful`
Copy of PR #4228
=> Added return instruction to One2MRelationship::add() function

include/Smarty/plugins/function.sugar_link.php
Actual links in suite look like:
`<a href="?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DHome%26action%3Dindex" id="moduleTab_Home" module="Home">Home</a>`
"module=xxxx" is no valid html attribute, so it should be:
`<a href="?action=ajaxui#ajaxUILoc=index.php%3Fmodule%3DHome%26action%3Dindex" id="moduleTab_Home">Home</a>`
Copy of PR #4388
=> module="xxx" is not a valid attribute for an a tag

install/installConfig.php, modules/Campaigns/WizardEmailSetup.html, modules/Configurator/tpls/adminwizard.tpl, modules/EmailMan/tpls/config.tpl, modules/Emails/templates/editAccountDialogue.tpl, modules/Emails/templates/outboundDialog.tpl, modules/Users/tpls/EditViewFooter.tpl, modules/Users/tpls/wizard.tpl
Allows the usage of SMTP usernames and passwords that are over 64 characters.
Issue reference: #4173 
1. Go into the admin panel -> email settings.
2. Set an SMTP username and password above 64 characters.
3. Check that the set SMTP settings work correctly.
=> Fixed #4173 - SMTP Password form input fields contain a max length of 64 (should be larger)

modules/AM_ProjectTemplates/tpls/ListViewGeneric.tpl
Fixes the wrong labels being displayed in basic/advanced search when in the project templates module.
Issue ref: #3716
1. Go into project templates.
2. Delete all records or do a basic/advanced search.
=> Fixed #3716 - Project templates - Wrong labels

modules/EmailTemplates/vardefs.php
Fixes email templates from having a maximum size of 65,535 bytes due to having type TEXT.
Issue reference: #3811
This allows users to create email templates that are above 65,535 bytes and not have the email template get truncated.
1. Create an email template with a size over 65,535 bytes
=> Fixed  #3811 - Direct html content gets truncated - incomplete html

include/EditView/EditView.tpl
Tabcount should count only Tabs and not Panels 
In Detailview it is correct:
https://github.com/salesagility/SuiteCRM/blob/e0a0a9cd8ad2f01049ef2d412f024fb435151652/include/DetailView/DetailView.tpl#L52-L59
Copy of PR #4398 for use in hotfix-7.8.x
=> Tabcount should count only Tabs and not Panels

modules/AM_ProjectTemplates/views/view.edit.php
Fixes project templates not being duplicated when a user clicks "Actions -> Duplicate" and instead returning a blank screen.
Issue ref: #2992
1. Create a project template.
2. Enter project template detail view.
3. Click actions -> duplicate.
4. Check that the template has been duplicated
=> Fixed  #2992 - Cannot Duplicate Project Template

modules/AOS_Quotes/converToInvoice.php
Previously, when creating an invoice, it would create new line items for each item in the quote but use the existing group. This meant that if you modified a quote then the totals on the invoice would be wrong. To reproduce bug:
1. Create a quote
2. Convert to invoice
3. Modify quote so that the total is different
4. Look at invoice and see the totals are now wrong
Relates to issue #1394 
Fixes a bug
Create a quote and then convert to invoice. Modify the original quote and then ensure that the totals are still correct on the invoice.
=> Fixed #1394 - Bug in Quote to Invoice Conversion

install/install_utils.php
My system is failing on the redirect due to the path being case sensitive ( API !== api).  The files are stored in "API" and thus the rewrite should be to the correct path.
Unable to use the instance after running `php tests/install.php`
Run the `tests/install.php` and attempt to run the tests or go to the api in the instance.
=> Fix API controller path due to case sensitivity

modules/Emails/include/ComposeView/EmailsComposeView.js
Fetches the correct language strings for the popup which informs about the body and subject being replaced by the template.
Issue #4649
=> Fix #4649 Compose Email: Fetching the correct language strings for popup

modules/CampaignTrackers/vardefs.php
Changes the vardef tracker_name length from 30 characters to 255. This fixes click trackers from getting truncated after the 30th character.
Issue reference: #3316 
1. Create a campaign
2. Insert a click tracker with more than 30 characters
=> Fixed #3316 - Click tracker is truncating the urls after the 30th character

modules/Emails/EmailsController.php
Added a check to make sure language strings are present and loaded when displaying the Compose modal from other modules such as Contacts or Accounts.
Issue #4653
The Compose modal was not loading any of the Emails language strings.
In the Accounts module, from the activities subpanel select Compose Email.
Hover the mouse over any of the buttons in the modal footer and see that the tooltip is not 'undefined'.
=> Fix #4653 Compose Email Modal Language Strings

modules/Activities/Popup_picker.php
Fixed accounts view summary not sorting
Issue reference: #4502
1. Enter accounts module.
2. Open history sub-panel.
3. Click on the "View Summary" popup.
4. Check that each tab is sorted correctly.
=> Fixed #4544 - Accounts Summary List not sorted - 7.9.7

modules/Emails/Dashlets/MyEmailsDashlet/MyEmailsDashlet.data.php
Changed the Email Dashlet vardefs to use the same variable for the To field as the regular listview because the other was not being set.
Issue #4667
=> Fix #4667 Make To field in the Email dashlet display address correctly

include/ListView/ListViewColumnsFilterLink.tpl, include/ListView/ListViewSearchLink.tpl
Add missing attribute to make the buttons visible to screen readers using "alt" or "title" ...
Currently they see "void(0)".
Issue reference: #4671
=> Fixed #4671 - bug - bulk action, filter and column chooser missing attributes

modules/Audit/Popup_picker.php
Strict Standards: Non-static method Audit::get_audit_list() should not be called statically, assuming $this from incompatible context in /crm/modules/Audit/Popup_picker.php on line 104
Issue reference: #942
=> Fixed #942 - PHP strict warning

modules/Schedulers/Scheduler.php
Additional of the wrong method was being used, also by multiplying the result with 1, it makes sure that that the result is numeric. This was causing warnings on PHP 7.1. Code to reduce leading zeros is not needed anymore.
=> Fixed #4496 - bug wrong SugarDateTime minutes method used

modules/InboundEmail/InboundEmail.php
When a user accesses the emails module. If they have Inbox which have a large number of emails (or greater than 2000 emails), the have to wait in excess of 60 seconds. 
This change helps to improve the performance by up 12x, when the user is not using a filter. It still takes on average around up to 10 seconds to load, hover this is an improvement on the 60 seconds I mentioned earlier.
I tested these loading times against my inbox which has around 6500 emails in it. I was running this on my local computer.
Due to the limitations that we cannot cache the emails, we can only improve the performance on the sort by date field.
- Set up emails
- Access emails module
- Measure loading times.
=> Improve non filtered email performance

themes/SuiteP/tpls/_headerModuleList.tpl
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /cache/smarty/templates_c/%%F6^F60^F609237E%%_headerModuleList.tpl.php on line 985
=> PHP Warning count(): Parameter must be an array in headerModuleList.tpl

modules/AOP_Case_Updates/CaseUpdatesHook.php
At AOP and Case flow.
In the area "Admin>AOP Setting > Case Status Changes" not running.
=> Fixed #3374 – Apply Status to Case Updates

modules/Campaigns/WizardMarketing.html
See issue #3703
Made the Datetimecombo use the correct separator between hours and minutes in a time string, depending on the user settings.
It was always using the 23:00 format when sending the start time for the campaign, causing the Datetime convert to fail when the user format and expected input was in the 23.00 format.
It should solve #3703 
1. Go into the user profile and set the time format to 23.00
2. create a campaign
3. create a template
4. go back to view campaigns
5. select/edit campaign
6. click "next" to go to Marketing
7. enter a date, marketing email name and other required fields
=> Fix #3703 Make time use the correct separator

modules/EmailTemplates/EmailTemplate.php, modules/EmailTemplates/vardefs.php, tests/unit/modules/EmailTemplates/EmailTemplateTest.php
Removed the ability to inline edit the DATE_ENTERED and DATE_MODIFIED dates in the ListView (they shouldn't be editable).
Made the DATE_MODIFIED display in full in list view (it was being truncated to only show the date but not the time, which doesn't make much sense and is not consistent with the way the DATE_ENTERED is shown right next to it).
Deleted 2 obsolete lines from the get_list_view_data() function (the globals are not being used and the comment is some old code).
Removed the function entirely as it is now identical to the parent function it extends.
The date fields shouldn't be editable in ListView.
The dates should display in full.
=> Fix Email Template ListView date issues

include/SubPanel/SubPanelTiles.php, themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
In SuiteP when the subpanel is minimised, it still loads the subpanel data.
In previous themes, it would load the contents via ajax when the subpanel is maximised. This can be a huge performance hit, and the functionality should be restored.
When building the subpanels before displaying a record, we check if each subpanel will be shown expanded or collapsed by default, and in the latter case we don't preload the contents.
The expand button has been modified to load the contents of the tab being expanded at that moment.
Improves performance.
=> Feature: Only load Subpanels when they are expanded

modules/AM_ProjectTemplates/AM_ProjectTemplates_sugar.php
Enable importing Project Templates
Clicking on the import button in the Project Templates module presents the user with a popup box that reads:
'Imports are not set up for this module'
=> Fix: Enable importing Project Templates

modules/Calendar/Calendar.php
Make the calendar recognize 'basicWeek' as a type of week.
Issue #4753
=> Fix #4753 Error with basicweek dates in the calendar

modules/AOS_PDF_Templates/templateParser.php, modules/AOW_Actions/actions/actionSendEmail.php
The templateParser was identifying any field from the AOP_Case_Updates module as a date field and truncating the content to one word.
Issue #4742
=> Fix #4742 Make email variables replace correctly in AOP Case Updates

modules/Emails/Email.php
Change the names of the fields in which the Email object stores the to / cc / bcc addresses.
Issue #4517 
When fetching the addresses from the DB they were being stored in variables which according to the vardefs are deprecated (from_addr). The listview was expecting other variables (from_addr_name).
=> Fix #4517 Change deprecated field names

themes/SuiteP/css/suitep-base/editview.scss
Rescheduling a call in the edit view of calls was not possible as the the popup was greyed out.
This was solved by overriding the z-index of the popup panel and bringing the rechedule forward.
1) Create a call
2) Navigate to the edit call view via the dashlet
3) Use the dropdown menu and select Reschedule call
4) The popup should now be accessable
=> Fix issue #3902 reschedule greyed out.

jssource/src_files/include/SubPanel/SubPanelTiles.js
Make subpanels load asynchronously.
Show a loading image to give the user feedback.
Loading subpanels with a lot of content (or over a slow connection) was taking a long time and the user wouldn't know why.
=> Make subpanels load asynchronously and show a loading screen

modules/AOS_PDF_Templates/vardefs.php
Changed the the type of the ''description" field to allow PDF templated with html tags to be saved.
Issue #4781 
Create a template with any kind of html tag.
It will no longer be removed.
=> Fix #4781 Change PDF templates field type to allow html tags to be saved

modules/Calls/Call.php
Avoid a silent crash when editing a call with no duration.
Issue #4440
=> Fix #4440 Make Call not crash on missing duration field

modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php
Fixed a possible bug introduced in 680896d4d6b16ca46ebfde21051b23b99de1f3bf which overwrites changes made in Studio.
Issue #4231
=> Fix #4231 Stop appending duplicated viewdefs

jssource/src_files/include/SugarFields/Fields/Datetimecombo/Datetimecombo.js
Fixes the vertical alignment of the Datetimecombo time element in views such as the Campaign Wizard and the New Meeting from calendar dialog. 
The time not being aligned correctly with the date.
=> Fix 7.10 Campaign field - schedule Time/date is out of allignment

jssource/src_files/include/javascript/sugar_3.js
Fix jquery dialog offset in listview
Jquery UI docs:
Note: The appendTo option should not be changed while the dialog is open.
List view tables have an 'i' hover button which revels a text box, this goes off screen.
=> Fix jquery dialog offset in listview

modules/Emails/include/ComposeView/EmailsComposeView.js
Adds functionality for loading template attachments into the compose view.
When selecting a template that has attachments it should now correctly load the attachments.
Additionally prevents duplicating the form elements that caused the duplicate attachment bug.
Most of the code is straight from the solution proposed by @KaKite
Issue #3925
Issue #3818 
Create an email template that has an attachment
Go into compose Email
Load the template
Send
Verify that email arrives with attachments
=> Fix #3925 and Fix #3818 email template attachments & duplicate attachments

include/SugarFolders/SugarFolders.php
Make sure only the own folders are visible to each user in his profile.
Issue #4842 
1. Log in as user A
2. In profile, create an inbound email account
3. Make sure it shows in Folder Management
4. Log in as user B
5. In profile, make sure the folder from user A is NOT shown in Folder Management
=> Fix #4842 Only show folders of own email accounts in profile

modules/Project/chart.php
Modified the Resource Calendar to allow more space for longer links to previous and next month in other language.
Issue #4765
=> Fix #4765 Make links not truncate for lack of space

jssource/minify_utils.php
Updated the list of excluded folders for the JS minify utils.
Added 'upload'
Modified 'cache/' to 'cache'
Minify JS would fail sometimes if it encountered unexpected contents in the upload folder.
Also the cache folder was not being excluded because of a trailing slash character.
=> Avoid including cache and upload folder into JS minify path

modules/AOS_PDF_Templates/TemplateSampleService.php, modules/AOS_PDF_Templates/samples/smpl_Account_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Contact_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Invoice_Group_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Invoice_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Lead_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Quote_Group_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Quote_Sample.php
Modified the default template samples for AOS_PDF_Templates module to use the absolute path to the CRM logo instead of the relative path to avoid it not showing up in emails.
Replicates #4739
=> Make Template Sample use absolute Logo URL 7.8.x

modules/AOS_PDF_Templates/TemplateSampleService.php, modules/AOS_PDF_Templates/samples/smpl_Account_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Contact_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Invoice_Group_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Invoice_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Lead_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Quote_Group_Sample.php, modules/AOS_PDF_Templates/samples/smpl_Quote_Sample.php, modules/Emails/include/ComposeView/EmailsComposeView.js
Modified the default template samples for AOS_PDF_Templates module to use the absolute path to the CRM logo instead of the relative path to avoid it not showing up in emails.
Issue #4736
=> Fix #4736 Make Template Sample use absolute Logo URL

modules/AOR_Reports/AOR_Report_Before.js
Make the tooltip data load from JS instead of Smarty TPL (because it's not a template)
Issue #4766
=> Fix #4766 Make tooltip load language string correctly

include/SugarObjects/templates/person/Person.php, modules/Users/User.php
Moved the User Profile specific save function from the parent Person class to the User class.
Issue #4780 
This function being called from any of the classes inheriting from Person except User would result in an error message being thrown due to the function expecting to be called only from the User module.
=> Fix #4780 Move User specific save function from parent to User class

themes/SuiteP/css/editview.scss
Date picker was showing behind the popup display.
The z-index was changed to allow the date picker to be accessed and in full display.
1) Have the 'Outcome By Month' dashlet on display
2) Click the edit icon
3) Click on the date icon to select a date
The css will need to be rebuilt for this change.
=> Fix #4176 Date Picker

modules/AM_ProjectTemplates/css/style.css, themes/SuiteP/css/listview.scss
This is a fixed version of [this PR](https://github.com/salesagility/SuiteCRM/pull/4809)
=> Fix-540 modal dropdown #4809

data/SugarBean.php
In some cases sugar retrieves more object of the edited type. This leads to that the optimistic locking id is not the one thats in the edit view, but some other (maybe from relation).
So if someone saves the same record in a different session, the one that saves later simply overwrites the first changes, and does not show the dialog for conflicting saves.
This change makes sure the id from the request is stored in the session, not the id from the last fetched record that maybe from a related bean.
On conflicting saves under specific circumstances the conflict dialog is not shown.
Not quite sure about the exact requirements for this bug. I assume it is some custom relationships, that relate to the same module, or to an other module and then to the same module again.
Expected:
When saving a …
=> Optimistic Locking not working in some cases

themes/SuiteP/css/main.scss
Popup after save click on studio edit was not clickable.
The index of the mask was reduced to allow the popup to be accessible. 
1) Navigate to studio module
2) Select a module to edit
3) Navigate to Edit View inside Layouts
4) Select save
=> Fix studio popup.

modules/Emails/include/ListView/ListViewDataEmails.php
Solution proposed by @likhobory 
Properly decodes special characters in email from addresses.
Issue #3626
=> Fix #3626 Decode from address names with special characters

modules/OutboundEmailAccounts/language/en_us.lang.php
Fixed typo in outbound email LBL's:
'LBL_SMTP_FROM_NAME' => '"From" address',
'LBL_SMTP_FROM_ADDR' => '"From" name',
Issue reference: #4942
=> Fixed #4942 - Name and address fields labels switched?

include/SuiteGraphs/RGraphIncludes.php, modules/Charts/Dashlets/MyPipelineBySalesStageDashlet/MyPipelineBySalesStageDashlet.php
Makes the URL for drilldown filtering use the item name instead of the label.
Issue #4984
=> Fix #4984 Make my pipeline dashlet not use labels for drilling down URL

themes/SuiteP/themedef.php
Relation to https://suitecrm.com/suitecrm/forum/feedback/17448-suitecrm-7-10rc-no-theme-when-i-switched-the-default-language
This change corrects the default theme.
- Fixes a bug in the new color scheme logic.
- Install a language pack
- Goto admin
- goto locale
- change language.
- log out
You should still be able to see the theme colors.
=> Fix default color scheme

modules/AOS_Quotes/controller.php
Remove first empty line from quotes export CSV file
Before:
After:
This fix quotes export CSV file by remove first empty line
1. open quotes list view
2. select at least one quote
3. from bulk action menu select "Export"
4. before and after described in "Description" block
=> fix(Quotes): Remove first empty line from quotes export CSV file

include/SugarFields/Fields/Datetimecombo/EditView.tpl
Fixes a smarty syntax issue.
Issue reference: #5029
Check that the date selector in calls and workflows works correctly.
=> Fixed #5029 - DateTime calendar popup button & manual edit of data entry doesn't work in 7.9.10

include/SugarFields/Fields/Multienum/SugarFieldMultienum.php
Fixes this
```php
WARNING: [2] Declaration of SugarFieldMultienum::displayFromFunc
($displayType, $parentFieldArray, $vardef, $displayParams, $tabindex) should be compatible with
SugarFieldEnum::displayFromFunc
($displayType, $parentFieldArray, $vardef, $displayParams, $tabindex = 0) on line 124 in file 
/home/meldooco/public_html/include/SugarFields/Fields/Multienum/SugarFieldMultienum.php 
```
A couple of User reports on the forums
https://suitecrm.com/forum/suitecrm-7-0-discussion/17070-importing-contacts-from-excel-csv
https://suitecrm.com/forum/suitecrm-7-0-discussion/17076-multi-select-error-warning-message
**Please note that this was breaking the app, it's not just an error in the logs.**
Please see forum threads
=> Fix PHP Warning in Import wizard

modules/ModuleBuilder/MB/MBModule.php
Fixed Deprecated: Non-static method MBModule::getTypes() should not be called statically in /.../modules/ModuleBuilder/views/view.module.php on line 74
Issue reference: #5054 
Issue reference: #4139
=> Fixed #5054 - Broken HTML in new module dialog in module builder

include/SugarObjects/templates/basic/language/en_us.lang.php, themes/SuiteP/modules/SavedSearch/SavedSearchForm.tpl
The direction option was missing corresponding labels which made it unclear which option had a certain impact on the filter.
This fix allows the lables to be displayed so the user can see how the results will be ordered.
1) Navigate to one of the modules (e.g. Emails)
2) Select view on the side navigation
3) Select advanced filter options
4) View the directions radio buttons at the bottom of the page
=> Fix missing labels for the directions of the filter

modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php, modules/Calendar/Dashlets/CalendarDashlet/CalendarDashletOptions.tpl
The calendar dhashlet was missing all of the labels related to this view.
The changes allow for all of the strings within the calendar dashlet to be visible.
1) Add the calendar dashlet to a tab
2) Click the edit icon 
3) View the correctly applied labels.
=> Fix missing labels in the calendar dashlet.

themes/SuiteP/css/suitep-base/forms.scss
In the inbound email settings module, when selecting folders, the list was displayed with both a vertical scroll bar and also a drop down arrow overlapping.
This fix removes both of these elements as they are not rquired in this instance.
1) Under the admin menu, select inbound email settings
2) Fill out the required information to allow a folder to be selected
3) Used any of the select buttons on the right hand side to select a folder
4) See that the list should not have out of place scroll options.
=> Fix styling issue regarding scroll bar and drop down arrow overlapping.

themes/SuiteP/css/suitep-base/editview.scss
In the Security Groups Management, the filter options has a '?' logo that can be clicked to provide the user with some hints and information. Currently the popup is displayed behind the original box.
1) Navigate to the Security Groups Management
2) Select Filter
3) Under the Advanced Filter tab, click on the '?' icon
4) View the popup as the front window
=> Fix help popup in security groups manager view.

modules/Emails/EmailUI.php
Fixed a stray linebreak in an html string which was causing line editing to fail.
After inline editing the email would show a garbage html value. The new value would be saved correctly but not displayed right.
Steps to reproduce:
- Enter accounts module list-view
- Inline edit an email address
=> Remove linebreak from html string

modules/ModuleBuilder/parsers/views/DashletMetaDataParser.php
Fixes an error when saving the dashlet layout in Studio.
PHP Fatal error:  Uncaught Error: Cannot access protected property DeployedMetaDataImplementation::$_history
See [this forum post](https://suitecrm.com/suitecrm/forum/suitecrm-beta/17411-change-dashlet-error)
=> Use getter to access protected field

modules/DynamicFields/DynamicField.php
A parameter that was being modified inside a function was being passed by value, and therefore the modification lost.
Issue #5095 
1. Create a custom relate field on Contacts
2. Set a filter based on the value. Subpanel shows filtered results.
3. Select a few records
4. Click Bulk Action/Export
5. Observe there is no error in the log
=> Fix #5095 Pass parameter that gets modified by reference

include/SugarEmailAddress/SugarEmailAddress.php
When user installs SuiteCRM with demo data, the email address in the account module appears to be missing.
- Fixes bug
- Install SuiteCRM with demo data
- Go to accounts
You Should be able to see the email addresses next the the demo accounts.
=> Fix email address seed data for accounts

modules/Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php
When a Calendar Dashlet is used a PHP Warning is logged every time the Dashlet reloads.
PHP Warning: Creating default object from empty value in /Calendar/Dashlets/CalendarDashlet/CalendarDashlet.php on line 66
Issue reference: #3279
=> Fixed #3279 - PHP Warning logged for Calendar Dashlet

include/SugarEmailAddress/SugarEmailAddress.php
This is the duplicate of #5117 for suitecrm 7.8.x
When user installs SuiteCRM with demo data, the email address in the account module appears to be missing.
- Fixes bug
- Install SuiteCRM with demo data
- Go to accounts
You Should be able to see the email addresses next the the demo accounts.
=> Fix conflict SugarWidgetSubPanelEmailLink and populateComposeViewFields

themes/SuiteP/css/suitep-base/forms.scss
Within the campaigns module, time fields were missing drop down icons.
This change adds in the drop down icons for the time fields within the campaigns module, making it clear that these fields can be changed.
1) Begin to create an email campaign
2) Navigate to the Marketing screen
3) Check the Schedule time and date to see if the boxes have dropdown icons
=> Fix missing drop down icon on time fields.

themes/SuiteP/css/listview.scss
SuiteP Theme - The Heading row on the "Geocoded Counts" table is a very light white, against a very light background, making it hard to read. This PR corrects this.
Replaces PR: #2497 , (Which is outdated, as it was made before the move to Sass.)
Related to issue: #2480
Makes the header row in the Geocoding Table, (along with a few other labels, such as "Related to" when composing an Email), more readable.
Navigate to the "Geocode Count" table in the Admin panel
=> Fixed - #2480 SuiteP Theme - Geocoded Counts Table Header unreadable

include/ListView/ListViewColumnsFilterDialog.tpl, include/MVC/View/views/view.list.php
Solves the issue where listview filters disappear when displayed columns are changed.
Works only with advanced search.
Adds an extra flag to the request when changing columns, which then loads the stored query (instead of starting with a blank query), then adds the changed columns to the storedQuery object, and saves it back.
Issue #4197 
1. Accounts-Listview - do an advanced search
2. use "choose column" to add some columns in listview
3. see the filter is still applied and the columns have changed
=> Fix #4197 Make listview remember advanced search parameters when changing columns

modules/Emails/javascript/ajax.js
Do not base the height of the quickcreate dialog on the nodes contained in the body because when cancelling and reopening it there are no nodes during the render and the dialog would have 0 height.
Issue #4482
email list view
click or double-click on email
click Quick Create --> Lead
click cancel
repeat Quick Create --> Lead
=> Fix #4482 Do not base height on nonexisting nodes

modules/jjwg_Areas/views/view.area_detail_map.php, modules/jjwg_Areas/views/view.area_edit_map.php, modules/jjwg_Markers/views/view.marker_detail_map.php, modules/jjwg_Markers/views/view.marker_edit_map.php
Fix #4970 Modules jjwg doesn't work
Add google api key to urls for maps in edit modes.
Added api key to url that pulls js from google maps
On add map area or map marker maps section displays an error stating api key not working
It enables users to use google maps on adding map markers and map areas.
Add map marker and map area after adding google api key in settings.
If map shows then it works
=> #4970 modules jjwg doesnt work

include/language/getJSLanguage.php, install/install_utils.php, modules/Administration/UpgradeAccess.php, modules/Import/views/ImportView.php
Fix #5025 Undefined when importing contacts
Fix all calls to module language file for modules without
load $mod_strings into SUGAR.language.languages and fix .htaccess redirect to entrypoint for generated language file in cache/jsLanguage/
This was causing undefined labels on message boxes and buttons specifically in the Import module. Though this will affect all modules that do not have a bean and therefor have to load the language file manually
Any entry point with module as parameter will redirect to actual module if module exists. Therefor cannot use parameter module to pass module name to entrypoint function.
Change htaccess generation code to update module to modulename
in .htaccess
RewriteRule ^cache/jsLanguage/(.._..).js$ index.php?entryPoint=jslang&module=app_strings&lang=$1 …
=> Fix #5025 Undefined when importing contacts

modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php, modules/Users/authentication/SugarAuthenticate/SugarAuthenticateUser.php
When two factor authentication is enabled, and the user enters the code incorrectly, SuiteCRM will send a new code to the users email. Resulting in the user recieving many auth codes.
This pull request changes the 2 factor logic to only resend the code when the user requests the code to be resent.
- Corrects the 2 factor functionality to meet software requirements
* set up email settings
* Go into password management
* set the 2 factor email template
* edit a user
* enable 2 factor authentication
* logout
* login
* enter code incorrectly
You should still only have one email code sent to you.
=> Preventing 2 factor authentication from resending lots of codes

include/SugarEmailAddress/SugarEmailAddress.php, modules/Campaigns/WebToLeadFormBuilderOptInCheckbox.tpl, modules/Campaigns/WebToPersonCapture.php, tests/unit/include/SugarEmailAddress/SugarEmailAddressTest.php
When a targe/contact/account/lead has not selected the checkbox to opt in from a web to person form. The suitecrm should mark the email address as not opted in.
This change updates the business logic to match the requirements in the description
* set up web to person form
* untick opt in
* you should not see an opt in status next to the record in the crm
=> Adding not opted in feature to Web To Person

themes/SuiteR/css/style.css
Slight modification of PR #2333
The changes made in PR2333 are a step in the right direction, but still leave a small gap in the screen resolution where the user would have no search view on the SuiteR theme, when using the legacy search fields.
The change made here covers this gap.
Related to issue #1208
Change allows user to toggle search on/off on specific resolutions when using SuiteR theme, and the old legacy search fields.
Enable legacy search fields
Navigate to the module with legacy searching
Minimize your browser/snap browser to the side of the screen
Ensure you can toggle on/off search fields.
=> Fixed #1208 - Search function in list view disappears in smaller windows

themes/Suite7/css/colourSelector.php
The change is the same as the 2nd commit found on the PR #2641
However, this PR has an unrelated commit associated with it.
So, this PR is created to merge in the correct change, to the correct branch, with ease.
This change corrects colorSelector.php to look for the \<header> tag, rather than an element with id "header"
Related to issue #2640
Allows users to change the top menu's colours on Suite7 theme.
Navigate to the Admin Panel -> Themes
Enter into the Colour Picker for the Suite7 theme
Change the colours for the top menu
=> Fixed #2640 - Suite 7 Theme Custom Header Color

modules/Campaigns/TrackDetailView.tpl
Change is the same as PR #2345
However, this one is pointed to the correct hotfix branch, whereas the previous PR is not.
Related to issue #2341
Change improves the appearance of Campaign -> View Status on all Themes
Create a Campaign, and click "View Status"
=> Fixed #2341 - In Campaign view status page, row out of box

themes/Suite7/css/style.css
Change is similar to the one provided in PR #2353 , However, I've changed the font-weight to normal, rather than bold, to keep consistent with the other themes in the system.
Additionally, This PR is pointed to the correct hotfix branch, whereas the linked PR (2353) is not.
Related to issue #2346
Text was unreadable on the Suite7 theme, as it was white text on a white background.
Create a Campaign, go to "View Status", and view the chart
=> Fixed #2346 - Campaign view status page color text issue

include/SubPanel/SubPanelTiles.php
Collapsed subpanels on legacy themes weren't loading on expansion
#5027
Change theme to Suite7 or SuiteR
Enable Collapsed subpanels under system settings 
Expand a subpanel and see if it loads.
=> Fixed #5027 - Subpanels on legacy themes not showing data on expansion

modules/Leads/views/view.showduplicates.php
Breaking because the variable name used does not exist, as it is spelled correctly on definition.
Effects 7.8.11, 7.9.x and 7.10
=> Typo in variable name dublicate -> duplicate, would break

include/language/en_us.lang.php, modules/AOR_Charts/AOR_Chart.php
references issue #1433
1. Removed the "Polar Chart" option from the charts dropdown.
2. Removed case "Polar" from AOR_Chart.php line 572
3. Removed getPolarChartData() and getPolarChartConfig() from AOR_Chart.php as they were only utilised by Polar Chart.
1. The polar chart option does not render anything in the Reports module.
2. Polar Chart is a synonym for Radar Chart which already exists in the module. Radar chart is a generally used term.
Reports module -> Create a new report -> add chart -> Polar Chart does not render anything
=> Fixed #1433 - Removed duplicate name Polar Chart.

modules/Cases/Case.php
Just add a variable assignment that should always have been there.
See Issue #5131
=> Fix #5131 make case_numer variable available to notification templates

modules/ModuleBuilder/views/view.property.php
Fixes this error:
`Strict Standards: Declaration of ViewProperty::init() should be compatible with SugarView::init($bean = NULL, $view_object_map = Array) in /modules/ModuleBuilder/views/view.property.php on line 150`
I didn't create an Issue for this. I am not using an IDE, just editing directly here on GitHub, so forgive me for not tidying up the file.
Error reported in Forums
https://suitecrm.com/suitecrm/forum/developer-help/17775-error-editing-fields-in-studio-layot-view
Please see Forum thread
=> Fix PHP Strict Standards SugarView::init() in ModuleBuilder/views/view.property.php

modules/FP_events/language/en_us.lang.php
Giving details to translators should be done as comments to language strings.
To make them visible in Crowdin system it requires needs to be in the same line so Crowdin displays it to translators (when working that string)
This info is in the hotfix only, not in hotfix 7.8 
See screen after fix:
=> Details as comments to language strings needs to be in the same line

install/seed_data/Advanced_Password_SeedData.php
This change adds a check to the Advanced_Password_SeedData so that we can call it from the upgrade packages. So that it the existing templates and settings are preserved on upgrade.
- Preserves settings
- Makes upgrade packages easier to build
- Make installer and upgrade packages
=> Adding checks to Advanced_Password_SeedData for upgrade purposes

include/SugarTheme/SugarThemeRegistry.php
Fixes a bug where the styles are not selectable when using a default language other than english.
Issue #5281 
Note: you can use english language to login and test!
1- Install a language pack
2- Go to Admin / Locale
3- Set default language to the installed language in 1
4- Go to Administrator menu / Profile/ / Layout options
5- the templates dropdown should be visible
=> Use the subtheme key

modules/Surveys/javascript/Survey.js, modules/Surveys/language/en_us.lang.php, modules/Surveys/tpls/Reports/other.tpl, modules/Surveys/tpls/reports.tpl
When viewing Survey reports the user clicks on the show all responses but it does not toggle the state so this can be confusing to the user. 
Toggle texts have been changed to show/hide responses
[if you don't have survey with text field, please, create a new one]
- go to survey report
- click on show responses
- see, if results are shows with the correct link text
=> change survey toggle

include/language/en_us.lang.php
Display label changed to make it more clear for the user to filter their search.
1) Navigate to the 'Contacts' module
2) Select filter
3) Navigate to the bottom of advanced filter
4) View the labels in 'Opt in Primary Email'
=> Fix opt in label in contacts filtering.

themes/SuiteP/tpls/_headerModuleList.tpl
A check has been put in place to stop email addresses being displayed in the sidebar navigation.
This fix is put in place as emails should not be visible in recently viewed.
1) Navigate to a contacts email address
2) Click on the email to enter compose
3) Afterwards, check to see if this is visible in the recently viewed
=> Fix emails addresses showing in the side bar.

data/SugarBean.php
Often when we're `grep`ing a log for errors this comes up. However, I don't think it's really a cause of concern. I am also basing this judgment on the fact that whoever put this line into the code made it a simple `DEBUG` level message.
So this PR is just to remove the word `error` from that message, so that people don't waste time looking for their problems in the wrong place. This has been happening a lot with email troubleshooting, people ask about this.
If this could please go into 7.8, 7.9, and 7.10, I would appreciate it.
=> Remove word "error" from a debug message

include/MVC/View/SugarView.php
Ensure the current active module link is displayed at the bottom of any tab group list even when the module list is greater than the max tabs limit.
As the module list is split into two arrays one for the main module list and one for an extra list which gets pushed to the groupTabs array after the main list in which the active module is contained. Added a condition to check if the list is greater than the max tab limit and if so also push the active module to the extra list also.
To ensure the shortcut tab group is still built correctly for the active module, rather than unsetting the current active tab at this point or simply not pushing it into the main list, it is unset after the array used for the shortcut tab functionality is built by looping through the groupTabs array and checking …
=> Fix Issue #2307

modules/AOP_Case_Updates/CaseUpdatesHook.php
Fixed by updating conditional statements to validate against email template id rather than the email template object which will always return true whether or not the template is set. Appears creation update had been fixed previously by validating the config value for the template but still saw fit to update the email template object validation to use the id as it was still present in the condition and removed the config value as it was unnecessary. Emails should no longer be sent when there is no template set in AOP settings.
AOP emails empty messages when cases are updated and no templates are selected.
Also occurs on case closure and was reported to occur on case creation but had been fixed in that case.
Issue #576 
1. Ensure you have Outbound Email configured with an smtp account or …
=> Fix Issue #576

ModuleInstall/PackageManager/ListViewPackages.php
Issue is on [this forum thread](https://suitecrm.com/suitecrm/forum/installation-upgrade-help/17932-upgrade-7-9-14-to-7-10-fails-when-uploading-file).
Error message was keeping the upgrade from succeeding, even after turning off display_errors. 
```php
[Mon Feb 26 12:25:21 2018] [error] [client 192.168.101.10] PHP Warning: Declaration of 
ListViewPackages::setup($data, $file, $where, $params = Array, $offset = 0, $limit = -1, $filter_fields = Array, $id_field = 'id') should be compatible with 
ListViewDisplay::setup($seed, $file, $where, $params = Array, $offset = 0, $limit = -1, $filter_fields = Array, $id_field = 'id', $id = NULL) 
in /var/www/html/suitecrm/ModuleInstall/PackageManager/ListViewPackages.php on line 42, referer: http://192.168.101.55/suitecrm/index.php
```
To get the …
=> Fix PHP Error in ListViewPackages.php

include/SugarObjects/templates/file/File.php
This change allows the Subject field to be visible in all views.
[#5327](https://github.com/salesagility/SuiteCRM/issues/5327)
1) Create a note with a subject field
2) Select this note to navigate to the Detail view
3) Check to see if the subject field is populated
4) Also, navigate to the edit view
5) View the subject field in this view
=> Fix #5327 Subject broken in Notes detail view

include/SugarEmailAddress/templates/optInStatusTick.tpl, include/generic/SugarWidgets/SugarWidgetSubPanelEmailLink.php
Removes a duplicate closing tag from the email link in listview after inline editing.
Removes dead code and makes use of the correct function EmailUI->populateComposeViewFields to show emails in subpanels
Issue #5173 
1. Go to Contact or other list view
2. Inline edit email address
1. View emails in subpanels
=> Make email addresses display work in subpanels and inline edit

modules/Campaigns/WebToLeadFormSave.php
Fixes a small encoding issue on the Web 2 Person form
String was being encoded to UTF-8 even though it is a UTF-8 string by default.
Issue #5167 
Create a campaign web2person form
Include some non latin characters in the form HTML (tinymce)
Save the campaign and see the characters are not garbled
=> Fix #5167 avoid duplicate encoding

include/SugarEmailAddress/SugarEmailAddress.php, themes/SuiteP/css/suitep-base/detailview.scss
It seems to be a rendering issue in windows instead of a css issue. Edge is correctly selecting the css selector. other browsers such as Firefox have the same issue on windows. The tick does will always be green regardless of the css.
The solution would be to use an icon instead, so that it is not using the unicode value.
- This ensures that the color of the confirmed opt in tick displays the correct colors in web browsers on Microsoft windows.
- Fixed #5174
- Rebuild sass
- Clear browser cache
- test the color of confirm opt in on Microsoft edge
=> Fixed #5174 - Confirmed Opt in tick - Microsoft edge

modules/Campaigns/WizardMarketing.html
In the email marketing screen in campaigns, the calendar popup does not show when you click on the button.
- fixes issue by add the id back into the button
- create an email campaign
=> fixing calendar picker in the campaign marketing screen

themes/SuiteP/css/suitep-base/suitepicon.scss
This fix re positions the expand icon into the middle of the display.
The expand icon was out of alignment.
1) Minimise the side bar,
2) View the expand icon.
=> Fix out of line expand icon.

modules/AOR_Reports/controller.php
override theme background background-color with white
see: https://github.com/salesagility/SuiteCRM/issues/5307
Reports pdf inherits user theme background-color, for SuiteP it is grey. 
when printing report it uses ink for nothing and report does not look pretty.
1- switch to SuiteP theme
2- run a report
3- download pdf
- [X ] New feature (non-breaking change which adds functionality)
=> Fix #5307 Set default pdf body to white

modules/AOW_WorkFlow/controller.php, suitecrm_version.php
Just removed an extra space on the PHP code that was added to the ID field.
Javascript code was failing on AOW Conditions operator dropdown when the selected option was changed.
- Edit a Workflow
- Add a condition
- Choose a field
- Change operator
=> AOW Conditions operator failing due to extra space on ID 

include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.php
Fixes a small bug with scheduled report where a function redeclaration would cause the module to crash.
Unsure under which circumstances SugarFieldCronSchedule->setup() would be called twice, but it happens sometimes.
1. Create a report
2. Create a scheduled report
3. Go into detail view and see it doesn't crash
=> Refactor map function to avoid declaring a function twice

include/MVC/View/SugarView.php
While using a language pack certain modules like products do not show the sidebar menu.
Issue reference: #5424 
1. Install a language pack such as PL.
2. Go into "Products" module.
3. Check that the sidebar displays correctly.
=> Fixed #5424 - Missing add product menu while using PL language - 7.10.1

install/language/en_us.lang.php, modules/UpgradeWizard/uw_utils.php
Removes check for allow-call-time-pass-reference which was removed in php 5.4.0
Issue reference: #4747 
http://php.net/manual/en/ini.core.php#ini.allow-call-time-pass-reference
https://docs.suitecrm.com/admin/compatibility-matrix/
=> Fixed #4747 - Allow Call Time Pass Reference is to be On or Off?

modules/InboundEmail/language/en_us.lang.php
Removed unnecessary &quot
Issue reference: #4717
=> Fixed #4717 - XTemplate doesn't support output escaping

modules/jjwg_Maps/views/view.map_markers.php
The URL of marker images in Maps were wrong
See #5356 
1.- Create a Map.
2.- Show that map 
3.- Verify that marker images are shown
=> FIX #5356 - The marker images URLs in Maps were wrong

modules/Accounts/Account.php
Fixes a bug in the Accounts export query generation, when exporting Accounts the generated query does not handle related fields correctly.
#4958 
Add a related field such as 'parent_name' or 'campaign_name' to the available fields on layouts filter and list views using studio
Filter accounts by this field, filter works fine
Select all accounts after filter and export them using export on 'bulk action' menu
The export works
=> Fix #4958 Replace related fields

modules/ModuleBuilder/tpls/labels.tpl, modules/ModuleBuilder/views/view.labels.php
Changes the name of the variable in which studio stores the language strings when editing labels, to avoid them being overwritten by the 'ModuleBuilder' module strings.
Issue #5432 
1. Click on Admin.
2. Click on Studio.
3. Click on a module
4. Click on Labels
=> Prevent studio labels being overwritten by generic module labels

jssource/JSGroupings.php
SuiteCRM can try to load in external YUI3 JavaScript not included YUI grouping file, when using HTTPS or internal instance this can cause functionality to fail
- Rebuild cache js, clear browser cache
- Go to the Calendar
- Click any slot to add a meeting
- See that no additional JavaScript files are attempted to be load in externally ,
- It will still try to load external CSS file, but are not necessary!?!
=> Fix #719 YUI https - Blocked loading mixed active content

include/SubPanel/SubPanelTiles.js, include/SubPanel/SubPanelTiles.php, jssource/src_files/include/SubPanel/SubPanelTiles.js, themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
Fixes a bug introduced in earlier versions causing subpanel collapse status was not being saved in cookies.
Issue #5280 
1. Enter any record with subpanels
2. Expand or collapse a subpanel
3. Enter another record of the same type
4. See the same subpanels are collapsed or expanded
=> Fix #5280 Set cookie to remember subpanel collapse status

install/install_utils.php
When troubleshooting in the forums, we often ask people to check for any errors in their `install.log`.
There's one particular message they always report about, which is 
`installerHook: Could not find custom/install/install_hooks.php`
That looks like an error, but it isn't. They say that file isn't there, where can they get it, etc.
So I'm suggesting a more explicit message.
Let's be wild and crazy and not test this.
This should go into all branches, 7.8, 7.9 and 7.10. Thanks
=> Change misleading message in install_utils.php

ModuleInstall/ModuleScanner.php, modules/Emails/Email.php, modules/ModuleBuilder/MB/MBModule.php, modules/ModuleBuilder/language/en_us.lang.php, tests/unit/modules/Emails/EmailTest.php
Currently deploying from module builder throws the following notice
```
==> ../logs/error_log <==
[Fri Dec 29 10:36:06.733469 2017] [:error] [pid 20671] [client ::1:36681] PHP Notice:  Undefined index: LBL_SEARCH in /srv/suitecrm/modules/ModuleBuilder/MB/MBLanguage.php on line 184, referer: https://suitecrm.localhost/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Dec 29 10:36:06.733494 2017] [:error] [pid 20671] [client ::1:36681] PHP Stack trace:, referer: https://suitecrm.localhost/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Dec 29 10:36:06.733502 2017] [:error] [pid 20671] [client ::1:36681] PHP   1. {main}() /srv/suitecrm/index.php:0, referer: https://suitecrm.localhost/index.php?module=ModuleBuilder&action=index&type=mb
[Fri Dec 29 10:36:06.733506 2017] …
```
=> Fix undefined notice "LBL_SEARCH" during Module Builder Deploy

modules/AOW_WorkFlow/aow_utils.php
Because, TCPDF could not read image content from download Entrypoint link. So, We need change image download link from entryPoint to image base path. I'll working.
1. Go to studio > Select any module (Module A) > create new field type of Image.
2. Create new record on Module A > select image for field type of image.
3. Go to Reports module > Create new report with Module A > Select image field to display.
4. On Edit dropdown button > Select Download PDF.
Expected:
- Image need showing on Report.
- [x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> Fix #5441: PDF report not showing image in the image field instead it shows a small red x

install/ready.php, modules/Schedulers/Scheduler.php
This fixes text instructing how to set up Scheduler jobs on Windows.
If a user has SuiteCRM on a different drive than the working directory of the batch file, the `cd` command would fail to change the drive.
So, if you're on `C:` and you type `cd E:\Suite` you're still left at `C:`.
You could either type two commands, `E:`, them  `cd \Suite`, or use the `/D` switch on  `cd`, which is what I propose.
Run Admin / Schedulers on Windows, see text is different at the bottom of the page.
I guess this is as low priority as it gets. :-)
But it does fool a few people, and they have to go ask in the forums...
=> Fix Windows cron instructions for cases where a Drive change is required

modules/UpgradeWizard/PasswordExpirationService.php, modules/UpgradeWizard/end.php, modules/UpgradeWizard/language/en_us.lang.php
Drung the upgrade of SuiteCRM, password expiry's set to zero and user be informed about that.
- upgrade Suite
- check the warning message about password expiry in the end.
- check password expiry changed in password management [or systexpiration => '' in config.php[]
=> set password expiry to zero when upgrading

modules/Import/views/view.confirm.php
When you click view import file properties in the importer, the example for name display does not show initially·
Show the example on the page load instead of only after modifying the field.
Fixes the example being blank
Begin to import a file, then click view import file properties - see the name example is blank. Apply fix and see that the example is there.
=> Fix example display in importer

modules/Emails/javascript/ajax.js
Set contH to document.body["scrollHeight"] as default.
#2927 - On second click body.childNodes[i] isn't available so height calculation defaults to original (default) setting. Setting this to document.body["scrollHeight"] ensure the height calculation works on subsequent clicks.
This changes ensures the the 'view relationships' pop up is viewable on multiple clicks.
Once implemented, requires rebuild JS grouping files.
For the email list, right click an email, select 'view relationships'. After the pop up opens, close it and repeat. The subsequent pop up will remain viewable, where previously it was limited to a height of 10px.
- [ x] My code follows the code style of this project found …
=> Fix #2927 - Emails View Relationship popup collapses on second use

include/javascript/tiny_mce/themes/advanced/skins/default/content.css, jssource/src_files/include/javascript/quickCompose.js, modules/Emails/javascript/EmailUICompose.js, modules/Emails/templates/dceMenuQuickCreate.tpl
I changed some style settings in the email composer that make using it a little easier. 
1) I increased the font size in the editor since the default was very small. 
2) I increased the quick compose window height since by default it didn't even show the email content without resizing the window.
I have been getting constant complaints about both issues.
Click compose email in the action tab with a lead, contact or account. 
- [X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
=> Email Composer Size Improvement

download.php, include/SugarFields/Fields/File/DetailView.tpl, include/SugarFields/Fields/File/ListView.tpl
I provide a link to preview documents.
include/SugarFields/Fields/File/ListView.tpl: Added an eye icon besides filename field to enable preview. This links to download entrypoint with preview=yes parameter.
download.php: Added header( "Content-Disposition: inline" if $_REQUEST['preview'] === "yes"
You don't always want to download PDFs or JPGs documents.
Go to documents list, look for a PDF or JPG file and click in the eye.
A new tab is opened instead of downloading the document.
Small new feature
- [X ] My change requires a change to the documentation.
=> Preview documents

modules/Tasks/Task.php
An empty override in Task::fill_in_additional_list_fields was preventing the parent_name field from showing correctly in List View.
Found and fixed by @Jason-Dang 
1. Create a couple of Tasks with Relate To records
2. See they show correctly in List View
=> Removes a blank inherited function preventing the parent from running

modules/Users/password_utils.php
Check for password expiration only when password was system generated
By default, 7.10 would ask users to change their passwords after 7 days even though the password was not system generated. The only way to disable this is to enable the generation of system generated passwords and disable password expiration.
Don't change any system settings, ie. make sure not to enable system password generation (and keep the default of 7 days password expiration in that section). Set the value of "pwd_last_changed" to a date more than 7 days old. Without my fix, you will be asked to change your password at login; with my change, you won't.
=> Fix for #5166

modules/InboundEmail/InboundEmail.php
Simple fix for #5544 
Adding a .'+' to the \DateTime::RFC2822 will make the pattern more tolerant and accept Date: headers with CFWS (comments)
Headers with or without CFWS will be tolerated:
RFC2822 date without CFWS:	"Date: Tue, 19 Jan 2016 16:51:02 +0300"
RFC2822 date with CFWS:	        "Date: Tue, 19 Jan 2016 16:51:02 +0300 (MSK)"
=> Fix for #5544

include/Smarty/plugins/block.minify.php, themes/SuiteP/include/EditView/tab_panel_content.tpl
Currently because of the smarty templating the label text has text around it which is is playing havoc with the CSS which states wrapping behavior.
This could be fixed by changing the css or by cleaning up the outputted html. I chose to go with the latter route.
P.s. as a note you can see this behavior even in [one of the screenshots](https://suitecrm.com/wiki/index.php/File:Release_notes4.png) of [7.10 Release Notes](https://suitecrm.com/wiki/index.php/Release_notes_7.10.0).
The edit form looks bad with the symbol wrapping around and into the label
1. Checkout branch
2. Clear template cache
=> Stop required symbol from wrapping on edit form

modules/SecurityGroups/SecurityGroup.php
Deprecated: Non-static method SecurityGroup::getGroupWhere() should not be called statically in /home/ccxxxx/public_html/suitecrm/data/SugarBean.php on line 3554
1. Check that the PHP error is no longer present on the homepage
Issue reference: #5586
=> Fixed #5586 -PHP error: Non-static method SecurityGroup::getGroupWhere() should not be called statically

include/language/en_us.lang.php, themes/Suite7/tpls/_globalLinks.tpl, themes/Suite7/tpls/_headerModuleList.tpl, themes/SuiteP/tpls/_headerModuleList.tpl, themes/SuiteR/tpls/_headerModuleList.tpl
The quick create labels at top are not responsive to change when i change say the module contact to be persons module. quick create will still say contact
Issue reference: #716 
1. Check that the quick create drop-down shows the correct values when changing a module name.
=> Fixed #716 - The quick create labels at top are not responsive to change

data/SugarBean.php
Use the appropriate module when translating the module name in assignment notications. Previously this would rely on the `mod_strings` matching the current bean which is not always the case.
Fixed #4287 - module name is incorrect in assignment emails in some conditions.
Follow the steps in #4287 - It should now show the correct module name in the email.
=> Fixed #4287 Use the correct module for module name translations.

modules/AOR_Fields/fieldLines.js
Allow format for datetimecombo fields in report's view
Previously format function were not allowed for date-time fields of type "datetimecombo".
Steps:
1. Create field of type "datetimecombo"
2. Create report and drag the selected field to the "Fields" section
3. Format options are not visible
Allow time format for custom date-time fields
1. Create field of type "datetimecombo"
2. Create report and drag the selected field to the "Fields" section
3. Format options should be visible
=> allow also time format in report for datetimecombo field

modules/AOR_Reports/Dashlets/AORReportsDashlet/dashletConfigure.tpl, modules/AOR_Reports/aor_utils.php
In some situations `getConditionsAsParameters()` in file `modules/AOR_Reports/aor_utils.php` line 161, return a array `$conditions=>field`  that contain a input tag like this:
```html
<input type="text" name="parameter_value[5]" id="parameter_value[5]" size="30" maxlength="255" value="3" title="" tabindex="1">
```
For this reason, the input form values are like this:
```html
<div id="">
<input type="hidden" name="parameter_id[]" value="7d0d3274-b3f7-6467-6a0b-57e2ae3f07c5">
<input type="hidden" name="parameter_operator[]" value="Equal_To">
<input type="hidden" name="parameter_type[]" value="Value">
Account - <em>ID Seller</em> - Like to 
<input type="text" name="parameter_value[5]" id="parameter_value[5]" size="30" maxlength="255" value="3" title="" tabindex="1">
</div>
```
For this …
=> Hotfix 7.8.x # Improvement in parameters for dashlet reports

modules/AOR_Reports/AOR_Report.php
Fix the issue https://github.com/salesagility/SuiteCRM/issues/3275 
At the end of each csv export there is an extra delimiter. For example you have
Field1,Field2,Field3,
Instead of 
Field1,Field2,Field3
- export any report into CSV
=> Fix 3275 - Remove extra delimiter at the end of the exported line

include/Smarty/plugins/block.minify.php
Fixes missing functionality in block.minify.php causing "An error has occurred, There was an error processing your request, please try again at a later time" when attempting to access a page that is using inline style.css in a custom label.
Issue reference: #5702 
1. Check for any regressions with #5282
2. Create a custom label using inline style (style=\'display:none\'). See #5688 for detail.
3. Check that the style correctly displays.
=> Fixed #5702 - Can't create new Target List in 7.10.4

include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
issue: #5639 
$emailUI->populateComposeViewFields has been incorrectly used in this
case, as it is meant to be used for the list view or detail view.
So I have recreated the link in
SugarWidgetSubPanelTopComposeEmailButton.php . The menu in the
activities subpanel should show the label "Compose email".
- Fixes bug
- Create an account or view an existing account
- In the detail view expand the activities sub panel
- Select the drop down menu inside toolbar of the subpanel
- You should see compose email link
=> Fixed #5639 - compose email link in activities subpanel

include/utils.php
Print the error message on `sugar_die()`.
See issue #2971
If the URL of a deleted CRM Record is entered into the browser a blank screen is displayed instead of an message. In the previous versions a message was displayed, something like
that the user either has no access or the record is deleted.
1. Create an Test-Call
2. Copy URL of Test-Call
3. Delete Test-Call record
4. Insert the copied URL of Test-Call in browser
5. It will display a blank page instead of error message as in earlier versions
=> Fix 2971 - A blank screen is displayed instead of an message

modules/Emails/include/ComposeView/EmailsComposeView.js
Issue: #3733 
In the emails module. When a users composes an email and selects the to field and then selects an account, a messagebox appears "invalid email address".
The solution is to remove the message and use a callback function instead.
- Fixes bug
- Compose an email
- Select an account or a contact to set the email address
=> Fixed #3733 - Removing messageBox and adding callback

include/SugarEmailAddress/SugarEmailAddress.php
Fixes a bug where $optInFlag was being set to 0 in every case.
Fixes #5901 
1. Have Lead with Confirmed Email
2. Select Action/Convert
3. Converted Contact's Email is still confirmed opt in
4.
=> Fix bugged opt-in flag change

themes/SuiteP/css/sidebar.scss
Appears to be a missing space between "a" and the class "side-bar-View" that keeps the eyeball from appearing on custom module menus.  I am using 7.8.19 but it appears to be in the 7.9.x branch as well.
Create a custom module.  No eyeball in the list view of custom modules next to the action View.
Create a custom module.  Go to the list view.  The side bar menu will show an eyeball icon next to the View <module> link.   
=> Fix typo so view icon appears in custom modules

include/MassUpdate.php
Changes the way massupdate will set the value of dynamic enum fields.
Previously a child field would always be set to `Open_Open` if the parent value was `Open`, regardless of this being a valid status for the child field or not, causing some bugs.
Now it is consistent with the way it works in the edit view: upon changing the value of the parent field, the child field will take the first available valid value.
Fixes #5949 
1. Create account (or use existing)
2. Create a case from account
3. Change this case state to 'closed' with mass update in list mode
4. Change this case state to 'open' with mass update
=> Make massupdate choose the value of dynamic enum fields better

themes/SuiteP/css/suitep-base/editview.scss
Currently if you have more than one row of text in a text field it makes all of the text double spaced within it. It appears this is a side-effect of attempting to use line-height to center the text in form fields.
Multi-line text such as long notes look terrible because it's all double-spaced.
* Create a note object which has more than one line within the body of the note.
* Look at how it looks (double spaced)
* Build scss files, clear cache
* Look at how the note looks now
**Note** Some people may like this look :-/ but it seems to go against the new theme to try and remove excess spacing.
**Note** I have not committed the compiled scss file as I'm not sure if the project would prefer that or not.
=> Fixing styles in form to remove double spacing of multiline text fields

modules/SugarFeed/SugarFeed.php
Bug #5918 documents that the Activity feed now shows all items being from 0 seconds ago. This fixes that.
Want to know when the activity occurred. 
Open up 7.10.5's home page with activity feed on 7.10.5 and this PR.
=> Check for existance of the global variable, do not use it in isset()

include/ListView/ListViewSubPanel.php
Fixes a bug where every contact in a subpanel was showing the parent record's email address.
Fixes #5934 
1. Go to account record
2. Look on subpanel Contacts
3. relate some contacts to account
4. refresh page and see the emails displays correctly for each record
=> Fix subpanels producing wrong email link

modules/AOS_Products/AOS_Products.php
When the image have the same filename, it would overwriteen the previous
image of another product. So added guid as a prefix to the filename to
differentiate the images with the same filename.
=> fix a bug for product image overwritten by the other product image

modules/Notes/Note.php
When deleting an attachment from a Note a bug was preventing the file name field from clearing.
Fixes #5872 
Fixes #5873
1. Create a note and attach a file
2. Edit that note
3. click on remove attachment
4a. attach a new file and save
or
4b. save
=> Clear an additional field to make sure filenames are forgotten on delete

modules/AOS_PDF_Templates/templateParser.php
Prevent aos pdf template parser from formatting an already formatted number.
Fixes #5829
Create a quote
Create a line with discount > $1000
Generate a PDF of the quote
=> Stop formatting already formatted number

modules/Cases/views/view.edit.php
Fixes the case description field not showing correctly when using the save and continue or next/previous actions.
Issue #5815 
1. You must have more than 1 Case in the Module
2. Edit a Case
3. Press the Save and Continue button (or Next/Previous) buttons
=> Fix cases description not showing wysiwyg editor in certain cases

modules/Studio/wizards/RenameModules.tpl
Fixes a bug when renaming modules with apostrophes in their title.
Issue #5717 
1. Install a module with an apostrophe in its name (or a translation)
2. Try to rename it
=> Replace single quotes by double to avoid apostrophe bug

modules/Emails/include/ComposeView/EmailsComposeView.js
See issue #5998
We are trying to attach a document when sending an email, applying a filter. The document is not attached.
1. Go to Emails, click Compose.
2. Click the attach document button.
3. Apply a search on the oppened popup.
4. Select one document.
5. See that the document is not attached.
6. Apply PR and repeat 1-4.
=> Fix #5998 - Can't select document on email compose using search

modules/EmailTemplates/EmailTemplateParser.php
This fixes the survey entryPoint URL sent out in survey campaigns 
"&tracker" was missing from the URL causing the contact id in the url to be double length as it included the tracker id, which causes a Database error on completing the survey
Create and send a campign survey and see that you can complete the survey successfully
=> Fix invalid survey Campaign link

modules/Emails/EmailsController.php
The from address should be the outgoing account email address, not the
outgoing account username. Fixes issue #6015 
It's a one line fix. The system level email address should be filled with the email address, not the username when composing an email. Without this, outgoing email will fail unless the outgoing account user name matches the email address exactly.
Enable "Allow users to use this account for outgoing email", compose an email and select the system account. The "From" will have the email address filled in now instead of the accounts user name.
=> Fix for issue #6015

include/language/en_us.lang.php, modules/Users/language/en_us.lang.php
Removes unused language strings. See #4605 for context.
Issue reference: #5690
1. Check that the quick-create drop-down labels are displayed correctly.
=> Fixed #5690 - [language] Unused language strings in ver. 7.10.4

modules/SugarFeed/SugarFeed.php, tests/unit/modules/SugarFeed/SugarFeedTest.php
The fix in 7.10.5 doesn't fully fix this issue
This fix correctly calculated the time elapsed and handles invalid start dates
Check the Activity Stream time elapsed calculates correctly regardless of date/time settings
=> Fix #5918 Activity Stream elapsed time calculation

themes/SuiteP/images/calendar_next.svg, themes/SuiteP/images/calendar_previous.svg
Removed references to inkscape due to its z-index causing errors in edge browser.
Issue ref: #3662
This fixes the calendar icon causing an error when clicked on instead of opening a miniaturised calendar popup.
1. Using suiteP theme and edge browser, open calendar module.
2. Click on calendar icon next to "settings" button
=> Fixed #3662 - Calendar date selector popup

modules/AOS_PDF_Templates/templateParser.php
Fixes a bug where the pdf template parser was not recognizing percentage type fields.
Fixes #6162 
1. Create a line item with a 20% discount
2. Apply a PDF template which makes use of this discount
3. Inspect the discount in the PDF
=> Strpos may return 0 when a match is found

modules/Cases/views/view.edit.php
Another fix for the cases description field. This time to fix a bug introduced in the last fix, which prevents tiny from correctly sending the description field content when editing an existing case.
Fixes #6081 
1. Go to Cases module
2. Create a new case, fill out description
3. See it saves correctly
4. Edit the same case, change the description
5. See it saves correctly
=> Do not call tiny mceAddControl on edit view

modules/AOW_WorkFlow/aow_utils.php
If field type is 'date' display the field as 'date' not as 'datetime'.
See #6052
We have some reports that have date fields, and the result when you consult the report or export it as PDF is that date fields are displayed lke datetime fields.
1. Create a new report on Invoice module.
2. Add at least 'Invoice Date' field.
3. See that the values of this column displays the date + hour while only the date should be shown.
4. Apply PR.
5. Repeat step 3 and see that now 'Invoice Date' field is displayed in date format.
=> Fix #6052 - AOR_Reports are showing date+hour on date fields

modules/Campaigns/wizard.js, modules/Emails/javascript/EmailUIShared.js, modules/Emails/javascript/complexLayout.js
Previously the emails module would be too wide if the left sidebar was opened, forcing the user to use the bottom scrollbar.
Checks if the left sidebar is opened, then substracts the width from the available space for the emails module.
1. Go to the Emails module
2. Click Compose
3. See you can access the sidebar on the right (to upload documents) without scrolling
=> Adjust the emails module width taking into account the sidebar

themes/SuiteP/modules/Calendar/tpls/header.tpl
In the calendar dashlet, right / left navigation icons are not visible in SuiteP:
This change updates the month header to use the same colour as the calendar module:
Issue reference: #2783
1. Repair and rebuild.
2. Add calendar dashlet to homepage.
3. Check that the left/right navigation icons are visible in all themes.
=> Fixed #2783 - In the calendar dashlet, right / left week icons are not visible

modules/FP_events/vardefs.php
Disabled inline edit for this field.
Fixes #6179 
The function which builds the template list for Events edit view is not called during the setup of the inline edit field.
Disabling inline editing for this field seems to be cleanest option in my opinion.
Not much to test since inline editing is disabled now
=> Make Email Template field in Events not be inline editable

modules/Audit/Audit.php
If a user is missing in the user table the audit log entries are not shown. But even if you do not know the user it is good to know there was a change.
=> Show Audit log even if user does not exist (anymore)

include/database/DBManager.php, include/database/MssqlManager.php, include/database/MysqlManager.php, include/database/MysqliManager.php, include/database/SqlsrvManager.php
This pull request fixes #3560
Now each log line represents one (and only one) system action.
Now a log line with a query is recorded this way:
Tue May 16 09:58:11 2017 [30922][1][INFO] Query: SELECT  alerts.*  , jt0.user_name modified_by_name , jt0.created_by modified_by_name_owner  , 'Users' modified_by_name_mod , jt1.user_name created_by_name , jt1.created_by created_by_name_owner  , 'Users' created_by_name_mod , jt2.user_name assigned_user_name , jt2.created_by assigned_user_name_owner  , 'Users' assigned_user_name_mod FROM alerts   LEFT JOIN  users jt0 ON alerts.modified_user_id=jt0.id AND jt0.deleted=0     AND jt0.deleted=0  LEFT JOIN  users jt1 ON alerts.created_by=jt1.id AND jt1.deleted=0     AND jt1.deleted=0  LEFT JOIN  users jt2 ON alerts.assigned_user_id=jt2.id AND …
=> FIXED #3560 - Now we log queries in one, and only one, log line

include/database/DBManager.php
If field value contains single quote, on each save CRM will treat this field as a changed and add new line to bean change-log with same value before and after
fix issue https://github.com/salesagility/SuiteCRM/issues/6126
1. Create Account with single quote in name
3. Open and save Account without changes
4. New line will not added to change-log
=> #6126 fix(Change-log) - decode prev value before compare

modules/Favorites/Favorites.php
Steps to reproduce:
- Add 200 to 400 Favorites for a user
- SuiteCRM becomes unusable slow ( For me <1sec will become 6-10 sec on each page load)
Solution: There are never more than 30 favorites displayed, so we do not need to get all of them.
Refers to https://github.com/salesagility/SuiteCRM/issues/6142
=> Prevent massive slowdown if someone accidently added many favorites

include/SugarFields/Fields/Base/SugarFieldBase.php
Default tabindex for form fields should be 0. Previously it was being set to -1, preventing users from tabbing through a form's fields.
#5995 
#6069
1. In listview, open the search popup
2. From a subpanel, open the select record popup
3. See that you can tab through fields in their logical order.
=> Set default field tabindex to 0 instead of -1

data/BeanFactory.php, modules/AOW_Actions/actions/templateParser.php
Sometimes when creating a new bean, the data stored in the cached version of the BeanFactory will not be correct. For example auto increment fields will only have correct data once they've been inserted and then retrieved.
Adds an unregister function to the BeanFactory. Calling it will remove a given Bean from cache, so that next time it will be fetched from the DB.
In the workflow template parser we check for a bean being new, and then make sure it is retrieved at least once from the db.
Fixes #5814
Fixes #3468
Fixes #5719
1. Create a new workflow
2. Related to cases
3. Run on saving new records
4. Action: send email, case creation template
5. Create a new case
=> Do not get the cached version for newly created beans from Factory

modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php, modules/Users/authentication/SAML2Authenticate/SAML2AuthenticateUser.php
SAML2 authentication currently results in either a fatal error occurring (white screen, 500) or fails to login.
Currently the external_auth_only check in place is a boolean, meaning, only upon it not being a SAML user should the return be empty, not when an auth is. The current logic would return no results. No OneLogin instance was working prior to these changes.
Issues raised that could relate to this:
https://github.com/salesagility/SuiteCRM/issues/5921
https://github.com/salesagility/SuiteCRM/issues/5885
...And possibly others, though, non descriptive error codes.
- Create a trial one login account.
- Link it to a SugarCRM SAML2
- Add the user to one login
- Set the user up in the CRM
- Login to the CRM with the urls set and x509 cert set.
- Confirm non SAML users are working with …
=> Fix #5885 - SAML2, Resolve failure to login

include/SugarFields/Fields/Image/DetailView.tpl
This PR fixes a small bug with the image type field from Studio / Module Builder.
Image fields have in their src attribute the url of an entrypoint composed of the id of the record we're viewing and the name of the field. However, once we clear an image field, since this url doesn't change the browser might display a cached version where we would expect not to see any image.
1. Add an image field to any module
2. Add it to detail and edit view
3. Edit a record, upload an image to this field
4. See it displays in detail view
5. Edit the record, remove the image
6. See it doesn't display in detail view. The img tag should have an empty src attribute.
=> Do not show img tag with same src attribute if an image field is empty

modules/AOR_Reports/AOR_Report.js
Fixed issue #6244 
The report fails with a MySql syntax error when using a non-simple Date value and hitting the Update button. The report also fails when paginating, exporting CSV and exporting PDF.
1. Create a report with a date condition such as today-36 months as a parameter.
2. Click on Update or Paginate the report.
=> Fixed #6244 - 7.8.20LTS AOR_Report fails using a date parameter

include/Smarty/plugins/function.sugar_literal.php, include/Smarty/plugins/function.sugar_varname.php, include/SugarFields/Fields/EmailBody/DetailView.tpl, include/SugarFields/Fields/Html/DetailView.tpl
When users access the detail view of multiple emails, the body of the email appears to be the same.
This fix utilises the fact that the template is parsed twice. I have added two new methods. sugar_varname to get the smarty variable name. sugar_literal to by pass the second parsing, so that elements such as "style" or "script" do not break the smarty parser.
- Fixes bug
- Ensure development mode is turned off
- Set up inbound email
- Access multiple emails
- Check that the body is not the same as the previously accessed email
=> Fix: Email body is the same on the detail view

include/Dashlets/DashletGenericChart.php
If you have charts in a dashlet in 7.8.21 php throws an error and does not show the home dashboard at all.
Issue reference: #6312 
1. Navigate to dashboard.
2. Add chart dashlet.
=> Fixed #6312 - Charts in Dashlets cause php errors in 7.8.21

include/Dashlets/DashletGenericChart.php, tests/_support/Step/Acceptance/Dashboard.php, tests/acceptance/modules/Home/HomeCest.php
If you have charts in a dashlet in 7.10.8 php throws an error and does not show the home dashboard at all.
Issue reference: #6312 
1. Navigate to dashboard.
2. Add chart dashlet.
=> Fixed #6312 - Charts in Dashlets cause php errors in 7.10.8

include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php, tests/acceptance/modules/Accounts/AccountsCest.php
"PHP Parse error: syntax error, unexpected 'return' (T_RETURN), expecting function (T_FUNCTION) in (root directory)/include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php on line 61"
Issue reference: #6322 
1. Create an account.
2. Add a parent account.
3. View parent account/
=> Fixed #6322 - creating parent-child relationship in clean install of 7.10.9 causes parent display to break

modules/Schedulers/Scheduler.php
Fixes an issue with schedulers job drop-down only showing a single value "URL".
Issue reference: #6364 
1. Go to Administrator -> Admin -> Scheduler -> Create Scheduler -> click on Job field
2. Check that the drop-down has all the expected values not just URL.
=> Fixed #6364 - "Create Scheduler" broken - no Jobs to select

README.md, modules/Emails/include/ImportView/ImportView.tpl, modules/Emails/include/ListView/ImportEmailAction.js, suitecrm_version.php
Fixed #6321 - using same form name as back-end does
the popup didn't fill out the form because didn't find it. caused by the wrong form-name
see at issue #6321
see at issue #6321
=> Fixed #6321 - using same form name as back-end does

modules/Users/language/en_us.lang.php
Fixed #5286  - Empty help message when creating user
When creating a user and clicking the exclamation mark next to "Module Menu Filters" an empty help message was displayed.
1. Click create user
2. Click Layout Options
3. Click the exclamation mark next to the text "Module Menu Filters"
=> Fixed #5286 - Empty help message when creating user

include/ListView/ListViewDisplay.php
Fixes a bug that prevents $this->lv->email = false; from having an effect on showing the email link in the list-view.
Issue reference: #5656 
1. Go to employees module..
2. Check that the email link next to bulk action is gone.
=> Fixed #5656 - ListViewDisplay Incorrectly Checking for $this->email to be 'Set' Instead of True/False

modules/Administration/Search/ajaxSubmit.js, modules/Administration/language/en_us.lang.php
Fix: Redirect the user back to the Administration section when saving the Elastic Search.
Within the current version the save button on the "ElasticSearch" page alerts the user that the section has save successfully; however, the other sections redirect the user back to the Administration section. This fix will take away the alert message and redirect the user back to the Administration page as expected.
To keep the flow of the application consistent.  
1. Go to Scheduler and locate the Elastic Search Schedule, if there is no schedule for Elastic Search created. Click on "Create Scheduler" (On Left). Create a new Elastic Search Scheduler in the normal way.
2. Go to: Admin > click "ElasticSearch" > Input the correct Host, Username and Password and Click the "Test connection" button. Click …
=> Fixed: ElasticSearch Save Redirect

themes/SuiteP/css/suitep-base/navbar.scss
Fix: Notification Count Styling 
This fix will correct the styling on the notification count, at the moment one of the sides of the count is hidden, this will fix this issue and display the count background properly. 
To fix the display of the application.
From:
To:
=> Fix: Notification count styling

modules/Users/Save.php
It is useless if it is not used, and then default defaults to group modules.
=> Default navigation paradigm should be used

modules/AOW_WorkFlow/AOW_WorkFlow.php
Any 'Date' conditions fails to build correct SQL query.  
There is an incorrect error condition where when there is **no error** the condition sets the `$params`  to a empty array. This should the the opposite of what is needed.  set `$params = [null]` when it _fails_ .  
This fixes #6328. 
None of Workflow with Date conditions work. 
1. Create Workflow with date condtion
2. See logs that mysql error .
1. Error is due to incorrect query
1.  Apply patch
1. See no errors in log entries
2. Verify that workflow ran successfully
=> Workflow Date - Remove incorrect branch when unserialize fails - Fix #6328

modules/AOR_Reports/AOR_Report.js, modules/AOR_Reports/controller.php
Given a report with parameters, the action "Add To Target List" did not
take into account the report parameters, resulting in all records getting
added to the target list as if there were no parameters.
Fix this by updating the form with the current parameters and also send
it to the "addToProspectList" controller action. In the controller extract
the parameters before creating the query like with other actions.
This makes the list of records added to the target list match the one the user
sees on the report page.
Fixes #4123
1. Create a report which has a parameter and results in a record being shown
2. Adjust the parameter so that no record is shown
3. Use the Add To Target List" action and select a target list
4. With this fix applied no record should get added to the target list
=> Fixed #4123 - reports: fix adding parameterized reports to target lists

modules/AOS_PDF_Templates/templateParser.php
Datetime fix in the email template, previously for datetime field it was only taking the date in email templates.
It was taking the only date in the email for DateTime fields as well because in the logic it was splitting the value with space. In the value first part is date and the second part is time but it was assigning only first part that's why only date value was assigned in a variable and displayed in emails.
Lot of people were facing this issue because they were not able to see time in email.
1- Create a field as DateTime in any module
2- Create an email template and use this variable in email
3- Send this email template and check if it date and time both
=> Time issue fixed in email template for datetime fields

themes/SuiteP/include/EditView/EditView.tpl
This is a fix for issue where only panels do not show correctly under each tab
This edit fixes Edit View
The fix has only been tested for Version 7.9.2
- [X ] Bug fix (non-breaking change which fixes an issue)
=> Fix for issue #2786 - Edit View (Updated)

include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Fixes an issue where the compose email button in the activities subpanel would have its popup duplicated 3 times. Also fixes an issue where a user's role that does not include "Meeting" will prevent this button from being visible.
Credit for this fix goes to @mattlorimer 
Issue reference: #6351 
Issue reference: #6467 
```
1. Open any contact in Contact module
2. Try to send email from Activities subpanel
3. See result
```
```
1. Create role R with permission to Email and Contact modules, and user U with role R.
2. Create some contact C with email address
3. Disable AJAX for Contact module.
4. As user U, go to contact C, see Activities sub-panel, there is no "Compose Email" button.
5. Modify role R and add permissions for Meeting module.
6. As user U, go back to contact C, see Activities …
```
=> Fixed #6351 - Triple email sending when i use activities subpanel in Contact Module

include/SuiteEditor/SuiteEditorConnector.php
Images can no longer be inserted in Email Templates with TinyMCE
Added image button
=> Insert images in Email Templates with tinyMCE

modules/EmailTemplates/EmailTemplateParser.php
When sending an email template through the campaigns module, the variables do not parse correctly.
Issue reference: #5944
Issue reference: #5771
Issue reference: #3321
1. Admin panel -> studio -> contacts -> contact_salutation drop-down menu -> edit.
2. Create a template with the $contact_salutation variable and an accounts module variable.
3. Use the template within a campaign.
4. The variables will be correctly replaced with the language string for both contacts and accounts.
=> Fixed #5771 - Salutation variable in campaigns displays item name instead of value 7.10.4

modules/Campaigns/WizardMarketing.html
In the campaign wizard the editor (mozaik in this case) is embedded in the
main table. The table has the CSS classes "other view" and the theme contains
various rules that just force the size of all img tags there etc. This affects
various elements of the editor making the preview not match the actual email.
To avoid the theme CSS affecting the editor move the editor out of the table.
Fixes #6472
* Create an email template with an image and resize the image to be smaller
* Start the campaign wizard and select the email template
* Look at the template preview at the bottom, it should look the same as in the editor
=> Fixed 6472 - Fix wrong image sizes for email templates in the campaign wizard

modules/Campaigns/utils.php
In the subscription manager sometimes a newsletter ends up in the subscribed
list even though the contact/lead is in the exempt list of that newsletter.
The code was checking if the user was unsubscribed with the list ID of the
subscription list. This will never work and depending on the iteration order
(if the unsubscribed list gets checked first) this results in the user being
displayed as subscribed even in case he/she is on an exempt list.
This fixes the code to check if the campaign name is in the unsubscribed list
instead, like happens in the case where the non-exempt list comes first.
get_subscription_lists_keyed(), which does the same thing as
get_subscription_lists() but returns the result in a more structured way,
also uses the campaign name and the same logic for this case.
The …
=> Manage subscriptions: Fix unsubscribed users showing up as subscribed sometimes

include/SugarTinyMCE.php, modules/Cases/views/view.edit.php
Fixed #6570 -Case description not saving when AJAX is disabled
Fixed #6574
=> Fixed #6570 -Case description not saving when AJAX is disabled

modules/ModuleBuilder/parsers/views/GridLayoutMetaDataParser.php
The parser rewrites editviews, detailviews and quickcreateviews. It however deletes all (filler) elements (see bug description for images).
The method _convertToCanonicalForm does include code to convert the (filler) elements to empty placeholders, however this code is never reached, because before it checks if the field name corresponds to an existing field definition.
This change make sure that (filler) elements are not removed when rewriting a view layout, see issue #6516 
It solves deletion of (filler) elements in view layouts:
* when new modules are installed or uninstalled that are related by many-to-one with a parent module
* when layouts are manipulated directly using the GridLayoutMetaDataparser
See reproduction in #6516
=> Fixed #6516 - (filler) elements in layouts are removed by gridlayout parser

modules/Schedulers/_AddJobsHere.php
Fixed #6414 
When the scheduler runs to check for inbound emails, the following error is reported:
`PHP Notice:  Undefined variable: isGroupFolderExists in /var/www/suitecrm/public
/modules/Schedulers/_AddJobsHere.php on line 649`
=> Fixed #6414 - Bug in modules/Schedulers/_AddJobsHere.php

modules/AOS_Products_Quotes/line_items.js, tests/acceptance/modules/Invoices/InvoicesCest.php
The `function formatNumber`  does not correctly handle the round of numbers that causes an increase in the integral part. 
The function formatNumber does not correctly handle the round of numbers that causes an increase in the integral part. Reported as issue #6003. 
The function should round up values correctly. 
Apply changes and test in browser console giving number 475.99999999999994, round=2 and precision=2.
=> Fix round up for cases where there is an increase in integral part. 

include/SugarEmailAddress/SugarEmailAddress.php, modules/Campaigns/WebToPersonCapture.php, modules/EmailMan/EmailManDelivery.php, modules/Emails/Email.php
confirm_opt_in_sent_date, confirm_opt_in_date and confirm_opt_in_fail_date get
set to the local time and then saved to the database. Other modules like
reports and workflows expect dates in the DB to be in the DB timezone and
convert them to the local time. Since the dates are saved in the local time
this result in the wrong time being used/shown.
Fix this by always using the DB time when setting those fields like everywhere
else.
See #6487
=> Fixed #6487 - opt-in: use the DB time for writing confirm_opt_in_*date

include/SubPanel/SubPanelTiles.php
Passes the expected `flat` variable into the function that creates subpanel buttons.
The function that builds the array of subpanel buttons checks for a variable named `flat` to decide on an individual subpanel basis whether to display the buttons ins drop down menu.
This variable was never being passed into the function from the SubPanel class despite being available.
Now we can define individual subpanels as flat in the defs.
Result: Flat and Dropdown subpanels in the same instance and the same module.
1. Override a subpanel definition (example `custom/Extension/modules/Leads/Ext/LayoutDefs/myCustomization.php`)
2. Add this line: `$layout_defs['Leads']['subpanel_setup']['history']['flat] = 1`
3. Repair and Rebuild
4. Go to Leads module
5. See only the History module now has its buttons …
=> Fix/Individual Flat Subpanels
