- custom/Extension/modules/Contacts/Ext/Language/en_us.customaop_case_updates_contacts.php
This is the fix for the problem described by deftaxias:
https://suitecrm.com/forum/bug-tracker/4082-contacts-mass-update#16545
> Added Account Disabled string needed by the mass update function

- modules/AOS_PDF_Templates/PDF_Lib/config.php
Fix for #38 Chinese Characters not displaying in pdf
> Fix for #38

- include/HTMLPurifier/HTMLPurifier.standalone.php
- modules/Users/GeneratePassword.php
Issue #218 should be fixed, plus the xtra bug which was mentioned in the forums by a user
> Regex email validation issue218

- modules/ProspectLists/ProspectList.php
Exporting a prospect list, where a prospect had changed companies, was giving incorrect
data in the export.  This patch fixes this problem.
> Fix bugs 43617 and 43440 at http://bugs.sugarcrm.com.  

- modules/AM_ProjectTemplates/vardefs.php
This minor correction allows the correct generation of the popup URL according to the discussion of Issue #240.
> Solves the problem with the popup on choosing the Project Manager (Issue #240)

- custom/modules/Connectors/connectors/sources/ext/rest/twitter/language/en_us.lang.php
> Twitter connector typo

- modules/Campaigns/tpls/WizardCampaignTargetListForNonNewsLetter.tpl
Found this error in the wizard when you try to add target lists either new or from the pop-up, you would get a javascript error.
> Fixing javascript error in campaign wizard non-emailed based campaign

- modules/SchedulersJobs/language/en_us.lang.php
fixing english typo on string LBL_PERCENT
> Typo for "percent"

- custom/modules/Project/chart.php
Removed left-padding from project resource chart so "previous month" displays correctly.
> Fixes Issue #342

- jssource/src_files/modules/Alerts/alerts.js
Alerts now looks for the login form then stops updating the alert manager.
> issue #400 fix

- modules/ModuleBuilder/tpls/LayoutEditor.css
- themes/Suite7/tpls/footer.tpl
- themes/SuiteR/css/style.css
- themes/SuiteR/tpls/footer.tpl
Some CSS Fixes that come from Forum Posts.
> CSS Fixes - Updated

- modules/ModuleBuilder/tpls/listView.tpl
This fix should be combined with Jims proposal to remove references
> Fix for issue #353

- modules/AOS_Contracts/AOS_Contracts.php
Suppresses php notice that fills apache log files.
> Annoying php notice in log file

- themes/Suite7/css/style.css
Same bug and fix like here, just other theme:
https://github.com/salesagility/SuiteCRM/commit/c0b3fd5764e937f59ebaa094949237b52e05107e
> Scrolling in Edit of Layout in Studio/ModuleBuilder not possible

- include/InlineEditing/inlineEditing.js
Fixes issue #511 where middle click does not open in a new tab
> Fix #511 middle click on webkit browsers

- modules/Emails/javascript/Email.js
Users able to create Contacts via the Email's To/CC/Bcc fields by the QuickCreate Popup.
> Fix for Issue#631

- custom/modules/Contacts/metadata/subpanels/FP_events_subpanel_fp_events_contacts.php
The variables were not being resolved properly for the label values.  Calls to $APP were replaced with references to the $app_strings array.  This has been tested as working as shown in the image below:
> This closes #588.  

- modules/Calls/Call.php
- modules/Calls/metadata/quickcreatedefs.php
- modules/Meetings/Meeting.php
- modules/Meetings/metadata/quickcreatedefs.php
- modules/Reminders/Reminder.php
- modules/Reminders/Reminders.js
- modules/Reminders/controller.php
- modules/Reminders/tpls/reminders.tpl
Multiple-reminders added to Contacts and Leads modules Activities sub-panel and bring it over to full form.
store "reminder email sent" flag on upgrade
> reminders to related person modules and upgrade fixed

- include/MVC/SugarApplication.php
- include/SubPanel/SubPanel.php
- include/database/DBManager.php
- include/database/MssqlManager.php
- include/database/MysqliManager.php
- include/database/SqlsrvManager.php
- include/utils.php
- include/utils/sugar_file_utils.php
- install.php
- install/UserDemoData.php
- install/install_utils.php
- install/language/en_us.lang.php
- modules/Calendar/CalendarActivity.php
- modules/Calendar/processScreenSize.php
- modules/EmailMan/testOutboundEmail.php
- modules/ModuleBuilder/parsers/relationships/DeployedRelationships.php
- modules/ModuleBuilder/views/view.modulefield.php
- modules/ModuleBuilder/views/view.relationships.php
- modules/Relationships/Relationship.php
- modules/Relationships/RelationshipHandler.php
- modules/Schedulers/language/en_us.lang.php
- modules/SecurityGroups/AssignGroups.php
- modules/SecurityGroups/SecurityGroup.php
- modules/Users/authentication/SAMLAuthenticate/SAMLAuthenticate.php
- modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
- modules/vCals/vCal.php
More php strict and some php error fixed
> Php errors

- modules/Reminders/Reminders.js
reminders validation message fixed
> fix: issue #735

- suitecrm_version.php
> 2016 year update

- themes/SuiteR/css/colourSelector.php
This pull request fixes #739 
- The alert button has the same background color as navbar.
- The dashlet icons are now set to the page_link setting.
- The search form button has the same background color as navbar and the icon has been set to the icon setting.
> Updated theme settings for #739

- modules/FP_events/responseEntryPoint.php
> Fix typo in events

- modules/AOR_Reports/views/view.detail.php
This fixes the issue of Chromium not showing the graphs on load and also ensures the resize event respects the graphs per row value.
> Fixing Chrome RGraph issues

- modules/AOR_Conditions/AOR_Condition.php
Added missing $post_data[$key.'value_type'][$i] === 'Value' check to line 81
> Fix for issue #856

- modules/Studio/language/en_us.Portal.html
Including some tags to allow translation wit Crowdin
> Formating with html tags to allow translation - Studio

- modules/UpgradeWizard/language/en_us.lang.php
Making it easy to use Transifex tool to translate and prepare language packs.
Note: if possible please change this to normal array so it don't require post processing files to be translated in Transifex.
> Moving mixed array to the end of file

- themes/SuiteR/css/colourSelector.php
- Added !important for action menu
- Fixed typo for top search button.
@willrennie @mattlorimer i advise to merge this so the action menu cannot crash after saving the theme colors. (verified with the hotfix branch)
> Fixes for theme settings.

- modules/ModuleBuilder/javascript/ModuleBuilder.js
Fixed #707 added an if statement which stops script from leaving to another view if action is Clone
> Fixed #707 added an if statement which stops script from leaving to another view if action is Clone

- modules/ModuleBuilder/javascript/ModuleBuilder.js
Reverts salesagility/SuiteCRM#1003
> Revert "Fixed #707 added an if statement which stops script from leaving to another view if action is Clone"

- modules/AOS_Quotes/metadata/detailviewdefs.php
- modules/Opportunities/controller.php
Created opportunities controller and added editview method.  Also added js within detailviewdefs.php
> Fix for github issue #1004 

- modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
Fixes #1070 by changing the displayed item to be the value rather than the key.
> Fixes #1070 by changing the displayed item to be the value rather than the key.

- modules/AOR_Reports/aor_utils.php
Fixes #1066.  As per the OP's suggestion, I have updated this to be the current month -1.
> Fixes #1066.  The last month parameter was set to the same value as the "this month" parameter.

- install/language/en_us.lang.php
Install language - remove duplicated string
> Install language - remove duplicated string  [Language]

- modules/Project/language/en_us.lang.php
Removing several duplicated strings.
> Project module - Removing duplicated languages strings [Language]

- modules/AOR_Reports/tpls/report.tpl
Fixed #1082 - changes local date format to db date format for correct comparison
> Fixed #1082 - changes local date format to db date format for correct comparison

- include/SearchForm/tpls/SearchFormGeneric.tpl
- include/SearchForm/tpls/SearchFormGenericAdvanced.tpl
Fixed #1140 - make sure that onclick function runs only once
> Fixed #1140 - make sure that onclick function runs only once

- include/InlineEditing/inlineEditing.js
Fixed #373 added message_field which gets its string from system field name
> Fixed #373 added message_field which gets its string from system field name

- modules/ProjectTask/Dashlets/MyProjectTaskDashlet/MyProjectTaskDashlet.data.php
Fixed #907 - Changed incorrect array key from ProjectTaskDashlet to MyProjectTaskDashlet
> Fixed #907 - Project Tasks not displaying in My Project Tasks Dashlet

- modules/AOS_PDF_Templates/generatePdf.php
> Fixed #756: Modified search and replace arrays

- jssource/src_files/include/javascript/jsclass_async.js
Fixed #208 - take Daylight saving time into consideration. Also, dont forget to change System Settings -> vCal Updates Time Period in order to see more than 2 months.
> Fixed #208 - take Daylight saving time into consideration. 

- modules/Reminders/vardefs.php
- modules/Reminders_Invitees/vardefs.php
Fixed #1128 - created indices for Reminder and Reminder_Invitee which increased the speed by 30%. Also, see further explanation related to the addNotifications() function in the linked forum post.
> Fixed #1128 - created indices for Reminder and Reminder_Invitee

- include/InlineEditing/inlineEditing.js
Added a check to see if the element exists
> Fixed #829 - Inline Editing JavaScript Errors

- install/installConfig.php
toggler for appropriate fields and remove values on hide
> fixed #549 - Issues with SMTP Authentication on Install

- modules/AOR_Reports/AOR_Report.php
escape value before use in query
> fixed #1206 - AOR_Reports - main group sql query sanitizing

- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/aor_utils.php
Fixed #1253 - added a switch statement which adds a period instead of a plain date (if condition has Equal to preiod).
> Fixed #1253 - added a switch statement.

- modules/AOR_Reports/tpls/report.tpl
Fixed #1082 - only change to DB format if its a date. Also, change dtes back to the user format
> Fixed #1082 - only change to DB format if its a date. 

- modules/AOR_Reports/AOR_Report.php
Fix for issue 1232 - items listed in a single report, should adhere to the same standard as ListView items.
> Fix for issue 1232 - items listed in a single report, should adhere to the same standard as ListView items.

- modules/ModuleBuilder/views/view.modulefield.php
Fixed #1177 - added new stdClass() in order to to prevent Creating default object error.
> Fixed #1177 - added new stdClass() in order to to prevent Creating default object error.

- modules/AOR_Reports/AOR_Report.php
Fixed #1251 - added a missing parameter to the function call
> Fixed #1251 - added a missing parameter to the function call

- modules/jjwg_Maps/views/view.map_markers.php
Fixed #1186 - changed the code to point to the themes directory instead of custom/themes .
> Fixed #1186 - changed the code to point to the themes directory instead of custom/themes

- modules/Reminders/Reminders.js
Fixed #1161 - prevent adding duplicate invitees by checking for duplicates in array alreadyInvited
> Fixed #1161 - prevent adding duplicate invitees

- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/aor_utils.php
Fixed #1253 - added back if(!whwere_set) clause
> Fixed #1253 - added back if(!whwere_set) clause

- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/aor_utils.php
- modules/AOR_Reports/tpls/report.tpl
Fixed #1272 - added some functionality to handle Date type parameter update. This should be combined with the latest #1082 fix.
> Fixed #1272 - added some functionality to handle Date type parameter update.

- modules/AOR_Reports/AOR_Report.php
In relation to Issue #1221:
I have added a fix so that the total functions display currency fields correctly.
It assumes that the data is in USD. Then it converts the currency into the currency specified in the user's preferences. 
A future improvement could be to add the ability to change the currency based on the format field.
> Fix #1221: Adding currency handling in the total functions 

- modules/AOW_Actions/actions/actionCreateRecord.php
Checks if today is selected, then assigns the $date variable to today.
> Fixed #1132 - AOW - Date = Today calculated as 01/01/1970

- .gitignore
- modules/EmailTemplates/EmailTemplateFormBase.php
Reverts salesagility/SuiteCRM#1403
> Revert "Gymad campaign wizard ui"

- modules/Campaigns/WizardMarketing.html
- modules/Campaigns/WizardMarketing.php
Using func to determine which page the wizard moves to .
> Adding func hidden field to campaign wizard.

- include/javascript/mozaik/jquery.mozaik.js
- modules/Administration/language/en_us.lang.php
- modules/Administration/metadata/adminpaneldefs.php
- modules/Campaigns/WizardMarketing.html
- modules/Campaigns/WizardMarketing.php
- modules/Campaigns/language/en_us.lang.php
- modules/Campaigns/tpls/WizardHomeStart.tpl
- modules/Project/chart.php
- modules/Project/language/en_us.lang.php
- modules/Project/project_table.php
- modules/Project/views/view.ganttchart.php
- modules/jjwg_Maps/views/view.geocoded_counts.php
Labels are no longer hard coded. Some change for the campaign labels have also been changed.
> fixed: #1478

- modules/InboundEmail/EditView.php
> File includes itself in a loop then exits.apache memory overflow

- modules/Campaigns/WizardMarketing.html
The marketing name field conflicts with the campaign name validation. So I have removed it
> Cwui em validation

- include/MassUpdate.php
Fixed #1549 - Dynamic field should have an appropriate value after update.
> Fixed #1549 - Dynamic field should have an appropriate value after update.

- include/Trait/RemoveUnInvitedFromReminders.php
- modules/Calls/Call.php
- modules/Meetings/Meeting.php
(cherry picked from commit 4d467a4)
> Fixed#1570 - Removing uninvited from reminders

- modules/Calendar/views/view.quickedit.php
- modules/Reminders/controller.php
- modules/Reminders/tpls/reminders.tpl
Calendar Quick Edit now populates the json required for reminders.
> Fixed: #1490 - Fixed reminders in the calendar quick edit view

- install/installConfig.php
This removes a couple of trailing </div> tags so that the layout of the installation configuration is correct.
> This removes a couple of trailing </div> tags so that the layout of the installation configuration is correct.

- modules/Configurator/language/en_us.lang.php
in modules/Configurator/language
Please enclose multi-line string with ' ' 
LBL_FONT_LIST_CIDINFO_INFO
PDF_INSTRUCTIONS_ADD_FONT
> Enclose multiline string with single quotes  [Language]

- data/SugarBean.php
This fixes bugs with AOW not picking up on any change when a field is audited.
> Bug Fix for audit fields not working with AOW any change.

- include/javascript/sugar_3.js
Issue with core JScript file. Requires a Repair ->  Repair JS Files
> Fixed #1136 - "Email" Action on Listview gives Error

- include/InlineEditing/InlineEditing.php
> Fixed #706 - Inline Editing Display Error in Documents Module

- include/utils/layout_utils.php
Added create_link id to the anchor tag.
> Fixed #1121 - Create button missing styling in some areas

- include/SugarFields/Fields/Address/en_us.DetailView.tpl
Fixed #999 changed htmlentitydecode to -> html_entity_decode (html_entity_decode was added as a fix for issue 662)
> Fixed #999 changed htmlentitydecode to -> html_entity_decode (html_entity_decode was added as a fix for issue 662)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Adding new folder to store the templates for new issues and pull requests
> Adding new issue and pull request templates for git.

- include/generic/SugarWidgets/SugarWidgetSubPanelTopButton_c.php
Fix fatal on delegates subpanel in event module detail view.
> Fixed #1462.

- include/SuiteGraphs/RGraphIncludes.php
- modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
PipelineBySalesStageDashlet is malforming url when clicking on graph bar
To reproduce the problem click on **Add Dashlets** -> **Pipeline By Sales Stage**
**Problem:** PipelineBySalesStageDashlet is malforming url with sales_stages labels instead of keys when clicking on any graph's bar:
>eg: http://localhost/yourcrm/index.php?module=Opportunities&action=index&query=true&searchFormTab=advanced_search&start_range_date_closed=2016-05-12&end_range_date_closed=2016-11-12&sales_stage=A%20LABEL
This pull request corrected the problem to ...&sales_stage={key}
>>eg: http://localhost/yourcrm/index.php?module=Opportunities&action=index&query=true&searchFormTab=advanced_search&start_range_date_closed=2016-05-12&end_range_date_closed=2016-11-12&sales_stage=a-key
Regards,
Pull request created on Wrong …
> PipelineBySalesStageDashlet is malforming url when clicking on graph bar

- themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
> Fixed: subpanel filter by renaming subpanel id to list_subpanel_{module}

- themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
> fixed: subpanel structure.

- jssource/JSGroupings.php
It resolves the unresponsiveness in the installer
Install a new instance via the installer - should work as expected.
…instance.
> Removing unused Groupings - this causes issues when installing fresh install

- include/SugarFields/Fields/Datetimecombo/EditView.tpl
- themes/SuiteP/css/style.css
Making fixes to form elements for the new SuiteP theme. The date and time combo boxes are now split into two lines. Allowing the date field to be wider· The relate field buttons have been forced to be on the bottom of the relate field. This is to make it more consistent across different platform.
Allows users to enter in the date manually.
Go into any module that uses dates and related fields.
> Suitep form fixes

- modules/AOS_Products_Quotes/Line_Items.php
- modules/AOS_Products_Quotes/line_items.js
- modules/Campaigns/tpls/WizardCampaignBudget.tpl
- themes/SuiteP/css/style.css
- themes/SuiteP/tpls/footer.tpl
More fixes on Campaign Wizard style and ui for SuiteP theme
Campaign Wizard style and ui for SuiteP theme
Campaign Wizard style was broken in new SuiteP theme
Make Camapigns with Campaign Wizard
> non-email campaign / budget page - fixed

- modules/FP_events/Menu.php
View Events icon is missing. Changed menu.php to correct this.
> Fixed #1874 - Missing view icon in view events menu item

- themes/SuiteP/css/style.css
Styles the create person form for the SuiteP Theme
SuiteP did not contain the css selectors that exists in the other themes. So I have added them in and I changed the colours to match the theme.
- Go into campaigns
- Select the Create Person Form in the side bar top navigation.
> Fixed - Create Person form css for SuiteP

- themes/SuiteP/css/style.css
- themes/SuiteP/css/wizard.css
Tidy up User Wizard for new users
The fields are abit all over the place - need some refining.
related for task 198
Create a new test user and login
> Tidy up User Wizard for new users

- themes/SuiteP/css/style.css
on Admin page, Role module doesn't show Edit button  
Role edit (duplicate/delete) impossible without this fix
Edit any Role
> Fix for Role Edit Button

- modules/Calendar/Cal.js
- modules/Calendar/Calendar.php
- modules/Calendar/CalendarActivity.php
- modules/Calendar/tpls/main.tpl
- modules/vCals/vCal.php
Issue: Users on the forum have been experiencing an issue where the calendar doesn't show up.
The reason it doesn't show is because the id of the calendar is hard coded to 1. In Cal.js the script looks of the div element "calendar" + the users id. So i have changed the form.tpl to change the template id dynamically so that the javascript correctly finds the code.
Also the ACL Check failed to check the key activity - this had worked for admin because the ACL check will always return true.
Calendar being initialised and viewing a regular's users activities
- Log in as a standard user (not admin)
- Goto the calendar
- Check that it displays correctly
> Fixed Regular Users viewing Calendar and Activities

- include/SubPanel/SubPanelDefinitions.php
- include/SubPanel/SubPanelTiles.js
- include/SubPanel/SubPanelTiles.php
- include/SubPanel/SubPanelTilesTabs.php
- include/SubPanel/tpls/SubPanelTiles.tpl
- include/SubPanel/tpls/singletabmenu.tpl
- jssource/src_files/include/SubPanel/SubPanelTiles.js
- themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
In the detail view. When a user has subpanel tabs turned on and the the current sub panel is not the "All" tab, the user will only see a limited number of sub panels. The issue then is that when user switches to a tab and the subpanels have not been loaded in they see a blank tab content  area.
My fix has moved the filtering to the client side in order to fix this issue 
See description
Use the show tabs in the user preferences
Switch to an other tab
Reload the page
Swich throught the tabs to check that there are no blank tab containers.
- [ x I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
> Fixed #1817 Subpanel Tabs.

- include/SubPanel/SubPanelDefinitions.php
- include/get_form_header.tpl
Fix for some php notice and warning when upgrade process running
> Hotfix upgrade errors

- modules/ModuleBuilder/javascript/studio2.js
Issue with the newly added SVG icons for Studio that the Edit View and the Detail View of the module would not appear on the studio layout screen.  
Adding this specifically for the admin/studio rather than making it specific via the getImage function.
This was introduced due to a merge through hotfix between master (7.7) and (7.7.1).
Have instance at the state of before this commit and you shouldn't be able to see the edit or detail layout screen via Studio for a module.  To confirm it works, apply this fix and it should appear and be editable.
> Resolving Studio Issue with .svg edit_inline icons on Edit/Detail layout screen

- themes/SuiteP/js/style.js
home module dashboards and some of the actions doesn't load
Click the home icon on the top-left of the page, click any actions (add dashboard for e.g.)
> fix for home module dashboards and some of the actions loading

- themes/SuiteP/css/style.css
Removing title case in the style.css.
It interferes with the language translation. 
- Install a language pack (in this case it's Portuguese) 
- Go to the action menu anywhere in the application.
- Make sure that each word doesn't start with a capital letter. Especially conjunctions like "de".
> Fixed #1911 - Removing title case in the style.css

- themes/SuiteP/css/style.css
Change the style the required divs.
Due to feedback, the style has been changed back to the way it was previously styled.
> Fixed style of * for required fields.

- themes/SuiteP/css/style.css
Reverts salesagility/SuiteCRM#1973
> Revert "Fixed style of * for required fields."

- themes/SuiteP/css/style.css
- themes/SuiteP/js/style.js
Footer size follow collapsed/expanded sidebar width and content resize for full screen
make a Quick Repair and clear cache. refresh the page and resize the browser window
> Suite P footer wider than content (task 212)

- modules/Calendar/Cal.js
- modules/Calendar/tpls/main.tpl
- themes/SuiteP/css/style.css
1. Refactored the way the calendars are constructed.
2. Fixed a minor CSS issue for the suitep theme.
3. Fixed the code to match our coding standards
My changes ensure that the calendar titles are the users name. Before this change the top user would be mixed up with the administrator, due to the naming convention of each calendars div.
1. Go to the calendar
2. Got to a shared view
3. Ensure that the calendar settings are set to sepeared by user
4. Ensure that each calendar title correctly identifies the user by hovering over the events in that calendar.
> Fixed - user names in the calendar titles

- themes/SuiteP/css/style.css
Change the style the required divs. Fixed error field instead.
Due to feedback, the style has been changed back to the way it was previously styled.
> Updating style to fix error messages.

- include/SugarTheme/SugarTheme.php
- modules/ModuleBuilder/tpls/MBModule/dropdown.tpl
- modules/ModuleBuilder/views/view.dropdown.php
SuiteCRM 7.7(7.7.1) is not having issue by creating a dropdown using DropDown Editor. However, after the upgrade, the DropDown editor is having an issue creating a drop down parameter.
Create and Edit Drop Downs in admin/DropDown Editor
> Fixed #1945, fix for task 240 'Drop Down Editor is not functioning'

- include/SugarTheme/SugarTheme.php
- modules/ModuleBuilder/tpls/MBModule/dropdown.tpl
- modules/ModuleBuilder/views/view.dropdown.php
Reverts salesagility/SuiteCRM#1985
Failed change of Theme test
> Revert "Fixed #1945, fix for task 240 'Drop Down Editor is not functioning'"

- include/SugarTheme/SugarTheme.php
- modules/ModuleBuilder/tpls/MBModule/dropdown.tpl
- modules/ModuleBuilder/views/view.dropdown.php
SuiteCRM 7.7(7.7.1) is not having issue by creating a dropdown using DropDown Editor. However, after the upgrade, the DropDown editor is having an issue creating a drop down parameter.
Create and Edit Drop Downs in admin/DropDown Editor
> fix for task 240 'Drop Down Editor is not functioning' (revision)

- modules/Administration/metadata/adminpaneldefs.php
Just to recommit changes that were overwritten by a conflicting merge.  Tidies up the Admin Panel.
Housekeeping
Navigate the Admin Panel
> Resolving overwritten changes from commit - 56d57d7

- modules/Spots/controller.php
this PR contains a fix for Spots layout and an other fix for 'Sales Date' field on the Spot layout see in commit 68c14df05f53a5ce0f926d61546a72a39a95831f
Spots UI doesn't work on SuiteCRM 7.7.1
(reference: task 211, forum 10494)
> Fix for spots ui bug on php7

- download.php
> a download bug fixed

- include/DetailView/DetailView.tpl
- themes/SuiteP/css/style.css
- themes/SuiteP/include/DetailView/DetailView.tpl
- themes/SuiteP/include/DetailView/tab_panel_content.tpl
- themes/SuiteP/include/EditView/tab_panel_content.tpl
SuiteP Edit/Detail view issue with one field per row (task 229 issue #1931)
PR contains a fix for issue #1931
see instructions in related issue #1931 and change layouts of Edit/DetailView (in studio)
> SuiteP Edit/Detail view issue with one field per row (task 229 issue #1931)

- modules/AOR_Reports/AOR_Report.php
Relates to issue #1558. Reports now correctly link to records for the module field.
- Add a field into a report
- Set the link checkbox 
- Test the report
https://github.com/salesagility/SuiteCRM/pull/2006
> 7.6.4 - AOR - If row has "Link" checked, the ID is missing from the link

- themes/SuiteP/css/style.css
- themes/SuiteP/modules/Studio/TabGroups/EditViewTabs.tpl
Related it issue #1943
Drag and drop not working due to XML in smarty template variable. Set inner html to be blank:
> subspan1.innerHTML = '';
I also restyled the form to make it more suitable for the SuiteP theme.
Prevents user from changing the menu filter.
Change the menu filters.
> Fixed #1943 - Configure Module Menu Filters now working.

- modules/ModuleBuilder/javascript/ModuleBuilder.js
- modules/ModuleBuilder/tpls/assistantJavascript.tpl
- modules/ModuleBuilder/tpls/index.tpl
- themes/SuiteP/css/style.css
- Changed the style for the ajax status div.
The status messages/notifcations in studio were not appearing. This was due to the div being placed behind the top navigation.
- Select admin
- Select studio
- Select a module
- Go into layouts menu option
- Select a layout
- Make a change
- Select Save and Deploy
- You should see the white box show up in the middle if the screen
- 
-[x] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
> Fixed - studio ajax div status

- modules/ModuleBuilder/javascript/ModuleBuilder.js
An Issue with the drop down editor. When select save the in progress  dialog appears, but completed action dialog doesn't display.
Without this fix the user cannot continue editing drop downs after they save.
1. Admin
2. Dropdown editor
3. Select dropdown
4. Save 
Test Passes: when you see "This operation is completed successfully" in the dialog box.
> Fixed: status messages for the drop down editor.

- include/SearchForm/SearchForm2.php
I noticed an issue where search did not work on accounts module
use search filter on accounts module
> fix search form

- themes/SuiteP/css/style.css
In relation to issue #2000. This fixes the problem.
The columns in the admin panel were not responsive.
- Select Admin
- View the admin panels in different devices or screen widths
> Fixed #2000 - admin panel for mobile, tablet, laptop, and destkop

- include/TemplateHandler/TemplateHandler.php
This pull request is in relation to issue #1958.
This fixes changes the way the tpl cache is cleared, by clearing the tpl's per theme templates.
When a user changes a layout in studio it previously wouldn't clear the tpl cache correctly, causing the view to remain the same.
1. Admin
2. Studio
3. Module
4. Layouts
5. Edit View
6. Change the layout
7. Select Save And Deploy
8. Check that the view now matches the view in studio
9. Repeat this a couple of times
> Fixed #1958 - Clear tpl cache on a per theme basis.

- modules/Leads/views/view.convertlead.php
Fixed: Converted contact activity doesn't appear in Calendar
fix check users connected to bean.
Referenced to issue #971 
fix check users connected to bean.
Created a Call Activity "TestCalendar" for the Lead « Galen Polak », assigned to Chris Olliver
Converted Lead to Contact (selecting contact, not Account)
RESULT => Call from the Lead is displayed at the calendar, but not the call of the Contact
Fixes issue in converting contact activity appeariance in Calendar
Repeat steps from issue replication
> Fixed #971 Converted contact activity doesn't appear in Calendar

- themes/SuiteP/tpls/_headerModuleList.tpl
- themes/SuiteR/tpls/_headerModuleList.tpl
fixed Dashboard inside Dashboard - Double clicking Column Heading on Dashlet
A few minor changes in _headerModuleList.tpl
References bug #442
First, Go to Homepage by clicking the "SuiteCRM" on the top-left of the CRM.
Then, when double clicking on a Column's Heading on a Dashlet, i.e: "Name" or "Subject", It creates a 2nd Dashboard at that location. This 2nd dashboard seems to be a copy of the 1st, just on a smaller scale.
Prevent display Dashboard inside Dashboard
First, Go to Homepage by clicking the "SuiteCRM" on the top-left of the CRM.
Then, when double clicking on a Column's Heading on a Dashlet, i.e: "Name" or "Subject", It creates a 2nd Dashboard at that location. This 2nd dashboard seems to be a copy of the 1st, just on a smaller scale.
…g on Dashlet
> Bug442 Dashboard inside Dashboard - Double clicking Column Heading on Dashlet

- jssource/src_files/modules/Calendar/Cal.js
- modules/Calendar/Cal.js
Issue is the JSsource file is out of date with the cal.js file within the calendar module, this pull request syncs these and compresses the modules/calendar/cal.js file.  
Fixes issue #2052 
Fixes the issue around repair JS files in the admin panel. 
Run the repair JS files and test the calendar functionality
> Fixes #2052 - Problem with "Repair JS Files" and Calendar

- include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
- themes/SuiteP/css/style.css
- themes/SuiteP/include/SearchForm/tpls/SearchFormGeneric.tpl
- themes/SuiteP/include/SearchForm/tpls/header.tpl
Basic & advanced search odd layouts using SuiteP v7.7.x
This PR contains fix for layout issues: #1940 #1967 #1969 #2024 plus gymads changes
> Fixed - Restyled basic search

- include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
- themes/SuiteP/css/style.css
- themes/SuiteP/include/SearchForm/tpls/SearchFormGeneric.tpl
- themes/SuiteP/include/SearchForm/tpls/header.tpl
Basic & advanced search odd layouts using SuiteP v7.7.x
this PR contains fix for layout issues: #1940 #1967 #1969 #2024
task 236
see the instructions in related issues (quick repair and rebuild needed)
> Hotfix search layout task 236 issue 1940

- themes/SuiteP/css/style.css
Making text more prominent
It makes it more closer to the design.
Look at the main navigation
It should appear more bolder
> TopNav: making text more prominent

- themes/SuiteP/css/style.css
In Firefox is not correctly displaying the dropdown in suitep.
This pull request fixes the issue while keeping the style displaying correctly for other browsers.
Go into an edit view that has a dropdown selection
> Fixed - dropdown style in firefox

- config_override.php
- modules/iCals/iCal.php
iCal now export VTODO and no VEVENT
iCal now export VTODO and no VEVENT
References to bug #2094
Changes has been made with contribution of @chandon.
Thanks for contribution.
iCal now export VTODO and no VEVENT
Get the ics file with http://YOURSERVER/ical_server.php?type=ics&key=xxxx&email=yyyy@zzz.com
Check the ics file
Fixed iCal export VTODO and no VEVENT
> Fixed #2094 iCal now export VTODO and no VEVENT

- include/SugarFields/Fields/Link/DetailView.tpl
- modules/Accounts/metadata/additionalDetails.php
Bad html link to site(record information dialog-box)
Referenced issue #2101 
remove duplicated string for url.
remove duplicated string for url.
Create new account
Add some website link after "http://" text
Save record
Go to listview an click on information button
Click on link
Solve problem with URL in additional information, list view.
Repeat steps from replication.
> fixed #2101 - Bad html link to site(record information dialogbox)

- modules/AOR_Reports/AOR_Report.php
Added code to build_report_csv to calculate currency values correctly
If you had a report with different currencies it wouldn't calculate the values correctly for a csv export (this bug wasn't present in the html or pdf version)
Relates to issue #2035
Set up more than once currency type, then create opportunities with different currencies. Next create a report on opportunities and check the values look the same on the page as they do in a CSV report. 
> Fixed #2035 CSV Export of reports didn't carry out currency calculations

- themes/SuiteP/css/style.css
this PR redefine the contents size (and some css attribute on the pages) for eliminate the horizontal scrollbar from the bottom of screen
task 212
normally on the edit/list/detail-views you shouldn't see horizontal scrollbar at bottom (except if the current module contains a too big content or graphics for e.g. charts)
(quick repair and rebuild needed)
> Hotfix footer task 212 (2)

- include/language/en_us.lang.php
- modules/Home/index.php
- themes/SuiteP/include/MySugar/tpls/MySugar.tpl
> Fixed#1915 - Menu ACTIONS its not translatable - SuiteP

- include/language/en_us.lang.php
- install/suite_install/scenarios.php
- modules/AM_ProjectTemplates/controller.php
- modules/AM_ProjectTemplates/create_project.js
- modules/AM_ProjectTemplates/language/en_us.lang.php
- modules/AOP_Case_Updates/Case_Updates.php
- modules/AOP_Case_Updates/language/en_us.lang.php
- modules/AOR_Reports/tpls/report.tpl
- modules/AOS_Product_Categories/metadata/subpaneldefs.php
- modules/AOW_WorkFlow/metadata/detailviewdefs.php
- modules/AOW_WorkFlow/metadata/editviewdefs.php
- modules/Administration/BusinessHours.php
- modules/Administration/UpgradeWizard_commit.php
- modules/Administration/language/en_us.lang.php
- modules/Calendar/language/en_us.lang.php
- modules/Calendar/tpls/settings.tpl
- modules/Calls/language/en_us.lang.php
- modules/Calls_Reschedule/reschedule_form.js
- modules/Campaigns/TrackDetailView.php
- modules/Campaigns/WebToLeadCreation.html
- modules/DynamicFields/templates/Fields/Forms/iframe.tpl
- modules/DynamicFields/templates/Fields/Forms/url.tpl
- modules/Project/chart.php
- modules/Project/controller.php
- modules/Project/language/en_us.lang.php
- themes/SuiteP/tpls/footer.tpl
Fixed non-translatable labels outline in this bug description. Did not do JJW_Maps as these are status codes.
relates to issue #1772 #2097
> Bugfix 1772 - Not Translatable labels

- themes/SuiteP/css/style.css
this PR make Relate field buttons show on one line
task 214
> Relate field buttons show on new line (task 214)

- modules/Campaigns/WebToLeadFormBuilder.php
Changed the signature to fix the duplicate argument
relates to issue #1591
Breaks the web to lead builder.
Test the web to form process.
> Fixed #1591 - Redefinition of parameter $fieldRequired

- include/ListView/ListViewDisplay.php
relates to issue #2177 
returns results for contacts. 
Search for a contact using global search (not AOD)
> Fixes #2177 - Global Search Issue

- themes/SuiteP/css/style.css
- themes/SuiteP/include/DetailView/tab_panel_content.tpl
This change corrects the text in the detail view and exit view to better match the design of SuiteP.
Aesthetics
Compare design with the detail and edit view.
> SuiteP: Fixed fonts in detail view and edit view

- include/SugarFields/Fields/Datetimecombo/EditView.tpl
- themes/SuiteP/css/style.css
This change adds CSS classes to the date time combo field. In order to provide more control over how the filed is presented. It also makes the time element inline with the date element in the edit view. So when there is enough horizontal space it takes up less vertical room.
Saves vertical space. Makes it like the other themes.
* Go into and edit view with date and time combo (eg meeting, calls)
Passes: when the time element is inline with the date element. 
Consideration: The time element should only be inline if there is enough space.
> SuiteP: Making date/time combo field elements inline

- modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
When a Chart dashlet, for example ‘Pipeline By Sales Stage’, contains only one bar in the bar graph the graph is not drawn. See #2196
The funnel dashlet previously required an empty element at the end of the data array. This is not the case for the bar graph which is currently used.
In modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php the following check was done when generating the graph.
```
if(!is_array($chartReadyData['data'])||count($chartReadyData['data']) < 2)
```
Because there is actually no empty element at the end of the array this should be
```
if(!is_array($chartReadyData['data'])||count($chartReadyData['data']) < 1)
```
The other chart dashlets are ok, they all check that the count is < 1
Fix #2196
See #2196
> Fix #2196 - chart dashlet not drawn when there is a single element

- modules/Project/Project.php
Fix duplication of the project
Fix duplication of the project
References issue #2154
file Project.php doesnt have getDefaultStatus function
Click on random Project
Click duplicate button 3. 4.
make possible duplication of the project
Repeat steps from replication
> Fixed #2154 - Unable to duplicate Project

- modules/ModuleBuilder/language/en_us.lang.php
'LBL_RESET_LAYOUTS' value has a duplicated closing tag
> Duplicated closing tag on Reset Layouts value

- themes/SuiteP/css/style.css
SuiteP theme button spacing
see in #1942
see in task 238
> Fixed #1942, task 238 - margin added to buttons

- modules/Users/metadata/detailviewdefs.php
- modules/Users/metadata/editviewdefs.php
Fixed Photo field in Users module appearance
Fixed Photo field in Users module appearance, naming conflict fix
Referenced issue #2233
> Fixed #2233 - Photo field in Users module incorrect in layout

- modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
Fixed My-activity-stream-options-generates-error
Fixed My-activity-stream-options-generates-error
Referenced issue #2225 
Fixes My-activity-stream-options-generates-error
> Fixed #2225 - My-activity-stream-options-generates-error

- themes/SuiteP/include/DetailView/DetailView.tpl
- themes/SuiteP/include/EditView/EditView.tpl
- themes/SuiteP/js/style.js
the panels in detail view have no spacing between them (at bottom)
(the PR also contains a js error fix and relate to same task as PR 2224)
task/270
> fix for sub-panel spacing and a js error fixed

- themes/SuiteP/css/style.css
- themes/SuiteP/tpls/_headerModuleList.tpl
This issue is related to #2191. Due to the width of the sidebar, when an action in the sidebar is too long, the text wraps which causes the icon to display each state of the icon, showing multiple icons at the same time.
This change corrects the CSS and DOM so that the text can still can wrap when it reaches the width of the sidebar. I have also simplified the break points in relation to the side bar, the main content, and the footer.
1. Go in to the contacts module. It has an action with long text "Create contact from vCard".
2. Change the resolution/size of the browser to try and cause the side bar text to wrap.
Assert: You should see only one icon next to an action. 
Assert: The text of each action should align to the vertical centre of the icon. Excluding the text that has wrapped.
> Fixed #2191 - Action menu icons in the sidebar.

- include/utils/layout_utils.php
- modules/Users/PopupSignature.php
Fixed issue with No htlm editor in Email / Settings / Signature
Fixed issue with No htlm editor in Email / Settings / Signature
references issue #456 
go to email module
click settings, pop-up appear
click create (beside "signatures:"), another pop-up appear,
see if heder with html option is there
Repeat steps from replication section
> Fixed #456 - No htlm editor in Email / Settings / Signature

- modules/MergeRecords/SaveMerge.php
Perform various checks in the merge code to prevent the creation of new records, performing a merge on a record that you don't have access to and performing a merge on a non duplicate_merge module.
Prevents being able to modify and create records for modules that you do not have access to.
This only affects the merge functionality, testing that the existing merge works and testing that engineering a POST request to SaveMerge doesn't allow access to modules which the user should have no access to.
> Prevent unauthorised access to merging some records.

- include/language/en_us.lang.php
Fixed Duplicated string - Include - case_status_default_key
Fixed Duplicated string - Include - case_status_default_key
Remove redundant code
References issue #866
> Fixed #866 - Duplicated string - Include - case_status_default_key

- themes/SuiteP/js/style.js
Reminders - Spilling off screen
desktop reminders - popup spills off screen to right
task 247
> Reminders - Spilling off screen - task 247

- themes/Suite7/css/style.css
- themes/SuiteP/css/style.css
- themes/SuiteR/css/style.css
Activity stream reply font-size (work for all themes)
Activity stream reply font-size (work for all themes)
References issue #581
> Fixed #581 - Activitystream reply font-size

- include/utils.php
- install/checkDBSettings.php
- install/performSetup.php
- modules/AOP_Case_Events/CaseEventsHook.php
- modules/AOP_Case_Updates/CaseUpdatesHook.php
- modules/Calendar/CalendarActivity.php
- modules/ProjectTask/updateDependencies.php
This PR contains some fix for php error and notice on intaller and upgrade
task/297
> Hotfix task 297 install upgrade errors

- modules/Calendar/language/en_us.lang.php
changed the copyright year
clean up
changed the copyright year
> Little file formating and copyright year

- themes/SuiteP/css/style.css
When a user selects an item from the drop down the user cannot see the selected item. This is due to the line height on some browsers. However I also change a the option to show the last selected item and the text colour of the select item. This is particularly noticeable in the mass update on the detail view. 
Fixes user experience.
check the mass update on the list view.
check test the dropdowns.
> Fixing Select elements

- modules/OutboundEmailAccounts/OutboundEmailAccounts.php
Fixes the test dialog in outbound email accounts.
Prevents user from navigating around suitecrm.
- Go into the edit view for outbound email accounts
- click test email
- you should be able to test the email
> Fixed: Test Email popup disappears and unable to close

- modules/Cases/controller.php
#1876 Knowledge Base Query not Strict SQL compatible
related Issue #1876
task/321
> Hotfix task 321 cases knowledgebase suggestion mssql

- modules/Calendar/CalendarDisplay.php
Fixed CalendarDisplay.php text next to arrays prev next. The text breaks the layout.
> Fixed CalendarDisplay.php text next to arrays prev next

- themes/SuiteP/css/style.css
related to #2369 - fix sidebar icons bg-colour on hover
> fix sidebar icons bgcolor on hover

- themes/SuiteP/css/style.css
bootstrap.css is overriding select element when it has a size attribute
Goto meeting/calls. The date dropdowns should correctly show the correct size
> Fixed select option css

- themes/SuiteP/css/style.css
icons are in the way of the text in meeting reminders
Fixes the issue
> Fixed reminder buttons in suitep

- themes/Suite7/css/style.css
Fixed - Suite 7 theme table width issue
Fixed - Suite 7 theme table width issue
References issue #2355 
In Suite 7 theme, all modules page have table width issue. Second table is a little bit wider than 1st table.
Improve appearience of suite 7 theme
Repeat steps from bug replication section
> Fixed #2355- Suite 7 theme table width issue

- include/MySugar/javascript/retrievePage.js
- include/MySugar/tpls/MySugar.tpl
> dashboard: fixes

- modules/Meetings/metadata/editviewdefs.php
- modules/Reminders/Reminders.js
Meeting created without a subject
This Pull Request revert a commit from issue #1178 (Validation failed on POST) and fix the issue #2510 
(Empty subject saved)
PR also contains a bugfix for Reminders (add all invitees by default)
Meeting created without a subject (task/337)
Save or Create a Meeting without Subject
> Hotfix task 337 issue 2510 meeting save

- themes/SuiteP/css/style.css
this PR set the correct background colour for Top Nav Search field
see issue #2453
> Fixed #2453 - Set top nav search bgcolor in FF

- themes/SuiteP/css/style.css
- themes/SuiteP/images/sidebar/modules/search-close.svg
- themes/SuiteP/js/style.js
- themes/SuiteP/tpls/_headerModuleList.tpl
Fixed the global search button for mobile and tablet. This change enables the user to toggle the search form. I have moved the search form to over lap in the purple bar. I have also moved the xs breakpoint to 750px width. This is due an issue found after testing on an iPhone. When the iphone is oriented horizontally you cannot see the search text with the keyboard in view. So I have extended the breakpoint to ensure that the user can see the text.
Also found an issue at around 1150px, the quick create button floats off the purple bar. I have also added a fix, by reducing the padding of the navigation menu's on small desktop screens.
iPhone
iPad
Desktop
This change is only for SuiteP.
Try searching something on mobile and tablet.
You can now toggle the search form.
Moved xs breakpoint …
> Fixed search for mobile/tablet. Moved xs breakpoint to 750px.

- modules/jjwg_Maps/views/view.config.php
Wrong API key max length - fixed
Wrong API key max length - fixed
References issue #2413
> fixed - #2413 Wrong API key max length

- modules/Favorites/Favorites.php
To resolve the issue of showing deleted favourites in sidebar:
"Favorite records that was deteted still appear in menu but without name. There is only icon of the module in which record was created and the edit icon."
Resolved by ensuring that the returned array contains info of the bean if it exists.
Looks likes this resolves these issues:
https://github.com/salesagility/SuiteCRM/issues/826 and https://github.com/salesagility/SuiteCRM/issues/761
Add a favourite and see it appear on your favourites list (on sidebar).  Delete this record and see that the item from the favourites list has been removed also.
> Fixed 826 - Deleted favorite records still appear in menu

- modules/FP_events/language/en_us.lang.php
Unused language strings (FP_events) - fixed
Unused language strings (FP_events) - fixed
References issue #2592
> fixed - #2592 Unused language strings (FP_events)

- modules/Delegates/language/en_us.lang.php
Unused language strings (Delegates) - fixed
Unused language strings (Delegates) - fixed
References issue #2591
> fixed - #2591 Unused language strings (Delegates)

- modules/Emails/language/en_us.lang.php
Unused language strings (Emails) - fixed
Unused language strings (Emails) - fixed
references issue #2582
> fixed - #2582 Unused language strings (Emails)

- include/ListView/ListViewColumnsFilterDialog.tpl
- include/ListView/ListViewColumnsFilterLink.tpl
- include/ListView/ListViewGeneric.tpl
- include/ListView/ListViewPagination.tpl
- include/SearchForm/SearchForm2.php
- include/SugarEmailAddress/SugarEmailAddress.php
- include/language/en_us.lang.php
- modules/SavedSearch/SavedSearch.php
- themes/Suite7/css/style.css
- themes/SuiteP/css/style.css
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
- themes/SuiteP/include/ListView/ListViewPagination.tpl
- themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl
- themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
- themes/SuiteR/css/style.css
Column Header Customization
User preferences based columns customization popup chooser added to list view header
SCRM-25 US 5.3 - Column Header Customization
> Feature scrm 25 column header customization

- themes/SuiteP/js/style.js
- themes/SuiteR/css/style.css
bulk action button css fixed on SuiteR theme
> bulk action button fixed on SuiteR

- include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
- include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonMeetings.php
- themes/SuiteP/js/style.js
- themes/default/js/style.js
This fixes the labels in the subpanel so that in english they are title case.
This PR is in response to internal testing.
> Fixing Lower Case labels

- themes/SuiteP/css/panels.scss
- themes/SuiteP/css/style.css
- themes/SuiteP/css/style.scss
- themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl
- themes/SuiteP/js/style.js
Made fixes to the way footable is initialised. And fixed css regression.
Test the subpanels in the detail view
> Fixing regression

- include/ListView/ListViewPagination.tpl
- themes/SuiteP/css/style.css
- themes/SuiteP/include/ListView/ListViewPagination.tpl
- themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl
- themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
- themes/SuiteP/js/style.js
Relate Fields are not auto searching when typing in. Issue on PR #2764 
contains a fix for filter button on mobile screen
> fix autocomplete on search fields

- modules/AOW_WorkFlow/vardefs.php
Inline editing - Workflow - fixed
Inline editing - Workflow - fixed
References issue #573 
If you try to inline edit the conditions or actions sub panel on Detail view. All fields are lost and unable to change specific fields.
The values are still kept 'safe' but user is unable to change the values
!Note - the inline editing in described places shouldnt be in options, i the fix disables inline edit in this place.
> fixed - #573 Inline editing - Workflow

- themes/SuiteP/js/style.js
Access tab does not work in USERS module(detailView) - fixed
Access tab does not work in USERS module(detailView) - fixed
References issue #2842 
References issue #2137
> Fixed #2842 - Access tab does not work in USERS module(detailView)

- Api/V8/Controller/ActionController.php
- Api/V8/Controller/ModuleController.php
- Api/V8/Controller/UserController.php
- Api/V8/Controller/UtilityController.php
- Api/V8/Library/ModuleLib.php
- Api/V8/Library/UserLib.php
- Api/V8/Library/UtilityLib.php
- Api/V8/Route/ActionRoutes.php
- Api/V8/Route/ModuleRoutes.php
This is the current state of the V8 in our repo
> Updated the V8 with our updated & improved version

- themes/SuiteP/css/style.css
7.7.4 Suite P theme not wrapping text in Accounts Billing and Shipping details - fixed
7.7.4 Suite P theme not wrapping text in Accounts Billing and Shipping details - fixed
References issue #2203
> Fixed #2203 - 7.7.4 Suite P theme not wrapping text in Accounts Billing and Shipping details

- include/ListView/ListViewColumnsFilterDialog.tpl
- include/SearchForm/SearchForm2.php
- include/SearchForm/tpls/footerPopup.tpl
- include/SearchForm/tpls/headerPopup.tpl
- modules/MySettings/StoreQuery.php
- themes/SuiteP/css/listview.scss
PR for Tab Search View issues (ref.  SCRM-114)
- save selected search tab
- show selected tab on mobile
> PR for Tab Search View issues (ref.  SCRM-114)

- include/ListView/ListViewColumnsFilterDialog.tpl
- modules/MySettings/StoreQuery.php
Maintain Search Filter when adjusted Listview Layout (ref: SCRM-140)
> Maintain Search Filter when adjusted Listview Layout (ref: SCRM-140)

- include/MVC/View/views/view.list.php
- modules/SavedSearch/SavedSearch.php
- fix saved search name on search form 
- revert last columns filter changes
> fix search form and revert last columns filter changes

- include/ListView/ListViewSearchLink.tpl
Rename 'Saved Search' dropdown (ref. SCRM-182)
> Remove None option 'Saved Search' dropdown

- include/ListView/ListViewSmarty.php
- include/SearchForm/SearchForm2.php
Rename config option 'use_legacy_search' (ref. scrm 183)
use 'enable_legacy_search' instead 'use_legacy_search'
> Rename config option 'use_legacy_search'

- include/MVC/SugarApplication.php
- modules/Campaigns/EmailQueue.php
- modules/Campaigns/MailMerge.php
- modules/Campaigns/RoiDetailView.php
- modules/Campaigns/TrackDetailView.php
- modules/Campaigns/Tracker.php
- modules/Campaigns/WebToLeadCapture.php
- modules/Campaigns/WebToPersonCapture.php
- modules/Campaigns/WizardEmailSetupSave.php
- modules/Campaigns/WizardHome.php
- modules/Campaigns/WizardMarketingSave.php
- modules/Campaigns/WizardNewsletterSave.php
- modules/SavedSearch/SavedSearch.php
hanging issue in Firefox fixed
ref: SCRM-27 US 5.5 - Saved Searches
related to commit cd74e3904434d7e24bb350058a4654d4a415d14e
> hanging issue in Firefox fixed

- themes/SuiteP/css/campaigns.scss
- themes/SuiteP/css/editview.scss
- themes/SuiteP/css/forms.scss
- themes/SuiteP/css/yui.scss
Making the fields in the edit view appear to align together.
* More pixel perfect match of the design
* Compile style.css
* Check the the edit view in each module
> Aligning fields in the edit view

- themes/SuiteP/css/tabs.scss
Due a fix I made for the mobile. When a user accesses the detail view the first tab has a lot of white space at the bottom of the tab. The reason is that I needed to remove the inline style so that the user could see the tabs in the mobile. This change adds the display:none property using the css instead of inline thus fixing the problem.
* Bug fix
* compile sass
* access detail view
* check that the tab doesn't have extra white space at the bottom.
> Fixing detail view tabs (extra white space)

- modules/Leads/views/view.convertlead.php
> Fix Convert Lead function

- include/ListView/ListViewGeneric.tpl
- themes/Suite7/css/style.css
- themes/SuiteP/css/listview.scss
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
- themes/SuiteR/css/style.css
> Fixing styles for SuiteP, SuiteR and Suite7

- include/ListView/ListView.php
- include/ListView/ListViewSubPanel.php
mail merge js error
(ref: SCRM-255 Mail Merge javascript SuiteP)
When the Mail Merge setting is on there is a javascript error on all subpanels.
> mail merge js error

- include/SugarEmailAddress/SugarEmailAddress.php
- include/SugarObjects/templates/company/Company.php
- include/SugarObjects/templates/person/Person.php
- modules/EmailAddresses/EmailAddress.php
- modules/Emails/EmailUI.php
This PR contains a fix for issue #3000 (Warnings reported when cron.php is executed)
> fix for issue #3000: Warnings reported when cron.php is executed 

- themes/SuiteP/css/editview.scss
- themes/SuiteP/css/main.scss
- themes/SuiteP/css/navbar.scss
On smaller displays there is horizontal scroll bar in SuiteP.
* This corrects the css issue
* Recompile Sass
* Test SuiteP on 1440 x 900 px screen
* The dashboard is a good place to check.
> Fixed - Horizontal Scroll Bar when width < ~1500px

- include/social/get_feed_data.php
Required file moved from `'custom/modules/connectors/sources/ext/rest/rwitter/config.php'` to `'modules/connectors/sources/ext/rest/rwitter/config.php'`.
The required file has moved from `custom/modules/` to `modules/`.
Wrong path, crashes the application.
Use the twitter feature on the SuiteCRM Home page.  Before the fix, it was crashing the browser with a blank page.  Many forum posts.  See issue #905.
> Fix for #905. require_once, wrong path, crashes twitter feature.

- data/SugarBean.php
Fix problem with roles when configured for "owner" attribute.
When attribute in table is set to "Owner", the user don't see any record in list view, 
References #3054 
References #3120 
References #3134
> Fixed #3054 - problem with roles when configured for "owner" attribute

- modules/SecurityGroups/SecurityGroup.php
According to Issue reporter, "this breaks REST API ... and probably much more"
It's an obvious typo, so I just went in and fixed it : - )
> Fix #3151 typo in sql query

- themes/SuiteP/css/listview.scss
- themes/SuiteP/css/variables.scss
This PR re-styles the Security Group: Mass Assign form at bottom of ListView
(ref: SCRM-146)
https://github.com/salesagility/SuiteCRM/pull/3137#pullrequestreview-22661872
The changes need to rebuild style.css
> Security Group Mass Assign form re-style

- themes/SuiteP/modules/Users/tpls/DetailView.tpl
SuiteP Users DetailView refact and remove access tab form cache
(ref: SCRM-163 Detail View Issues)
user access tab cached by tpl cache incorrectly
- need to clear cache and QRR 
- open DetailView of any admin user
- open DetailView of any non-admin user
=> there is no access tab which is incorrect
- clear the cache and QRR
- open DetailView of any non-admin user
- select the access tab
- open DetailView of any admin user
- select the access tab
=> there is the previous non-admin user roles which is incorrect
> SCRM-163 Detail View Issues

- modules/AOW_Processed/Menu.php
This change fixes the icons issue #3104.
The action icons in the side bar appear missing in the AOW_Processed module.
* Fixes issue
* Navigate to the workflow module
* In the side bar select view process audit
> Fixed #3104 - side bar action icons for AOW_Processed

- modules/AOR_Reports/AOR_Report.js
- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
- modules/AOR_Reports/Dashlets/AORReportsDashlet/dashlet.tpl
- modules/AOR_Reports/controller.php
- themes/SuiteP/css/dashboard.scss
This change fixes the pagination for Reports. The initial issue was related to the the dashlet. However I noticed that we needed to unify the pagination in both the detail view and the dashlet. So this change attempts to do so. I have also added a change to fix the buttons in the dashlet.
* fixes the bug
* Rebuild the sass
* Create a report which result in more than  20 records
* Try and paginate through them
> Fixing pagination in reports

- include/MVC/View/tpls/Importvcard.tpl
- themes/SuiteP/css/editview.scss
Styling create lead / contact from vcard (SuiteP)
> Styling create lead / contact from vcard (SuiteP)

- themes/SuiteP/css/login.scss
- themes/SuiteP/tpls/login.tpl
This change fixes #3055. 
* Fixes issue with SuiteP Design
* Rebuild Sass
* Install language pack
* Log out
> Login: Adding space after language chooser (SuiteP)

- themes/SuiteP/tpls/_headerModuleList.tpl
The navbar overflows (between width: 1200px - 1215px). This fix attempts to remedy the issue.
This issue relates to #3025.
* Fix responsiveness
* clear browser cache
* see https://github.com/salesagility/SuiteCRM/pull/3025#issuecomment-281827611
> Removing filter from windowResize

- themes/Suite7/css/style.css
(ref.: SCRM-234 Filtering - Suite7 Theme)
- bulk action padding 
- red hover over buttons
> SCRM-234 Filtering - Suite7 Theme

- themes/SuiteP/css/editview.scss
- themes/SuiteP/css/listview.scss
This PR fix the bootstrap designed chechbox position on listview in Firefox
(ref: SCRM-146)
Recompile style.css
> listview checkbox position fix on FF

- modules/Home/About.php
- modules/Home/language/en_us.lang.php
Community translations acknowledge on the about page
Text can also be translated by each team on Crowdin
To make a reference to Crowdin collaborative translations at
https://crowdin.com/project/suitecrmtranslations
Apply changes, quick repair, reload!
functionality to change)
[here](https://suitecrm.com/wiki/index.php/Coding_Standards).
Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM)
guidelines.
> Translations acknowledge on About page

- include/social/twitter/twitter_auth/callback.php
- include/social/twitter/twitter_helper.php
- include/social/twitter/twitterapi.php
Fixed 3 files with incorrect require and include paths related to Twitter connector.
Twitter connector moved from custom to core.
Also, one require was trying to get file with path relative to current file folder and was not found.
White screen browser, crashed application.
Login to the Twitter connector on the Home page.
> More fixes for #905 Twitter connector crash.

- include/ListView/ListViewSmarty.php
Fixing typing error in list view after review of PR #3215.
* Fixes the edit button in the list view
> Fixing typing error in list view

- themes/SuiteP/include/ListView/ListViewGeneric.tpl
Removing $templateMeta from ListViewGeneric.tpl  review of PR #3215.
> Removing $templateMeta from ListViewGeneric.tpl

- include/javascript/mozaik/jquery.mozaik.css
- include/javascript/mozaik/jquery.mozaik.js
- themes/SuiteP/css/campaigns.scss
- themes/SuiteP/css/variables.scss
Change the current background colour of the Email Templater Editor's blocks to be 'off-white' #fafafa.
(ref: SCRM-330)
-	tpl editor bgcolor set to #fafafa (off-white)
> tpl editor bgcolor set to #fafafa (off-white)

- include/SugarTheme/SugarTheme.php
- themes/Suite7/themedef.php
- themes/SuiteP/themedef.php
- themes/SuiteR/themedef.php
This PR a branch correction for PR #3211 
Deprecate Suite7 & SuiteR Themes from themedef.php
(ref: scrm-333)
- acceptable suitecrm version added to themedef.php
- add/remove/modify value of $themedef['version']['regex_matches'] = array('^7\.[0-8][^\d]'); from themedef.php
- update $suitecrm_version (for e.g upgrade or just change it in suitecrm_version.php)
> Develop scrm 333 themedef

- modules/Contacts/updatePortal.php
Customer Portal Welcome Email Blank - fixed
References #3261
> Issue #3261 - Customer Portal Welcome Email Blank - fixed

- include/language/en_us.notify_template.html
- modules/Meetings/Meeting.php
Add field assignment when processing template.
Add field in missing places in the template.
See steps in related issue.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [  ] New feature (non-breaking change which adds functionality)
- [  ] Breaking change (fix or feature that would cause existing functionality to change)
- [ X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [  ] My change requires a change to the documentation.
- [ X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
> Fix #3222 meeting location field in email notifications

- README.md
- modules/Documents/metadata/subpaneldefs.php
> Fix for #3241

- modules/AM_ProjectTemplates/js/main_lib.js
- modules/Project/js/main_lib.js
- modules/Project/js/main_lib_chart.js
Project and project templates were trying to load a non existent image `themes/SuiteP/images/img_loading.gif` the correct location is `themes/default/images/img_loading.gif`.
See issue #3028 
Broken image.
See #3028 .  Click Project, try to add or edit an item. Your should see the animated gif.
> Fix #3028 path for img_loading.gif

- modules/SugarFeed/SugarFeed.php
Consider the following scenario:
You want to save an Opportunity with a name exactly 28 bytes long and the Account name is exactly 35 bytes long. The default currency is Euro with it's sign (€) in the config and the amount of the opportunity is 2016,03.
With the text of the SugarFeed, this will be more than 255 bytes long (since the € sign takes 3 bytes) so Suite gonna try to cut it after 255 bytes. Since this is at the "middle" of the 3 byte € sign, it will cut it half which results in two invalid characters, which can give the database a hard time.
If we count the UTF-8 characters instead of the bytes of the string, and cut the string as UTF-8, then the problem disappears.
Changed the string functions to their multi-byte counterparts.
Issue #2796
> SugarFeed content cut for UTF-8

- include/ListView/ListViewGeneric.tpl
Table header background issue (Suite 7) - fixed
Table header background issue (Suite 7)
References issue #2753
> fixed - #2753 - Table header background issue (Suite 7)

- modules/Users/controller.php
Added EditView Action and DetailView Action that checks if user is allowed access to these sections for the id parameter provided.
To reproduce login with non admin user and manual format url to include admin user 1 as parameter for editview also check for detailview 
Security update
Login with non admin user and manual format url to include admin user 1 as parameter for editview also check for detailview.
Also check that non admin user can change password
> Issue #2695 Fix Check If User Can Edit User With id In Users Controller

- themes/SuiteP/css/navbar.scss
- themes/SuiteP/css/tabs.scss
- themes/SuiteP/css/variables.scss
I noticed that that you can't easily change the colors of the quick create button. So i have fixed the variables so that you now can.
* Rebuild scss
* Change the variables under the quick create section
> Making Quick Create more customisable (SuiteP)

- include/InlineEditing/inlineEditing.js
- include/language/en_us.lang.php
- modules/AM_ProjectTemplates/controller.php
- modules/AM_ProjectTemplates/css/style.css
- modules/AM_ProjectTemplates/js/main_lib.js
- modules/AM_ProjectTemplates/metadata/detailviewdefs.php
- modules/AM_ProjectTemplates/project_table.php
- modules/AM_ProjectTemplates/views/view.ganttchart.php
- modules/Project/Project.php
- modules/Project/ProjectListViewData.php
- modules/Project/ProjectListViewSmarty.php
- modules/Project/Save.php
- modules/Project/chart.php
- modules/Project/controller.php
- modules/Project/css/style.css
- modules/Project/css/style_chart.css
- modules/Project/js/main_lib.js
- modules/Project/js/main_lib_chart.js
- modules/Project/metadata/detailviewdefs.php
- modules/Project/project_table.php
- modules/Project/views/view.ganttchart.php
US 2.1 - As a User I want Gantt views to display the appropriate drop down action buttons so that I can access functionality on the Gantt View.
US 2.4 - As a User I want to be able inline edit fields on the Gantt views so that it follows generic SuiteCRM functionality.
US 2.7 - As a User I want the detail view section of the Gantt view to be consistent with the rest of the CRM so that I can in line edit and access action buttons.
US 2.6 -As a User I want the duration of a project or project template to be calculated from the days between the start of the first project task and the end of the last project task.
US 4.2 - As a User creating filtering criteria on the Resource Chart I want the search criteria fields to display the same as a List View advanced search so that the CRM maintains …
> All the remaining commits on projects enhance branch

- modules/AOS_PDF_Templates/formLetter.php
Orders templates alphabetically as suggested in enchancement #712
> #712 order templates alphabetically

- modules/AOR_Charts/AOR_Chart.php
> Branch issue 1489

- include/language/en_us.lang.php
- modules/Emails/Dashlets/MyEmailsDashlet/MyEmailsDashlet.data.php
- modules/Emails/Email.php
- modules/Emails/field_arrays.php
- modules/Emails/language/en_us.lang.php
- modules/Emails/metadata/SearchFields.php
- modules/Emails/metadata/detailviewdefs.php
- modules/Emails/metadata/editviewdefs.php
- modules/Emails/metadata/listviewdefs.php
- modules/Emails/metadata/quickcreatedefs.php
- modules/Emails/metadata/searchdefs.php
- modules/Emails/metadata/subpanels/ForUnlinkedEmailHistory.php
- modules/Emails/vardefs.php
- modules/History/language/en_us.lang.php
- modules/History/metadata/subpaneldefs.php
adding a dropdown field to the Email module
> email category

- modules/AM_ProjectTemplates/controller.php
- modules/AM_ProjectTemplates/project_table.php
- modules/AM_ProjectTemplates/views/view.ganttchart.php
- modules/Project/Project.php
- modules/Project/controller.php
- modules/Project/js/main_lib.js
- modules/Project/js/main_lib_chart.js
- modules/Project/metadata/quickcreatedefs.php
- modules/Project/views/view.ganttchart.php
US 1.8 
Fixed - When linking a Project Template via a Project Edit View the tasks are incorrectly calculated - see screenshot 1-8, 1-8-1, 18-2 of my steps. When creating a Project task from the project its correctly calculated. The Project Template itself is also selected to have working days considered i.e. true.
US 2.6 
Fixed - Unable to Create Project via Project Template
I can not create a Project via the Project Template > Edit button > Create Project. There is no error logs and I have already RepairJS files.
It worked from detail view but gantt chart view had problems which are fixed.
US 4.1, US 4.3.1
Fixed - it appears that the task only shows its details on the start and the end date blocks, but nothing between including the 'non' working days that I have selected (in the …
> US 1.8, 2.6 , 4.1, 4.3.1 fixes

- include/SuiteMozaik.php
- include/javascript/mozaik/jquery.mozaik.js
email template width (scrm 300)
this PR revert back to setWidth function and apply some fix again on the develop branch and solve the width issue related the early PR: https://github.com/salesagility/SuiteCRM/pull/3200
(ref: kb scrm 300)
> email template width

- modules/Emails/include/ListView/CheckNewEmails.js
- modules/Emails/include/ListView/ListViewDataEmails.php
- modules/Emails/include/ListView/ListViewSmartyEmails.php
- modules/Emails/include/displayHasAttachmentField.php
- modules/Emails/include/displayIndicatorField.php
- modules/Emails/metadata/editviewdefs.php
- modules/InboundEmail/InboundEmail.php
- themes/SuiteP/css/variables.scss
This change handles the sorting and fitlers for imap headers.
> Email client filters

- include/javascript/mozaik/jquery.mozaik.css
- include/javascript/mozaik/jquery.mozaik.js
> email tpl width fix

- modules/AOS_PDF_Templates/views/view.edit.php
- modules/EmailTemplates/EditView.php
> insert value fix

- modules/InboundEmail/InboundEmail.php
> Fixing sorting in the email list view.

- modules/Home/About.php
> fix version on about page

- include/upload_file.php
> fixing upload_file path

- modules/UpgradeWizard/uw_utils.php
> upgrade version check fix

- include/SugarFolders/SugarFolders.php
- modules/Emails/EmailUIAjax.php
- modules/Emails/include/ListView/ListViewDataEmails.php
This change better complies with our coding standard
This change is a reaction to @gymad review on #3462 
na
> Code Review - Matching coding standards

- modules/Emails/EmailUIAjax.php
> Fix 500 error

- include/SugarLogger/SugarLogger.php
can we have something like this configurable log trace info which is very useful when debugging?
able to developers to find and solve any issue faster and easier
use the logger anywhere in the source: for e.g:
$GLOBALS['log']->debug("here we are... but where did we come from?");
and then switch on the `$sugar_config['show_log_trace'] = true;` in file `config.php` or `config_override.php`
> show_log_trace

- include/EditView/EditView2.php
- include/ListView/ListViewDisplay.php
- include/ListView/ListViewEval.tpl
- modules/Emails/controller.php
- modules/Emails/include/ListView/ImportEmailAction.js
- modules/Emails/include/ListView/ListViewDataEmails.php
- modules/Emails/include/NonImportedDetailView/NonImportedDetailView.php
- modules/Emails/language/en_us.lang.php
- modules/Emails/metadata/listviewdefs.php
- modules/Emails/metadata/nonimporteddetailviewdefs.php
- modules/Emails/templates/displayIndicatorField.tpl
- modules/Emails/templates/displaySubjectField.tpl
- modules/Emails/vardefs.php
- modules/Emails/views/view.detailnonimported.php
- modules/InboundEmail/InboundEmail.php
- themes/SuiteP/css/email.scss
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
This change adds a the email feature from the detail and list views. 
There is also an indicator in the list view to show which emails are imported using a tick.
There now is a new view called DetailedNonImported. This as its own metadata file nonimporteddetailviewdefs.php. It is responsible for display emails which haven't been imported. The reason for its own definitions is simply to remove SuiteCRM fields and only have an import action in the action menu. I have swapped the name field of a subject function field. So that I can pass the Imap information to "action_DisplayDetailView" controller action which decides which view to use. Imported emails will use the standard detail view.
You can override the bulk actions via the listviewdefs.php:
```
$viewdefs['Emails']['ListView'] = array( …
```
> Adding importing emails

- modules/Emails/metadata/composeviewdefs.php
- themes/SuiteP/css/email.scss
I have change css for the compose view in the modal so that the related fields look better in a single and dual column.
> Making email template and related to use single column

- include/SugarFields/Fields/Html/DetailView.tpl
This change fixes the parsing issues with the html field.
> Fixed html field detail view

- modules/Users/Login.php
- modules/Users/language/en_us.lang.php
Changed modules/Users/Login.php to check custom versions of login.tpl. This fixes placing tpl files in the custom folder not overriding the core SuiteP files.
> Fixed #3522 - Custom files not overriding SuiteP core - 7.9 Beta

- modules/AM_ProjectTemplates/language/en_us.lang.php
Punctuation change required
Issue details: Project Templates: Project from Project Title - language #3478
Translation issues
> Fixed #3478 - Project Templates: Project from Project Title - language

- modules/Home/index.php
A file_exists check is done on a file in a certain location but the fetch then uses another location.
It can fix the issue of a fetch being done on a file which doesn't exist.
Create a custom MySugar.tpl in 'custom/themes/' . $theme . '/tpls/MySugar.tpl' and then see the homepage doesn't display what is contained in that file. Apply fix and see that it now does.
> Fix file fetch

- include/ListView/ListViewData.php
- modules/Emails/include/ListView/ListViewDataEmails.php
- modules/Emails/language/en_us.lang.php
- modules/Emails/metadata/editviewdefs.php
- modules/Emails/metadata/searchdefs.php
- modules/Emails/vardefs.php
- modules/InboundEmail/InboundEmail.php
Task: scrm-10
This change provides a means to filter both CRM and IMAP fields in the email module. In order to keep the filter form consistent with the other modules. The ListViewDataEmails class now has two sources for the filters - CRM and IMAP. The CRM search uses the emails table to filter the content. The IMAP search uses just the IMAP fields (to, from, cc, bcc, subject, body) on the IMAP server. When the users filters the list view, the ListViewDataEmails class decides which search to use. There are three cases: IMAP only, CRM only, and IMAP and CRM. Since the email client imports all the information from the IMAP server the IMAP and CRM just filters the CRM.
There is a case where an email is imported into the CRM but it is removed from the IMAP server. I have added an orphaned …
> Adding improved filter support

- modules/AOS_PDF_Templates/PDF_Lib/mpdf.php
Fixed #2153  -Images in PDFs not showing
In PHP7, There was an issue that when you created a pdf with a png image it would not display it.
It solves the issue of displaying images in pdf templates in PHP 7
Set company logo to a png file, then export a report ensuring you are using php 7. You will see a red X where the logo should be in the report. Try the same thing again with fix applied and see the image.
> Fixed #2153 -Images in PDFs not showing

- include/MVC/Controller/SugarController.php
- include/SugarFolders/SugarFolders.php
- modules/Emails/controller.php
- modules/Emails/include/ListView/FoldersViewModal.js
- modules/Emails/language/en_us.lang.php
Task: scrm-6
Emails incorrectly displays the folders due to the SQL query not respected the deleted field
> Fix folders duplication for emails

- modules/jjwg_Maps/jjwg_Maps.php
- modules/jjwg_Maps/language/en_us.lang.php
- modules/jjwg_Maps/views/view.config.php
- modules/jjwg_Maps/views/view.map_markers.php
References issue #3070 
After a user creates a map related to an account or contact that has a billing address in the Maps Module. When they try to display the map (look at the maps field), it comes up with and error.
This error is a run time error. It it produced when the API key is not specified in the script element.
I have added an API key field to the google maps admin panel. I have also added a link to the google maps API page. So that a user can easily get an API key. 
When the API key is empty the display maps page will give an error instructing the user to set the API key in the admin panel.
There are new language labels that will need to be translated.
- Due to a change in the google API's with out the key you cannot use the google maps facility.
- Create a map
- Relate it to an …
> Fixed - Error message in display maps. Added Google Maps API Key field.

- modules/Spots/metadata/SearchFields.php
- modules/Spots/metadata/editviewdefs.php
- modules/Spots/metadata/searchdefs.php
- modules/Spots/views/view.edit.php
Fixed - Can add Spots to Favorites now
Fixed - Can add Spots to Favorites now
References issue #2053 
Favorites icon is not displayed on Spot's DetailView.
Make possible favour spots
Repeat steps from replication section
> Fixed #2053 - Can't add Spots to Favorites

- modules/Emails/EmailUI.css
- modules/Emails/templates/editAccountDialogue.tpl
- modules/Emails/templates/emailSettingsFolders.tpl
- modules/Emails/templates/emailSettingsGeneral.tpl
This fix changes the style of the email settings popup.
SCRM-526
> Email settings style

- modules/Users/Login.php
Fixed the login page displaying the wrong tpl due to a wrong path in the login.php if statements.
1. Go to the login page.
2. Check that the correct tpl is displayed depending on whether you have custom login tpls.
> Fixed wrong path for login tpls

- modules/UpgradeWizard/uw_utils.php
Upgrade fix (ref: scrm-519)
Upgrade process have to upgrade the UpgradeWizard files first.
This PR also contains a change to able to add extra files to pre-upgrade process manually in upgrade pack. If the upgrade contains an extra php file named files_to_add_post.php and it's contains an array definition like this: `$filesToAddPost = array('filename1', 'filename2', );` the upgrade process copy these files first.
Impossible to upgrade the crm when the release change the upgrade process itself
see: description
> Upgrade fix

- modules/InboundEmail/InboundEmail.php
issue with the fields not matching the correct email on the listview and detail views. 
This change fixes the uid and msgno.
> Fixing ListView & DetailView

- include/DetailView/DetailView2.php
- include/EditView/EditView2.php
- include/MVC/View/views/view.edit.php
- include/Sugar_Smarty.php
- include/TemplateHandler/TemplateHandler.php
- modules/Emails/include/DetailView/EmailsDetailView.php
- modules/Emails/include/DetailView/EmailsDraftDetailView.php
- modules/Emails/include/DetailView/EmailsNonImportedDetailView.php
- modules/Emails/views/view.detail.php
- modules/Emails/views/view.detaildraft.php
- modules/Emails/views/view.detailnonimported.php
Issue: when switching between the different detail views in the emails module. The action menu does not update due to how smarty caches templates.
This change fixes the issue where the action menu is not kept up-to-date.
Check the action menu for each detail view in the email module.
I noticed and opportunity to remove code duplication when checking for the custom template. We should go through the view.detail and view.edit files to remove get_custom_file_if_exists call.
> Fix smarty cache

- modules/Emails/include/ComposeView/EmailsComposeView.js
onTemplateSelect was removed during a merge.
This corrects the issue by adding back in.
Repair and rebuild
> Fixing merge issue - Email template ComposeView

- include/utils.php
- install.php
- install/installSystemCheck.php
- install/installType.php
- install/language/en_us.lang.php
- install/old_php.js
- install/old_php.php
- install/welcome.php
- modules/UpgradeWizard/language/en_us.lang.php
- modules/UpgradeWizard/preflight.php
- modules/UpgradeWizard/uw_utils.php
- php_version.php
This changes the way that php version comparisons are made, at installation time and at upgrade time.
It changes the way the minimum PHP version is defined and also the number of places where it is defined. I think is a saner approach than to have the same check / code repeated in half-dozen files.
Creates a new file: php_version.php where one can define a constant with the minimum supported PHP version and changes the version_compare stuff to use a modified check_php_version.
> Check php version

- include/language/en_us.lang.php
- modules/AOS_PDF_Templates/formLetter.php
- modules/Accounts/metadata/detailviewdefs.php
- modules/Contacts/metadata/detailviewdefs.php
- modules/Leads/metadata/detailviewdefs.php
Changed a label for language consistency.
Issue reference: #3578
> Fixed #3578 - Letter to PDF [Language]

- modules/Administration/AOPAdmin.php
When you have a lot of templates it is very hard to find the one you want.
This makes it much easier for a user to find a template as it is ordered by name.
Go to an instance with many templates, see the list is not ordered by name. Apply this and then see it is in order of name.
> Order templates by name in AOP admin

- modules/ProspectLists/ProspectList.php
It fixes #3363 
Added condition to check if the field is of non-db type or not.
Steps to Reproduce
1.   Set up a custom field of type HTML in one of the four target-list related modules
2.   Add a record of respective module to a target list
3.   Export target list as csv (from the actions menu in target list detail view)
4.   Database error
Target list export fails when any of the linked modules have a custom HTML(non-db) field set up. 
Steps to Reproduce
1.   Set up a custom field of type HTML in one of the four target-list related modules
2.   Add a record of respective module to a target list
3.   Export target list as csv (from the actions menu in target list detail view)
4.   Database error
> Fixed #3363 - Export Target List fails (Database failure)

- modules/Project/Save.php
Project Duplicate Problem fixing
When duplicating project, the duplicate is happening but the project tasks related to that particular project is not copying . instead of that some other tasks are copying to duplicated project. I found that duplicateid is parsed to Save.php but Save.ph is looking for relate_id which is a bug.
> Project Duplicate Bug Fixing

- data/SugarBean.php
- include/Sugar_Smarty.php
- modules/Emails/Email.php
- modules/Emails/include/DetailView/EmailsNonImportedDetailView.php
- modules/Emails/metadata/detaildraftviewdefs.php
- modules/Emails/metadata/detailviewdefs.php
- modules/Emails/metadata/nonimporteddetailviewdefs.php
- modules/InboundEmail/InboundEmail.php
Task: SCRM-575
When users view emails they cannot see value of the date field.
This change also includes some PHP docs and formatting.
Fixes the date field in the detail views 
- Repair and rebuild ( Clear tpl cache)
- View emails
- check date created field
> Fix date created

- modules/Emails/controller.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/language/en_us.lang.php
- modules/Emails/metadata/detaildraftviewdefs.php
- modules/Emails/metadata/detailviewdefs.php
- modules/Emails/metadata/nonimporteddetailviewdefs.php
Task: SCRM-582, SCRM-569 
Issue: #3616
This change adds the ability to reply-to, reply-to-all and forward emails. It also has a fix for the q-tips in the compose view.
Adds missing features
* Repair and rebuild
* Repair minifed js
* Repair js groupings
* Set up email account
* View Emails
* Select subject of an email
* In the action menu
* select reply to, reply to all and/or forward
> Feature Reply To and Forwarding

- data/Link2.php
- data/SugarBean.php
- include/SugarFolders/SugarFolders.php
- modules/Administration/SyncInboundEmailAccounts/SyncInboundEmailAccountsSubActionHandler.php
- modules/Emails/Email.php
- modules/Emails/EmailException.php
fix misspelled syntax in sql query
> fix the fixed query - related to (#3610)

- modules/FP_events/language/en_us.lang.php
removed unnecessary comment
`	// 2 lines bellow doesnt appear in git version`
> Removed unnecessary comment [language]

- include/ListView/ListViewGeneric.tpl
When doing an advanced search that returns no results, two strings are returned: "No results found." and "or change your search criteria". This fix changes this to return a single string: "No results found... Perhaps change your search criteria and try again?"
Issue reference: #3234
1. Repair and rebuild
2. Enter accounts module.
3. Click on filter > advanced filter.
4. Enter a non-existing record as the name and do a search.
> Fixed #3234 - Wrong advanced filter message in Suite7 and SuiteR themes

- modules/Users/views/view.detail.php
view.detail.php was trying to use a label that didn't exist due to a typo. I changed this to point to the correct label.
> Fixed missing label

- include/EditView/EditView2.php
- include/MVC/Controller/SugarController.php
- include/SearchForm/SearchForm2.php
- include/SugarFields/Parsers/EditViewMetaParser.php
- include/SugarFields/SugarFieldHandler.php
- include/formbase.php
- modules/Import/ImportFieldSanitize.php
- modules/Schedulers/EditView.php
- modules/Users/Save.php
Cleaning up the code in EditView2.php. Due to the comlexity. I have only cleaned up the easy fixes.
* Making the code more readable.
* Making it easy to navigate using an IDE
* SuiteCRM Edit Views
> Cleanup editview2

- modules/Emails/metadata/subpaneldefs.php
- themes/SuiteP/css/detailview.scss
- themes/SuiteP/css/mixins.scss
- themes/SuiteP/css/style.scss
Task: scrm-593
Issue: #3630
This feature doesn't add the menu item as requested in #3630 because you can add these relationships in the detail view under the subpanels. This means that you need to import the email first, before setting relating the email to other modules. The new email client doesn't support relating emails which have not been imported. For each subpanel, I have however updated the create button so that it uses the sames quick create feature found in other modules.
Regarding the print issue. Instead of adding a button in the actions menu. I have fixed the CSS in for the detail view. So that when you print using your web browser...it takes up less space by removing the subpanels and other elements. It also removes some of the additional padding. So that it saves paper. …
> Feature quick create and print

- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/language/en_us.lang.php
> Hotfix tplbug

- modules/Emails/include/ComposeView/EmailsComposeView.js
Fix some FF bugs:
fix FF bugs when: save draft, send email, disregard draft
SCRM-598, SCRM-599 
ref #3640
> fix FF bugs when: save draft, send email, disregard draft

- modules/Emails/EmailUI.php
- modules/Emails/EmailUIAjax.php
- modules/Emails/EmailsController.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/javascript/EmailUI.js
- modules/Emails/templates/editAccountDialogue.tpl
- modules/Emails/views/view.compose.php
- modules/Users/User.php
Task: SCRM-602
Issue: #3639
This change adds the signature to the body of the compose view.
*Fixes Issue
* Repair minified js
* Repair JS Groupings
* Create signature in the email settings
* Compose and email
> Feature signature

- include/EditView/EditView2.php
a bugfix for edit-view user function call in vardefs
bug appears on outbound email account editview
editview have to works
> fix: EditView2 user function call broken

- modules/Emails/EmailUIAjax.php
Issue: #3687
This issue corrects a typing mistake. in the switch case. 
* Fixes bugs
> Fixed #3687 - Typing error in Switch Statement EmailUIAjax.php

- service/v4/SugarWebServiceImplv4.php
Issue raised where using Outlook Plugin there were PHP 7 warnings displays and stops users from logging in.  This isn't specific to Outlook Plugin users but in general API users.
Really requires a more thorough PR to catch all 'unused' arguments.  
@param String $application -- The name of the application you are logging in from.  (Currently unused).
1. have PHP 7.1 environment
2. set login to use only user_auth (a single parameter).
3, should be able to successfully login.
> Resolving PHP 7.1 login issue for API v4

- data/Link2.php
- data/SugarBean.php
- modules/Emails/Email.php
- modules/Emails/EmailsController.php
- modules/InboundEmail/InboundEmail.php
- compose view clean up php errors (error.log)
- suitecrm log warning if user has not any signature (instead of php error)
> cleanup php error.log behind compose view

- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Favorites/controller.php
This change fixes the issue when users reply to an email and the signature doesn't show. The issue is due to a race condition between fetching the from fields and initialising the tiny mce editor. For big html emails tinymce takes longer than origionaly tested. 
I have added a deffered into the EmailsComposeView.js to wait until both conditions have been processed before running updateSignatures.
I have also added the "Signature above reply" into the EmailsComposeView.
Fixes bug
* Reply to email
* Check for signature
> Fixed - Reply to email - missing signature

- modules/Emails/EmailsController.php
see #3695
Fixed - Reply to email - missing signature
Adding Missing controller
> Fixed - Reply to email - missing signature - 3

- tests/testinstall.php
Issue: #3698
This fix removes the potential security issue where the config can be removed.
* Fixes security issue
> Fixed #3698 - removing config.php file

- .travis.yml
- modules/Emails/EmailUI.php
- modules/InboundEmail/InboundEmail.php
- modules/Schedulers/_AddJobsHere.php
This change ensures that when aop creates cases after an email has been receieved, the body field 
uses the uid instead of the msgno.
See: InboundEmail:importImportedEmail
Fixing bug where user cannot see the description of a case.
* Setup aop
> Fix case updates

- include/EditView/EditView2.php
- modules/Emails/include/ListView/ListViewDataEmails.php
- modules/Emails/include/ListView/ListViewDataEmailsSearchOnCrm.php
This change ensure that the new refactored code works on php 5.3. 
Even though we don't official support php 5.3, we need to let administrators see the new php version check first so that they can then upgrade their environments.
* Create, edit, view records
* View emails
> Making fixes to support php 5.3

- include/ListView/ListViewDisplay.php
This PR fix a delete button issue:
show listview delete button only if needed
for e.g: following modules have not Delete function on listview by default:
Users, Employees. 
Delete button should be disabled on User and Employees module list view 
anywhere  else (in other modules) it is enabled.
> Hotfix: delete button in bulk action

- modules/AOS_PDF_Templates/generatePdf.php
- modules/AOS_PDF_Templates/sendEmail.php
- modules/AOS_Quotes/metadata/detailviewdefs.php
- modules/AOS_Quotes/templates/showPopupWithOutTemplates.tpl
- modules/AOS_Quotes/templates/showPopupWithTemplates.tpl
- modules/AOS_Quotes/views/view.detail.php
- modules/Emails/Email.php
- modules/Emails/EmailsController.php
task: SCRM-604
hotfix: #3654 
Users are unable to email a quotation with the new compose view.
* Adds the missing functionality to email a quote
* Create a quote
* Action menu -> "Email Quotation"
You should see the compose view with the selected pdf template
> Fixed #3654 - Email Quotation

- include/language/en_us.lang.php
- include/utils.php
- modules/Emails/EmailUI.php
- modules/Emails/EmailUIAjax.php
- modules/Emails/EmailsController.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/javascript/EmailUI.js
- modules/Emails/templates/emailSettingsGeneral.tpl
- modules/Users/User.php
- modules/Users/UserEmailSettingsAccounts.tpl
When users selects none in an email account, the user expects the default signature in the general tab to be used instead. I have refactored this code so that the user can select "Default Signature" in the email account. I have also fixed some related issues in the compose view.
* Fixes issue
* Create multiple signatures
* Setup multiple personal emails with different signatures
* Test the compose view
> Fixed #3725 - Default Signature and Email Account Signature

- README.md
Add more detailed Roadmap link.
The Community Roadmap is nearly empty, missing all of the detail.
> Add More Detailed Roadmap.

- include/javascript/EmailsComposeViewModal.js
- jssource/src_files/include/javascript/EmailsComposeViewModal.js
- modules/Emails/include/ComposeView/ComposeView.tpl
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/views/view.compose.php
Reverts salesagility/SuiteCRM#3802
> Revert "Fixed #3655 - fix for popup compose view return message popup"

- modules/Emails/EmailsController.php
get email by mailbox_id - show emails only for owner users
please see related issue: #3848
please see related issue: #3848
> Fixed #3848 - get email by mailbox_id

- modules/Emails/EmailsController.php
- modules/Emails/javascript/EmailUI.js
If an Inbound Mail Account is marked as both Inactive, and is not selected as the Default, it still appears as an option on the "From" dropdown when Composing an Email address. (Despite being both Inactive and not chosen)
ref(scrm 625)
1) Create 2 inbound mail accounts via the "Settings" option on a User Profile
2) Ensure both can be seen when Composing under the "From" dropdown
3) Navigate back to "Settings" and set one as Inactive, (and ensure it is not set as default)
4) Navigate to Email Composing, and view the options under "From" dropdown.
> Default/Inactive Email Account Issue

- config_override.php
- modules/Campaigns/WizardMarketing.php
- modules/Campaigns/WizardNewsletter.php
- modules/Emails/Email.php
- modules/Emails/EmailsController.php
- modules/OutboundEmailAccounts/OutboundEmailAccounts.php
replace email variables
please see in related issue #3731
> Fixed #3731 - replace inserted variables

- config_override.php
- include/SugarFields/Fields/Base/SugarFieldBase.php
- include/SugarFields/Fields/Parent/SugarFieldParent.php
- include/SugarFields/Fields/Relate/SugarFieldRelate.php
- include/javascript/popup_helper.js
- include/javascript/popup_parent_helper.js
- jssource/src_files/include/javascript/popup_parent_helper.js
- modules/Emails/Email.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/metadata/composeviewdefs.php
issue: #3773 
tasks: scrm-628
To field is not populated when relating a account/contact in the email compose view.
* Adds missing or desired feature
* Repair and rebuild
* repair minified js
* repair js groupings
* view emails module
* compose email
* relate email to an account / contact
The to field should be populated with the email1 field
> Fix 3773 - Issues with sending email in 7.9.1

- modules/Emails/Email.php
- modules/Emails/include/ComposeView/ComposeView.tpl
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/views/view.compose.php
When forwarding an email, the attachments are not including in the new email.
* Fixes issue
* Repair js minified
* Repair js groupings
* Email Module
* Select email (with attachments :P )
* Select actions
* Select forward
* Check email
> Fixed #3798 - Attachments aren't in FORWARDED email

- include/ListView/ListViewSubPanel.php
Currently, only the "edit_button", "close_button" and "remove_button" can be shown in each subpanel row. 
If you were to create a new button inside the subpanel it will not be rendered
With this little change, it is possible to add new buttons with its own SugarWidget class.
Added the 
Row buttons in subpanels used to be customizable, adding custom logic to this buttons is a nice feature to have. I remember it used to work, maybe before the ListViewSubPanel creation.
Add a new button to a sub panel - Maybe something like this:
``` 
'create_button' => 
array (
'widget_class' => 'SubPanelCreateContract',
'module' => 'AOS_Quotes',
'width' => '5%',
'default' => true,
),
````
Go the the Module which the subpanel row should be shown and check if the button is rendered. You will see that it will …
> Allow SubPanel Rows to add Row Buttons

- modules/Calendar/tpls/repeat.tpl
display:none instead of disaply:none
> Fix style typo in repeat section

- modules/Accounts/Dashlets/MyAccountsDashlet/MyAccountsDashlet.php
- modules/Calls/Dashlets/MyCallsDashlet/MyCallsDashlet.php
- modules/Meetings/Dashlets/MyMeetingsDashlet/MyMeetingsDashlet.php
- modules/Opportunities/Dashlets/MyOpportunitiesDashlet/MyOpportunitiesDashlet.php
- modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
I wish I had time (and know-how) to do a more complete fix of PHP declarations, but I believe it is more important to merge these 5 ASAP since they keep coming up in the forums, one or two times a week, and they result in a terrible first impression for new users (broken fresh installations).
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [ X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
> Partially fix #942 Dashlets process functions

- include/clean.php
This PR contains a hotfix for a charset problem in issue #3903 
Hi @daniel-samson, can you please look at it how is effect your changes here:
https://github.com/salesagility/SuiteCRM/commit/f9f6cae2c24c39b21cfb2a629df6e15f3bd92b71
> Fixed #3903 - use correct charset

- modules/Users/views/view.detail.php
fixed: Edit action not working after selecting a user on Administrator User Management module (missing single quotes)
I added a couple of single quotes on 2 lines.
I searched a lot the issues but none was describing this bug, so, I created this commit
I can't edit any user
1- Open an instance of SuiteCRM 7.9.3 on Google Chrome
3- Open Inspect tool (CTRL+SHIFT+i)
4- Go to Admin -> User Management -> **select any user** -> Actions -> Edit Button (Create one if needed)
5- Nothings happen and the the following error is shown on inspect console:
> fixed: Edit action not working after selecting a user on Administrator User Management

- modules/Calls/vardefs.php
Previously would only display last name.
Simple change of vardefs to show full name.
Reports showing the Call's contact would only show the last name.
Create a report on Calls module and show the linked contact. Should now display full name.
>  AOR Calls module Contact link displays full name #3283

- composer.json
Incompatibe version of codeception in composer.json
> use codeception 2.0 for compatibility

- config_override.php
- data/SugarBean.php
- tests/install.php
Related to issue: #3698
Removes potential security risk where the config can be removed.
> Fixed #3698 - for feature codeception

- include/SugarFields/Fields/Html/DetailView.tpl
Task: SCRM-659
This change fixes the parsing issues with the html field causing emails to all have the same body.
Issue reference: #3919
Issue reference: #3934
1. Repair + rebuild
2. Open two different archived emails and check the body
> Fixed #3919 - All emails show the same body

- include/ListView/ListViewDisplay.php
Copy of a PR by [gymad](https://github.com/gymad) for use in 7.8.x LTS.
#3651
> Remove delete button in bulk action

- modules/Users/views/view.detail.php
Copy of a PR by [kdjmonaghan](https://github.com/kdjmonaghan) for use in 7.8.x LTS.
#3256
> Send correct password reset email

- data/SugarBean.php
- include/SugarFields/Fields/Html/DetailView.tpl
- include/SugarFields/Fields/Html/SugarFieldHtml.php
- include/clean.php
- modules/AOS_PDF_Templates/vardefs.php
- modules/Cases/vardefs.php
Copy of a PR by [daniel-samson](https://github.com/daniel-samson) for use in 7.8.x LTS.
#3851
> Improved clean html for sugar fields

- include/generic/DeleteRelationship.php
- include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
Copy of my #4094 PR for us in 7.8.x LTS.
#4094
> Relationship removal access issue

- include/language/en_us.lang.php
- install/language/en_us.lang.php
- install/seed_data/Advanced_Password_SeedData.php
- install/suite_install/AdvancedOpenEvents.php
- install/suite_install/AdvancedOpenPortal.php
- modules/EmailTemplates/DetailView.php
- modules/EmailTemplates/EditView.php
Copy of my #4096 PR for us in 7.8.x LTS.
#4096
> System email template access issue

- modules/Configurator/language/en_us.lang.php
Avoid issues when searching the code
`</eM> into </em>`
No issue created!
> Case Typo in html entity

- modules/Emails/EmailsController.php
Task: SCRM-651
If the mail signature contains special characters such as umlauts, they lose encoding in the compose view.
Herzliche Grüße => Herzliche GrÃ¼Ãe
Issue reference: #3863
This fixes the email signature json encoding to encode multibyte Unicode characters literally and to decode the utf8.
1. User profile -> email settings
2. Create an email signature that uses umlauts such as "Grüße"
3. Try to compose an email
> Fixed #3863 - Umlauts in signature lose encoding in compose-view

- include/language/en_us.lang.php
- jssource/src_files/include/javascript/EmailsComposeViewModal.js
- modules/Emails/include/ComposeView/EmailsComposeView.js
Task: SCRM-621
When composing an email from anywhere other than the email module, "Undefined" appears in the popup for selecting email templates and discarding drafts.
Issue reference: #3735 
Issue reference: #4041 
1. Repair + Rebuild.
2. Rebuild JavaScript languages.
3. Go into a contacts detailview.
4. Click on the email address field to bring up the email composer.
5. Select an email template.
> Fixed #3735 - Undefined values using templates from account module in 7.9.1

- modules/Emails/metadata/detailviewdefs.php
Task: SCRM-698
When you reply to, reply to all, or forward imported email, the view does not re-direct to the email listview and instead just closes the "Email Sent" popup. This leads to confusion of whether the email has been successfully sent or not.
Issue reference: #4048
1. Repair + Rebuild
2. Import email
3. Email detail-view –> Edit -> reply to, reply to all, forward to
4. Send email
5. Compose window stays open after clicking on the "Email Sent" popup.
> 	Fixed #4048 - 7.9.4 - doesn't close window if you reply to, reply to all, forward to imported email

- modules/Emails/Email.php
Task: SCRM-699
Issue 1:
'send Quote by Email' sends the email to the related contact regardless of whether the "To" field has been changed.
Issue 2: 
Replying/Forwarding an email sends the email to the address in the "From" field causing it to be sent to your own email and not the original sender.
This change allows the email composer to send an email that has been composed from a quote and had the "To" field manually changed.
Issue reference: #4053
Issue reference: #4101
Issue 1:
1. Select `Send Quote by Email` from a Quote.
2. The system puts the contact assigned to the quote in the `To:`  field.
3. Remove this address and put another one.
4. Hit `Send`.
Issue 2:
1. Receive an email.
2. Reply or Forward the received email.
3. Check that the email is sent to the intended target and not …
> Fixed #4053 - 'send Quote by Email' may send to wrong address

- install/old_php.php
Removes an unnecessary div that was causing the installer acceptance checkbox to be displayed off center.
1. Install SuiteCRM 7.8.x
2. Check that the installer accept checkbox is correctly centred on the page.
> 7.8.x Fixed installer checkbox html

- .github/ISSUE_TEMPLATE.md
> logs for issue template

- modules/ACL/ACLController.php
When attempting to select "Email Addresses" from the reports module tree a non-admin use is shown blank fields. This change gives non-admin users access to the email address category when using AOR_Reports in the ACLController.
Issue reference: #4067 
Issue reference: #3420
1. As a non-admin user create a report on Accounts
2. Check that "Email addresses" is populated with the email address fields.
> Fixed #3420 - Regular user does not reach email address field in Reports module

- modules/AOR_Charts/AOR_Chart.php
Large numbers on the Y axis when displayed are being cut off, resulting on the user not being able to read the numbers. This change corrects the issue by setting a higher gutter left value.
* Bug fix
- Create a report
- Set the module to opportunities
- add the "expected close date" as a field
- Set the group checkbox
- Set the format to Y
- Add the "amount as a field"
- Set the function to sum
- Click on charts
- set the x axis to expected close date
- set the y axis to amount
- save report
> Fixed AOR Charts

- modules/AOW_WorkFlow/aow_utils.php
Added asort($fields) to sort list of fields.
This will ensure that any drop down through which a user will select a field will be sorted in ascending order of Field Display Name.
Fix for issue Sorting of fields in condition list #4107 
Makes it easier and faster for user to find the field he/she is looking for.
Create new workflow
Select Module
Add Condition
open Field Drop Down (all fields will be displayed in alphabetical order)
- [X ] New feature (non-breaking change which adds functionality)
- [X ] My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
- [X ] I have read the [**How to Contribute**](https://suitecrm.com/wiki/index.php/Contributing_to_SuiteCRM) guidelines.
> Fix for issue Sorting of fields in condition list #4107

- modules/Contacts/metadata/subpanels/default.php
It's not possible to sort by "Account Name" in "Target Lists => Details => Contacts".
Issue reference: #3704
1. Enter Target List module.
2. Create new target list
3. Enter Contacts sub-panel
4. Add Contacts
5. Sort Contacts by "Account Name"
> Fixed #3704 - Cannot sort by "Account Name" in "Target Lists => Details => Contacts"

- modules/AOR_Reports/AOR_Report.php
issue: #4109
task: scrm-738
Users are unable to report on custom fields which are related to a module.
This changes attempt to fix the issue.
- Create custom field on a module eg accounts
- Create a report related it the same module
- Add custom field into the fields section of the report.
- Click save
- Check suitecrm.log
> Fixing AOR sql queries for custom fields

- modules/Activities/Popup_picker.php
- modules/Activities/language/en_us.lang.php
- modules/Activities/tpls/PopupBody.tpl
Fixes the "View Summary" popup in the history sub-panel not sorting by date. Also adds a tab for completed tasks.
Issue reference: #3723 
1. Enter an accounts detail-view.
2. Open the history sub-panel -> "View Summary".
3. Check that all tabs contain the correct records and are sorted by date.
> Fixed #3723 - History summary not sorted SuiteCRM 7.9

- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/aor_utils.php
- modules/AOR_Reports/controller.php
- modules/AOR_Reports/tpls/report.tpl
Fixes numerous issue with reports regarding the use of date fields with type "Value".
1. All operators for date fields with type "Value" return incorrectly
2. Reports only accept the format Y-m-d
3. PDF/CSV's do not respect date filtering
4. Report pagination returns a blank page when using date conditions
5.  Blank PDF/CSV when there are multiple parameters
6. 0 results shown when changing pages with two parameters
7. PDF/CSV have no data with date parameters
8. No option to use "Contains" operator on multi-select fields
9. "Contains" operator parameters fail to return
Issue reference: #1624
Issue reference: #3686 
Issue reference: #2725
Issue reference: #3506
Issue reference: #3094
Issue reference: #3124
Issue reference: #3366
Issue reference: #4084
Issue reference: #2189
1. Create …
> AOR Reports Fixes

- include/javascript/ajaxUI.js
- jssource/src_files/include/javascript/ajaxUI.js
- modules/ModuleBuilder/javascript/ModuleBuilder.js
Copy of a PR by [daniel-samson](https://github.com/daniel-samson) for use in 7.8.x LTS.
#4172
> Add ajaxUILoc XSS protection

- modules/AOW_WorkFlow/aow_utils.php
Copy of a PR by [daniel-samson](https://github.com/daniel-samson) for use in 7.8.x LTS.
#4179
> Adding blocking module fields in AOW

- include/database/MysqlManager.php
- modules/Emails/EmailUIAjax.php
Copy of a PR by [daniel-samson](https://github.com/daniel-samson) for use in 7.8.x LTS.
#4184
> Adding escaping to EmailUIAjax.php

- include/InlineEditing/InlineEditing.php
> Hotfix 7.8.x scrmbt 27 inline edit bugfix

- include/InlineEditing/InlineEditing.php
User type doesn't matter if current session user is not admin, "Only admin user can change/set admin access for users".
> safe change for user type

- include/SubPanel/tpls/SubPanelTiles.tpl
Fix for https://github.com/salesagility/SuiteCRM/issues/2767
> Fix subpanel remember state Issue #2767

- include/SuiteGraphs/RGraphIncludes.php
If max is less than 5 return 5, else return null so rgraph handles the scaling.
Fix for #1563
> Fix for https://github.com/salesagility/SuiteCRM/issues/1563

- themes/SuiteP/css/editview.scss
Editview labels padding fixed
(ref: SCRM-147 EditView Issues)
need to rebuild style.css
> Editview labels padding fixed

- include/SugarFields/Fields/Html/SugarFieldHtml.php
This corrects an issue with the the html fields, eg the description field in cases, knowledge base etc...
Where UTF8 strings are encoded and where the html is encoded.
* Bug fix
- Test the html fields in suitecrm
- Check the detail view and edit views to ensure that the values are exactly correct
> Fix sugarfieldhtml

- themes/SuiteP/css/editview.scss
Fixes line-height issue in edit-views.
1. Enter an account edit-view.
2. Check that the rows are aligned properly in every browser/device.
> Edit-view line-height

- .gitignore
- bower.json
This changes prepares suitecrm for bower. Bower is a node js package manager which helps to manage front end dependencies like css and JavaScript libraries which run inside the web browser. 
This doesn't yet implement or use bower.
- It will enable us to move the front end dependencies out of suitecrm
- It will enable us to upgrade libraries more effectively
- Run bower update
- It will download some libraries
> Adding bower to suitecrm

- include/utils/security_utils.php
> Add better client ip detection

- jssource/src_files/modules/Campaigns/wizard.js
- modules/Campaigns/wizard.js
update licence header in wizard.js
> update licence header in wizard.js

- .github/ISSUE_TEMPLATE.md
Small change to the issue template in order to remind users that they should report security issues through email.
> ISSUE_TEMPLATE.md

- modules/Spots/controller.php
> Typo in variable name

- themes/Suite7/tpls/_globalLinks.tpl
- themes/SuiteR/tpls/_headerModuleList.tpl
> Unclosed span tag

- themes/SuiteP/js/style.js
Fixes an issue with mobile view tabs failing to properly select.
Issue reference: #4183 
1. Open a record where tabs exist.
2. Change the screen size until the tabs convert to a dropdown, or use a smartphone.
3. Try clicking on the tab link in the dropdown.
> Fixed #4183 - SuiteP - Tabs not behaving correctly on small screens

- modules/Emails/Email.php
Task: SCRM-764
In order to reply to an email you will also need PR #4056 and #4059
When sending email from 7.9.4 the Display name does not display for the recipient of the email, e.g. When sending a message from Charlie Woodbridge cwoodbridge@mail.com, the recipient only see cwoodbridge@mail.com in from data.
From: cwoodbridge@mail.com
X-Google-Original-From: cwoodbridge@mail.com
The correct format as seen when sending a test email is:
From: SuiteCRM cwoodbridge@mail.com
X-Google-Original-From: SuiteCRM cwoodbridge@mail.com
This change allows the email composer to check "from_addr_name" for a name instead of only checking "from_name" which in the previous example would have been NULL.
Issue reference: #4133
1. Receive an email.
2. Click "Reply" in the email detailview actions dropdown.
3. …
> Fixed #4133 - 7.9.4 Email Display Name Doesn't Appear for Recipient

- modules/iCals/HTTP_WebDAV_Server_iCal.php
Task: SCRMBT-34 
Fixes iCal integration
> Refactoring HTTP_WebDAV_Server_iCal.php

- lib/SuiteCRM/API/v8/Controller/ModuleController.php
- tests/README.md
- tests/api/v8/ModulesMetaCest.php
- tests/api/v8/OAuth2Cest.php
> Feature restapi tests

- include/SugarEmailAddress/SugarEmailAddress.php
- include/utils.php
- include/ytree/Tree.php
- modules/Contacts/views/view.retrieveemail.php
- modules/Documents/TreeData.php
- modules/DynamicFields/templates/Fields/Forms/dynamicenum.php
- modules/DynamicFields/templates/Fields/Forms/enum2.php
- modules/MergeRecords/Step1.php
- modules/MergeRecords/Step3.php
The class don't have any constructor and the static functions don't use JSON_LOOSE_TYPE anyway
Also as I mention in the issue comments this bug is evolving like an evil pokemon, from Notice to Warning next one is Error
`PHP Warning:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' (this will throw an Error in a future version of PHP) in /.../include/utils.php on line 3992, , referer: http://localhost/test/suitecrm/index.php?action=ajaxui`
I'm currently using SuiteCRM 7.9.6 with PHP 7.2.0RC3
To avoid future PHP errors
I really don't know, I just create a new Account, Contact and Opportunity without any error.
> fix JSON_LOOSE_TYPE not defined closes #4136 

- include/clean.php
Data that looks like HTML tags is deleted from input fields.
Issue: #4446
> Fix #4446 - remove vs encode html tags

- include/SugarFolders/SugarFolders.php
- include/utils.php
- modules/Emails/EmailUI.php
- modules/Emails/EmailUIAjax.php
- modules/Emails/EmailsController.php
- modules/Emails/javascript/EmailUI.js
Issue: #4110 - 2 users of same email accounts - when one user import email.. it will cause for second problems
- fix email settings on user profile
- show group folders on emails list view
- Create two CRM User for testing
- Create a Group Inbound email Account and attach to users
- Login with first user and import some email
- Login with second user, should see the imported emails
- [] Breaking change (fix or feature that would cause existing functionality to change)
> Hotfix 4110 email 2 users

- modules/iCals/iCal.php
Fix iCal problem with Cyrilic charset
> Fix iCal car encoding

- modules/AOS_Products/tpls/EditViewHeader.tpl
- themes/SuiteP/include/EditView/SugarVCR.tpl
#3364 - Products save and continue button work
> Fixed  #3364 - Products save and continue button work

- modules/Users/User.php
- modules/Users/metadata/editviewdefs.php
add 2factor chkbox by default to user edit view
> add 2factor chkbox by default to user edit view

- lib/SuiteCRM/API/OAuth2/Repositories/ClientRepository.php
- lib/SuiteCRM/API/OAuth2/Repositories/ScopeRepository.php
- lib/SuiteCRM/API/v8/Controller/ApiController.php
- lib/SuiteCRM/API/v8/Controller/ModuleController.php
- lib/SuiteCRM/API/v8/Controller/SchemaController.php
- lib/SuiteCRM/API/v8/container/AuthorizationServer.php
- lib/SuiteCRM/API/v8/container/SchemaController.php
- lib/SuiteCRM/API/v8/route/schemaRoutes.php
- lib/SuiteCRM/API/v8/swagger.json
This change updates the swagger.json. There are two new calls:
- GET api/v8/swagger.json 
- GET api/v8/scheme
> Feature restapi swaggerfile

- themes/SuiteP/css/editview.scss
- themes/SuiteP/css/forms.scss
- themes/SuiteP/css/panels.scss
Fixed 7.10 staging css issues.
Reference: 1, 8, 9, 10
1. Rebuild SCSS
> Fixed SuiteP css issues

- include/SugarObjects/templates/basic/Dashlets/Dashlet/m-n-Dashlet.php
Already fixed in 7.9.x but still a bug in 7.8.x
> Substitution for Dashlet template broken

- themes/SuiteP/css/editview.scss
> Small css issue

- .gitignore
This change ignores the tags file which is generated by vim.
Enables developers to use vim as an IDE.
- Create tags file
> Adding generate ctags to .gitignore

- modules/Users/language/en_us.lang.php
Reference: 13
1. Check that the last page of the installer is populated.
> Fixed missing install strings

- modules/AOR_Reports/tpls/EditViewFooter.tpl
Copy of a PR by [kdjmonaghan](https://github.com/kdjmonaghan) for use in 7.8.x LTS.
#4499
Fixes issue #1532
Originally seemed fine on Chrome, but resulted in broken functionality in Firefox.
Resulted in broken functionality in FireFox on certain scenarios - corrected to enable a fully working experience.
Taken from the comments on the issue:
* Begin Creating a report by clicking the "Create" button on the right of the screen. On the report, you are unable to change tabs. (i.e, Fields, Conditions, Charts)
* If you have a report in the "Recently Viewed" panel, (Either on the Left of the CRM, or the one found by hovering over "Reports" on the Navigation bar), Click the Pencil icon to go straight to the Editview for this report. Then, you are unable to change tabs. (resolved with provided …
> Adjusted JS for Condition Line Views

- README.md
- suitecrm_version.php
Incremented readme and suitecrm_version.php
#4556
> Updated readme

- modules/Emails/include/ComposeView/EmailsComposeView.js
- fixing empty email contents from Email Quotation
- also fixing exists tests and code where the previous tests failed
related PR: #4547
issue #4497
- please follow instruction in related issue #4497
> issue 4497 - Quotations & email

- include/SugarEmailAddress/SugarEmailAddress.php
- include/utils/security_utils.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- tests/unit/include/SugarEmailAddress/SugarEmailAddressTest.php
- tests/unit/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
- tests/unit/modules/SchedulersJobs/SchedulersJobTest.php
- tests/unit/modules/jjwg_Maps/jjwg_MapsTest.php
- fixing empty email contents from Email Quotation
- also fixing exists tests and code where the previous tests failed
issue #4497
- please follow instruction in related issue #4497
> Hotfix 7.10 issue 4497 - Quotations & email

- modules/AOW_WorkFlow/aow_utils.php
#1308 - Doesn't respect the `reportable` property of vardefs #1308 fixed
> Fixed  #1308 - Doesn't respect the `reportable` property of vardefs #1308 

- themes/SuiteP/css/editview.scss
Reference: 17
1. Create a report.
2. Check that when adding a condition, it stays in the page.
> Fixed css issue with reports

- config_override.php
_config_override.php_ was never supposed to be part of the repository, it's actually in the _.gitignore_ file.  At some point early on when forking from SugarCrm to SuiteCRM it was added back
https://github.com/salesagility/SuiteCRM/commits/master/config_override.php
Removes the file _config_override.php_ from the repository so as not to conflict with locally modified files.
When running from source having this file coming from the repository conflicts with changes the local system makes.
> Remove config_override.php from the repository

- include/MVC/SugarApplication.php
- include/SugarEmailAddress/SugarEmailAddress.php
- include/language/en_us.lang.php
- include/utils.php
- modules/Administration/Administration.php
- modules/Administration/DisplayWarnings.php
- modules/Administration/PasswordManager.php
- modules/Configurator/Configurator.php
- modules/Users/User.php
- modules/Users/authentication/SugarAuthenticate/FactorAuthEmailCode.php
- modules/Users/authentication/SugarAuthenticate/FactorAuthFactory.php
- modules/Users/authentication/SugarAuthenticate/FactorAuthInterface.php
- modules/Users/authentication/SugarAuthenticate/SugarAuthenticateUser.php
- modules/Users/language/en_us.lang.php
Validate for two factor authentication email settings before save user and show validation messages.
fixing issue #4552 
- qrr & rebuild config file (admin menu)
- follow instructions in related issue
> Hotfix 7.10 issue 4552 2factor

- themes/Suite7/css/style.css
Syntax: unexpected comma after css selector
> Syntax: unexpected comma after css selector

- themes/SuiteP/css/normalize.css
> One closing bracket too much

- include/Dashlets/DashletGenericDisplay.tpl
Close the quotation marks after=== title="{sugar_translate label="LBL_VIEW_INLINE"}
https://github.com/sugarcrm/sugarcrm_dev/blob/master/include/Dashlets/DashletGenericDisplay.tpl
Issue reference: #4579 
1. Login in crm.
2. Load first page.
3. In the dashlets.
4. Check that Image with link works.
> Fixed #4579 - Dashlet DetailView link broken

- modules/AOR_Reports/AOR_Report_Before.js
This changes makes the tree in the reports module easier to navigate through. It allows the user to click on the fields directly instead of clicking the module then clicking the fields
> Feature Simplifiing AOR Reports Tree

- php_version.php
> min php version to 5.5.9

- themes/SuiteP/css/listview.scss
Fixing invisible text colour in css.
see in issue #4551 
Issue also appears in 7.9.7
- disable the imap extension in your server
- try to make an inbound email
> Fix for issue 4551 css

- include/SugarFields/Fields/Text/SugarFieldText.php
- modules/Campaigns/WizardNewsletter.php
- modules/EmailMarketing/EditView.php
- modules/InboundEmail/Save.php
fixing some php notice and wrong url after campaing test button
Try to test a campaign, where target list not selected at all.
> Hotfix 7.8.x - fixing some php error

- modules/Calendar/tpls/main.tpl
- modules/Calendar/tpls/settings.tpl
- modules/Calendar/tpls/shared_users.tpl
- themes/Suite7/tpls/footer.tpl
- themes/SuiteP/modules/Calendar/tpls/settings.tpl
- themes/SuiteP/modules/Calendar/tpls/shared_users.tpl
- themes/SuiteP/tpls/footer.tpl
- themes/SuiteR/tpls/footer.tpl
Remove incorrect html comments like 
Copy of PR #4395
> Remove incorrect html comments like <!--->

- data/Relationships/One2MRelationship.php
Set return value of function as the value returned from call to parent::add() function
One2MRelationship::add() functions last command is to call parent::add() function but it does not return value which is returned from parent::add(). 
Documentation states that it should return boolean value:
`@return boolean true if successful`
Function needs to return value as documented and intended to do so.
Make a call to create relationship between beans.
> Added return instruction to One2MRelationship::add() function

- modules/Calendar/tpls/main.tpl
- modules/Calendar/tpls/settings.tpl
- modules/Calendar/tpls/shared_users.tpl
- themes/Suite7/tpls/footer.tpl
- themes/SuiteP/modules/Calendar/tpls/settings.tpl
- themes/SuiteP/modules/Calendar/tpls/shared_users.tpl
- themes/SuiteP/tpls/footer.tpl
- themes/SuiteR/tpls/footer.tpl
Remove incorrect html comments like <!--->
https://github.com/salesagility/SuiteCRM/issues/4387
>  Remove incorrect html comments like <!--->

- include/SugarFolders/SugarFolders.php
- modules/Emails/Folder.php
- modules/Emails/include/ListView/ListViewDataEmailsSearchOnCrm.php
- modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
fixing mssql syntax in some query
Fix for issue #4246 - SuiteCRM Version 7.9.5 down to 7.9.x. Cannot change email folder and MSSQL error
Issue:
Cannot change to a different Email folder. (Sent, Archive, Etc.) in MSSQL
Expected Behavior:
Selecting an email folder will change folder and display contents
Actual Behavior:
Does not change email folder. MSSQL Errors Invalid column name
Steps to Reproduce:
SuiteCRM 7.9.5
Try to change email folder
Context:
Bug checking for Enterprise deployment and wanted to share fixes with community.
Environment:
IIS Server
PHP 5.3
MSSQL 2003
SuiteCRM 7.9.5
Server 2008
> Fix #4246 - fixing mssql syntax in some query

- modules/Campaigns/Subscriptions.php
- modules/Campaigns/Subscriptions.tpl
Before:
After:
Issue reference: #4152 
1. Enter a contact's detail-view.
2. Click "Manage Subscriptions" under the action menu.
3. Check that the "Save" and "Cancel" buttons are present.
> Fixed #4152 - Subscriptions missing Save/Cancel Buttons SuiteP

- modules/Users/Login.php
- fixing a php notice at logout
- code cleanup: Login.php
Copy of PR: #4258
> Fixing a PHP notice at logout

- modules/AOP_Case_Updates/tpl/caseUpdateForm.tpl
- modules/AOR_Reports/Dashlets/AORReportsDashlet/dashletConfigure.tpl
- modules/Administration/AOPAdmin.tpl
- modules/Employees/language/en_us.lang.php
- modules/Employees/metadata/editviewdefs.php
In cases after you click add file the buttons pull the image from the default theme making it appear stretched. I've changed this so it uses the correct path on each theme. The same button enlargement issue was found and fixed in the reports dashlet, AOP settings and the employee edit view.
Issue reference: #2734
1. Create case and click add file.
2. Add and edit reports dashlet.
3. Enter AOP settings, select distribution method single user. 
4. Enter employee's edit view.
> Fixed #2734 - Buttons enlarged in Cases/Reports/AOP/Employees

- install/installConfig.php
- install/install_utils.php
- install/language/en_us.lang.php
Fix for issue #4550 - missing email "from" installer
Set "from" fields on installer at 'SMTP settings' section.
> Fix for issue #4550 - missing email "from" installer (7.9.x)

- install/installConfig.php
- install/install_utils.php
- install/language/en_us.lang.php
Fix for issue #4550 - missing email "from" installer
Set "from" fields on installer at 'SMTP settings' section.
> Fix for issue #4550 - missing email "from" installer (7.8.x)

- include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
- modules/Emails/EmailUI.php
- modules/Users/User.php
Fixed #4659 - Compose Email From Contacts Loading 'Opt Out' Email
Please see relates issue #4659
Issue
If an email is being composed by selecting the 'activities->compose email' through the drop down, the compose email popup appears, if the contact has an opt out email address and a default address, the opt out email is still displayed in the 'To:' section.
Steps to Reproduce
Select the contacts module and select a contact
Scroll down to the 'Activities' Dashlet
Select the 'Compose Email' from the 'Create Task' drop down in the top left corner of that dashlet
This should then populate the 'To:' field with the old email address
>  Fixed #4659 - Compose Email From Contacts Loading 'Opt Out' Email

- include/ListView/ListViewColumnsFilterLink.tpl
- include/ListView/ListViewSearchLink.tpl
- include/language/en_us.lang.php
As described by @horus68 in #4673
> Changed title attribute to be translatable

- include/clean.php
When html is present in the body of an email, it displays as encoded html. This change removes the encoding from the html body 
- Setup emails
- View emails
- See the body field
> removing htmlentities from clean html

- modules/SecurityGroups/SecurityGroup.php
PHP Notice:  Undefined index: modules/SecurityGroups/SecurityGroup.php on line 611
> PHP Notice Undefined index in SecurityGroup.php

- include/ListView/ListViewSubPanel.php
PHP Warning:  A non-numeric value encountered in /var/www/html/SuiteCRM-github-develop/include/ListView/ListViewSubPanel.php on line 323, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?action=DetailView&module=Accounts&record=a508f714-6f4f-5e99-0ad9-5a31516f0f12&return_module=Accounts&return_action=DetailView&offset=1
> PHP Warning: non-numeric value in ListViewSubPanel

- include/Popups/PopupSmarty.php
PHP Warning:  Declaration of PopupSmarty::setup($seed, $file = NULL, $where = NULL, $params = Array, $offset = 0, $limit = -1, $filter_fields = Array, $id_field = 'id') should be compatible with ListViewDisplay::setup($seed, $file, $where, $params = Array, $offset = 0, $limit = -1, $filter_fields = Array, $id_field = 'id', $id = NULL) in /var/www/html/SuiteCRM-github-develop/include/Popups/PopupSmarty.php on line 46, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?action=DetailView&module=Accounts&record=a508f714-6f4f-5e99-0ad9-5a31516f0f12&return_module=Accounts&return_action=DetailView&offset=1
> PHP Warning: Declaration of PopupSmarty::setup

- include/parsecsv.lib.php
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/SuiteCRM-github-develop/include/parsecsv.lib.php on line 178, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?module=Import&action=Step1&import_module=Users&return_module=Users&return_action=index
> PHP Warning: count in parsecsv.lib.php

- export.php
PHP Notice:  Undefined index: members in /var/www/html/SuiteCRM-github-develop/export.php on line 80, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?module=Import&action=Step1&import_module=Users&return_module=Users&return_action=index
> PHP Notice Undefined index in export.php

- include/SugarFields/Fields/Image/SugarFieldImage.php
PHP Notice:  Undefined index: docType in /var/www/html/SuiteCRM-github-develop/include/SugarFields/Fields/Image/SugarFieldImage.php on line 90, referer: http://localhost:9072/SuiteCRM-github-develop/index.php
> PHP Notice Undefined index in SugarFieldImage

- modules/Users/Save.php
PHP Notice:  Undefined index: email_reminder_checked in /var/www/html/tests/SuiteCRM-7.9.8/modules/Users/Save.php on line 295, referer: http://localhost/tests/SuiteCRM-7.9.8/install.php
> Feature/php72 undefined index in users/save.php

- include/ytree/Tree.php
PHP Warning:  Use of undefined constant JSON_LOOSE_TYPE - assumed 'JSON_LOOSE_TYPE' (this will throw an Error in a future version of PHP) in /var/www/html/SuiteCRM-github-develop/include/ytree/Tree.php on line 76
> PHP Warning: undefined constant in Tree.php

- modules/Emails/Dashlets/MyEmailsDashlet/MyEmailsDashlet.php
PHP Warning:  Declaration of MyEmailsDashlet::process() should be compatible with DashletGeneric::process($lvsParams = Array, $id = NULL) in /modules/Emails/Dashlets/MyEmailsDashlet/MyEmailsDashlet.php on line 48
> Declaration of MyEmailsDashlet::process()

- themes/SuiteP/include/SearchForm/tpls/header.tpl
PHP Warning:  Use of undefined constant saved_views - assumed 'saved_views' (this will throw an Error in a future version of PHP) in /cache/smarty/templates_c/%%A1^A1B^A1B1823E%%header.tpl.php on line 47
> PHP Warning:  Use of undefined constant header.tpl

- suitecrm_version.php
> Increment suitecrm_version.php

- tests/unit/data/SugarBeanTest.php
Probably an accidentally removed test back.
> revert a test in SugarBeanTest

- tests/unit/include/SugarEmailAddress/SugarEmailAddressTest.php
fixing a test in SugarEmailAddressTest
> fixing a test in SugarEmailAddressTest

- tests/unit/include/MVC/View/views/view.quickeditTest.php
> Removing test view.quickeditTest::testdisplay

- tests/unit/modules/Users/UserTest.php
> Updating Tests User Test

- themes/SuiteP/css/suitep-base/panels.scss
On the subpanels, the page numbers were out or allignment.
Select a module that has subpanels under it. Inside it will say (x of x) on the right hand side, this is below the middle of the row.
> Page numbers out of line vertically.

- modules/AOR_Conditions/AOR_Condition.php
- modules/AOR_Fields/AOR_Field.php
[php7:notice] [pid 340] [client 172.18.0.1:35640] PHP Notice:  Undefined index: aor_fields_aor_reports in /var/www/html/SuiteCRM-github-develop/modules/AOR_Fields/AOR_Field.php on line 133, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?action=ajaxui
[php7:notice] [pid 340] [client 172.18.0.1:35640] PHP Notice:  Undefined index: aor_conditions_field in /var/www/html/SuiteCRM-github-develop/modules/AOR_Conditions/AOR_Condition.php on line 98, referer: http://localhost:9072/SuiteCRM-github-develop/index.php?action=ajaxui
[php7:warn] [pid 340] [client 172.18.0.1:35640] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/SuiteCRM-github-develop/modules/AOR_Conditions/AOR_Condition.php on line 98, referer: …
> Notices when saving new AOR Report

- tests/unit/modules/Schedulers/SchedulerTest.php
Fixes failing travis on develop
> Mark test as incomplete

- data/SugarBean.php
- include/ListView/ListView.php
- include/utils.php
- modules/UpgradeWizard/systemCheck.php
- themes/SuiteP/tpls/_headerModuleList.tpl
Added extra checks and explicits typecasts
To comply with stricter warnings and notices in PHP 7.2
> Feature/php 7.2 compatibility

- modules/Surveys/Menu.php
The Surveys module was missing the view icon in the side bar.
The view icon was added in to the side bar.
Open up the Surveys module, look over to the left hand side where the navigation is for that module.
> Fix Missing View Icon

- modules/AOS_Contracts/Menu.php
In the contracts module, the symbol inside the View button was missing.
Navigate into the Contracts module.
> View symbol was missing from left hand panel.

- modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php
Make child class function declaration compatible with parent
Issue #4813
> Fix #4813 Make child class function declaration compatible with parent

- themes/SuiteP/css/suitep-base/yui.scss
The module builder module had multiple instances of missing symbols.
Images were imported into a seperate file to allow the server to access these images. The text area for the close symbol was altered to allow it to fit correctly on the header.
1) Open module Builder,
2) There will now be arrows in the side panels,
3) Create a module,
4) Once the module is saved, the popup box will have the word 'Close' displayed.
> Fix #4824 Missing Decorations

- modules/ACLRoles/ListUsers.php
Fix the page redirect issue regarding the view roles by user form.
Description
Viewing the roles that a specific user has was redirecting away from the form, causing this page to be unusable.
How To Test This
1) Navigate to the admin panel
2) Select Role Management
3) Select List Roles By User
4) Select a user from the drop down menu
5) The page will now be persistant unti the user decides otherwise
> Fix #4836 Roles by user.

- modules/Emails/EmailsController.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
Added the system email account as a selectable option to the dropdown list of From Addresses when composing a new email.
Removes the need to create an Incoming Email Account in order to send email, as long as there is a system account email address existant and enabled for users to send emails from it.
Issue #3741
On upgrade from 7.8 to 7.9, there is no from address available to send from when composing an email,
it should allow me to send from the system email address, if "Allow users to use this account for outgoing email" is checked
Secondly to use a personal outbound email, I had to add a inbound account, where i would expect it to just pick up my outbound accounts.
strange error:-
Wed Dec 13 17:42:49 2017 [27469][1][SECURITY] User Administrator attempted to send an email using …
> Enable sending emails from system outgoing email account

- composer.json
zendframework/zend-crypt is not in use and should be removed.
> Remove zend from composer

- include/database/DBManager.php
The slow query log lines are written with an open parentheses that never closes.
Make the log files a little more readable.
Turn on the slow query setting in the system settings.  Check the log files.
> Add closing parentheses to slow query logging.

- include/SugarFields/Fields/Address/en_us.DetailView.tpl
- include/SugarFields/Fields/Address/en_us.EditView.tpl
Fixed a missing en_us.DetailView.tpl and en_us.EditView.tpl.
Issue reference: #4868
> Fixed #4868 - 7.9.8 billing/shipping fields blank

- themes/SuiteP/css/listview.scss
#4124 - Stylesheet miss behavior in Suite7.8.5 emails -Detailview SuiteP-Theme fixed
> Fixed  #4124 - Stylesheet miss behavior in Suite7.8.5 emails -Detailview SuiteP-Theme

- modules/Users/tpls/EditViewFooter.tpl
- modules/Users/tpls/EditViewHeader.tpl
Move the "Layout" section of the Advanced tab in the profile to a tab on it's own.
Users on the forums are commenting that they don't know where the theme colour chooser is. Perhaps we need to move it into a more visible location like a themes tab.
> Move layout and theme options to a separate tab

- modules/AOR_Conditions/conditionLines.js
- modules/AOR_Reports/tpls/EditViewFooter.tpl
Removed a duplicated function declaration that was introduced in an earlier bugfix.
Issue #4825 
Create or edit a Report.
Drop conditions.
Drag conditions.
Tested on Chrome and Firefox.
> Fix #4825 Remove duplicate function declaration

- themes/SuiteP/include/MySugar/javascript/retrievePage.js
When a navigation tab was deleted, it wasn't removed precisely.
This PR is a clone of [this PR](https://github.com/salesagility/SuiteCRM/pull/4762), because we want to merge into hotfix.
> fix-4762/unusable-tabs

- modules/Spots/tpl/ShowSpots.tpl
Fix spots module's table extend.
It's already [tested and reviewed](https://github.com/salesagility/SuiteCRM/pull/4796)
> fix #4796 - table overflow

- modules/Emails/EmailUI.php
This change adds addition cleaning checks to email.
> Adding htmlcleaning to email description

- jssource/src_files/include/SugarEmailAddress/SugarEmailAddress.js
Fixed a typo and a double assignment.
Added the line count to a couple of other ids.
When navigating to the profile page the browser console throws a lot of warnings about DOM elements having the same id. 
This probably affects data submitted in forms, js, and even if it not it's still very ugly.
> Modify line items to avoid duplicate ids

- modules/Calls_Reschedule/Reschedule_popup.php
- modules/Calls_Reschedule/reschedule_form.js
Calendar widget was not loaded in modal.
Please, check [this PR](https://github.com/salesagility/SuiteCRM/pull/4829).
> fix calendar in modal

- include/SugarEmailAddress/SugarEmailAddress.php
Fix limit clause in MSSQL.
- go to your profile
- edit and save it
> fix mssql bug at saving user

- include/clean.php
- modules/InboundEmail/InboundEmail.php
This change adds addition cleaning checks to email.
> Adding htmlcleaning to email description (7.9.x)

- modules/ModuleBuilder/language/en_us.lang.php
Fixed string typos
Issue reference: #3281
> Fixed #3281 - Language files: DetailView or Detail View?

- modules/AOR_Conditions/conditionLines.js
- modules/AOR_Reports/tpls/EditViewFooter.tpl
(cherry picked from commit 442d2ee)
Removed a duplicated function declaration that was introduced in an earlier bugfix.
Replicates #4828
> Remove duplicate function declaration 7.8.x

- include/Popups/PopupSmarty.php
> Fixed #4869 - PHP error when click on link REPORTS TO

- ModuleInstall/PackageManager/PackageManager.php
- install/install_utils.php
- install/language/en_us.lang.php
- modules/Administration/UpgradeWizardCommon.php
- modules/Administration/language/en_us.lang.php
- modules/UpgradeWizard/language/en_us.lang.php
- modules/UpgradeWizard/uw_utils.php
Removed references to SugarCRM and removed the checks for acceptable_sugar_flavors.
Issue reference: #3446
> Fixed #3446 - Removed checks for acceptable_sugar_flavors in the install_utils and packagemanager

- modules/SugarFeed/SugarFeed.php
- modules/SugarFeed/language/en_us.lang.php
In the global sugar feed the days and weeks are capitalised. It should be non capitalised words to make a proper sentence: 3 Weeks 4 Days ago
Issue reference: #3825
> Fixed #3825 - Activity Stream

- modules/AOS_PDF_Templates/generatePdf.php
Content in PDF is exploded while assigning values to PDF template variables. But after it's done with assigning values, it wasn't combining whole PDF template texts. So, I haved added a loop to add all content.
Copy of PR: #3813
> Export to PDF Missing lines of code

- modules/AOS_PDF_Templates/generatePdf.php
Content in PDF is exploded while assigning values to PDF template variables. But after it's done with assigning values, it wasn't combining whole PDF template texts. So, I haved added a loop to add all content.
Steps to Reproduce:
1. Import the template that is attached with the issue.
2. Go to invoices open one invoice "Export Pdf"
Issue #3738 
Before this change, there was an issue with exporting of PDF.
Steps to Reproduce:
1. Import the template that is attached with the issue.
2. Go to invoices open one invoice "Export Pdf"
> Fixed #3738 - Export to PDF Missing lines of code

- .pullapprove.yml
> pullapprove.yml

- modules/InboundEmail/InboundEmail.php
See #4802
This deals with an exception when an inbound email does not have a day of the week in the date.
Inbound emails are showing a white screen with an unhandled exception.
Look at an unimported inbound email with different valid RFC dates
> Checking for RFC822 and RFC2822 dates including optional parts in Unimported Inbound Emails

- .pullapprove.yml
Adds rules for enhancement PR's.
> Pullapprove Enhancements

- themes/SuiteP/modules/Users/tpls/DetailView.tpl
Fix edit/duplicate group user.
#4875 
- Admin > Users > 'Create Group User'
- Create a user and save
- See if you can edit or delete the user
> fix-#4875 add missing form into email template

- modules/AOR_Reports/controller.php
- modules/AOR_Reports/metadata/detailviewdefs.php
- modules/AOR_Reports/views/view.detail.php
Fixes #448 and prevents users with no export rights to reports from exporting the results.
Fixes users exporting reports when they should not be able to.
Create a user with no export rights on reports, log in as that user and confirm that the links are removed. Optionally create a POST request to the export URL to confirm that this cannot be bypassed.
> Fix #448 Prevent exporting results of Reports for user with no export rights.

- modules/Import/Importer.php
Create a new bean for each row in the import module instead of cloning the controller's bean.
Issue #4923
> Fix #4923 Avoid cloning beans on import

- modules/AOP_Case_Updates/AOP_Case_Updates.php
Case Updates Threaded messages in Case module are broken, because of unclosed HTML tags.
It ain't so easy to test it. Fortunately @mattlorimer knows everything.
> Hotfix 671/parse case update

- modules/Employees/Save.php
Update to pull request #2181 
Original pull request had a bug where it would not save the core fields.
Fixes issue where the pull request would save multiselect but not the core fields.
Go into an Employees record and attempt to save changes to any field.
> Fixed #391 - Can save all Employees fields

- modules/Emails/Email.php
Adds email template parsing to 7.8.x
Fixes #4636 
Takes code from aa1577ed62585530d5449aecc967fab60f034e26
Create an Email Template 
Relate to Cases
Insert a few Case variables
Compose an Email
Load the template
Select related case
Send Email
See that variables are replaced
> Fix #4636 Add template parsing to 7.8.x email

- modules/Campaigns/Menu.php
- modules/Campaigns/language/en_us.lang.php
Adds the button to import campaigns.
Issue #4981
> Fix #4981 Add a button to import campaigns

- include/generic/SugarWidgets/SugarWidgetSubPanelEmailLink.php
- include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
- modules/Emails/EmailUI.php
When you are on an Account page, and the Account has a Contact associated with it, if you click on the Contact email while being inside the Account page, the email popup fields get filled with wrong info.
Issue reference: #4036 
1. Open any account that has a contact linked to it, and scroll down to the Contacts section.
2. Open the section, and click on the Contact email.
3. Check that the email popup is populated with the contact info instead of the account info.
> Fixed #4036 - Email popup swaps account and contact data

- install/language/en_us.lang.php
This is a consequence of the discoveries in this discussion: #3168 
Just an improved label.
> Improved tooltip regarding DB configuration on install

- include/Dashlets/DashletGenericConfigure.tpl
- themes/SuiteP/css/suitep-base/dashboard.scss
The edit dashlet viewhad issues regarding overlapping fields and displays.
Click on the edit button on a dashlet, the contents should be in line and visible.
> Edit Dashlet views fix.

- modules/AOR_Reports/AOR_Report.php
Fixes a misnamed variable.
Issue #4973
> Fix #4973 Pass query array instead of string to function expecting it

- themes/SuiteP/css/suitep-base/panels.scss
Main page tab navigation no longer fit with the theme. The panels were too large which forced each tab out of line.
On the main navigation, add in extra tabs and then proceed to click 'edit tabs'.
> Fix tab navigation

- modules/Import/views/view.step2.php
An assignment for a template variable that was not being used was causing a PHP notice.
Removes a notice.
> Remove unused and inexistant mod string assignment

- modules/Campaigns/WebToPersonCapture.php
addresses #1671
Given you create Leads / Leads created from Web-to-form and the Leads are associated to the Campaign.......the Leads Created bar on the chart does not increase.
Allows the chart to display the correct information. 
create a lead/contact via the web2person functionality and view the campaign via the status page and the leads/contacts bar will now increment the number of new leads/contacts added to the campaign.
> Fixed #1671 - Leads created bar

- modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php
The Dashlet: "All Opportunities by Lead Source"
shows values instead of labels in the legend square.
addresses #1723 
Allows users to see labels instead of the array key, 
Create data in the opportunity and display the dashlet on the users home screen.
> Fixed #1723 - All Opportunities by Lead Source Labels

- modules/ModuleBuilder/parsers/views/UndeployedMetaDataImplementation.php
Changes visibility of field
Fixes #4962
> Make field protected to allow access to parent and children

- modules/jjwg_Maps/views/view.map_markers.php
> Fixed #1399 Quick Map Radius - Printing to PDF displays odd results

- themes/SuiteP/modules/Users/tpls/DetailView.tpl
Duplicate of PR #4951 
- Admin > Users > 'Create Group User'
- Create a user and save
- See if you can edit or delete the user
> Fixed #4875 - Unable to Edit/Delete Group User after Creation

- include/language/en_us.lang.php
Fixes missing LBL's in users list-view mass update.
1. Quick Repair and Rebuild
2. Open mass update in users listview
3. Check for added LBL's.
> Fixed missing LBL

- modules/Schedulers/Scheduler.php
Fixes a typo in date_time_start
Issue reference: #4926
> Fixed #4926 - Typo(?) in Scheduler.php

- modules/jjwg_Maps/jjwg_Maps.php
Duplicate of PR #4769 for use in 7.8.x
> Fixed php notice without google maps API key

- service/v4/SugarWebServiceImplv4.php
- service/v4/SugarWebServiceUtilv4.php
Copy of PR #3415 for use in hotfix-7.8.x.
Issue reference: #3262
> Fixed #3252 - rest interface problem

- modules/Home/Dashlets/RSSDashlet/RSSDashlet.en_us.lang.php
- modules/Home/Dashlets/RSSDashlet/RSSDashlet.php
Removes empty string
Issue reference: #4498
> Fixed #4498 - RSSDashlet empty string LBL_DBLCLICK_HELP'

- modules/OAuth2Clients/vardefs.php
- modules/OAuth2Tokens/vardefs.php
There was a problem about setting fields' sizes under MSSQL.
The size (4098) given to the parameter 'access_token' exceeds the maximum allowed (4000)
Install Suite with MSSQL
> fix fields sizes for mssql

- include/language/en_us.lang.php
- modules/Emails/include/displayEmailAddressOptInField.php
> fixing Empty email ID

- include/SugarTheme/SugarTheme.php
- include/SugarTheme/SugarThemeRegistry.php
- themes/SuiteP/themedef.php
This change adda sub theme check to fix a http 500 error during the upgrade process.
> Add sub theme check to fix a http 500 error during the upgrade process

- data/SugarBean.php
- modules/AOP_Case_Updates/CaseUpdatesHook.php
https://suitecrm.com/forum/suitecrm-7-0-discussion/6136-case-creation-auto-email
Creating a case and linking a Contact on the Case Record sends an Email.
Creating a case from the Contact's Record itself does not.
relates to issue #406
required to allow sending of email when case is created in the cases subpanel on a contact. 
moved when the after relationship save hook so it will now fire after the insert of the record into the database and then refreshes the bean itself so any changes e.g case_number is brought back to the bean for the hooks to have access. 
create a case via the cases subpanel in the contacts record.
> Creating Case from A contact record's subpanel doesn't send Automatic Email

- include/MVC/Controller/SugarController.php
- include/MVC/SugarApplication.php
- include/MVC/View/SugarView.php
- include/SugarEmailAddress/SugarEmailAddress.php
- include/SugarObjects/VardefManager.php
- include/language/en_us.lang.php
- modules/Accounts/metadata/detailviewdefs.php
- modules/Configurator/Configurator.php
- modules/Contacts/controller.php
- modules/Contacts/metadata/detailviewdefs.php
- modules/EmailMan/EmailMan.php
- modules/Emails/EmailUI.php
- modules/Leads/metadata/detailviewdefs.php
- modules/Prospects/metadata/detailviewdefs.php
- themes/SuiteP/css/Dawn/style.scss
- themes/SuiteP/css/Dawn/variables.scss
- themes/SuiteP/css/Day/style.scss
- themes/SuiteP/css/Day/variables.scss
- themes/SuiteP/css/Dusk/style.scss
- themes/SuiteP/css/Dusk/variables.scss
- themes/SuiteP/css/Night/style.scss
- themes/SuiteP/css/Night/variables.scss
Adding a 'Send Confirm Opt In Email' action link to Accounts/Contacts/Leads/Prospects DetailViews action menu. New menu item shows only if email settings opt in sets to "Confirm Opt In".
Note: this PR contains a TODO but first have to be merged all task of GDPR to solve this, see: https://github.com/salesagility/SuiteCRM/compare/feature/gdpr...gymad:feature/gdpr_fixes_2_action_opt_in?expand=1#diff-f36992067482fe7579621b960419fe7fR383
GDPR
- QRR needed
- Try to send a Confirm Opt In Email via Action menu in Accounts/Contacts/Leads/Prospects DetailViews 
- Confirm Opt In email sending possible only if Email Settings / Opt In drop-down set to 'Confirm Opt In', try out with different settings, email sending should failing.
- Try out with incorrect email settings (for e.g. wrong email account …
> Feature/gdpr  Confirm Opt In Email Sending Action Menu Item

- include/entryPoint.php
shows a message to user instead a http 500 error if composer autoloader not found.
Installer of SuiteCRM doesn't show any failing error.
Try to install SuiteCRM without composer.
> show composer error at install

- include/clean.php
- modules/Users/User.php
php errors fixes in installer
php errors in installer
Install SuiteCRM, apache log should be clean
> php errors fix on installer

- include/language/en_us.lang.php
- install/language/en_us.lang.php
- install/seed_data/Advanced_Password_SeedData.php
- modules/Users/authentication/SugarAuthenticate/FactorAuthEmailCode.tpl
- modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
Add default Two Factor email to installer,
Resend link added to two factor auth page.
There is no default template for Two Factor Authentication in installer
There is no "resend" code link at login
- Install SuiteCRM, should get default template for Two Factor Authentication email,
- Try to resend code at login
> 2 factor email in installer

- themes/SuiteP/css/suitep-base/aor.scss
This changes fixes the extra padding issue in the reports "report" subpanel which was is caused due to the css classes being designed for the dashlets.
- Rectifies bug
- Recompile Sass
- Reset file permissions
- Repair and Rebuld
- Create a report
You should see something that looks like:
> Fix css reports

- modules/Calendar/tpls/repeat.tpl
Please, check the ticket.
Please, check the ticket.
> hotfix-3056 fix JS in calendar template

- data/SugarBean.php
History subpanel wasn't loaded properly.
#5053
- go to opportunities module
- click on History subpanel
- see, if you have results
> #5053 fix subpanels lists

- modules/Campaigns/WebToLeadFormBuilder.php
add opt in to web form only if it's enabled in settings
create a web form
change email settings
create a web form
> add opt in to web form only if it's enabled in settings

- modules/Campaigns/utils.php
> remove unnecessary quotes

- modules/AOR_Reports/AOR_Report_After.js
- themes/SuiteP/modules/SavedSearch/SavedSearchForm.tpl
Fix the reports module allowing conditions and charts to be added.
1) Navigate to the reports module
2) Try to add a 'condition' or 'chart'
> Fix #5052 reports charts conditions

- modules/Spots/tpl/ShowSpots.tpl
Save buttons don't work.
#5043 
- switch theme to Suite 7
- go to Spots module and click on a record for editing
- save
> make save buttons work

- modules/Emails/Email.php
Small update to PR #4954 to take into account the [this comment](https://github.com/salesagility/SuiteCRM/pull/4954#issuecomment-361089303)
The fix in #4954 does fix the issue from the email module but not from the activities subpanel. This addition should take care of this.
Create an Email Template 
Relate to Cases
Insert a few Case variables
Compose an Email from the activities subpanel
Load the template
Select related case
Send Email
See that variables are replaced
> Take into account emails sent from activities subpanel

- themes/SuiteP/css/suitep-base/panels.scss
- themes/SuiteP/modules/SavedSearch/SavedSearchForm.tpl
This fix is used to alter the spacing of the subpanels in the emails module to fit with the rest of the theme.
1) Navigate to the Email Settings module
2) View the spacing between subpanels and panel title placement.
> Fix emails layout

- modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
The edit view of the Reports dashlet was missing various labels. This fix adds the labels into the relative locations.
1) Add the reports dashlet
2) Click the edit icon
3) All relative labels should now be visible.
> Fix reports dashlet missing labels.

- install/dbConfig_a.php
Removes an (arbitrary) limitation on the length of DB usernames during SuiteCRM install.
According to the MySQL manual "MySQL user names can be up to 32 characters long".
MSSQL seems to have 128 characters or no maximum length at all.
It seems unreasonable to limit the user to inputting only a 16 character username if the underlying systems accept much longer ones.
Issue #5012 
Install a new instance of SuiteCRM
Select 'Provide existing User' for the DB
> Fix #5012 Remove client side password length limitation

- modules/Help/index.php
Remove a SugarCRM reference
Issue #5160
> Fix #5160 Remove SugarCRM reference

- modules/AOS_PDF_Templates/views/view.edit.php
Allows <barcode> elements in TinyMCE.
Issue #4389 
1. Create or Edit a PDF Template
2. Open the HTML view of the document body
3. Add a barcode tag to the source <barcode code="978-0-9542246-0" type="ISBN" height="0.66" text="1" />
4. Click Update
> Fix #4389 Allow barcodes in pdf templates

- modules/Schedulers/language/en_us.lang.php
Reinstating language strings required to solve issue #5165 Scheduler Job dropdown menu missing labels
I opted to make this reinstate of removed strings because its the easiest solution for me. Bat it can be improved!
Missing labels in Scheduler Job dropdown menu
Solution by @pgorod from here https://github.com/salesagility/SuiteCRM/issues/4291#issuecomment-349289904
1- Admin / Schedule
2- Open Schedule / Edit
3- See Job pending menu: only URL is visible.
4- Apply patch and a Admin/Rebuild/Quick Rebuild
5- Al items are visible
1- Others can improve this PR by using the identical stings from the top of the same language file, the LBL_OOTB_ strings:
https://github.com/salesagility/SuiteCRM/blob/master/modules/Schedulers/language/en_us.lang.php#L45-L59
2- Note that the menu can overlap the …
> Fixed #5165 Scheduler Job dropdown menu missing labels

- lib/API/OAuth2/Middleware/ResourceServer.php
Make swagger.json available without Auth Middleware
GET /v8/swagger.json
> Add Oauth2 Clients to admin

- modules/Campaigns/metadata/detailviewdefs.php
Duplicate and Delete buttons use translated names in return_module.
This leads to an error message after deletion or duplication.
For example 'module Campagnes does not exist' when deleting a campaign in French
Replace translated name by module name
Log in a non-english language
Create a campaign 
Delete it.
The campaign is deleted but you get an error message
Log in a non-english language
Create a campaign 
Delete it.
No error message
> Fix Return module issues

- modules/jjwg_Maps/controller.php
- modules/jjwg_Maps/views/view.map_markers.php
#4568 
- go to accounts
- select few => bulk action => map
- click 'add to target'
- see they are added to the target list
> add bean ids to target list map

- modules/Reminders/Reminder.php
- modules/Reminders/vardefs.php
reminder confirm box shows up, even if clicked on ok
- create a new schedule / call
- confirm box appears. click OK.
- see, if confirm box won't show up anymore
> quickfix for notification

- themes/SuiteP/include/MySugar/javascript/retrievePage.js
Quickfix for loading DOM.
- create a new tab on the main page
- add a dashlet under it [like Cal]
- see the cal is loaded properly
> quickfix for dom load

- include/ListView/ListViewDisplay.php
- modules/Emails/EmailUI.php
This changes adds Email bulk action back into the list view.
* Access list view
* select all
* bulk actions 
* Email
> Fix Email bulk action in the list view

- modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
Makes  LDAPAuthenticateUser::authenticateUser compatible with  SugarAuthenticateUser::authenticateUser. 
This resolves #3442. 
Enable LDAP and check is any stack traces are generated due to authentication.
> loadUserOnLogin compatible with SugarAuthenticateUser::authenticateUser

- modules/AOW_WorkFlow/AOW_WorkFlow.php
Fix bug, condition with unchecked checkbox
1. create new WF for bean with checkobox field
2. add condition to field of type checkbox
3. set condition "Operator" to be "Equal To"
4. set condition "type" to "Value"
5. set condition "value" to uncheck checkbox
> fix(AOW_Workflow) - added support for condition with unchecked checkbox

- include/ListView/ListView.php
- include/MySugar/DashletsDialog/DashletsDialog.php
Fixed Warning: A non-numeric value encountered in ...\include\ListView\ListView.php on line 1605 on the currencies administration page.
Looks related to https://github.com/salesagility/SuiteCRM/issues/4185. The fixed proposed in #4145 was used.
Fixes Warning
For a new installation on windows 10, xampp with PHP 7.1.1 and apache 2.4.25 visit the currencies administration page
> Fixed Warning for non-numeric value on the currencies admin page

- modules/Emails/EmailUI.php
Fixes broken HTML being displayed when inline editing an email address
1. Inline edit an email address
> Inline edit fix

- data/SugarBean.php
- include/SugarEmailAddress/SugarEmailAddress.php
- modules/SecurityGroups/SecurityGroup.php
When importing contacts via the "Import Contacts" method each contact is saved with the first line's email address. The same email address is saved for more than the correct contact.
Issue reference: #5197 
1. Fresh install and then check that the accounts list-view has been correctly populated.
2. Enter contacts module and click "import"
3. Import a csv with the following data:
Email Address, First Name, Last Name
test1@domain.com, First1, Last1
test2@domain.com, First2, Last2
test3@domain.com, First3, Last3
> Fixed #5197 - Importing Contacts saves every contacts email as the first email in the csv.

- tests/_support/Helper/PhpBrowserDriverHelper.php
Fixes a typo that prevents API tests from passing
Run API test suite
> Update method for API test suite

- modules/Home/language/en_us.lang.php
Fixes an issue where the calendar dashlet labels are not displayed. Related to https://github.com/salesagility/SuiteCRM/pull/4928/commits/b2f9b740d4a1eca7173087e6cea78726cf1a0943
> Calendar dashlet lbl

- modules/Administration/UpgradeAccess.php
This change is required to allow the upgrade process to correctly change the .htaccess file while keeping the existing configuration.
It also adds the "done" message back in, so when you run rebuild .htaccess tool, the user will get a response message.
> Fixing htaccess file to prepend new rules instead of append

- modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
Fixes a fatal error on the homepage when using the reports dashlet.
> Fixed dashlet fatal

- modules/AOR_Reports/tpls/EditViewFooter.tpl
> Fixed  #2406 - css issue

- modules/Accounts/ShowDuplicates.php
- modules/Contacts/ShowDuplicates.php
- modules/Leads/views/view.showduplicates.php
Duplicate of #5038 for use in hotfix-7.8.x
> Fixed typo in variable name

- suitecrm_version.php
> Fixed timestamp

- include/language/en_us.notify_template.html
Translating online HTML files online having indentations requires each translator to also include hard indentation.
No issue created for this PR!
Makes transaltor life easier by allowing to use Translation memory
If updating to Crowdin it will loose actual transaltions
> Removing indentation from HTML strings

- install/language/en_us.lang.php
Updating URL to Wiki
Making this string the same as in the Upgrade script language file
> Updating URL to Wiki

- modules/Surveys/tpls/Reports/checkbox.tpl
- modules/Surveys/tpls/Reports/matrix.tpl
- modules/Surveys/tpls/Reports/option.tpl
Change charts' color.
- create a survey
- add matrix/checkbox/radio questions and change its status to public
- click on the survey's URL and fill it several times with different datas
- check the survey report and see the colors
> change colors

- modules/Surveys/views/view.reports.php
when a text field has html entities, the chart label appears wrong
- create a new survey
- add some chars like "'&^!%" to a text field
- click on the survey report and check graph labels appearing nice
> convert html entities

- themes/SuiteP/include/MySugar/tpls/MySugar.tpl
Menu Actions for accounts / profiles or cases can't be translated. This PR fixes bug reported here #5223
Note: hotfix branch is ok, only developer branch and 7.10.rc2 have the problem after this other edit:
https://github.com/salesagility/SuiteCRM/commit/2ed1f235a50caff15e94e8776b0e182865221289#diff-f83ca3eb1c411186a99fc09dca107ed1
Accounts view Before Fix (Portuguese language):
After fix (repair and rebuild is recommended):
> Fix #5223 - Menu actions translation for develop branch

- modules/AOR_Reports/AOR_Report.php
Fixes sorting of AOR Reports by date and datetime field
Issue #5317 
Create a report based on a module with a date field
Include the date field in the report
Order by the date field
Set date field format to d/m/y
Make sure date is ordered correctly
> Fix #5317 Report ordering by date field

- modules/Emails/Folder.php
Fixes an issue where the email list-view appears to be empty.
https://suitecrm.com/suitecrm/forum/installation-upgrade-help/17819-suitecrm-7-10-upgrade
> Fixed inbound email

- include/generic/SugarWidgets/SugarWidgetFieldbool.php
- include/generic/SugarWidgets/SugarWidgetFielddatetime.php
- include/generic/SugarWidgets/SugarWidgetFieldint.php
- include/generic/SugarWidgets/SugarWidgetFieldvarchar.php
Make function declarations compatible with parent
Fix PHP Notice
Possibly fixes issue #5275 
???
> Fix #5275 function declarations should be compatible with parent

- modules/EmailMan/EmailMan.php
- modules/EmailTemplates/EmailTemplateParser.php
Survey variables were not parsed properly.
- create a new survey campaign
- add some survey variables to the template
- send test email
- see if the variables replaced
> fix survey variables with new parser

- modules/UpgradeWizard/end.php
Upgrade script should update the htaccess after the upgrade process finished
> htaccess generate after upgrade

- modules/AM_ProjectTemplates/views/view.list.php
- modules/Calls/views/view.list.php
- modules/Employees/views/view.list.php
- modules/Meetings/views/view.list.php
- modules/SavedSearch/SavedSearch.php
- modules/Users/views/view.list.php
- themes/SuiteP/include/SearchForm/tpls/SearchFormGenericAdvanced.tpl
clone PR for 7.8.x
see at PR: #5347
> Hotfix 7.8.x 3784 my filters

- modules/InboundEmail/AOPInboundEmail.php
- modules/InboundEmail/InboundEmail.php
Same change made in both files. Instead of making a new case retrieve the existing one then set parent id to the retrieved case id.
Issue: Inbound emails for Cases #5315
Causes the case number to be null when send case emails. Solves issue of not being able to reply to cases.
Set-up emails for inbox to create cases.
Set-up to send out case created with case number within the email template.
Send email to cases inbox
Check history subpanel for outgoing mail
Check email has case number
> Fix for case number not being pulled into case creation emails.

- modules/ModuleBuilder/views/view.property.php
This change allows for labels within the layout view of studio to be edited and saved.
When trying to edit a label in the layout section of studio, an error was thrown and the edit icon was not clickable.
1) Navigate to studio inside the admin panel
2) Select and module
3) Enter a layout view
4) Select the edit icon (pencil) of any field and try to change the label
5) You should now be redirected to an edit screen
> Fix #5267 edit label in studio.

- include/MVC/View/SugarView.php
- modules/Reminders/Reminder.php
- modules/Reminders/vardefs.php
clone PR for 7.8.x
see at #5338
> performance: reminders alerts

- install/install_utils.php
Update link to point to new documentation site.
> Update wiki link

- modules/EmailTemplates/EmailTemplateParser.php
> change const array

- data/Link2.php
getRelatedFields is missing in Link2 while was there on Link.php and is used by the old API and solves #3510
Added missing method - it's a verbatim copy of the same function on Link.php.
Cannot set a new email for a contact using the REST api.
```
$parameters = array(
'session'         => '$sessionId', //Session ID
'module_name'     => 'Contacts', //Module name
'module_id'       => '$contactId', //Module name
'link_field_name' => 'email_addresses', 
'related_id'     => '$EmailID',
'name_value_list' => array(
array('name' => 'primary', 'value' => '1'),
),
'deleted'         => '0',
);
```
> fix: Adding missing method getRelatedFields

- modules/AOW_Actions/actions/actionSendEmail.php
When the Workflow action is 'email' and it is related to the Bean processed, the field related might be empty. 
When this happens the workflows fails with a fatal error due to $linkedBean->emailAddress->getPrimaryAddress  call.   All the scheduled workflows won't run after a failure like this.
$linkedBeans is present but with an empty array so this PR will check if the value is not empty before trying to access its properties.
When the Workflow action is 'email' and it is related to the Bean processed, the field related might be empty. 
When this happens the workflows fails with a fatal error due to $linkedBean->emailAddress->getPrimaryAddress  call.   All the scheduled workflows won't run after a failure like this.
1. Create a workflow tied to Opportunities
2. Select any condition you …
> fix: validation of the Email action on Workflows

- modules/ModuleBuilder/language/en_us.lang.php
`<b>Developer Tools</b1>`
tp
`<b>Developer Tools</b>`
Proper Html tags
bug also present in hotfix branch!
> Typo in html tag

- themes/SuiteP/tpls/_headerModuleList.tpl
This fix resolves the issue of the 'Base Implementation' navigation displaying in the side bar.
1) navigate using the emails module
2) Switch between sending emails and also viewing them
3) Ensure these do not show in the recently viewed side bar.
> Fix Base Implementation issue.

- include/ListView/ListViewDCMenu.tpl
- include/ListView/ListViewGeneric.tpl
- modules/AM_ProjectTemplates/tpls/ListViewGeneric.tpl
- themes/SuiteP/include/ListView/ListViewDCMenu.tpl
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
Duplicate of:
- #5351 
- #5352 
- #5353 
- #5354 
- #5355 
for use in hotfix-7.8.x LTS.
> Fixed - Warning: Use of undefined constant is_admin_for_user

- include/ListView/ListViewGeneric.tpl
Warning: Use of undefined constant is_admin_for_user
> Fix is_admin_for_user warning

- include/BeanManager.php
- include/EmailInterface.php
- modules/Accounts/Account.php
- modules/Contacts/Contact.php
- modules/EmailMan/EmailMan.php
- modules/EmailTemplates/EmailTemplateParser.php
- modules/Leads/Lead.php
- modules/Surveys/Surveys.php
- modules/Users/User.php
Small refactoring for parsing email template
- create a survey campaign and see, if the variables parsed
> refactoring email template parser

- modules/Users/User.php
Email addresses are invisible when email client is not Suite
- go to profile
- change email client to external email client at email settings
- save
- got to contact list view
- check if email addresses are visible
- dance
> fix email addresses in listivew in case of external email client

- install/language/en_us.lang.php
- modules/UpgradeWizard/language/en_us.lang.php
Removed unused strings
Issue reference #5258
> Fixed #5258 - SuiteCRM not compatible with this flavor - Language string

- include/language/en_us.lang.php
Removes some duplicated strings.
Issue reference: #5218
> Fixed #5218 - Duplicated language strings

- include/language/en_us.lang.php
- modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
Fixes Hard coded messages in SugarAuthenticate.
Issue reference: #5003
> Fixed #5003 - [language] Hard coded messages in SugarAuthenticate (ver. 7.10RC)

- modules/EmailMan/language/en_us.lang.php
Simple language string change for clarity.
Issue reference: #5163
> Fixed #5163 - Send notification from assigning user [text improvements required]

- modules/Administration/PasswordManager.php
- modules/Configurator/language/en_us.lang.php
- service/core/SoapHelperWebService.php
- service/core/SugarWebServiceImpl.php
- service/v3/SugarWebServiceImplv3.php
- service/v3_1/SugarWebServiceImplv3_1.php
- service/v4/SugarWebServiceImplv4.php
- service/v4_1/SugarWebServiceImplv4_1.php
- soap/SoapDeprecated.php
- soap/SoapHelperFunctions.php
- soap/SoapSugarUsers.php
- suitecrm_version.php
Fix for #5433
mycrypt is fully deprecated as of PHP 7.1. It will no longer be
available in future versions of PHP. This change, ensures that the
soap calls continue to work, by replacing mbcryp_cbc with openssl_encrypt for SOAP key over LDAP.
- PHP mcrypt extension is deprecated.
- password managment
- configure soap key for ldap
- test rest calls
> Fixed #5433 - admin encryption key for LDAP config

- include/ListView/ListViewDCMenu.tpl
- include/ListView/ListViewGeneric.tpl
- include/MVC/View/SugarView.php
- include/OutboundEmail/OutboundEmail.php
- modules/AM_ProjectTemplates/tpls/ListViewGeneric.tpl
- modules/AOW_Actions/actions/actionSendEmail.php
- modules/Administration/Administration.php
- modules/EmailMan/language/en_us.lang.php
- modules/ModuleBuilder/language/en_us.lang.php
- modules/UpgradeWizard/uw_utils.php
- themes/SuiteP/include/ListView/ListViewDCMenu.tpl
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
> Hotfix 7.9.x

- modules/AOP_Case_Updates/AOP_Case_Updates.php
Fix encoding issues in email case updates
Email a case update and see that no strange characters appear
> Fix #5339 Encoding issue with umlauts on email update in case

- modules/AOR_Conditions/conditionLines.js
- modules/AOR_Conditions/language/en_us.lang.php
> Fixed #3826 - Values "OR" & "AND" in report condition are not translatable

- modules/Emails/include/displayEmailAddressOptInField.php
To see more detail, please see in issue: #5550 
1. Go to Admin/Email Settings
2. Choose Opt in in Opt In Settings and save
3. Open a mail for detail view
Expected:
* Can access email view detail
> Fixed #5550: Can't display email when Opt-in on email settings

- include/EntryPointConfirmOptInHandler.php
- include/MVC/View/SugarView.php
- include/SugarEmailAddress/SugarEmailAddress.php
- include/language/en_us.lang.php
- install/suite_install/SystemEmailTemplates.php
- metadata/email_addressesMetaData.php
- modules/Administration/repairDatabase.php
- modules/EmailMan/EmailMan.php
- modules/Emails/language/en_us.lang.php
Using confirm opt in token to identify email address from confirm opt in request.
(also fix broken SuiteCRM in developer mode)
https://github.com/salesagility/SuiteCRM/issues/5548
- Clear cache and QRR.
- Confirm opt in your email address via Confirm opt in link, you shouldn't see your email address in the link.
- (also try to using SuiteCRM in developer mode)
> Hotfix: using confirm opt in token

- modules/Schedulers/Scheduler.php
Schedulers configured to run every few minutes run every minute.
See issue #5150
> Fix #5150 - Schedulers configured to run every few minutes run every minute

- modules/Administration/language/en_us.lang.php
Fix #4657 for hotfix branch language file - Change 2 dots to full stop
> Fixed #4657 Change 2 dots to full stop

- include/ListView/ListViewData.php
This fix allows the user to change the sorted order within the Contracts dashlet.
[#5406](https://github.com/salesagility/SuiteCRM/issues/5406)
1) Add the 'My Contracts' dashlet to the SuiteCRM dasboard
2) Try to change the sorted order within the list view from here, e.g. click on 'Name', 'Status'
3) Try to change between Ascending and descending
4) This should now change the order
> Fix #5406 ability to change sort order in dashlet.

- modules/Campaigns/WizardNewsletter.php
- modules/Campaigns/tpls/WizardCampaignTargetListForNonNewsLetter.tpl
Please see the description in #5344. apostrophe are not escaped in the campaigns target list, which is preventing users from creating target list with the campaign wizard.
- Fixes issue
- Install french language pack
- logout and login with the french language set
- select Marketing
- select Campagnes
- select Nouvelle Campagne
- select email
- set name (nom)
- select suivant
- create a suppression list (Liste D'exclusion par addresss Email)
You should now be able to create a target list.
> Fixed #5344 - Escaped apostrophe on array creating parsing error

- modules/AM_ProjectTemplates/controller.php
Changed line 347 with a time format string matching the time format provided in the date-time-string.
$dateformat depends on the user's profile. As this routine provides a date in a fixed format, the format string has to match this format.
See issue #5582
- [ x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
> Fix for #5582

- include/SugarEmailAddress/SugarEmailAddress.php
more secure encoding for email address in confirm-opt-in link
@zoltankocsardi still had a rainbow table :) 
https://github.com/salesagility/SuiteCRM/pull/5558#pullrequestreview-106120354
confirm opt in your email address from confirm-opt-in email
> extra salt on email address

- modules/Prospects/Prospect.php
Fixes an issue when sending a campaign email related to a prospect.
Issue reference: #5459
1. Send a marketing email to a prospect.
> Fixed #5459 - Campaign Emails Don't Send (test or otherwise)

- modules/Configurator/tpls/adminwizard.tpl
- modules/Emails/EmailUIAjax.php
- modules/Emails/javascript/EmailUI.js
- modules/Emails/javascript/ajax.js
- modules/Emails/templates/editAccountDialogue.tpl
- modules/Emails/templates/outboundDialog.tpl
SuiteCRM is not providing a consistent user experience when configuring outbound email addresses. It is not clear what the from name and from address is corresponds to which outbound email account.
See #5376 for details.
- Moves the from name and address to the outbound email account dialog
- Rebuild JS Minified
- Rebuild JS Grouping
- Quick Repair And Rebuild
- Select profile
- select email settings
- select mail accounts
- configure inbound email accounts
> Fixed #5376 - User's Outbound Email Settings Redesign

- include/Dashlets/DashletGenericDisplay.tpl
This change removes a field which was pointing to the incorrect module leading to a blank screen.
See description in [issue #5603 ](https://github.com/salesagility/SuiteCRM/issues/5603)
1) Add the 'My Contacts' dashlet to the homepage
2) Ensure that the current user being used to test has a Contact related to them
3) Click the 'Eye' view icon beside a contact
4) See that this leads to the detail view of the contact
> Fix #5603 Eye icon leading to a white screen in from contacts dashlet.

- include/MySugar/tpls/dashletsSearchResults.tpl
This change allows the icons to be shown within the search feature of 'Add dashlet' instead of just the file name.
[Issue #5602](https://github.com/salesagility/SuiteCRM/issues/5602)
1) From the homepage click on the actions tab
2) Select add dashlet
3) Enter in a search string, e.g. 'My'
4) See that the modules and icons are correctly displayed
> Fix #5602 icons not shown in add dashlet search.

- modules/Import/Importer.php
Replicates #4923 for 7.8.x
Issue #5574 
1. import
```
first_name;last_name;email1
first_name1;last_name1;email1@test.com
first_name2;last_name2;
first_name3;last_name3;email3@test.com
first_name4;last_name4;
first_name5;last_name5;email5@test.com
```
2. check imported contacts
> Fix #5574 avoid cloning beans on import

- include/SuiteGraphs/RGraphIncludes.php
- modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php
Fixes the drilldown link in a dashlet to work with language packs.
Issue #5557 
1. Change the language pack
2. Add Opportunities by Lead Source Dashlet to Home
3. Click on any lead source
4. Filter should work correctly
> Fix #5557 Make dashlet drilldown use the correct key

- data/SugarBean.php
Makes the log messages more informative.
Issue #5239
> Fix #5239 Make SugarBean logging more informative

- modules/Configurator/language/en_us.lang.php
This file was wrongly reverted somewhere in time!
PR merged but not in code now!  
Previously merged PR: https://github.com/salesagility/SuiteCRM/pull/3931
Note: No issue created for this new PR!
Avoid problems when searching the code
`</eM> into </em>`
> Case Typo in html entity - Take 2

- modules/AOR_Reports/AOR_Report.php
Fix issue Group display value is UUID if group by on field type of relate. (See detail in: #5418)
Fix issue PDF export missing grouped data (See detail in: #5427 )
1. Go to Navigation > Reports module > Create new report
2. Select Report module is Opportunities > Fields to display is: Opportunity Name, Assigned To; Checked Group on Assigned to and set Main Group is: Assigned to > Save.
Expected:
-  Grouping Opportunities by Assigned Users DISPLAY WITH NAME.
-  Download PDF NOT missing data.
- [x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
> Fixed #5418, #5724: PDF export missing grouped data

- composer.json
- modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php
Users with instances which run on PHP 7.1 and above are unable to login via SAML.
This change moves the SAML library to composer.
onelogin are currently developing version 3 - which removes the dependency of the mcrypt extension. So I have added the current (stablish) dev branch. See their [issue tracker](https://github.com/onelogin/php-saml/issues/255) for details.
- Create an account with [onelogin](https://www.onelogin.com/developer-signup)
- Add an application (SugarCRM SAML 2.0)
- In the application, configure the parameters to set the Email field to Username.
- In the SSO tab, use the X.509 to configure the certificate in the password management in suitecrm
- use the SAML 2.0 endpoint as the login url, and the SLO endpoint as the SLO url.
- (OneLogin) add a user called "admin", and …
> Fixed - mcrypt and SAML

- modules/AOW_WorkFlow/AOW_WorkFlow.php
Fix "Any Change" condition at Workflow on related field
Bug's steps to reproduce:
1. Create a Workflow on a module that has related field
2. Add condition of type "Any Change"
3. The workflow will always run, even if the related field's value was not changed
fixes the bug described below
1. Create a Workflow on a module that has related field
2. Add condition of type "Any Change"
3. The workflow will only run if the value of the relation will be changed
> add support for 'Any Change' condition on related field

- modules/AOS_PDF_Templates/templateParser.php
return: true/false instead of 1/0 - fixed
return: true/false instead of 1/0 - fixed
so now return True/false
References issue #592
> fixed - #592 return: true/false instead of 1/0

- lib/API/JsonApi/v1/Filters/Interpreters/FilterInterpreter.php
- lib/API/JsonApi/v1/Filters/Parsers/FilterParser.php
- lib/API/JsonApi/v1/Repositories/FilterRepository.php
- lib/API/v8/Library/ModulesLib.php
- lib/Utility/StringValidator.php
- tests/unit/lib/SuiteCRM/API/JsonApi/v1/Filters/Interpreters/FilterInterpreterTest.php
- tests/unit/lib/SuiteCRM/Utility/StringValidatorTest.php
See #5618 . Developers are unable to filter on custom fields.
Issue is due to the Filter Interpreter is not using the _cstm version of the table when a custom field has been introduced.
- Set up API
- Create custom field eg. firm_id in studio
- using a rest client  make call```GET /api/v8/modules/Accounts?filter[Accounts.firm_id_c]=[eq]12345678``
** use [[ eq ]] instead of [eq] ** github is not displaying it correctly :(
You should receive a 200 status instead of a 500.
> Fixed #5618 - API v8 filtering custom field

- themes/SuiteP/css/suitep-base/suitepicon.scss
This change realigns the profile and notification fields at the top right hand corner of the screen.
Profile and notification was not aligned.
1) Ensure the css files have been rebuilt
2) View the profile and notification in top right corner to ensure they are in line
> Fix out of line fields.

- include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.js
- include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.php
- modules/AOR_Scheduled_Reports/emailRecipients.php
- modules/AOR_Scheduled_Reports/metadata/detailviewdefs.php
#4194 
- go to scheduled report
scenario 1
- see if it's loaded properly
- create a new one
- set schedule daily at 6 o clock
- add few email recipients
- save
scenario 2 
- check if email recipients field appears and filled with proper values (under detail view)
scenario 3
- now go to editview
- see schedule shows **daily** instead of **monthly**
- dance
> fix schedule module

- modules/Emails/EmailsController.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/include/DetailView/EmailsNonImportedDetailView.php
- modules/Emails/javascript/EmailUI.js
- modules/Emails/metadata/nonimporteddetailviewdefs.php
- modules/Emails/templates/displaySubjectField.tpl
- modules/InboundEmail/InboundEmail.php
Fixes a series of bug in the email module. Some of them are related / some of fixes rely on eachother so they are grouped in one PR.
Make sure the inbound email folder passes the correct folder name to imap.
Add an extra check if a dom element exists before trying to edit it.
Add extra check to prevent invalid imap sequence.
Fix #5627
> Fix email bugs

- include/ListView/ListViewSubPanel.php
- modules/Calls/metadata/subpanels/ForHistory.php
- modules/Meetings/metadata/subpanels/ForHistory.php
- modules/Tasks/metadata/subpanels/ForHistory.php
1. Go to any module has History, Activities subpanel (Accounts, Contacts, Cases,...)
2. From Activities subpanel create new task or call or meeting record (MUST fill date for Due Date or End Date field, if is call record. Due Date value will auto calculate from Date Start and Duration) MUST set status is (Held, Not Held or Complete)
3. Save > System will auto reload History subpanel.
Expected:
* Due date need display in History subpanel
> Fixed #5515: Due date not showed anymore

- modules/ModuleBuilder/tpls/MB.css
- modules/ModuleBuilder/tpls/MBModule/module.tpl
#3558 Module Builder Fields fixed
> Fixed - #3558 Module Builder Fields

- modules/AOW_Actions/actions/actionCreateRecord.php
It fixes issue #3381 
Create a task that subject equals account name in workflow and get id instead of value
Steps to reproduce:
1.  Create workflow in opportunities module
2.  Create new task on create of opportunity.
3.  Set task's subject to account name.
4. Save and create new opportunity with any account record.
It creates a task that subject equals account name in workflow.
1.  Create workflow in opportunities module
2.  Create new task on create of opportunity.
3.  Set task's subject to account name.
4. Save and create new opportunity with any account record.
> Fixed #3381 - Workflow field gets id instead of value

- modules/Administration/AOSAdmin.php
AOS Settings: Initial Invoice Number - add validation
AOS Settings: Initial Invoice Number #792 - fixed
AOS Settings: Initial Invoice Number #792 - fixed
> Fixed #792 AOS Settings: Initial Invoice Number - add validation

- include/MVC/View/SugarView.php
Fixes an issue that caused the sidebar in administration modules to be hidden preventing the user from creating new Users, Inbound Email, OAuth Tokens.
1. Install a language pack such as PL.
2. Go into "Products" module.
3. Check that the sidebar displays correctly.
4. Go into "employees".
5. Check that you can create a new employee.
> Fixed list-view sidebar hidden in administration modules

- modules/ModuleBuilder/javascript/ModuleBuilder.js
issue #5677 
Users are unable to create a module in module builder. 
Handles when the YUI history has not been registered.
- Go to module builder
- Create Package
- Create basic module
> Fixed #5677 - Building new modules in builder do not work

- modules/ProspectLists/metadata/editviewdefs.php
See detail in #5683
1. Go to Target List
2. Create
Expected:
* Assigned To available to set in Edit View
> Fixed #5683: Can't assign user in Target list

- include/SugarObjects/templates/basic/Basic.php
- tests/unit/modules/Users/UserTest.php
See detail & discussion in: #5657 
1. Clean all empty records has email address is empty.
2. Go to Users list view or Contacts list view,,... (Any modules showed email address ListView)
3. See the email_addresses table in the database.
Expected:
No any empty records created in email_addresses table
> Fixed #5657: Multiple empty records are created in email_addresses table when access Users listview

- modules/Import/views/view.last.php
See [forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/18353-weird-error-on-import-import-incomplete).
Issue reference #5587 
1. Import a target.
> Fixed #5587 - PHP Error: [] operator not supported for strings

- include/SugarEmailAddress/SugarEmailAddress.php
issue: #5607 Undefined variable $new_confirmed_opt_in caused by when importing targets
- fixes bug
- login as admin
- goto the targets module
- select import action
- Select a csv which has specified email addresses
- select create new and update existing
> Fixed 5607 - Undefined variable $new_confirmed_opt_in

- modules/Users/login.tpl
- themes/SuiteP/tpls/login.tpl
* disabled autocomplete in the login form
> Turning off autocomplete in the login.tpl

- lib/API/v8/Controller/ApiController.php
When making the call api/v8/module/accounts/ you recieve the wrong error message instead of not found you get a invalid argument exception.
It is caused by the logger->log call. This is due a confusion between the SuiteLogger which is PSR3 and the SugarLogger. The PSR3 does not use fatal as a log level. The equivalent is **error** or perhaps **critical**.
- Set up API
- Authenticate with OAuth2
- create Get /api/v8/module/accounts/
You should see a not found error.
> Fix API error handling

- modules/Emails/Email.php
fixing emails sent from cases with template do not use case variables.
email templates send from cases do not use email values. email received is containing variables rather than values [CASE:$acase_case_number]  - $acase_name ($acase_priority)
1- create an email template with subject [CASE:$acase_case_number]  - $acase_name ($acase_priority)
2- create a case 
3- activities -> "compose email" 
4- select newly created template, 
5- send email 
6- received email subject is  "[CASE:$acase_case_number]  - $acase_name ($acase_priority)"
> fix case email template

- modules/AOR_Reports/controller.php
When you create a report containing fields having non-english characters, you get "Report Module - HTML contains invalid UTF-8 character(s)" error.
Before generating PDF, I have used `utf8_encode` function.
Steps to reproduce:
1.  Create a new Report containing fields which has non-english characters.
2.  Click on "Download PDF".
Issue no. #3742 
With this change, we can download PDF containing non-english characters.
Steps to reproduce:
1.  Create a new Report containing fields which has non-english characters.
2.  Click on "Download PDF".
> Fixed #3742 - Report Module - HTML contains invalid UTF-8 character(s)

- modules/EmailTemplates/EmailTemplate.php
fixing related PR #4485, (`$focus` was undefined)
should open again the related issue https://github.com/salesagility/SuiteCRM/issues/2802
Test failure: https://travis-ci.org/salesagility/SuiteCRM/jobs/370100711 in PR: https://github.com/salesagility/SuiteCRM/pull/5733
Undefined index: $focus
> Hotfix fixing PR #4485

- modules/EmailTemplates/EmailTemplate.php
Possible fix for PR: https://github.com/salesagility/SuiteCRM/pull/5733 
Travis build: https://travis-ci.org/salesagility/SuiteCRM/builds/370507246?utm_source=github_status&utm_medium=notification
a failing test
run tests
> fixing test: Array to string conversion

- composer.json
- tests/unit.suite.yml
Adding [mockery](http://docs.mockery.io/en/latest/) to the test suite. Since we need to support PHP 5.5.9 in SuiteCRM 7.10.x. I am using version 0.9.9 of mockery.
- Enables developers to mock dependencies of the unit they are testing
> Feature mocking

- include/SugarEmailAddress/SugarEmailAddress.php
- modules/EmailTemplates/EmailTemplate.php
Fixes an issue with the email1 field not saving correctly.
1. Create an account..
2. Populate account email address.
3. Save the account.
> Fix emailfield

- modules/Users/login.tpl
- themes/SuiteP/tpls/login.tpl
* disabled autocomplete in the login form
> Autocomplete
