SuiteCRM/SuiteCRM

modules/AOS_Products/vardefs.php
Enable merging AOS_Products
Merging module records is enabled for most other modules / by default for new modules built in module builder.
Fixes #5791
=> Allow merging AOS_Products

modules/AOS_PDF_Templates/templateParser.php
Now product images in templates are responsive.
This PR fixes: #4803
Product images replaced by $aos_products_product_image variable are sized to 50px width and height.
1. Create a PDF Template for Quotation including $aos_products_product_image variable
2. Create a Product with an image
3. Create a Quotation.
4. Email PDF this Quotation
5. Check that the image fits its container size
=> FIX 4803 - Now $aos_products_product_image is responsible in emails and PDFs

modules/Cases/views/view.edit.php
Replicates #5672 and #5816 for 7.8.x LTS
Fixes #5834
=> Fix/cases description 7.8

modules/AOR_Reports/AOR_Report.php, modules/AOR_Reports/tpls/report.tpl
Fixes numerous issue with reports regarding the use of date fields with type "Value".
1. All operators for date fields with type "Value" return incorrectly
2. Reports only accept the format Y-m-d
3. PDF/CSV's do not respect date filtering
4. Report pagination returns a blank page when using date conditions
5.  Blank PDF/CSV when there are multiple parameters
6. 0 results shown when changing pages with two parameters
7. PDF/CSV have no data with date parameters
8. No option to use "Contains" operator on multi-select fields
9. "Contains" operator parameters fail to return
Issue reference: #1624
Issue reference: #3686 
Issue reference: #2725
Issue reference: #3506
Issue reference: #3094
Issue reference: #3124
Issue reference: #3366
Issue reference: #4084
Issue reference: #2189
1. Create …
=> Update reports to be consistent with 7.8.x

.travis.yml, composer.json, lib/Robo/Plugin/Commands/CodeCoverageCommands.php, lib/Robo/Plugin/Commands/TestEnvironmentCommands.php, tests/unit/lib/SuiteCRM/Robo/Commands/CodeCoverageCommandsTest.php
This change adds the ability to run codecoverage and send the reports to codecov
- Helps track how much of our code is covered by unit tests
- Helps to encourage contributors to write tests.
This PR needs to merged first before we can get a base value to work from.
=> Adding codecov support

include/utils.php, modules/AOS_Products/vardefs.php, modules/Campaigns/Subscriptions.php, modules/Cases/views/view.edit.php
hotfix-7.8.x -> hotfix
-	modules/Cases/views/view.edit.php
=> Hotfix merge

README.md
This change adds the code cov bad to the readme
displays our current code coverage 
-view README on my branch https://github.com/daniel-samson/SuiteCRM/tree/feature/code_coverage_badge
=> Adding CodeCov Badge To README.md

modules/Users/UserViewHelper.php, modules/Users/views/view.wizard.php
see: https://github.com/salesagility/SuiteCRM/pull/3873/files/683866ac5964faf4c8d632adcce006f96036115a
Users can not use default outbound anymore but still calculate this value before this part.
- [x My code follows the code style of this project found [here](https://suitecrm.com/wiki/index.php/Coding_Standards).
=> remove unnecessary code

download.php
See Forum thread 
https://suitecrm.com/suitecrm/forum/developer-help/12163-image-field-is-not-working-for-cases-module
1. Add image field in case module
2. Add image in one case
3. check if it shows correctly in Detail view
=> Fix image fields in Case module

include/OutboundEmail/OutboundEmail.php, modules/Administration/Administration.php, tests/_support/AcceptanceTester.php, tests/_support/Step/Acceptance/Administration.php, tests/_support/Step/Acceptance/EmailMan.php, tests/acceptance/modules/EmailMan/EmailManCest.php
Fixes an issue that was causing the SMTP settings to continue instead of saving.
Issue reference: #5908
1. Go into admin panel -> email settings
2. Save SMTP settings
=> Fixed #5908 - SMTP Server not configured after upgrading to 7.10.5

custom/blowfish/rapelcg_svryq.php
Removes an accidentally commited file from the hotfix 7.8.x branch that breaks LDAP. This file has already been removed from the 7.9.x and 7.10.x branches: https://github.com/salesagility/SuiteCRM/commit/ee8f9fcc1ea12cfc68c3ed936620aece2d6f9876
Issue reference: #5909
=> Fixed #5909 - blowfish encryption file breaks ldap

modules/iCals/HTTP_WebDAV_Server_iCal.php
#5820 
Calendar iCal makes an auth even if you type your user credentials correctly.
url: {{ YOUR_SUITE_INSTANCE_URL }}/ical_server.php?type=ics&key={{ YOUR_CALENDAR_KEY}}&email={{ YOUR_EMAIL }}
Scenario 1
- make a request with valid calendar key and email (if either key or email is invalid, ou have to authenticate)
- ics file is generated
Scenario 2
- now make a request with invalid key. you have to authenticate.
- login with valid username and password
- ics file is generated
now dance.
=> fix ical request

include/database/MssqlManager.php, include/database/MysqlManager.php, modules/OAuth2Tokens/OAuth2Tokens.php, modules/OAuth2Tokens/metadata/SearchFields.php, modules/OAuth2Tokens/metadata/subpanels/default.php
Fixes a bug with MSSQL.
Fixes #5931 
1. Using MSSQL
2. See OAuth2Token detail view
=> Replace NOW() by actual datetime string to avoid DB conflict

modules/Project/Project.php
Fixes a missing parameter in the Project module as [mentioned here](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19316-changes-aren-t-saving-after-upgrade-to-7-10-5)
1. Edit a project
2. Save
=> Fix missing parameter

modules/AOW_WorkFlow/aow_utils.php
Translate the module name in workflow send email action
Issue #5728 
1. Select some non-English langpack and login into system (tested with ru/pt languages)
2. Create some workflow record with Send Email action
3. Choose Related field as types of recipient
=> Translate module names in workflow send email action related fields

jssource/src_files/include/javascript/EmailsComposeViewModal.js, modules/Emails/EmailsController.php
Fix for issue #5955
Allows sending email, automatically related to record, by clicking on email address in subpanel.
After applying this patch, you can click on an email address in the contacts subpanel, while in an Account or Opportunity, and the compose window will automatically populate the 'Related To' and 'Email To' fields.
=> 7.10.5 subpanel email fix

include/formbase.php, modules/Emails/include/DetailView/EmailsNonImportedDetailView.php, modules/Emails/include/ListView/ListViewDataEmails.php, modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php, modules/Emails/metadata/listviewdefs.php, modules/Emails/views/view.detailnonimported.php, modules/InboundEmail/InboundEmail.php
These changes address some of the performance issues in the emails modules.
**Issue 1: Attachment Indicator**
List view attachments indicator makes 20 requests to the imap server to open each email. I have removed this column by default and updated inbound email to only run these calls when the column is in the list view.
**Issue 2: Sanitizing HTML**
Detail view calls SugarCleaner twice, one for each body (html, plain). Since we only show one body, I have updated Inbound email to only process the body we will be displaying.
**Issue 3: Too many calls to get Email Headers**
The IMAP functions to get the headers sends too many commands to the imap server. I have reduced down to one call.
**Also:**
I have removed some PHP notices
- up to 50% performance Improvent
- Set up  emails
- List …
=> Fix email detailview performance

include/generic/SugarWidgets/SugarWidgetFieldenum.php, include/generic/SugarWidgets/SugarWidgetFieldid.php, include/generic/SugarWidgets/SugarWidgetFieldmultienum.php, include/generic/SugarWidgets/SugarWidgetFieldname.php, include/generic/SugarWidgets/SugarWidgetFieldsingleenum.php, include/generic/SugarWidgets/SugarWidgetFieldtext.php, include/generic/SugarWidgets/SugarWidgetFielduser_name.php, include/generic/SugarWidgets/SugarWidgetFieldvarchar.php, include/generic/SugarWidgets/SugarWidgetSubPanelConcat.php, include/generic/SugarWidgets/SugarWidgetSubPanelEditRoleButton.php, include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php, include/generic/SugarWidgets/SugarWidgetSubPanelRelFieldEditButton.php, include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonAccount.php, include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButtonProjects.php, modules/AOW_WorkFlow/aow_utils.php, modules/Calls/Call.php, modules/Relationships/RelationshipHandler.php
See #5303
Fix some PHP Warnings.
=> Fix #5303 - PHP Warnings on SugarWidgetFieldName and SugarWidgetFieldId

include/formbase.php, tests/acceptance/Core/ModuleBuilderFieldsCest.php, tests/acceptance/modules/Accounts/AccountsCest.php
This reverts commit 8f8357fbf33a045a99cb2c86bd55b0d52ed95b23.
Fix for issue #6006
=> Fix for issue #6006 - Revert "making check correctly fit the warning message"

modules/Campaigns/WizardNewsletter.php, tests/_support/Step/Acceptance/Campaigns.php, tests/_support/Step/Acceptance/InboundEmail.php, tests/_support/Step/Acceptance/ListView.php, tests/_support/Step/Acceptance/TargetList.php, tests/acceptance/modules/Campaigns/CampaignsCest.php, tests/acceptance/modules/TargetLists/TargetListsCest.php
Provide a fix for issue #6025 - Newsletter campaign target list selection broken
Target list selection should works
see everything in the related issue above
=> Fixed #6025 - Fix for issue #6025 - Newsletter campaign target list selection broken

modules/Emails/include/displayEmailAddressOptInField.php
=> Fix regression from #5559 (displayEmailAddressOptInField)

README.md
=> Wrong link of roadmap

include/generic/Save2.php, modules/SecurityGroups/SaveSecurityGroupUserRelationship.php
disabling group relationship for regular users
(same as https://github.com/salesagility/SuiteCRM/pull/6099)
bug 2817
=> disabling group relationship for regular users (into 7.8.x)

include/generic/Save2.php, modules/SecurityGroups/SaveSecurityGroupUserRelationship.php
disabling group relationship for regular users
bug 2817
=> disabling group relationship for regular users

include/MVC/View/views/view.list.php, tests/unit/include/MVC/View/views/view.listTest.php
Additional unit test, indicated by PR #6117
=> Adding test

README.md
Points the badge to the correct branch
=> Travis badge fix

modules/Administration/index.tpl
Mon Jun 25 14:27:09 2018 [11050][5e4ccfa6-e520-5359-fcd4-5aa91e21ee38][FATAL] log call at: modules/Administration/index.tpl:54 - MY_FRAME is not set
MY_FRAME was unset shortly after the initial commit.
=> MY_FRAME is not set

include/MVC/View/views/view.list.php
Fixes a bug with pagination.
Fix #5495 
1. Navigate to a listview
2. Add or remove a display column
3. See pagination still works as expected past the second page
=> Fix a bug with pagination

composer.json, lib/Robo/Plugin/Commands/CodeCoverageCommands.php, tests/unit/lib/SuiteCRM/Robo/Commands/CodeCoverageCommandsTest.php
This pr is to address the comments on #5858.
=> Fix test codecoverage

service/v4/SugarWebServiceUtilv4.php
Fix typo : Undefined variable singleSelect
=> Fix Undefined variable

service/v4/SugarWebServiceUtilv4.php
Duplicate of PR #6104 for use in hotfix-7.8.x
Updates a language string for context
=> Fixed typo

modules/jjwg_Maps/controller.php
Copy of PR #3091 for use in hotfix-7.8.x
Go to Map module/display map. Click Add to target List. Label should change to Processing and after few seconds to name of the target list.
=> Fixed maps LBL

modules/jjwg_Maps/jjwg_Maps.php
#6108 -fixing the missing Google API key in the jjwg_Maps.php code
Stops the over quota message in properly configured Google accounts
Using the sample data, geocode the data once (should partially run if it fails), clear the data and run again, you should NOT get any missed data (assuming the addresses are all entered).
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> Issue 6108

modules/AOR_Reports/AOR_Report.php
Html entity decode fields before exporting to csv
Fixes #6161 
1. Create Company with the character '
2. Create report that contains the company
3. Export the report
4. Open CSV
=> Html entity decode fields before exporting to csv

include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Fixes the style of the compose email button in the activities subpanel.
1. Profile -> Layout Options -> Select Style
2. Go to system settings -> Disable display actions within menus
3. Accounts -> Activities subpanel -> Compose Email
=> Fix activities subpanel style

.gitignore, composer.lock
Adding composer.lock to master to ensure that when installing from the GitHub repo (Non develop or hotfix branch) the release is fully tested with the locked dependencies. This shouldn't be necessary for the hotfix and develop branch. See following links for more detail:
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
https://www.phptherightway.com/#Updating_your_dependencies
Issue reference: #4555
=> Add composer.lock

composer.lock
Duplicate of PR: #6157 
Adding composer.lock to master to ensure that when installing from the GitHub repo (Non develop or hotfix branch) the release is fully tested with the locked dependencies. This shouldn't be necessary for the hotfix and develop branch. See following links for more detail:
https://getcomposer.org/doc/01-basic-usage.md#commit-your-composer-lock-file-to-version-control
https://www.phptherightway.com/#Updating_your_dependencies
Issue reference: #4555
=> Add composer.lock 7.8.x

.gitignore, modules/AOR_Reports/controller.php, modules/AOS_PDF_Templates/generatePdf.php
fix code typo
as @PedroErnst raised, the code was misspelled
=> Hotfix 7.8.x fix code typo

modules/Campaigns/WizardMarketing.php
Fixes a faulty logic in Campaigns.
Fixes #6172 
1. go to campaigns, 
2. edit an existing campaign via the wizard
3. use next to move from "Templates" to "Marketing" to "Send Email ..."
4. go to the campaign's detail view
5. look under "email marketing" subpanel
6. see there is no new entry that wasn't there at the beginning of the process
=> Fix faulty logic causing EmailMarketing not loading properly

modules/Users/UserViewHelper.php
=> Fix #5446 make UserViewHelper.php code-customizable

include/entryPoint.php, modules/AOR_Reports/controller.php
Fixes an issue with composer causing a fatal when exporting reports.
1. Create a report
2. Export the report as a PDF
=> Fixed pdf export fatal

modules/Activities/Popup_picker.php
Duplicate of PR #6035 for hotfix-7.8.x.
Create a call and assign a user and/or group that with the appropriate roles another user should not have access to it. Then sign in as that other user. That user should not see the call if roles are set to restrict for that specific scenario.
=> Duplicate PR for hotfix-7.8.x

modules/AOW_Actions/AOW_Action.php
If you save a workflow using `hotfix-7.8.x` branch, the actions are not saved properly. This was detected on PR #5070.
Avoid adding this bug on the new release.
1. Create a workflow using updated version of `hotfix-7.8.x` branch.
2. See that actions are not saved properly.
3. Apply PR and repeat step 1.
4. See that now is working ok.
=> Fixing AOW_Actions save

include/SugarFields/Fields/File/ListView.tpl, include/SugarFields/Fields/File/SugarFieldFile.php
Fixes the link for file type fields in listview.
Fixes #5790 
1. Create a custom module based on the file template
2. Add the uploaded file field to listview
3. Create a record and upload a file
4. Go to listview
5. Try to download the file from listview
=> Fix uploaded file link in listview

.travis.yml, modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
Same changes are in PR https://github.com/salesagility/SuiteCRM/pull/6220
but additional commit is removing memory limit for composer install in travis via environment variable.
composer install failing in PR https://github.com/salesagility/SuiteCRM/pull/6220 but it shouldn't
=> gcoop libre hotfix 6008 with no mem limit for composer install

modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
This Pull Request fixes #6008 
I added a private function called "retrieveEmailAssignedUser" in in modules/Emails/include/ListView/ListViewDataEmailsSearchOnIMap.php
This function returns an array with "assigned_user_id" and "assigned_user_name" for a specific email.
This function is called in the function "search" in the same file.
This change solves the problem described in #6008 
1.  Go to Emails modules
2. Import any message and assign it to an user
3. Back to inbox view
4. Click "Column selector" button
5. Drag and drop "Assigned to" rectangle to the upper list (it will turn green)
6. Save changes
7. Verify the assigned user is shown in the list
=> FIX #6008 - Now Assigned-to column is not empty

modules/InboundEmail/InboundEmail.php, modules/Schedulers/_AddJobsHere.php
This PR fixes  #6230 
See #6230 
See  #6230
=> FIX #6230 - Emails imported automatically in group inbound account are not marked as read

modules/InboundEmail/AOPInboundEmail.php, modules/InboundEmail/InboundEmail.php, tests/unit/modules/InboundEmail/InboundEmailTest.php
Now the classes InboundEmail and AOPInboundEmail has a property called $job_name in order to let getNewMessaeIds() execute the right query
To fix #6231 
1. Activate scheduled job: "Check Inbound Mailboxes"
2. Set the variable only_since and unset the variable only_since_last
3. Logging in debug mode, verify searching "-----> getNewMessageIds() executed query: "
=> FIX #6231 - Now the query executed in getNewMessageIds has no WHERE harcoded

modules/Users/User.php
Make sure that `findUserPassword` function only gets non deleted records.
See #3864
If you delete a user and then you create a new user using the same username, the login fails since function `findUserPassword` is not filtering by `deleted=0` users.
1. Create a new user.
2. Delete the previously created user.
3. Create a new user with the same username that you used in step 1. Set a diferent password as before.
4. Try to login with the new user and see that you get an error.
5. Apply PR and try to login again and see that now you can login.
NOTE: This error does not always appear. It only appears if the record that retrieves the findUserPassword method is the user that has been deleted instead of the new one.
=> Fix #3864 - Deleted and recreated user can't login with system generated password

modules/AOS_Contracts/metadata/editviewdefs.php
See #6133
When you create a AOS_Quotes or AOS_Invoice record, when you open the popup to select the contact, the results are filtered by the specified account. On AOS_Contracts module the contact popup doesn't apply this filter.
1. Create new AOS_Contract.
2. Select an account.
3. Open contacts popup to select a contact.
4. See that results are not filtered by the previously specified account.
5. Apply PR.
6. Repeat 1-3 and see that now the contacts are filtered by account.
=> Fix #6133 - Contact popup of AOS_Contracts doesn't filter by account

include/utils.php, modules/Employees/Error.php, modules/Favorites/Favorites.php, modules/Users/ChangePassword.php, modules/Users/Error.php, modules/Users/Save.php, modules/Users/views/view.edit.php, tests/unit/include/UtilsTest.php, tests/unit/modules/Employees/EmployeeTest.php, tests/unit/modules/Users/UserTest.php
Code refactoring on hotfix branch
=> Hotfix fixes

include/SugarFolders/SugarFolders.php
Fix found by @boombata and described [here](https://github.com/salesagility/SuiteCRM/issues/5852#issuecomment-406207546)
Fixes a bug introduced in #4877
Fixes #5852 
Fixes #5774
Follow steps in the issue report above
=> Fix/5852 email group folders / bug introduced in PR 4877

composer.lock, include/utils.php, modules/Employees/Error.php, modules/Favorites/Favorites.php, modules/Users/ChangePassword.php, modules/Users/Error.php, modules/Users/Save.php, modules/Users/views/view.edit.php, tests/tests/include/UtilsTest.php, tests/tests/modules/Employees/EmployeeTest.php, tests/tests/modules/Schedulers/SchedulerTest.php, tests/tests/modules/Users/UserTest.php
Refactiring on hotfix-7.8.x branch. ref: https://github.com/salesagility/SuiteCRM/pull/6212
=> Hotfix 7.8.x fixes

modules/Calls/metadata/subpanels/ForActivities.php, modules/Meetings/metadata/subpanels/ForActivities.php, tests/_support/Step/Acceptance/Calls.php, tests/acceptance/modules/Activities/ActivitiesCest.php, tests/acceptance/modules/History/HistoryCest.php
Fixes an issue with the activities subpanel not displaying the due date of calls and meetings
Issue reference: #5515
1. Create a Call/Meeting and associate it to a Contact/Account.
2. Check that the "Due Date" in the activities and history sub-panels is correct.
=> Fixed #5515 - Due date not showed anymore

modules/vCals/vCal.php, tests/tests/modules/vCals/vCalTest.php
Fixes an issue with the vcal organiser property.
1. Send a meeting invite through the calendar
2. Check the organiser name in the received meeting invite.
=> Fix vcal name

modules/MySettings/StoreQuery.php
Duplicate of PR #5821 
1. open e.g. accounts listview (or an other listview of another module)
2. hide a column by "Column Chooser"
3. filter for an account
4. remove the filter
=> Fixed #5794 - Added Column gets removed from listview after removing filter

modules/AOR_Reports/AOR_Report.js, modules/AOR_Reports/AOR_Report.php, modules/AOR_Reports/Menu.php, modules/AOR_Reports/aor_utils.php, modules/AOR_Reports/controller.php, modules/AOR_Reports/language/en_us.lang.php, modules/AOR_Reports/vardefs.php, modules/AOR_Reports/views/view.detail.php, modules/AOR_Reports/views/view.edit.php, tests/tests/modules/AOR_Reports/AOR_ReportTest.php
Fixes missing commits in the hotfix-7.8.x branch. Related to #6244
A full regression test of reports is required.
=> AOR Reports 7.8.x

include/SugarFields/Fields/EmailBody/SugarFieldEmailBody.php
Fixed an issue with the email detailview not displaying the correct view when using xampp and instead outputting raw PHP code.
Issue reference: #6131 
1. Repair and rebuild
2. See if the email module detail-view displays correctly.
=> Fixed #6131 - Issue with DetailView of Email module on 7.10.7 xampp

tests/tests/modules/Schedulers/SchedulerTest.php
Fixes the testderiveDBDateTimes test that is currently failing on travis.
=> Fix testderiveDBDateTimes

modules/AOS_PDF_Templates/templateParser.php
…ecentage fields
Original issue is #6162 and fixed proposed here https://github.com/salesagility/SuiteCRM/pull/6167
However further testing this caused a regression issue with other non percentage fields. 
Added a new Validator class for specifically Suite objects/validation rules
Resolved regression on hotfix branch
With Percentages:
1. Create a line item with a 20% discount
2. Apply a PDF template which makes use of this discount
3. Inspect the discount in the PDF
Without Percentages:
1. Create a line item with a 20% discount
2. Apply a PDF template which makes use of this discount
3. Inspect all other non percentage field values in the PDF
=> Fixed #6162 for 7.8.x branch

include/SugarTheme/SugarTheme.php
Updated from 7.8.18 
Problems with DatePicker and Editview. includign yui.css again fixes this.
=> SuiteR and Suite7 Theme dont work anymore in 7.8.21

modules/Meetings/language/en_us.lang.php
=> Remove unused lbl

modules/Emails/javascript/Email.js
Added support for attachments when editor is TinyMCE or Direct HTML
variable mozaik was not defined.
Just define it!
Go to https://demo.suiteondemand.com.
Try to add attachments to an email template. 
These attachments won't be saved.
#5961 
Adding attachments when editor is TinyMCE or Direct HTML
Change editor to TinyMCE in profile and add attachments to an email template
=> Allow attachments in email templates when editor is not Mozaik

include/javascript/mozaik/vendor/tinymce/tinymce/plugins/media/plugin.js, include/javascript/tiny_mce/plugins/media/js/media.js, modules/jjwg_Areas/views/view.area_detail_map.php, modules/jjwg_Areas/views/view.area_edit_map.php, modules/jjwg_Maps/tpls/AccountsInfoWindow.tpl, modules/jjwg_Maps/tpls/CasesInfoWindow.tpl, modules/jjwg_Maps/tpls/ContactsInfoWindow.tpl, modules/jjwg_Maps/tpls/InfoWindow.tpl, modules/jjwg_Maps/tpls/LeadsInfoWindow.tpl, modules/jjwg_Maps/tpls/MeetingsInfoWindow.tpl, modules/jjwg_Maps/tpls/OpportunitiesInfoWindow.tpl, modules/jjwg_Maps/tpls/ProjectInfoWindow.tpl, modules/jjwg_Maps/tpls/ProspectsInfoWindow.tpl, modules/jjwg_Maps/tpls/UsersInfoWindow.tpl, modules/jjwg_Markers/views/view.marker_detail_map.php, modules/jjwg_Markers/views/view.marker_edit_map.php
Updating the google maps URL.
Issue reference: #6326 
1. Set up google maps API in admin panel.
2. Test geocoding in admin panel
3. Create a quick radius map in maps module.
=> Fixed #6326 - Quick radius map + Geocode test issue 7.8.x

modules/Schedulers/_AddJobsHere.php
Fixed an undefined variable.
Issue reference: #6291
=> Fixed #6291 - undefined variable in _AddJobsHere.php

include/javascript/mozaik/vendor/tinymce/tinymce/plugins/media/plugin.js, include/javascript/tiny_mce/plugins/media/js/media.js, modules/Meetings/language/en_us.lang.php, modules/Schedulers/_AddJobsHere.php, modules/jjwg_Areas/views/view.area_detail_map.php, modules/jjwg_Areas/views/view.area_edit_map.php, modules/jjwg_Maps/tpls/AccountsInfoWindow.tpl, modules/jjwg_Maps/tpls/CasesInfoWindow.tpl, modules/jjwg_Maps/tpls/ContactsInfoWindow.tpl, modules/jjwg_Maps/tpls/InfoWindow.tpl, modules/jjwg_Maps/tpls/LeadsInfoWindow.tpl, modules/jjwg_Maps/tpls/MeetingsInfoWindow.tpl, modules/jjwg_Maps/tpls/OpportunitiesInfoWindow.tpl, modules/jjwg_Maps/tpls/ProjectInfoWindow.tpl, modules/jjwg_Maps/tpls/ProspectsInfoWindow.tpl, modules/jjwg_Maps/tpls/UsersInfoWindow.tpl, modules/jjwg_Markers/views/view.marker_detail_map.php, modules/jjwg_Markers/views/view.marker_edit_map.php
=> Hotfix-7.8.x merge

modules/Schedulers/_AddJobsHere.php
Syntax error in _AddJobsHere.php causes scheduled report not to render properly
Issue reference #6204 
1. Run any scheduled report and check the content in email.
=> Fixed #6204 - Syntax error in _AddJobsHere.php causes scheduled report not to render properly

modules/EmailMan/tpls/config.tpl
Fixed #6341 - Users may send as themselves tick is never hide
Issue #6341 itself
=> Fixed #6341 - Users may send as themselves tick is never hide

composer.json
updating saml vendor version in composer.json
=> updating saml vendor version in composer.json

lib/API/JsonApi/v1/Resource/Resource.php, tests/api/v8/ModulesCest.php
Fixed #6362 - mentioned fix to omit file data
Issue #6362
=> Fixed #6362 - mentioned fix to omit file data

metadata/emails_beansMetaData.php
related to #5265 - using InnoDB as default on email_text table
issue #5265
=> Hotfix #5265 - using InnoDB as default on email_text table

modules/Emails/include/ListView/ListViewDataEmails.php, modules/InboundEmail/InboundEmail.php, modules/InboundEmail/Save.php
Fixes an issue where the inbox folder would not change from the default "inbox" to what the user had set in user profile -> email settings. Also fixes an issue where an inbound email would not display anything in the list-view if you ticked the "Create Case from Email" box.
Issue reference: #6392 
Issue 1:
1. Create a new Inbound email account (used gmail)
2. Select a different monitoring folder by clicking"Select" (e.g. "Support")
3. Check inbox by clicking Emails and select the new created email.
4. Note that the shown emails does not correspond with your selected folder, but with your inbox folder.
Issue 2:
1. Create a group inbound email through the admin panel -> inbound email.
2. Check the "Create Case from Email" box.
3. Ensure you only have this single inbound email account …
=> Fixed #6392 - Changing Managing Folders Has No Effect

modules/OAuth2Clients/language/en_us.lang.php
Fixed #5726 - Token expires/expiry [language]
Language string mismatch for same key
=> Fixed #5726 - Token expires/expiry [language]

modules/Administration/language/en_us.lang.php
Fixed #6315 - [language] Duplicated language strings in ver. 7.10.8
Removed duplicate string 'LBL_GLOBAL_SEARCH_SETTINGS_DESC'
=> Fixed #6315 - [language] Duplicated language strings in ver. 7.10.8

modules/InboundEmail/AOPInboundEmail.php, modules/Schedulers/_AddJobsHere.php
Hotfix for case creation by email
cron failing when handle case create
create case from emails
=> Hotfix cronfix

build/push_output.sh, tests/acceptance/modules/Meetings/MeetingsCest.php
Replacing the acceptance test image output file host with uguu.se as rokket.space is temporarily unavailable.
See travis: https://a.uguu.se/cdE8dNeezBee_MeetingsCest.testScenarioEditStartDate.fail.png
=> Push acceptance test output to new file host

lib/Search/UI/SearchResultsView.php, lib/Search/UI/templates/search.results.tpl
Using the ElasticSearch global seraching, any result will correctly direct user if they have an subfolder instance.
=> Resolving results to use site_url

lib/Search/SearchResults.php, lib/Search/UI/SearchResultsController.php, lib/Search/UI/templates/search.results.tpl, tests/unit/codecept/lib/SuiteCRM/Search/SearchResultsTest.php
Users now able to:
- Able to click through to the EDIT VIEW of the search result row
- Able to click through to RELATED RECORDS from the search result rows
- Able to see the total count of records found next to the title of the module
see in story 4479
use elastic search
=> Develop 4479 format elastic list as basic

modules/FP_events/controller.php, modules/FP_events/language/en_us.lang.php
Added keys in language file for Accept and Decline links
Go to French language (or whatever other language).
Send invitations.
You will always see Accept and Decline
Incorrect events invites in non english languages
=> Change hard coded labels in Events invites

modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
The PipelineBySalesStageDashlet was not converting currency when determining amounts shown in the chart. However, it was changing the currency symbol to the user's selected currency. This is a bug as the user's currency could be the Japanese Yen, so it would show the Yen symbol (¥) next to US Dollar amounts.
Just adjusting the query that grabs the values for the chart so that the query converts the us_dollar amounts to the user's default currency. If user has no default currency, we use the system's default currency.
Prereqs: Have user default currency in USD
1. Add the PipelineBySalesStageDashlet to dashboard
2. Notice currency symbol and amounts
3. Change default currency to something else
4. Go back to dashboard
5. Notice that the currency symbol has changed BUT the value amounts are …
=> Fix #6240 -  PipelineBySalesStageDashlet not converting currency

modules/Users/Save.php
Duplicate of PR #6523 for the hotfix branch.
=> Default navigation paradigm should be used

tests/tests/modules/Schedulers/SchedulerTest.php
Mark test as incomplete in hotfix-7.8.x branch (Already removed in hotfix).
=> markTestIncomplete: testderiveDBDateTimes

modules/AOS_PDF_Templates/templateParser.php
Duplicate of PR #6381 for the hotfix-7.8.x branch.
=> Time issue fixed in email template for datetime fields

modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
Duplicate of PR #6241 for hotfix-7.8.x
=> PipelineBySalesStageDashlet not converting currency

themes/SuiteP/include/EditView/EditView.tpl
Duplicate of PR #3889 for hotfix-7.8.x
=> Fix for Edit View

themes/SuiteP/include/DetailView/DetailView.tpl
Duplicate of PR #3888 for hotfix-7.8.x
=> Panel tab fix

modules/Import/tpls/step2.tpl, modules/Import/views/view.step2.php
Duplicate of PR #2861 for hotfix-7.8.x
=> Import mapping publish button

modules/AOW_WorkFlow/AOW_WorkFlow.php, tests/tests/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
Duplicate of PR #6482 for the hotfix-7.8.x branch.
=> Workflow Date - Remove incorrect branch when unserialize fails

composer.json, composer.lock
=> updating composer

php_version.php
=> FIX #6568 - Adjust SUITECRM_PHP_REC_VERSION to 7.1.0

php_version.php
See issue #6568 and closed PR #6569
=> FIX #6568 - Change minimun and recommended PHP

lib/Search/SearchResults.php
Additional code cleanup and refactoring code complexity to PR https://github.com/salesagility/SuiteCRM/pull/6536 to resolve some codacy bot and clean coding issues.
clean code
behaviour should not change as it is in https://github.com/salesagility/SuiteCRM/pull/6536
=> code cleanup

include/utils/php_zip_utils.php
Updating zip error logging on hotfix-7.8.x branch.
=> php_zip_utils.php

include/database/DBManagerFactory.php, include/utils/php_zip_utils.php
Duplicate of PR #6266 for hotfix branch.
=> php_zip_utils

composer.json, composer.lock
Updates composer.lock and Bumps [flow/jsonpath](https://github.com/FlowCommunications/JSONPath) from 0.3.4 to 0.4.0.
<details>
<summary>Commits</summary>
- [`f022281`](https://github.com/FlowCommunications/JSONPath/commit/f0222818d5c938e4ab668ab2e2c079bd51a27112) Better handling of negative indexes (Fixes [#15](https://github-redirect.dependabot.com/FlowCommunications/JSONPath/issues/15))
- [`5de3d83`](https://github.com/FlowCommunications/JSONPath/commit/5de3d83e60983e470222b53f9800355a61caf4ba) Better handling of negative indexes (Fixes [#21](https://github-redirect.dependabot.com/FlowCommunications/JSONPath/issues/21))
- [`c4123e3`](https://github.com/FlowCommunications/JSONPath/commit/c4123e38dfa581239110e5bde8185c8c7b2c656f) Strip trailing comma in index query during parsing (Fixes …
=> Update composer.json + composer.lock

modules/Emails/Email.php, modules/Emails/EmailsController.php
When you import email to a record like an Account. The reply to/reply to all/ forward options on the imported email do not auto-populate the related to field.
Issue reference: #4046 
1. Import email and relate it to an account
2. Open email in detail view
3. Choose one action: reply to/reply to all/ forward to
4. Check if is relate to field is auto-populated
=> Fixed #4046 - 7.9.4 - imported emails are not auto related to related records when you reply to/reply to all/ forward them

include/SugarFields/Fields/File/ListView.tpl, include/SugarFields/Fields/File/SugarFieldFile.php
See #6511  for more details
To resolve the issue I had to first check if the display parameters are there and if not then the current module would be used. 
1. Pull down this branch
2. Install demo data
3. upload a document to any Account via the quick form
4. within the account try and click the link from the subpanel
5. It should download the file as expected.
1.Create custom module of a file type and add the filename to the module's ListView
2. Deploy custom module
3. Create a new record of this custom module (uploading a file)
4. Via the custom module's ListView click the link from the ListView
5. It should preview the file as expected.
=> Fixed #6511 - Document Attachment Subpanel link incorrect

include/SugarFolders/SugarFolderEmptyException.php, include/SugarFolders/SugarFolders.php, tests/unit/phpunit/include/SugarFolders/SugarFolderTest.php
Fix For My Account Loading Error #5506
This fix sanitises the data being entered into the queries allowing for special characters to be escaped  
Because it is a security issue and will allow saving data correctly.
=> Added/Refactor: Clean MySql Queries in SugarFolders

modules/Campaigns/vardefs.php, modules/Surveys/vardefs.php
This PR add a missing relationship
Fixes #6549
=> FIX #6549 - Add missing surveys_campaigns relationship

modules/Calendar/CalendarUtils.php
Fix bug #6579
When adding daily recurrence for a before noon (12:00) meeting and a end by date is set, an extra meeting is created, on the day after the defined end date.
Fix Calendar daily recurrence with end by date set. Avoid extra meetings being created.
1. Go to the Calendar
2. Create an 1 hour meeting for any time before noon
3. Set repeat type = Daily
4. Se the end by date for 2 days after (for instance)
5. Save
6. Actual: An extra meeting is being generated on the day after the `end by` date.
7. Expected: Meetings should only be generated until the `end by` date
=> Fix #6579 - Calendar daily repeat end by

modules/jjwg_Maps/controller.php, modules/jjwg_Maps/language/en_us.lang.php, modules/jjwg_Maps/views/view.geocoded_counts.php
changed background colour to make text visible.
added rounded corners to table header.
added table headers to language files.    
repair and rebuild 
go to the admin panel then open the geocoded counts page and view changes.
=> Fixed #5783 - The table header with geocoded objects is not visible

install/ready.php
Change provides better styling of installation wizard by fixing the p tag
Look prettier.
1. Pull a fresh instance down
2. Go through instllation wizard and confirm that the:
Writable Modules Sub-Directories and Files OK
Writable Data Sub-Directories OK
are on two separate lines.
=> Fixed installWizard styling - check writable module

include/MVC/View/SugarView.php
usage of the Bean instead of create a new class instance for Favorites and Trackers in the SugarView. 
The previous definition was not allowing to customise any method of the Favorites class.
The sidebar should still working as expected.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> Definition of Favorites and Trackers Beans in Sugar View

include/language/en_us.lang.php
Change text in all modules menu to make the task of translation easier.
see #1866
It makes it easier for maintaining translations into different languages
see #1866
=> Fix For #1866 Display module by alphabetical order

.github/CONTRIBUTING.md
Fixes a broken link and updates the label info + bug fixing guide section. A similar PR will be made to the doc site.
=> Updated contributing.md

install/language/en_us.lang.php
=> Fixed #6285 - LBL_DBCONFIG_B_MSG1_LABEL empty string

codeception.yml
Excludes some third party libraries from codecov.
See code coverage report below.
=> Codecov exclude

themes/Suite7/include/DetailView/DetailView.tpl, themes/SuiteR/include/DetailView/DetailView.tpl
Fixed #717 - Field Indented on Detailview when by itself on panel 
Add single field work correctly now
Fixed #717 - Field Indented on Detailview when by itself on panel
=> Fixed #717 - Field Indented on Detailview when by itself on panel

themes/SuiteP/css/navbar.scss
#3083 - Calendar pop up windows are going under MENU bar - Fixed
=> Fixed  #3083 - Calendar pop up windows are going under MENU bar

themes/SuiteR/css/navhighlight.css, themes/SuiteR/js/navhighlight.js, themes/SuiteR/tpls/_head.tpl, themes/SuiteR/tpls/_headerModuleList.tpl
Fixed #583 Navigation module highlighting added
Added highlight currently used module
Improve user experience
=> Fixed #583 Navigation module highlighting added

modules/Emails/EmailUI.css, themes/Suite7/css/yui.css, themes/SuiteP/css/yui.scss, themes/SuiteR/css/yui.css, themes/SuiteR/js/style.js
Pagination bar in Emails no hidden any more
Pagination bar in Emails no hidden any more
References issue #163 
We have in system more as 1000 emails, but if i want go to history, the pagination nav bar is under layer which show the emails
=> Fixed #163 - Pagination bar in Emails

modules/Users/User.php
Set collapsed_subpanels preference.
This was accidentally removed during a merge.
See tests passing in Travis.
=> Set collapsed_subpanels preference

modules/Opportunities/SugarFeeds/OppFeed.php, modules/SugarFeed/language/en_us.lang.php
Duplicate of PR #6633 for hotfix branch.
Issue reference: #5509
1. Repair and rebuild.
2. Create an opportunity
3. View the activity stream dashlet and check the label has updated.
=> Fixed #5509 - [language] New label 'FOR_AMOUNT' in activity stream for opportunity

modules/Documents/Document.php
Call parent function to correctly deleted relationship
Called parent to correctly delete relationship from join table.
Solves issue of relationship with documents not being deleted correctly. 
Go to Studio->Documents->Relationships
Create one to many to Accounts
Add relate field in Accounts' edit view
Go to Accounts module and add document via relate field
Go to Documents module and delete document
The document will be deleted and the link will be deleted.
=> Fix issue where link is not deleted for documents

tests/tests/modules/AOS_Products/AOS_ProductsTest.php
=> Updating Product Test and remove unnecessary parameters 

themes/SuiteP/include/DetailView/tab_panel_content.tpl
See https://github.com/salesagility/SuiteCRM/issues/5477 for issue details.
- Remove unnecessary conditionally displayed div with clear:both styling to fix alignment issue in detail view where row has filler on left and field on the right.
- This was added to resolve an issue where the filler is on the right and field on the left resulting in the following row being misaligned. See https://github.com/salesagility/SuiteCRM/issues/1931.
- The above issue is actually addressed by an :after pseudo element applied to the .row class in themes/SuiteP/css/bootstrap.min.css:6449 and other css files.
Issue where using fillers on the left column and a field in the right column of the same row caused the field to be misaligned (displays in left column but aligned right instead of being displayed in …
=> Fix for issue #5477

modules/AOR_Charts/AOR_Chart.php
This way it is easier to identify the colour of the label you are looking for.
Superseeds #1536 and #6638
=> Generate chart colors based on labels

include/utils.php, install/ready.php, modules/Documents/Document.php
Merge latest hotfix changes into hotfix-7.8.x (if it's possible)
See:
https://github.com/salesagility/SuiteCRM/pull/6662
https://github.com/salesagility/SuiteCRM/pull/6656
https://github.com/salesagility/SuiteCRM/pull/6654
=> Merge latest hotfix changes into hotfix-7.8.x (if it's possible)

include/SugarTinyMCE.php, include/utils.php, install/install_utils.php, install/language/en_us.lang.php, modules/ACLRoles/EditAllBody.tpl, modules/Administration/UpgradeAccess.php, modules/Administration/UpgradeWizard_prepare.php, modules/Calendar/CalendarUtils.php
Merge latest hotfix-7.8.x changes into hotfix (if it's possible)
See:
https://github.com/salesagility/SuiteCRM/pull/6663
https://github.com/salesagility/SuiteCRM/pull/6661
https://github.com/salesagility/SuiteCRM/pull/6660
https://github.com/salesagility/SuiteCRM/pull/6659
https://github.com/salesagility/SuiteCRM/pull/6664
https://github.com/salesagility/SuiteCRM/pull/6645
https://github.com/salesagility/SuiteCRM/pull/6655
https://github.com/salesagility/SuiteCRM/pull/6658
https://github.com/salesagility/SuiteCRM/pull/6667
=> Merge latest hotfix-7.8.x changes into hotfix (if it's possible)

modules/Calendar/CalendarUtils.php
Copy of #6580  from hotfix-7.8.x to hotfix
=> Added: Fix for calendar daily repeat end by

modules/Administration/PasswordManager.php
Resolving blank screen and Fatal error due to missing function.
[php7:notice] [pid 12] [client 172.19.0.1:42708] PHP Fatal error:  Uncaught Error: Class 'ImapHandlerFactory' not found in /var/www/html/mysuitecrmfork/modules/Administration/PasswordManager.php:147
1. Pull down hotfix
2. Enter PassWordManager via Admin Panel
3. See Blank screen & Fatal in PHP error.log
4. Pull down PR
5. Enter PassWordManager via Admin Panel
6. See expected PasswordManager settings
=> Resolved blank screen on PasswordManager

modules/AOR_Charts/AOR_Chart.php
Additional changes to #6647:
- code clean up to standards
- writing unhandled errors into log
**TODO: Needs test**
**Note: should it be duplicated to `hotfix`?**
=> Hotfix 7.8.x gunnicom patch 11

modules/Emails/views/view.compose.php
A few very minor log entry grammar errors are corrected.
'Attacment' changed to 'Attachment'
'id' changed to 'ID'
'exists' changed to 'existing'
=> Minor grammar fixes to log entry

modules/ProjectTask/metadata/subpanels/default.php
Adds missing edit/remove button to project tasks subpanel.
Issue reference: #532
=> Fixed #532 - Add the edit/remove button to Project Tasks subpanel

RoboFile.php, lib/Robo/Plugin/Commands/CleanCacheCommands.php
See #6648 
You can run the new task:
`$ ./vendor/bin/robo clean:cache`
=> FIX #6648 - We add a task in RoboFile.php for cleaning cache directory

include/utils.php, modules/InboundEmail/EditView.php, modules/UpgradeWizard/uw_utils.php
Upgrade Wizard shows a blank screen, (php error in apache log)
Unable to use Upgrade Wizard.
Install CRM
-> go to Admin/UW page
-> click next to system check => blank screen
=> Hotfix php error on uw page

include/utils.php
Fixes #6581.
#6581 pretty much describes the whole problem that made me open this PR.
I'm not sure this actually caused any problems, but it seemed like it would cause subtle potential issues.
=> Fix an erroneously-commented return statement.

modules/Emails/views/view.import.php
Fixes the import email related to popup.
1. Setup inbound email.
2. Import an email and select an account to relate it to.
=> Fix email related to

include/language/en_us.lang.php
Removed duplicated string.
#6758
=> Fixed #6758 - [language]Duplicated language strings - develop branch

modules/Emails/javascript/Email.js
This is a duplicate of #6757 but against the newly created hotfix-7.10.x branch
=> Fixed #6484 for LTS - Fix image insertion with mozaik

modules/Users/User.php
When creating a new user the password field isn't saved to the db.
Issue reference: #6787
1. Admin panel -> user management
2. Create a new user
3. Try to login as this user.
=> Fixed #6787- SuiteCRM 7.11 User password not saving and could not change

modules/Emails/include/ListView/ListViewDataEmails.php
The solution from @michelhcote fix issue for 7.10.12 + 7.11 #6767
We've installed v.7.10.12
The ListViewDataEmails.php wasn't displaying the emails and the only option was to CREATE or upload. When clicking on CREATE we would get the following msg:
Error: File [modules/Home/metadata/editviewdefs.php] is missing. Unable to create because no corresponding HTML file was found.
We had to remove from lines 145 up to 161 and put back the v.7.10.11 code for it to work, we now have this code and everything works fine:
{
$inboundEmailID = $currentUser->getPreference('defaultIEAccount', 'Emails');
$id = $folder->getId();
if (!empty($id)) {
$inboundEmailID = $folder->getId();
}
$isValidator = new SuiteValidator();
if ($inboundEmailID && !$isValidator->isValidId($inboundEmailID)) {
throw new …
=> Email view not working after upgrade from v.7.10.11 to 7.10.12 + 7.11

modules/Campaigns/WizardEmailSetup.php
=> Fixed #6810 - Campaign page failure/imapfactory

modules/Emails/include/ListView/ListViewDataEmails.php
=> Group email list-view fix

tests/acceptance/modules/Users/UsersCest.php
Increase wait time for addemailaccount test.
See Travis
=> Travis Fix

tests/acceptance/modules/Users/UsersCest.php
Increase wait time for addemailaccount test.
See Travis
=> Fix Travis

composer.json, lib/API/v8/Library/ModulesLib.php
Replaced league/url with league/uri:
```
$ composer install
Loading composer repositories with package information
Package league/url is abandoned, you should avoid using it. Use league/uri instead.
```
Issue reference: #6140 
1. Install the ext-intl PHP extension
2. Checkout branch
3. Run composer install or composer update
4. Check that there are no issues with the league/uri replacement in lib/API/v8/Library/ModulesLib.php
=> Fixed #6140 - Switch from league/url to league/uri due to deprecation

include/SugarObjects/templates/company/Company.php, include/SugarObjects/templates/person/Person.php
=> Fixed #6468 - Wrong WHERE composition upon NULL precondition in Company

service/core/SoapHelperWebService.php, soap/SoapHelperFunctions.php
Fixes openssl_decrypt from returning false when using LDAP.
1. Enter admin -> password management
2. Configure soap key for ldap
=> Fix LDAP openssl_decrypt

composer.lock
Bumps [consolidation/robo](https://github.com/consolidation/Robo) from 1.3.2 to 1.3.4.
<details>
<summary>Changelog</summary>
*Sourced from [consolidation/robo's changelog](https://github.com/consolidation/Robo/blob/master/CHANGELOG.md).*
> ### 1.3.4 12/20/2018
> 
> * Allow for aborting completions or rollbacks by James Sansbury ([#815](https://github-redirect.dependabot.com/consolidation/Robo/issues/815))
> * BUGFIX: Allow commands to declare '[**param**](https://github.com/param) InputInterface' to satisfy code style checks
> 
> ### 1.3.3 12/13/2018
> 
> * Add StdinHandler to the standard Robo DI container ([#814](https://github-redirect.dependabot.com/consolidation/Robo/issues/814))
> * BUGFIX: Add test to ensure rollback order is in reverse by James Sansbury …
=> Bump consolidation/robo from 1.3.2 to 1.3.4

modules/AOW_WorkFlow/AOW_WorkFlow.php
=> Duplicate: Better this way to avoid warnings

install/suite_install/suite_install.php, modules/Emails/Email.php
Duplicate of #6867 for hotfix-7.10.x
=> Confirm opt-in fix

composer.json
Fixes a deprecation warning in composer.
Issue reference: #6870 
1. Clone the SuiteCRM repository
2. Make sure you're using Composer 1.8.3 (I'm not sure if this was introduced any earlier than that? I don't remember seeing it with 1.8.0), use `composer self-update` if necessary.
3. Run any composer command, like `composer install` or `composer --version` in the SuiteCRM directory.
4. Note that there's no deprecation warnings.
=> Fixed #6870 - Composer deprecation warning

modules/AOW_Actions/actions/templateParser.php
A previous merge commit (acf2960) introduced a bug in this file, duplicating some code and adding a brace that is never closed.
Issue #6796
See ##6796
=> Fix duplicated code and broken braces introduced in a previous merge.

modules/Campaigns/TrackDetailView.tpl
Fixed white box that appearers to the right of the campaign status page.
issue - #6904 
1. Open campaign view status page 
2. Look at the box.
=> Fixed #6904 - In Campaign view status page, row is out of box

.travis.yml
Lint PHP files in the Travis build to prevent issues like #6796 
See Travis.
=> Fix/php lint 

modules/AOR_Reports/AOR_Report.php
Duplicate of #6811 for the hotfix branch.
=> Duplicate: Reports: Fix "One of" operator for multi select fields

modules/InboundEmail/InboundEmail.php
Fixes an issue with file attachments giving invalid file reference.
Issue reference: #6423 
1. Setup a group email account with auto-import and auto-case generation.
2. Send an email to this account with an attachment.
3. View the created case and try to open the attachment.
=> Fixed #6423 - after upgrading 7.8.13 to 7.8.22 getting Invalid File Reference from attachments in inbound

modules/ModuleBuilder/parsers/parser.label.php
=> Fixed #551 - add functionality to save new labels for relationships

modules/AOR_Reports/aor_utils.php
Fixes a PHP Fatal when updating a report parameter with the period operator.
Issue reference: #6036 
1. Create a new report with any module (e.g. Cases), with any fields (e.g. Account Name) and with at least one condition checked as a parameter using a date field (e.g. Date created). Save the report.
2. In the report view, choose any operator, Period type and any value for the date field parameter.
3. Press update.
4. Page displays
=> Fixed #6036 - Reports entering a date parameter with Period operator

include/MVC/View/views/view.list.php
Fixes an issue where If the "User" column is visible by default in the list view, pagination works and breaks upon hiding it or if the "User" column is hidden by default in the list view, pagination works and breaks upon displaying it.
Issue reference: #6298
1. Ensure any one of "User" / "Assigned To" / "Modified By" columns are available in default list view, through Studio, either as displayed or hidden.
1. Go to either Accounts / Opportunities / Contacts list view.
2. Set Column Chooser to display/hide "User" or "Assigned To" column and save changes (the opposite of whatever is the default setting).
3. Pagination will work.
=> Fixed #6298 - Pagination not working on list views

modules/AOBH_BusinessHours/AOBH_BusinessHours.php, modules/AOBH_BusinessHours/vardefs.php, modules/Administration/BusinessHours.php, modules/Administration/BusinessHours.tpl
Fixes an issue with business hours on mssql due to a reserved word "open".
Issue reference: #6419 
1. Admin -> business hours.
2. Change days to be open or closed.
3. Check that the changes have been applied.
=> Fixed #6419 - Reserved mssql keyword in query, crash business hours module

modules/Emails/Email.php
Fixes an issue with the from name when sending an email from the CRM with special characters.
1. Setup system email settings.
2. Send an email with the from name as "König"
3. Check that the received email is encoded correctly.
=> Fix email encoding

modules/AOS_PDF_Templates/templateParser.php
Fixes a PHP warning due to missing quotes.
https://github.com/salesagility/SuiteCRM/pull/4745#commitcomment-32272443
1. Create a email template to run on case_updates.
=> Fix missing quotes typo

modules/AOR_Reports/controller.php, modules/AOS_PDF_Templates/PDF_Lib/classes/cssmgr.php
Removed CSS property that was make the checkbox disappear
7.10.4 - Checkboxes are missing in downloaded PDF from Reports #5706
7.10.4 - Checkboxes are missing in downloaded PDF from Reports #5706
7.10.4 - Checkboxes are missing in downloaded PDF from Reports #5706
=> Fix for checkbox in PDF

tests/README.md
Duplicate of #7010 for hotfix-7.10.x
=> Fix link to testing documentation. [ci-skip]

modules/AOW_WorkFlow/AOW_WorkFlow.php
Adds and deprecates a removed function.
Issue reference: #6971 
Create a scheduler workflow and add a condition field of a related module.
=> Fixed #6971 - Function removed instead of being Deprecated

composer.json
At the moment this is the only possible solution to remove the tests directory as composer does not allow specifying a dir/file to avoid pulling down. I've also added elasticsearch to prefer dist in the hope that elasticsearch will add a .gitattributes file that ignores the tests directory.
Issue reference: #6978 
1. ```composer install```.
2. Check that the tests directory has been removed in vendor/elasticsearch
3. Test elasticsearch.
=> Fixed #6978 - Hosting company is blocking ports because of YamlRunnerTest.php

modules/AOS_PDF_Templates/templateParser.php
Fix PDF templates from setting no value when 0.00 is entered (for 7.10.x)
1. Go to 'Product - Categories' and create a product category.
2. Then go to 'Products' and create a product.
3. Next, go to 'PDF - Templates' and create a template, make sure you put the variable in the body 
($aos_products_quotes_product_discount), and then save the template.
4. Then go to 'Quotes' and create a new quote.
5. Go to 'Line Items' and click 'Add group'. 
6. Add the product you just made and then change the 'Discount' price to "0.00" and save.
7. Once save, Click 'Print as PDF' and then open the PDF.
8. See that the value is now "0%" instead of  " ".
=> Fix PDF templates from setting no value when 0.00 is entered

.travis.yml, suitecrm_version.php
Adds the DotReporter to codecept so that the Travis output is reduced. It will essentially only display on errors and failures.
Issue reference: #6844 
See Travis.
=> Reduce travis output - DotReporter

modules/InboundEmail/InboundEmail.php
Fixes an issue where non-imported emails display a blank body due to always being processed as HTML. This fix will detect what type of email is received and only run the SugarCleaner::clean once.
Issue reference: #7054 
1. Setup inbound/outbound email.
2. Send a plaintext and html email to yourself.
3. View both the plaintext and html email, check that the body is visible.
4. Import the emails and check the body is still visible.
=> Fixed #7054 - Email body blank when sent as plaintext only

codecov.yml
Adds "Threshhold" to codecov to prevent PR's from failing when they reduce code coverage.
See Travis
=> Codecov threshold

modules/Calendar/CalendarActivity.php
https://www.sugaroutfitters.com/support/securitysuite/653
Issue reference: #675
=> Fixed #675 - Suitecrm 7.3.2 Calendar entries are not displayed

modules/AOR_Reports/AOR_Report.php
This is a commit to help 3592 and the possible problems with quotations.
See #3592
1. Create a Report 
2. Set a Date parameter (Date Created, for example)
3. Select Period as the type and choose any value given 
4. There should be a value given.
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] My change requires a change to the documentation.
- [ X] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> bugfix 3592

include/Dashlets/Dashlet.php, include/SugarLogger/LoggerManager.php
=> FIX #7051 - Fixing a limit of 2.147.483 seconds for autoRefresh

include/ListView/ListViewSmarty.php, modules/Emails/include/ListView/ListViewDataEmails.php
Prevents the suitecrm.log from being spammed with:
```List view smarty data must be an array, undefined data given and converting to an empty array```
```ListViewDataEmails::getEmailRecordFieldValue: email list should be a Countable```
1. Set log level to warn.
2. Enter the email list-view.
3. Check the suitecrm.log.
=> Fix warnings in log

lib/Search/ElasticSearch/ElasticSearchIndexer.php
On branch ElasticSearchIndexer_patch
Changes to be committed:
modified:   lib/Search/ElasticSearch/ElasticSearchIndexer.php
Fix for issue #6985
=> Issue: #6985 Fix Exception on Repair/Quick Repair and Rebuild

include/Smarty/plugins/modifier.htmlparser.php, include/SugarFields/Fields/Text/SugarFieldText.php, include/SugarFields/Fields/Wysiwyg/DetailView.tpl, include/SugarFields/Fields/Wysiwyg/EditView.tpl, include/SugarFields/Fields/Wysiwyg/ListView.tpl, include/SugarFields/Fields/Wysiwyg/SugarFieldWysiwyg.php, include/SugarFields/Fields/Wysiwyg/css/wysiwyg-editview.css, include/generic/SugarWidgets/SugarWidgetFieldwysiwyg.php, modules/AOS_PDF_Templates/templateParser.php, modules/DynamicFields/templates/Fields/Forms/wysiwyg.php, modules/DynamicFields/templates/Fields/Forms/wysiwyg.tpl, modules/DynamicFields/templates/Fields/TemplateWysiwyg.php, modules/ModuleBuilder/language/en_us.lang.php, themes/SuiteP/tpls/_head.tpl
Created a new field type that uses latest tinyMCE to have HTML Editor in any module.
Admin can create field type called WYSIWYG in studio.
=> WYSIWYG Field type core contribution

include/SearchForm/SearchForm2.php, include/SugarLogger/LoggerManager.php
=> FIX Error in SearchForm2.php when having a function in field definition

include/MVC/SugarApplication.php, include/SubPanel/SubPanelTiles.php, modules/UserPreferences/UserPreference.php, modules/Users/Logout.php, modules/Users/views/view.detail.php
This PR ensures that when setting a cookie we mark it as secure if SSL is being used.
Setting cookies to be secure where we can means that we reduce the chance of various security issues.
Testing would likely involve using the CRM in general with HTTP and HTTPS to ensure that cookie functionality hasn't been affected (though it shouldn't).
More in depth testing would also involve examining the cookies generated.
=> Ensure we use secure cookies when appropriate.

modules/Emails/include/ComposeView/EmailsComposeView.js
Fixes an issue where the enter key would send a new email every keypress.
JSFiddle: https://jsfiddle.net/e1f82qua/
Issue reference: #6729
1. Email module -> compose email.
2. Click send.
3. Hit the enter key.
=> Fixed #6729 - Email Style Issue - Black screen

modules/AOR_Reports/AOR_Report.php
Duplicate of #6639 for hotfix-7.8.x branch.
Issue reference: #3592
1. Create a report.
2. Add a date parameter.
3. Select Period as the type and select a range.
4. Check the resulting report contains the correct records.
=> Fixed #3592 - AOR Report - Date parameter doesn't work with any value of type 'Period'

include/utils.php, install.php, install/download_modules.php, modules/UpgradeWizard/silentUpgrade_dce_step1.php, modules/UpgradeWizard/silentUpgrade_dce_step2.php, modules/UpgradeWizard/silentUpgrade_step1.php, modules/UpgradeWizard/silentUpgrade_step2.php
Simply removing a reference to sugar.
=> Fixed - Removed sugar reference

modules/Emails/vardefs.php
Modify `emails_meetings_rel` definition to avoid overriding of `parent_id` of Meetings.
See issue #5971 
1. Create the following workflow.
(create an email template with whatever text)
2. Create a new Meeting related with a Lead that has a valid email.
3. Wait until the mail is sent.
4. Open the afected Meeting and observe that Lead "has disappeared".
5. Now it's time to do some SQL querys:
```
SELECT parent_type, parent_id FROM meetings WHERE id = '<meeting_id>'
```
6. See that `parent_type` is correct but `parent_id` of `meetings` table corresponds to an id of `emails` table.
7. Apply the PR and repeat 1-6 steps. Se that Meetings parent related is not replaced with the id of the email reccord.
=> Fix #5971 - Send email with Workflow using Meetings module breaks parent_id

lib/Robo/Plugin/Commands/UpgradeCommands.php
Adds a robo task for upgrading the CRM through command line.
Issue reference: #6710 
1. Composer install.
2. Download an upgrade pack compatible with your SuiteCRM version.
3. Run ```./vendor/bin/robo upgrade:suite [upgradeZipFile] [logFile] [pathToSuiteCRMInstance] [adminUser]```
Example of command running with an admin user called admin and upgrade pack in root suitecrm directory:
```
./vendor/bin/robo upgrade:suite SuiteCRM-Upgrade-7.10-to-7.10.12.zip upgradeLog.log ../suitecrm-mysql admin
```
TODO:
- Progress meter
- More logging
- Cleanup modules/UpgradeWizard
=> Performing an upgrade from the CLI #6710

modules/Emails/vardefs.php
Duplicate of #5972.
See #5972.
=> Fixed #5971 - Send email with Workflow using Meetings module breaks parent_id

lib/API/OAuth2/Repositories/AccessTokenRepository.php, lib/API/OAuth2/Repositories/ClientRepository.php, lib/API/public/index.php
This fixes three main bugs which were introduced to the (little) v8 API after v7.10.10 and onwards.  Since (big) V8 API is not feature complete compared to (little) v8, this is is a PR to get (little) v8 working again.
This PR addresses some of #7083 
I was using the API and rely on feartures which are missing (see #7083)
* Load up PR
* Attempt to continue using the API after 7.10.10
=> Fix (little) v8 API for v7.10.10+

include/SugarObjects/LanguageManager.php
Reverts changes made in #6946 pending further discussion.
=> Revert: Fix priorities when loading language files

soap/SoapPortalUsers.php
Missing curly brace in SoapPortalUser.php.
See Travis which runs ```php -l``` on modified files.
=> Fixing typo

README.md, include/StateChecker.php, include/StateSaver.php, include/Sugar_Smarty.php
Duplicate of #7055 for hotfix-7.10.x branch.
=> Fixed #6921 - Verbose logs for popErrorLevel

modules/AOR_Reports/controller.php
Duplicate of #6007 for hotfix-7.10.x branch.
=> Fixed #6755 - Adding setFooter('{PAGENO}') to the PDF

themes/SuiteP/tpls/_headerModuleList.tpl, themes/SuiteP/tpls/header.tpl
Duplicate of #7049 for hotfix-7.10.x branch.
=> Give cookie a default value to stop from throwing notices

include/SugarFolders/SugarFolders.php
Duplicate of #7099 for hotfix-7.10.x branch.
=> Fix: For MS SQL Support

tests/unit/phpunit/modules/Accounts/AccountTest.php, tests/unit/phpunit/modules/EmailMan/EmailManTest.php, tests/unit/phpunit/modules/Employees/EmployeeTest.php, tests/unit/phpunit/modules/Leads/LeadTest.php, tests/unit/phpunit/modules/Users/UserTest.php
```
1) EmailManTest::testget_list_view_data
Failed asserting that Array &0 (
'IN_QUEUE' => '0'
'SEND_ATTEMPTS' => '0'
'DELETED' => '0'
'RELATED_CONFIRM_OPT_IN' => '0'
'EMAIL1_LINK' => '            <a class="email-link" href="mailto:"
onclick="$(document).openComposeViewModal(this);"
data-module="EmailMan" data-record-id=""
data-module-name="" data-email-address=""
></a>'
) is identical to Array &0 (
'IN_QUEUE' => '0'
'SEND_ATTEMPTS' => '0'
'DELETED' => '0'
'RELATED_CONFIRM_OPT_IN' => '0'
'EMAIL1_LINK' => '<a class="email-link" onclick="$(document).openComposeViewModal(this);" data-module="EmailMan" data-record-id="" data-module-name="" data-email-address=""></a>'
).
```
See Travis.
=> Fix EmailManTest::testget_list_view_data

.travis.yml
Duplicate of #6770 for hotfix-7.10.x.
See Travis.
=> Don't delete the composer.lock when running tests on travis.

Api/V8/Config/routes.php
Fixed Typo in `routes.php`
API can now delete relationships.
See issue  #6761 
The public and internal documentation all say that relationships can be deleted. This makes that possible
Run through the API requests in the included Postman collection. 
Specifically delete two linked records by making the following API call:
`DELETE {{suitecrm.url}}/V8/module/[module]/[focus_id]/relationships/[relationship]/[related_id]`
- [ x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [x ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> Fixed 6761 - Api/V8 - Unable to Delete (unlink) relationships

Api/Core/Loader/CustomLoader.php
Modified the default `routes.php` location provided to `CustomLoader::loadCustomRoutes`. This causes the custom `routes.php` file to be in the same location as other custom files. 
This solves the problem addressed in #6862. It provides a _consistent_ location for custom files. 
Create a custom `routes.php` file and place it at `custom/application/Ext/Api/V8/routes.php`. Confirm that it is recognized by the API. 
If someone had already customized the api by adding a `routes.php` file, they would need to move this file.
=> Fixed #6862 - API - Custom Routes file is stored separately from other custom files

Api/V8/Config/routes.php
API routes were missing the DeleteRelationShipParams import.
Issue reference: #6761 
1. ```DELETE {{suitecrm.url}}/V8/module/[module]/[focus_id]/relationships/[related_module]/[related_id]```
=> Fixed #6761 - Api/V8 - Unable to Delete (unlink) relationships.

Api/Core/Loader/CustomLoader.php
Updated the default routes.php location in CustomLoader::loadCustomRoutes to be consistent with the rest of the custom extension files.
Issue reference: #6862 
Create a custom routes.php file and place it at custom/application/Ext/Api/V8/routes.php. Confirm that it is recognized by the API.
=> Fixed #6862 - Api/V8 - API - Custom Routes file is stored separately from other custom files

include/MVC/View/SugarView.php
=> FIX #7207 - Get Menu.php from custom/modules/MODULE_NAME

modules/jjwg_Areas/Menu.php
When attempting to import Map Areas a dialog box appears with the words "An Error has occurred". So, the issue with the url, where in query,"module" was mentioned "jjwg_Areas", instead of "Import".
With this change, user can import records into "Map Areas".
1. Open the Map Area option from the menu
2. Select the Import option from the Right Hand menu.
=> Fixed #5724 - Map Area - Import Option Fails : An Error has occurred

include/Popups/tpls/header.tpl
Adds missing ```$STYLE_JS``` to header template.
Fixes #7162 
1. Enter a record detail view
2. Go to a subpanel and choose Select
3. Select current page
4. Select all
=> Fixed #7162 - Popup select All records btn hidden in SuiteCRM 7.11.x

Api/V8/Config/routes.php
Changed ```DeleteRelationShipParams::class``` to ```DeleteRelationshipParams``` to match the qualified class name and ::class constant.
=> Fixed DeleteRelationshipParams typo

Api/V8/Service/RelationshipService.php
All returned links should be relative to the base_uri ```https://crm.example.org/Api/.```
Call: {{suitecrm.url}}/V8/module/Contacts/ef9bcee0-8068-0346-29b2-5cb448bc67f9/relationships/email_addresses):
Before fix:
```
{
"data": [
{
"type": "EmailAddress",
"id": "477609bb-ceda-6046-1207-5cb448434181",
"links": {
"self": "/V8/module/EmailAddress/477609bb-ceda-6046-1207-5cb448434181"
}
}
]
}
```
After fix:
```
{
"data": [
{
"type": "EmailAddress",
"id": "477609bb-ceda-6046-1207-5cb448434181",
"links": {
"self": "V8/module/EmailAddress/477609bb-ceda-6046-1207-5cb448434181"
}
}
]
}
```
=> Fixed relationship links url

Api/V8/Controller/BaseController.php, Api/V8/Factory/ParamsMiddlewareFactory.php, Api/V8/Middleware/ParamsMiddleware.php, Api/V8/OAuth2/Repository/AccessTokenRepository.php, Api/V8/Service/UserService.php, include/Smarty/plugins/function.sugar_button.php, modules/OAuth2Clients/js/ClientCredentialsValidation.js, modules/OAuth2Clients/js/PasswordCredentialsValidation.js, modules/OAuth2Clients/metadata/editcredentialsviewdefs.php, modules/OAuth2Clients/metadata/editpasswordviewdefs.php, modules/OAuth2Clients/vardefs.php
- Make assigned user required for client credentials grant types.
- For password grant types set the given user id as the assigned user id on access tokens.
- For client credential grant types set the client assigned used as the assigned user on access tokens.
- Set the current user global using the assigned user ID from the given access token in ParamsMiddleware.
- Validate Oauth2Client form.
- Change UserService::getCurrentUser to get the current user from the access tokens assigned user instead of the client.
*Note this PR depends on #7215
Issue reference: #6483 
1. Pull down this branch + #7215.
2. Call ```Api/access_token``` to get a new access token.
3. Create a record with POST ```{{suitecrm.url}}/V8/module``` with type parameter set to any module.
4. Check that the created_by and …
=> Fixed #6483 - V8 API Doesn't popuplate created_by and modified_user_id

Api/V8/Service/ModuleService.php
Updates the V8 API to allow the user to create/update records with the ```created_by```, ```created_by_name```, ```modified_user_id```, ```modified_by_name```, ```date_entered```, and ```date_modified``` fields.
Issue reference: #4661 
```POST: {{suitecrm.url}}/V8/module```
1. Create a record with the V8 API and check that all the passed attributes are correctly applied:
```
{
"data": {
"type": "Accounts",
"attributes": {
"name": "TEST API POST ACCOUNT",
"created_by": "1",
"created_by_name": "admin",
"modified_user_id": "1",
"modified_by_name": "admin",
"date_entered": "2030-01-01 01:01:01",
"date_modified": "2032-02-02 02:02:02"
}
}
}
```
2. Update an existing record and check that all the passed attributes are correctly applied:
```
{
"data": {
"type": "Accounts",
"id": …
```
=> Fixed #4661 - Ability to create / edit object's "Created By" "Date Created" using API

modules/AOS_Products_Quotes/line_items.js
Fix for isssue #7220
Modified JS function 
Issue
-Create a new contract
-Create a new group and line item
-In the description and note field type: 123,132,132,132.00
-Save
-Re-open the Edit view
-The description and note field display: -NaN.NaN
https://github.com/salesagility/SuiteCRM/issues/7220
https://github.com/salesagility/SuiteCRM/issues/7220
Expected Behavior
They should display 123,132,132,132.00
Actual Behavior
The description and note field display: -NaN.NaN
1-Create a new contract
2-Create a new group and line item
3- In the description and note field type: 123,132,132,132.00
4- Save
5- Re-open the Edit view
6- The description and note field display: -NaN.NaN
- [] Bug fix (non-breaking change which fixes an issue)
=> Fix bug_7220

modules/AOS_Products_Quotes/line_items.js
Duplicate of #7222 for hotfix-7.10.x branch.
Issue reference: #7220 
1-Create a new contract 
2-Create a new group and line item
3- In the description and note field type: 123,132,132,132.00
4- Save
5- Re-open the Edit view
6- The description and note field should display the values correctly.
=> Fixed #7220 -  Description/note fields in the contract line items formats the numeric values as currency

codecov.yml
Removes the patch status check as it's unreliable and causes PR's to appear as failing.
View [docs](https://docs.codecov.io/docs/commit-status). This PR won't take effect until it's merged into master.
=> Remove codecov patch status

lib/Search/UI/SearchThrowableHandler.php, modules/Administration/Search/view.tpl, modules/Administration/language/en_us.lang.php, modules/Home/language/en_us.lang.php
Fixed #6540 - Hard coded text to language files
Created language entries for the hard coded text (see Issue for more details).
So the text can be translatable.
View the text that has been changed (see Issue). Change Language file, Check that the text is changing in the appropriate sections.
=> Fixed #6540 - Hard coded text to language files

tests/acceptance/modules/AOS_Product_Categories/AOS_Product_CategoriesCest.php
`AOS_Prouduct_Categories` => `AOS_Product_Categories`
=> Fix AOS_Product_Categories test name.

.travis.yml
Caches the composer packages.
Issue reference: #6829 
See Travis.
=> Fixed #6829 - Cache composer packages on Travis CI

include/InlineEditing/InlineEditing.php, include/generic/DeleteRelationship.php, modules/Leads/LeadFormBase.php, modules/Leads/tpls/DetailViewHeader.tpl
Fix #6498 (Inconsistencies in Leads-Accounts relationship)
See Issue.
See Issue.
=> Fix #6498 - handling of Account names and ids in Leads

composer.lock, include/Popups/tpls/header.tpl, include/SugarObjects/templates/basic/metadata/detailviewdefs.php, include/SugarObjects/templates/company/metadata/detailviewdefs.php, include/SugarObjects/templates/file/metadata/detailviewdefs.php, include/SugarObjects/templates/issue/metadata/detailviewdefs.php, include/SugarObjects/templates/sale/metadata/detailviewdefs.php, modules/AOR_Reports/tpls/EditViewFooter.tpl, modules/AOW_WorkFlow/AOW_WorkFlow.php, modules/jjwg_Areas/Menu.php
Duplicate merged Hotfix/Hotfix-7.10.x PRs for hotfix-7.8.x
PR Reference: #6680
PR Reference: #7105
PR Reference: #6128 
PR Reference: #6745
PR Reference: #7170
=> Hotfix/Hotfix-7.10.x -> Hotfix-7.8.x

composer.lock, data/Relationships/M2MRelationship.php, include/InlineEditing/InlineEditing.php, include/SugarObjects/templates/basic/metadata/detailviewdefs.php, include/SugarObjects/templates/company/metadata/detailviewdefs.php, include/SugarObjects/templates/file/metadata/detailviewdefs.php, include/SugarObjects/templates/issue/metadata/detailviewdefs.php, include/SugarObjects/templates/sale/metadata/detailviewdefs.php, include/generic/DeleteRelationship.php, modules/AOW_WorkFlow/AOW_WorkFlow.php, modules/Leads/LeadFormBase.php, modules/Leads/tpls/DetailViewHeader.tpl, modules/jjwg_Areas/Menu.php
Duplicate merged hotfix PRs for hotfix-7.10.x.
PR Reference: #6680
PR Reference: #7105
PR Reference: #6128 
PR Reference: #6048 (Hotfix-7.8.x -> Hotfix-7.10.x)
PR Reference: #6499 (Hotfix-7.8.x -> Hotfix-7.10.x)
=> Hotfix -> Hotfix-7.10.x

Api/V8/Service/ModuleService.php, lib/Exception/AccessDeniedException.php
Adds ACL functionality to the V8 API.
Issue reference: #7188
1. Create a user + role and set the module permissions.
2. Assign the role to the created user.
3. Generate OAuth client for the created user.
4. Call Api/access_token API for an access token.
5. Try to view/update/create records in restricted modules..
=> Fixed #7188 - ACL doesn't work on JSON API V8

tests/acceptance/modules/Activities/ActivitiesCest.php, tests/acceptance/modules/History/HistoryCest.php
Hopefully fixes the due date acceptance test from failing.
See Travis.
=> Travis due date fix

install.php
Duplicate of #7273 for hotfix-7.8.x branch.
1. Install a fresh instance and verify the upload logo functionality works as expected.
=> Fixed install syntax error

include/SugarLogger/LoggerManager.php
=> FIX  #7268 - Fatal Error with PHP 7.3

.travis.yml, Api/V8/Param/Options/Fields.php, Api/V8/Param/Options/Sort.php
This depends on #7124 (this PR includes it for now)
Turns out the tests pass now with two small fixes.
Don't regress with php7.3 by testing in CI
=> RFC:  travis-ci: add a job for PHP 7.3 

modules/ProspectLists/vardefs.php
=> FIX #7291 - Field name in ProspectLists is now varchar(255)

modules/Cases/Dashlets/MyCasesDashlet/MyCasesDashlet.data.php
Fixes an issue where the cases dashlet wouldn't display new cases until you hit edit and save.
Issue reference: #7183 
1. Create a case, assign it to yourself, make sure it has a state of Open and a status of New, Assigned or Pending Input 
2. Navigate to the Dashboard and add a 'My Open Cases' Dashlet.
3. Observe that there are no cases displayed
=> Fixed #7183 - My Cases dashlet searchFields status default values are incorrect

modules/DynamicFields/DynamicField.php
=> Fixed - #7133 - Fix Changes in Studio do not make an override file

include/ListView/ListViewSmarty.php
=> FIX #7250 - Remove PHP Notices in include/ListView/ListViewSmarty.php

themes/SuiteP/include/ListView/ListViewGeneric.tpl
Fixed OAuth2Token error where the Create and Import buttons were visible but had no functionality, to fix this I used a "hide_edit_link" to determine if the buttons should be visible or not.
#6915 
1. Create or Edit Oauth2 Token
2. Check to see if list view buttons are visible on other modules.
=> Fixed #6915 - File OAuth2Tokens/metadata/editviewdefs.php is Missing.

modules/Users/User.php, modules/Users/controller.php, tests/_support/Step/Acceptance/Administration.php, tests/_support/Step/Acceptance/UsersTester.php, tests/acceptance/modules/Users/UsersCest.php
Fixes an issue introduced by #6404 causing both user management inline editing to break along with the new user creation form.
Issue reference: #6869
1. As an admin user, create a new user.
2. Login as this user and fill out the form.
3. Check that the user has saved correctly.
4. Check that admin user management mass update works correctly.
5. Check that user settings save correctly.
=> *WIP Fixed #6869 - Saving user resets preferences

modules/FP_events/controller.php
The query fails while managing event delegates in MSSQL while Performing Manage Delegates & Manage Acceptances 
Issue No: #6851
=> Manage delegate mssql

install/dbConfig_a.php, install/installConfig.php, install/installDisabled.php, install/installType.php, install/license.php, install/old_php.php, install/performSetup.php, install/ready.php, install/siteConfig_a.php, install/welcome.php
Find and replaced old forum link with new one.
1. Check the forum link works in the install screen footer.
=> Fix support forum link

tests/api/V8/GetFieldsMetaCest.php, tests/api/V8/GetModulesMetaCest.php
Fixes failing tests for PR #7277
Fixes #7310
=> Fix #7277 tests

.travis.yml
Just here to kick off Travis on salesagility repo. Interestingly seems to be passing on my fork.... https://travis-ci.org/Dillon-Brown/SuiteCRM/builds/542693864
See Travis.
=> Fixed hotfix-7.8.x Travis

include/utils/file_utils.php, modules/Administration/DiagnosticRun.php
This fixes an issue with the diagnostic tool returning an empty array when trying to calculate the md5 difference. I also updated the dirs to ignore when running the md5 execution.
Issue reference: #6872 
1. Admin -> diagnostic tool.
2. Enable MD5 info, copy files.md5 and copy MD5 calculated array.
3. Check that the downloaded zip contains all 3 files with the correct data.
=> Fixed #6872 - Installation and upgrades files checksums not provided

include/SubPanel/SubPanelDefinitions.php
=> FIX #7234 - Get subpaneldefs.php from custom/modules/MODULE_NAME/metadata

RoboFile.php
`RoboFile.php` was previously removed in 23824dd479a1a7a0db8729698b096ea1a2b2ab50, but this introduced a problem where an erroring or incorrect Robo command would also print an error about a missing `RoboFile.php`.
This could make debugging errors with Robo commands confusing, since an unrelated error was appearing.
e.g. you'd see error messages like this when running a task that hits a file permissions error:
```
suitecrm-upstream connorshea$ ./vendor/bin/robo driver:run-chrome --reinstall
➜  Driver Run Chrome
➜  macOS detected
[Filesystem\DeleteDir] Deleted /Users/connorshea/code/sites/suitecrm-upstream/build/tmp/...
[error]  Unable to create file structure /Users/connorshea/code/sites/suitecrm-upstream/build/tmp/ 
➜ …
```
=> Add RoboFile.php to root directory again.

modules/Home/index.php
Fixes an issue where a custom MySugar.tpl is never loaded due to a missing slash.
Issue reference: #7357 
1. Create the custom file ```custom/themes/' . $theme . '/include/MySugar/tpls/MySugar.tpl```.
2. Check that this file is loaded in home module index.
=> Fixed #7357 - Home module index page loading bad MySugar file location

README.md
Add Info about making PR's in GitHub project README
=> Info about making PR's in GitHub project README

themes/SuiteR/tpls/_headerModuleList.tpl
The variable name is "module_name" not "module"
=> Favorite link in active Module does not get generated

include/database/DBManager.php, modules/Audit/Audit.php
Update the audit logging code to store multienums (which use a text field) in the before_value_text and after_value_text columns.
This resolves #7391 and prevents DB failures in cases where the multienum field is more than 255 characters.
- Create or choose a multienum field.
- Ensure it has lots of options or options with long keys.
- Select all options
- Save record
- Examine DB/Logs
- Before fix there will be no audit record for that field. After the fix there will be.
=> Fixed #7391 - DB Error on audit logging large multi select fields.

tests/_support/AcceptanceTester.php
=> Remove waitForElementNotVisible timeout in login function.

jssource/src_files/include/javascript/sugar_3.js
Copy of a PR by [samus-aran](https://github.com/samus-aran) for use in 7.8.x LTS.
#750
This fixes custom required fields not alerting the user when they don't fill it out.
Issue reference: #715
Issue reference: #1280
Create a custom radio button field with a blank value as the default. Set this field as "Required" and attempt to create a record without selecting a value for this field.
=> Fixed #715 - Custom Required Field not flagging

modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
When on the activity stream dashlet, there is a reply button, you can enter a reply and it will show as normal but when you filter the activity stream to a module the reply doesn't show up.
https://github.com/salesagility/SuiteCRM/issues/7319 
1. Click Reply and see an input box underneath the entry you want to reply to.
2. Enter Text and Click POST button
3. Dashlet refreshes and you see the Reply underneath the entry with a user's profile picture.
=> FIXED #7319 - Activity Stream dashlet "reply" function doesn't appear to do anything

modules/Emails/EmailsController.php, modules/Emails/include/ListView/DeleteEmailAction.js, modules/Emails/include/ListView/ListViewHeader.js, modules/Emails/language/en_us.lang.php, modules/Emails/metadata/detailviewdefs.php, modules/Emails/metadata/listviewdefs.php, modules/Emails/metadata/nonimporteddetailviewdefs.php
Adds new functionality to allow deletion of email from IMAP server through both the list-view bulk action and detail-view actions. I'd suggest pulling down #7400 to fix the bulk action functionality.
Issue reference: #3727 
1. Setup emails
2. Test out the bulk action functionality for deleting emails from IMAP (Test both deleting single, multiple, imported and non-imported).
3. Repeat this in the detail-view of imported and non-imported emails.
=> Fixed #3727 - IMAP server delete button on DetailView

.travis.yml, tests/_envs/travis-ci-hub.yml, tests/_support/Step/Acceptance/Calls.php, tests/_support/Step/Acceptance/DetailView.php, tests/_support/Step/Acceptance/ModuleBuilder.php, tests/acceptance/Core/ModuleBuilderFieldsCest.php, tests/acceptance/modules/Accounts/AccountsCest.php, tests/acceptance/modules/Activities/ActivitiesCest.php, tests/acceptance/modules/History/HistoryCest.php
This doesn't speed up the test suite like I had hoped - or at least not by any noticeable amount - but it should make the tests more consistent across environments.
=> Remove wait from Codeception Travis env

include/Imap/ImapHandler.php
Fixes an issue with auto-import not importing emails due to BADCHARSET.
Issue reference: #6866 
1. Setup group inbound email with auto-import.
2. Setup cron.
3. Receive emails to this account from exchange and non-exchange servers and check both emails import correctly.
=> Fixed #6866 - 7.10.12 Auto Import of Emails not working

modules/Users/User.php
Duplicate of #7439 for hotfix-7.8.x.
See original PR for details.
=> Update password hash to use php password_hash by default

modules/Leads/views/view.convertlead.php
Please see Issue #7455
See the steps to reproduce in the Issue.
=> Fix #7455 Leads conversion - handle copying photo file, if present

README.md, suitecrm_version.php
Update suitecrm_version and README.
=> Increment suitecrm_version

modules/Surveys/Entry/Survey.php
Fixed an issue with the survey entry displaying a 500 page.
Issue reference: #7467 
1. Create a new Survey, just give it a name, make it `Public` and hit `Save`.
2. A URL is shown on the detail view, something like this: `https://demo.suiteondemand.com/index.php?entryPoint=survey&id=4511ebc3-c962-2aab-56d1-5d1206de0a50`.
3. Click that URL.
=> Fixed #7467 - Survey entry-point broken in 7.11.5

modules/Emails/EmailsDataAddressCollector.php
Fixed an issue where the from and reply to address would be formatted incorrectly preventing emails from being sent.
Issue reference: #7407 
1. Create a system outbound email.
2. Add an email address to user profile (Profile edit view, not profile email settings).
3. Compose an email and check that the username is not duplicated and the email sends correctly.
=> Fixed #7407 - "Users may send as themselves" broken - Invalid address: (punyEncode)

modules/Emails/EmailUI.php
Fixed an issue where a user could bypass the inbound email settings option by marking a group account as active in user profile.
Issue reference: #6992 
1. Create a group email account.
2. Check this account is visible in user settings while logged in as an admin.
3. Check this account is not visible when logged in as a regular user.
4. Mark this account as usable in inbound email settings and check that it is now visible in user profile.
=>  Fixed #6992 - Group Email Inbox accounts doesn't respect reply as option in admin

include/vCard.php
Allows users to upload a vcf file that has multiple contacts.
Issue reference: #2620 
Upload the following .vcf to contacts:
```
BEGIN:VCARD
VERSION:2.1
N:name1;name2;;;
FN:name2 name1
TITLE:
NICKNAME:
ORG:org 1;
TEL;WORK:000001
EMAIL;WORK:mail1@tld
END:VCARD
BEGIN:VCARD
VERSION:2.1
N:name3;name4;;;
FN:name4 name3
TITLE:
NICKNAME:
ORG:org2;
X-PB-SYNC:yes
TEL;WORK:000002
TEL;CELL:000003
END:VCARD
```
=> *WIP Fixed #2620 - Need to import multiple contacts from single VCARD .vcf file

modules/Users/vardefs.php
=> FIX #7509 - Using prefix index to not hit Key threshold in MySQL5.6/UTF-8

modules/InboundEmail/InboundEmail.php
Fixes inline images in emails and cases.
Issue reference: #6470 
1. Import an email with an inline image.
2. Receive a case with an inline image.
=> Fixed #6470 - Email module: Inline image not shown in received/sent email

install.php
Fixes the silent installer displaying a 500 error instead of the login page.
Issue reference: #7511 
1. Setup config_si.php.
2. Install through ```install.php?goto=SilentInstall```.
3. Check that the final step takes you to the login page.
4. Check that the standard install still works correctly.
=> Fixed #7511 - Silent installer tries to do unknown things on completion

modules/ModuleBuilder/javascript/ModuleBuilder.js
This reverts commit 3aacb42243400e91337d52f89233fda4d5328021.
The goal here is to fix the flaky Module tests.
=> Revert "FIXED #3756 - Popup Studio and Calendar don't auto-close"

modules/InboundEmail/InboundEmail.php
Fixed an issue with the email attachment icon not appearing in the email list-view.
1. Set up inbound email.
2. Receive emails with attachments.
3. Check that all emails containing attachments show the icon in the list-view regardless of import status.
=> Fixed email attachment icon

include/EditView/SubpanelQuickEdit.php, include/MVC/View/views/view.quickcreate.php, include/MVC/View/views/view.quickedit.php, modules/Connectors/tpls/administration.tpl, modules/Contacts/views/view.quickcreate.php, modules/Home/SubpanelEdits.php, modules/ModuleBuilder/tpls/Preview/layoutView.tpl, modules/ModuleBuilder/tpls/Preview/listView.tpl, modules/ModuleBuilder/tpls/layoutView.tpl, modules/ModuleBuilder/tpls/listView.tpl, modules/Project/views/view.quickedit.php, modules/Users/views/view.quickedit.php, themes/SuiteP/modules/ModuleBuilder/tpls/layoutView.tpl
Removed sugarflav=pro references.
=> Remove sugar references

install.php
Fixed an old sugar_login.php reference and updated it to suitecrm_login.png
Issue reference: #7547
=> Fixed #7547 - use correct login image on install.php

.travis.yml
So it looks like codecov broke at some point and nobody noticed :D. This fixes the pathing so it can find the coverage.xml.
```
==> Travis CI detected.
project root: .
Fixing merge commit SHA
Yaml found at: codecov.yml
-> Found 1 reports
==> Detecting git/mercurial file structure
==> Appending build variables
+ TRAVIS_OS_NAME
+ TRAVIS_PHP_VERSION
==> Reading reports
- file not found at ./_output/coverage.xml
--> No coverage data found.
```
See Travis and check that the code coverage is outputted correctly.
=> Fix codecov path

lib/Robo/Plugin/Commands/BuildCommands.php, lib/Robo/Plugin/Commands/CleanCacheCommands.php, lib/Robo/Plugin/Commands/UpgradeCommands.php, lib/Robo/Traits/CliRunnerTrait.php
Backports robo tasks in the hotfix branch to the hotfix-7.10.x branch, namely:
- BuildCommands:buildSuitP
- BuildCommands:buildSuitePColorScheme
- CleanCacheCommands
- UpgradeCommands
- CliRunnerTrait (Allows developers to initialise an instance of the CRM inside tasks).
Run each of the modified/new tasks and check they still work in the 7.10.x branch.
=> Backport hotfix robo tasks

modules/Emails/EmailUI.php
Added a missing function called in ```_AddJobsHere.php```.
This fixes a PHP fatal when trying to create a case using a distribution method other than round-robin.
1. Setup a group inbound email account that automatically creates cases and assigns them using a method other than round-robin.
2. Check that the cases are created and assigned correctly.
=> Fix missing function getAssignedEmailsCountForUsers

modules/Emails/EmailUI.php
Fixed a typo causing "data error" on ```profile -> email settings``` when setting up personal inbound email.
An inbound email account isn't a sugar folder :).
1. Check that #7476 is still resolved.
2. Setup personal inbound email.
3. Check that the email is visible.
=> Fixed email settings "data error"

modules/Meetings/metadata/subpanels/ForActivities.php
Fixes a DB error when adding meetings to the activities subpanel.
Issue reference: #7267
1. Schedule a meeting in the activities subpanel of an account.
2. Check that the meeting displays in the subpanel with a DB failure.
=> Fixed DB failure with activities subpanel

include/SugarCharts/SugarChartFactory.php
=> Fix travis JIT failure

modules/InboundEmail/InboundEmail.php
Fixed an issue with plain-text + attachments emails not displaying a body on non-imported and imported emails.
Issue reference: #7667 
Test receiving emails that were sent as plain-text and include attachments, both imported and non-imported should show the correct body. I would also recommend trying with multiple different email clients along with sending multiple different email types to ensure that everything still works as expected.
=> Fixed #7667 - Cannot import Email if plain-text plus attachment

modules/InboundEmail/InboundEmail.php
Fixed:
```
PHP Notice: Undefined variable: msgnos in /var/www/suitecrm/public/modules/InboundEmail/InboundEmail.php on line 6871
```
Issue reference: #6415
=> Fixed #6415 - Bug when inbound email "Leave Messages On Server" set to "No"

modules/EmailMan/EmailMan.php
When scheduling a NewsLetter Campaign to send emails and the Campaign contains target list type 'Suppression list by Email Addresses' the list is not checked and sends emails to recipients regardless if a record with same email address is inside the suppression list.
Issue reference: #7138 
1. Create a campaign.
2. Add 'default' and 'suppression list by email addresses' target list.
3. Schedule campaign.
4. Check the campaign log.
=> Fixed #7138 - EmailMan sendEmail missing restricted_addresses check

include/SugarCharts/Jit/Jit.php, include/SugarCharts/Jit/js/mySugarCharts.js
Fixed an issue with missing ```include/SugarCharts/Jit``` causing the homepage dashlets to fail.
Issue reference: #7696 
Issue reference: #7688
Test all homepage dashlets and modules that contain charts.
=> Fixed #7696 - Folder "include/SugarCharts/Jit" missing in 7.11.7 installation

include/Smarty/Config_File.class.php, include/Smarty/Smarty.class.php, include/Smarty/Smarty_Compiler.class.php, include/Smarty/internals/core.assemble_plugin_filepath.php, include/Smarty/internals/core.assign_smarty_interface.php, include/Smarty/internals/core.create_dir_structure.php, include/Smarty/internals/core.display_debug_console.php, include/Smarty/internals/core.get_include_path.php, include/Smarty/internals/core.get_microtime.php, include/Smarty/internals/core.get_php_resource.php, include/Smarty/internals/core.is_secure.php, include/Smarty/internals/core.is_trusted.php, include/Smarty/internals/core.load_plugins.php, include/Smarty/internals/core.load_resource_plugin.php, include/Smarty/internals/core.process_cached_inserts.php, include/Smarty/internals/core.process_compiled_include.php, include/Smarty/internals/core.read_cache_file.php, include/Smarty/internals/core.rm_auto.php, include/Smarty/internals/core.rmdir.php, include/Smarty/internals/core.run_insert_handler.php, include/Smarty/internals/core.smarty_include_php.php, include/Smarty/internals/core.write_cache_file.php, include/Smarty/internals/core.write_compiled_include.php, include/Smarty/internals/core.write_compiled_resource.php, include/Smarty/internals/core.write_file.php
This is essentially a duplicate of #7719 but for #7591. See #7719 for details.
1. See Travis
2. Test smarty.
=> Fix smarty backwards compatibility

modules/Administration/UpgradeAccess.php
This PR will fix the loading issue with files.
The current .htaccess file is causing issues with loading, the requests are responding with 302 code with Forbidden.
This PR will allow the correct files to be loaded.
Install SuiteCRM
Access Administrator Panel
Access Repair
Access Rebuild .htaccess file
Hard Refresh Browser (Disable cache if possible)
View Network tab and check all files are loaded correctly.
Test System to check all functionality is as expected.
Example of generated .htaccess file:
```
RedirectMatch 403 (?i).*\.log$
RedirectMatch 403 (?i)/+not_imported_.*\.txt
RedirectMatch 403 (?i)/+(soap|cache|xtemplate|data|examples|include|log4php|metadata|modules|vendor|custom)/+.*\.(php|tpl)
RedirectMatch 403 (?i)/+emailmandelivery\.php
RedirectMatch 403 (?i)/+.git
RedirectMatch 403 …
```
=> Fixed #7761 htaccess issue

.travis.yml
Currently, the travis.yml is set up to run PHP 5.6, 7.0, 7.1, 7.2 and 7.3 and then 7.0 again to generate code coverage. I've updated this to remove PHP 7.0 since it already runs in the code coverage job and 7.1, 7.2 as I feel they don't give many benefits when it takes 20+ minutes to complete a job and we're already testing 7.0 and 7.3.
Issue reference: #6830
See Travis.
=> Fixed #6830 - Code coverage as a separate stage in CI

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds a comment about how to add code within a PR & Issues.
Ensure that PRs & Issues stay correctly formatted
N/A
=> Update issue & PR templates to comment on how to include code

themes/SuiteP/tpls/_headerModuleList.tpl
Read #7825
Before the fix:
After the fix
For users that use other languages than English, the interface is not fully translated
1. Install a language translation for SuiteCRM, for example Spanish
2. Verify that the title tag for rentently viewed is not translated
=> FIX #7825 - Now we translate the title tag for recently viewed links

.travis.yml
This is a temporary fix to remove the PHP 5.5 job in Travis as chrome 77 dropped support for Ubuntu Trusty which we need for the acceptance tests. For now this will unblock us from merging in PRs while a more complete solution can be investigated/developer (Potentially dropping PHP 5.5, manually including chrome binaries, etc)
Issue reference: #7848
See Travis.
=> Temporarily revert PHP 5.5 from the Travis build

include/Dashlets/DashletGeneric.php
=> Fix 'customMetadate' typo in DashletGeneric.php.

jssource/src_files/include/HTMLPurifier/standalone/HTMLPurifier/Printer/ConfigForm.js
This probably isn't necessary and can be removed?
Just make sure the tests pass in CI.
=> Remove HTMLPurifier ConfigForm.js file.

modules/AOW_WorkFlow/metadata/searchdefs.php
Added option to filter WFs by module name from 'Advanced Filter' tab
Easy way to filter by module name
1. Open Workflow list
2. Click on filter icon
3. Switch to "Advanced Filter" tab
4. New option to  filter by module name
=> #7817 fix(WorkFlow) - added option to filter WorkFlows by module name

modules/AOR_Reports/AOR_Report.php
The generated query adds a Group by TABLE.currency_id which happen only for non-usdollar fields
Do not generate GROUP BY currency_id for xxxusdollar fields
Create an opportunity in Dollars
Create an opportunity in Euros
Create a report for Opportunities with
- Sales Stage (check group)
- Amount (function Sum)
The generated report or charts will show sales stage for each currency
https://github.com/salesagility/SuiteCRM/issues/7784
Wrong group reports
=> Fix grouping by with xxx_usdollar currency fields

.github/SECURITY.md
Adds a security policy to SuiteCRM as per the GitHub [docs](https://help.github.com/en/articles/adding-a-security-policy-to-your-repository).
Issue reference: #7885
=> Fixed #7885 - Add a SECURITY.md to the repository

modules/Emails/EmailUI.php
Errors in User profile with French translation (quote)
Escape quote characters
#7917 
Load french translation
Go to User profile
Look at browser console and click Parameters
=> Fix issue with french translation

metadata/audit_templateMetaData.php
=> Fix typos in audit template metadata

modules/Project/controller.php
Changed if statement to use correct Business Hours field name
See #3129
Fixes hanging issue with adding task on gantt chart
See See #3129
=> Fix #3129 Use correct Business Hours field name for opening hours check

.gitattributes
Updated the .gitattributes export-ignore list with a few files I missed the last time around. The idea behind this is that you should be able to pull down the repository without getting unncessary "development" files that you wouldn't need in a production environment.
Download a .zip of this branch on [my fork](https://github.com/Dillon-Brown/SuiteCRM/tree/fix/gitattributes) and check that the files and directories referenced here are missing:
```
/tests export-ignore
/build export-ignore
/.github export-ignore
/.gitmodules export-ignore
/.gitignore export-ignore
/php_cs.xml export-ignore
/codacy.yml export-ignore
/codeception.dist.yml export-ignore
/.codecov.yml export-ignore
/.travis.yml export-ignore
travis.php.ini export-ignore
/.phpcs.xml export-ignore
/.gitattributes export-ignore …
```
=> Update the .gitattributes export-ignore list

modules/Administration/Async.php
see issue  #7955
fix a fatal php error
see the admin panel always displays
=> Fix #7955 - admin blank screen post upgrade to 7.11.8

modules/InboundEmail/InboundEmail.php
Fix typo referred to in issue #3860.
See issue #3860.
Look at file InboundEmail.php
=> Fix typo in InboundEmail.php

include/SugarLogger/LoggerManager.php
This change is purely to help the IDE pickup the magic method calls
for SugarLogger. While I was here I also reformatted the class and
fixed a few inspections.
Prevents "method not found" inspections.
No real way to test this except to check that the SugarLogger is still working. You could also check that your IDE picks up the @method tag correctly.
=> Updated LoggerManager to use @method + code cleanup

README.md
Fixed typos and made it grammatically better
Better readability and looks better + HacktoberFest + Trick or Suite Thursdays!
=> Fixed typos and made it grammatically better

include/templates/Template.php
Signed-off-by: Akshit Sarin <akshitsarin99@gmail.com>
• Corrected the tense - 'will be *remove* in 7.8' to 'will be *removed* in 7.8'
Corrected the tense of a verb [remove to removed]
Change is required to remove incorrect use of grammar in the code.
=> Fixed a grammatical error in include/templates/Template.php

modules/Administration/metadata/adminpaneldefs.php
Fixed missing icons in the admin panel.
Issue reference: #8025 
1. Go to admin panel.
2. Check that Oauth Keys and OAuth2 Clients and Tokens have icons.
=> Fixed #8025 - OAuth Keys & OAuth2 Clients and Tokens icons are missing

Api/V8/Service/UserService.php
Removed an unnecessary `include` statement from the UserService
See #7586 
This improves legibility of the code. 
Run the `GET /Api/V8/current-user` route before and after the PR is applied and ensure that you get the same results
=> Fixed #7586 - Unnecessary include in UserService

modules/AOR_Reports/AOR_Report.php, tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
see issue #7964
Fix report total formatting
See that report total format correctly when doing 'SUM' or 'Average' totals
=> Fix #7964 - Report Total Field formatting is inconsistent

include/Dashlets/DashletCacheBuilder.php
Add the ability to extend and override core dashlets.
- Add check for custom dashlet class and skip building cache fore core if found.
Previously unable to extend core dashlets.
- Extend the `MyAccountsDashlet` class with a class called `CustomMyAccountsDashlet` in `custom/modules/Accounts/Dashlets/MyAccountsDashlet/CustomMyAccountsDashlet.php`.
- Ensure that the `$dashletData` and `$dashletMeta` keys match the class name so in this case `CustomMyAccountsDashlet`.
- In `Admin > Repair` use the `Rebuild SuiteCRM Dashlets` button to rebuild the dashlet cache.
- Check that the custom class is loaded and the core is not.
=> Skip cache building if custom class exists for dashlets

modules/AM_ProjectTemplates/gantt.php, modules/Project/gantt.php
Fixed broken paths for the milestone image.
Issue Reference: #5709
=> Fixed paths to milestone image

Api/V8/Config/services/middlewares.php, Api/V8/OAuth2/Repository/RefreshTokenRepository.php
- Enable refresh token grant type.
- Include deleted records when revoking refresh token.
Fixes issue https://github.com/salesagility/SuiteCRM/issues/7397 where you cannot refresh tokens.
- Get a normal token and refresh token using `grant_type` of `password` .
- Make a POST call to the `access_token` endpoint with a body as below.
```
{
"grant_type": "refresh_token",
"client_id": "{{client_id}}",
"client_secret": "{{client_secret}}",
"refresh_token": "{{refresh_token}}"
}
```
=> Fix #7397 Implement Refresh Token Grant

tests/_support/Step/Acceptance/Calls.php, tests/_support/Step/Acceptance/InboundEmailTester.php, tests/_support/Step/Acceptance/ModuleBuilder.php, tests/_support/Step/Acceptance/Workflow.php, tests/acceptance/Core/CompanyModuleCest.php, tests/acceptance/modules/AOS_Products/AOS_ProductsCest.php, tests/acceptance/modules/Activities/ActivitiesCest.php, tests/acceptance/modules/Campaigns/CampaignsCest.php, tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Mostly PHPDocs and formatting improvements.
The main thing for this PR is to review the code changes and make sure the tests continue to pass.
=> Misc improvements to the acceptance tests.

include/UploadStream.php, jssource/minify_utils.php, lib/Robo/Plugin/Commands/TestEnvironmentCommands.php, modules/Administration/UpgradeWizard_prepare.php, modules/InboundEmail/InboundEmail.php, modules/UpgradeWizard/upgradeMetaHelper.php, modules/UpgradeWizard/uw_utils.php
Small change to ```mkdir``` to improve our error handling when it fails to make the directory.
No real way to easily test this, I guess you could intentionally cause mkdir to fail in one of these places and check that it handles it correctly. I would check that the upgrade wizard.
=> Updated mkdir calls to throw RuntimeExceptions

include/GoogleSync/GoogleSyncBase.php, include/GoogleSync/GoogleSyncHelper.php, tests/unit/phpunit/include/GoogleSync/GoogleSyncTest.php
Clears the sync data from the users records if the 'SuiteCRM' Google Calendar gets deleted. Then recreates the Google calendar and re-syncs it.
If the User doesn't have a Google calendar named 'SuiteCRM', then we clear all the sync data from the records to be synced before we create the Google calendar and sync. This prevents the system from breaking if the user deletes the 'SuiteCRM' Google Calendar. Without this fix, syncing will break in a way that requires SQL commands to resolve. With this fix, deleting the 'SuiteCRM' calendar will trigger that fix automatically, and prevent it from breaking in the future.
See issue #7312
Sync with your Google Calendar.
Find the 'SuiteCRM' calendar in your Google account and delete it.
On the next sync, a new 'SuiteCRM' calendar will be created with …
=> Fix for salesagility/SuiteCRM#7312

lib/Search/SearchResults.php
There is a missing `use` statement in `SearchResults.php`. This PR adds it. 
See #7969
Otherwise the whole thing fails and the user doesn't see any results
1. Create an invalid record (not sure if this should be done with vardefs or the db record. In my instance, all I had to do was to create a Case)
3. Set log level to `warn`
2. Configure and Index ES
3. Perform a search that would include your bad record
4. Before PR - no records shown. After PR - records shown and entry in log
=> Fix #7969 - Cannot call logger

lib/Search/ElasticSearch/ElasticSearchIndexer.php, lib/Search/ElasticSearch/ElasticSearchModuleDataPuller.php
Fixes: #7886 
This PR refactors the ElasticSearch Indexing process in order to paginate through the Sugarbeans rather than try to hold them all in memory at once. 
I decided to move this into a dedicated class in order to keep functions short and responsibilities tight. I also wanted to start to provide the means, if necessary, to customize the process on a per-module basis. 
I'm using the same batch size (1000) as what is being used to send data to ES. In my testing, this could probably be raised, but seems like a fairly reasonable starting point. 
I did have to change the logging slightly - and I am logging each time that it completes a chunk to ES.
On larger instances (100k+ records), the process of Indexing the records causes memory issues. The culprit is likely the `get_full_list` …
=> Fixed #7886 - Elasticsearch Indexing memory usage

modules/InboundEmail/InboundEmail.php
This was originally done in #8075 but was overridden by #8080.
@Dillon-Brown 👀
=> Fix a deprecated string concatenation.

README.md
Previously the contributors badge linked to the same image.
=> Link contributors badge to contributors insights

include/MVC/View/SugarView.php
Fixed an undefined index warning due to the global ```server_unique_key``` not being set. I've changed this to pull the value from the ```unique_key``` set in config as this matches what we do in the rest of the system.
Issue reference: #7764
Load any SugarView and check the log.
=> Fixed #7764 - Undefined index: server_unique_key

install/install_utils.php
For backwards compatibility reasons, we need to check for SUGARCRM so
that we can correctly replace it with the new SUITECRM restrictions.
1. Upgrade the CRM.
2. Check the ```.htacess``` has been correctly replaced.
=> Added a check for SUGARCRM restrictions in htaccess

modules/AOR_Reports/aor_utils.php
Fix  #8107 by using the fix suggested there - replace the `$dateCount` keys with the use of `$key`. This ensures that the date parameters work correctly
Needed to fix #8107 - otherwise date parameters can't be updated in some situations.
Create a new calls report
Create a parameter for status set to anything
Create two date parameters on start date
Be sure to use the "Date" type with, for example "Now + 12 months"
Set the second date parameter to something similar but distinct
Save the report and click update on the parameters
Examine the updated date parameters - the first will be empty and the second will have taken the firsts settings before this fix and will display correctly afterwards.
=> Fix multiple date parameters in reports

include/SugarFields/Fields/Datetime/DetailView.tpl
see issue #7997 
DateTime caching issue
see how to replicate on issue #7997
=> Fix #7997 - Datetime field caching issue

include/TimeDate.php, modules/ACLActions/ACLAction.php, tests/api/V8/GetModulesMetaCest.php
This was happening due to trying to use $this in static methods. While here I also cleaned up some inspections.
See Travis.
=> Fixed ACLAction Travis failure

include/language/en_us.lang.php
'LBL_LOGIN_AS' - Removed String
'LBL_LOGOUT_AS' - Removed String
https://github.com/salesagility/SuiteCRM/issues/6314
Check that labels are not being used elsewhere.
=> FIXED #6314 - [language] Unused language strings (logout & login)

modules/AM_TaskTemplates/vardefs.php
Change length of milestone_flag to 1 as data type is boolean
When using ms database am_tasktemplate changes do not execute after repair and rebuild
See #6001, #5199 and #2586
Using ms db, after running repair and rebuild, it should execute normally
=> Fix issue #6001

modules/AOR_Reports/AOR_Report_Before.js
Fix issue #8108 
See issue #8108
=> Fix #8109 - Reports Incorrect Module path

ModuleInstall/PackageManager/PackageController.php, include/Dashlets/Dashlet.php, include/ListView/ListView.php, include/ListView/ListViewSubPanel.php, include/MVC/View/views/view.metadata.php, include/SugarEmailAddress/SugarEmailAddress.php, include/javascript/tiny_mce/plugins/autosave/editor_plugin_src.js, include/javascript/tiny_mce/plugins/paste/editor_plugin_src.js, include/utils/sugar_file_utils.php, modules/Administration/SyncInboundEmailAccounts.php, modules/Campaigns/WizardEmailSetup.php, modules/Emails/include/ListView/ListViewDataEmails.php, modules/Import/views/view.step3.php, modules/Schedulers/Scheduler.php, service/core/SugarRestServiceImpl.php, service/core/SugarWebServiceImpl.php, service/core/webservice.php, service/v2_1/SugarWebServiceImplv2_1.php, service/v3/SugarWebServiceImplv3.php, service/v3_1/SugarWebServiceImplv3_1.php, service/v4/SugarWebServiceImplv4.php, soap/SoapDeprecated.php, soap/SoapHelperFunctions.php, soap/SoapRelationshipHelper.php, soap/SoapSugarUsers.php, tests/api/v8/ModulesCest.php
=> Fix typos and improve grammar

modules/AOW_Actions/actionLines.php
see #8173
see #8173
See workflow action appear in edit and detail view
=> Fix #8173 - Workflow actions missing in edit and detail view

modules/AOR_Scheduled_Reports/AOR_Scheduled_Reports.php
Added new function to convert the next run and current time before comparison so scheduled reports execute in the timezone specified in the config with: $sugar_config['default_timezone']
https://github.com/salesagility/SuiteCRM/pull/8179
Set $sugar_config['default_timezone'] = 'inset php timezone' in config override
Set scheduled report to run at specified time
It should execute at the correct time
=> Fix for Issue #7305 hotfix-7.10.x branch

modules/ACLActions/ACLAction.php
This fixes a strict comparison in ACLAction breaking the group ACL role permissions.
*This will be merged directly into master for the next release and then merged back into the hotfix branches.
Issue reference: #8183
Assign a user a role with Group only access to List. Log in as the user and the user will not be able to view non-group records on the list view (assuming data is set up correctly).
=> Fixed #8183 - non-group records show on list view if group only access

install/performSetup.php, modules/ACLRoles/DetailView.php, modules/Emails/Email.php, modules/InboundEmail/InboundEmail.php, tests/unit/phpunit/modules/ACLRoles/ACLRoleTest.php
I've added the role repair to the end of the installation wizard (This has already been done for the upgrade module, silent upgrade, etc).
Before this fix, you would have to run the role repair in order to see this module.
1. Install a fresh instance of the CRM from this branch.
2. Check that the employee module is visible in the ACL role menu list.
=> Fixed employees module not appearing in ACL role list

modules/Administration/metadata/adminpaneldefs.php
Fixes salesagility/SuiteCRM#8203
Thanks to @ApatheticCosmos for the fix
=> Repair Administration section & Google Calendar settings menu option

modules/ACLActions/ACLAction.php
Duplicate of #8201 for the 7.11.x branch.
=> Fixed #8178 - 7.11.9 Employee role control is lost, invalid

tests/unit/phpunit/modules/EmailMarketing/EmailMarketingTest.php, tests/unit/phpunit/modules/Employees/EmployeeTest.php, tests/unit/phpunit/modules/Groups/GroupTest.php, tests/unit/phpunit/modules/Roles/RoleTest.php, tests/unit/phpunit/modules/UserPreferences/UserPreferenceTest.php, tests/unit/phpunit/modules/Users/UserTest.php, tests/unit/phpunit/modules/jjwg_Address_Cache/jjwg_Address_CacheTest.php
Cleaning up tests. These shouldn't overlap with the changes in other PRs I've opened today, so it should be relatively safe to merge.
These tests had a bunch of unnecessary white space, typos, etc.
Cleaning up some code.
=> Clean up misc unit tests

include/TimeDate.php, tests/unit/phpunit/include/TimeDateTest.php
This was already somewhat tested by its usage by other pieces of code that _are_ tested, but this adds actual unit tests for the functionality directly.
Test coverage :)
Make sure the tests pass in CI.
Tests :)
=> Add tests for TimeDate class.

include/utils.php
This function is unused, so I've deprecated it.
No need for dead code.
Make sure the code is indeed unused.
Technical debt.
=> Add PHPDoc and deprecate unTranslateNum.

modules/Activities/EmailReminder.php
Fixed an issue with email reminders calling a non-existing function causing a PHP fatal.
Issue reference: #6990
Issue reference: #8277
Check that email notifications send correctly.
=> Fixed #6990 - Run Email Notification not working

tests/unit/phpunit/include/TimeDateTest.php
Adds a few more tests to `TimeDateTest.php`. This is building on top of the PR I opened last week, #8300.
More test coverage :)
Make sure CI passes.
Tests
=> Add more TimeDate tests

include/ListView/ListViewPagination.tpl, themes/SuiteP/include/ListView/ListViewPagination.tpl, themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl, themes/SuiteP/include/ListView/ListViewPaginationTop.tpl
We add a way to hide/show columnChooser in ListViews. 
By default the columnSelector is shown:
If in `config_override.php` you add an entry like this one:
```php
$sugar_config['hideColumnFilter'] = [
'Accounts' => true,
];
```
The columnChooser is hidden:
If you have a custom view.list.php where you assign to the template a value to `hideColumnFilter` like this:
`$this->lv->ss->assign('hideColumnFilter', 1);`
This will prevail over the settings in `config_override.php`
Read #8099 
1. Add a config like this one in `config_override.php`
```php
$sugar_config['hideColumnFilter'] = [
'Accounts' => false,
];
```
2. Verify the columnChooser is hidden
=> FIX #8099 - Add a way to hide/show columnChooser in ListViews

include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
This commit adds a check on the selected e-mail client: "External" vs "SuiteCRM"
=> Provides fix for #8273

include/MassUpdate.php
Fix Issue https://github.com/salesagility/SuiteCRM/issues/8351 more detail in the Issue
=> Fix #835 datepicker missing in massupdate for custom datetime field type

Api/V8/Service/ModuleService.php
Email1 field now gets populated through API with the primary email.
1. Call Accounts and scroll down to the relationship array and find EmailAddresses
or
2. Call a specific Account and scroll down to the relationship array and find EmailAddresses
=> Email1 field now gets populated through API

Api/Core/Config/ApiConfig.php, Api/V8/Helper/VarDefHelper.php, include/SugarObjects/templates/company/vardefs.php, include/SugarObjects/templates/person/vardefs.php, modules/Accounts/vardefs.php, modules/Leads/vardefs.php, modules/Prospects/vardefs.php
The API now returns the Relationship link of EmailAddresses.
1. Call Accounts and scroll down to the relationship array and find EmailAddresses
or 
1. Call a specific Account and scroll down to the relationship array and find EmailAddresses
=> API returns the emailAddress Relationship link

tests/unit/phpunit/include/TimeDateTest.php
Pretty self-explanatory. Added tests for `TimeDate`'s `splitTime()` function
Test coverage is good.
Make sure CI passes.
Tests
=> Add tests for splitTime() on TimeDate.

include/utils.php
Please see Issue #2464
Another user recently confirmed in the forums that this works
https://suitecrm.com/suitecrm/forum/suite-themes/27994-unable-to-replace-logo-with-png-extension#92257
=> Fix #2464 - logo upload

include/Localization/Localization.php, modules/Schedulers/Scheduler.php, tests/unit/phpunit/include/utils/autoloaderTest.php
Improve formatting for some code. Replacing some tabs with spaces, adding spaces where there weren't any, etc.
We should really add a linter.
Clean up some code.
Technical debt.
=> Misc code formatting improvements

.travis.yml, modules/Administration/metadata/adminpaneldefs.php
Fixes an issue with missing search settings should under the Administration panel.
1. Go to admin panel -> search settings.
2. Check everything works as expected.
=> Fixed #8246 - Search settings disappeared from Admin after upgrade 7.11.9 -> 7.11.10

modules/Administration/AOSAdmin.php, modules/Administration/AOSAdmin.tpl
Change field type to number and remove int check
Fix issue with aos settings not changing.
Changed field type to 'number' and removed int check validation
see #8421
see #8421
=> Fix issue with validation on aos settings #8421

include/Zend_Oauth_Provider.php
Fixed missing zend references which are now kept in vendor.
Test Zend still works as expected.
=> Fixed zend composer autoloading

Api/V8/Service/ModuleService.php, modules/Notes/language/en_us.lang.php, modules/Notes/vardefs.php
To add functionality allowing for file attachment of notes via the V8 API. 
This allows file attachment of notes via the API. It requires use of the filename (which should include file extension) and filecontents (which should be base64 encoded) parameters in the API request. Other than these two parameters it should work the same as any other insert or update API call.
Currently this is not possible via the API.
This can be tested by created API calls to create, update and delete a note. For the create and update calls, you should include the filename and filecontents parameters (ensure these are the right format as stated above). Ensure that the file is added/changed to the record in the CRM and also check the record is correct in the upload directory (the name in this directory should …
=> Add functionality allowing for file attachment of notes via the V8 API. 

install/installConfig.php
Adding the Advanced DB options to the original More Options list and fixing layout issues with the install page.
It improves the layout of the install page.
Go through the installation process, ensure that all install pages display correctly (specifically that the white border round the text covers the full list of options). Ensure that you can install as expected.
=> Fix install layout db options

include/Zend_Oauth_Provider.php
Fixed missing imports breaking Oauth.
```
[Wed Dec 25 11:36:24.730796 2019] [php7:error] [pid xxxx] [client xxxx:xxxx] PHP Fatal error:  Uncaught Error: Class 'SuiteCRM\\Zend_Uri_Http' not found in /var/www/html/crm/include/Zend_Oauth_Provider.php:266\nStack trace:\n#0 /var/www/html/crm/include/Zend_Oauth_Provider.php(288): SuiteCRM\\Zend_Oauth_Provider->getRequestUrl()\n#1 /var/www/html/crm/include/SugarOAuthServer.php(175): SuiteCRM\\Zend_Oauth_Provider->checkOAuthRequest(NULL, Array)\n#2 /var/www/html/crm/service/v4/SugarWebServiceUtilv4.php(489): SugarOAuthServer->__construct()\n#3 /var/www/html/crm/service/v4/SugarWebServiceUtilv4.php(477): SugarWebServiceUtilv4->checkOAuthAccess(Object(SoapError))\n#4 /var/www/html/crm/service/v4/SugarWebServiceImplv4.php(672): …
```
=> Fixed #8406 - Oauth not working in suitecrm 7.11.10

tests/SuiteCRM/Test/Driver/WebDriver.php, tests/_support/AcceptanceTester.php, tests/_support/Step/Acceptance/ModuleBuilder.php
- Fixes/Avoids WebDriver Timeout by waiting 1s and using some JS to check for element instead of the `waitForElementVisible` function. 
- Reduces timeouts by overriding 3 methods, setting defaults to 3s (generous still) and updates signatures.
- Intermittent Timeouts on the popup close for create/save new module tests in ModuleBuilder.
- Default 10s timeouts.
- Look at the travis builds and restart them as many times as you see fit.
- Merge this PR.
- Make a PR ;)
- Look at the travis builds across the board.
=> Fix/Avoid WebDriver Timeouts in Travis createModule Tests

themes/SuiteP/css/Day/variables.scss, themes/SuiteP/css/Dusk/variables.scss
Fixing typo in separator as failing css build.
=> Fixing typo in seperator/separator change

include/database/MysqlManager.php, include/database/MysqliManager.php
=> Fix #8541 - MySQL Database breaking on special characters

include/Localization/Localization.php, include/utils.php, install/installConfig.php, install/install_utils.php, modules/Administration/Locale.tpl, modules/Configurator/tpls/adminwizard.tpl, modules/Currencies/Currency.php, modules/Import/tpls/confirm.tpl, modules/Import/views/view.confirm.php, modules/Users/UserViewHelper.php, modules/Users/tpls/EditViewFooter.tpl, modules/Users/tpls/wizard.tpl, modules/Users/views/view.wizard.php, modules/jjwg_Markers/views/view.marker_edit_map.php, service/v3_1/SugarWebServiceImplv3_1.php, service/v4/SugarWebServiceImplv4.php, tests/travis_config_si.php
Changing config value for number separators may needlessly have impact on third and custom code
=> Roll back backward incompatible config change

include/HtmlSanitizer.php
`SugarBean->cleanBean` is a performance bottleneck. It is used to clean string values and calls `HtmlSanitizer::cleanHtml` each time, which instantiates itself, invoking a beefy constructor. 
Let's forget the fact it's instantiating itself from within a static method for now. This can and should be used as a singleton which should greatly improve speed of save operations. Ideally these classes need some serious refactoring and re-design.
Should help to address performance issues detailed in #8416.
1. Save a bean and note execution time.
1. Apply fix, re-save same bean and note execution time.
=> Clean Bean Speed

include/SugarDateTime.php, tests/unit/phpunit/include/SugarDateTimeTest.php
This covers a few of the methods in the class. I left out any that weren't in active use within the codebase. This doesn't cover all used methods, though.
The deprecated functions are either no longer necessary because they're implemented in the core PHP language or because they're unused in the codebase.
Some of it is internal, so I'm not sure if we even need to deprecate it?
More test coverage, deprecate unnecessary code.
Make sure the unit tests pass.
Adds some unit tests and deprecate unused functions.
=> Add tests for SugarDateTime and deprecate useless functions in it.

modules/AOW_WorkFlow/aow_utils.php
Add editview check to stop cacheing issues for dates on aow conditions
User cannot add to date fields on aow conditions
See #6676
=> Fix issue #6676

include/SugarFields/Fields/Time/SugarFieldTime.php
The function declaration of SugarFieldTime::save() deviated from the overridden
function in the parent class SugarFieldBase.
Only the parameter $bean should be passed by reference to this function.
1. In the Admin panel navigate to "Scheduler"
2. Edit a Scheduler job
3. Save the job
4. Check Apache error log for messages like
```
PHP Warning:  Declaration of SugarFieldTime::save(&$bean, &$inputData, &$field, &$def, $prefix = '')
should be compatible with SugarFieldBase::save(&$bean, $params, $field, $properties, $prefix = '')
in /var/www/html/suitecrm/include/SugarFields/Fields/Time/SugarFieldTime.php
```
After applying this PR this message should not appear anymore.
=> Fix function declaration of SugarFieldTime::save()

.travis.yml
Small fix to remove ```sudo: required``` as it's been deprecated.
See Travis.
=> Remove deprecated sudo from .travis.yml

modules/ModuleBuilder/parsers/views/GridLayoutMetaDataParser.php
Issue reference: #8450
Don't use array_keys() twice and fix typo in variable name '$panelId'.
In the function GridLayoutMetaDataParser::addField() the code for determining
the ID of the first panel in a view is broken.
1. Add a "One to Many" or "One to One" relationship to another module using Studio.
For testing it's best to use a custom module, since most core modules already have relationships to more or less all other core modules
2. Hit "Save & Deploy"
3. In Studio navigate to the "Edit View" layout of the target module of the relationship
4. Before applying this PR the related field - that has the name of the source module of the relationship as label -  should be listed in the list of available fields instead of already being part of the layout.  
After applying this PR the related …
=> Fixed #8450 - Minor bug in GridLayoutMetaDataParser::addField()

modules/Campaigns/WizardNewsletter.php
strip out entries for email and newsletter does not work for non-english speaking users
Use keys of campaign type instead of translation of values
strip out entries for email and newsletter does not work for non-english speaking users
Login in a language other than english.
Create a campaign
Chose Non based on emails
Look at the type dropdown
Emails and Newsletters are no longer visible
=> Fix issue for non based on Emails Campaigns

include/utils.php
expected  'Customer','Prospect'
but returns 'Customer\\',\\'Prospect'
because $ db->quote is applied twice if strpos($args[$i], ',') !== false, leading to a wrong result
Also, $enable = false leads to an error as $db is not defined in that case
Search with query_type 'format' and subquery with a multiple selection
=> fix string_format

modules/Administration/DiagnosticRun.php
Added Download link
Remove duplicated Download link
- run Diagnostic.
- The Download link is displayed twice
Diagnostic file cannot be deleted
Duplicate Download link
=> Download link displayed twice. No Delete link in Diagnostic

themes/SuiteP/css/suitep-base/navbar.scss
This correct the fix #7822 for issue #7821 to work for all screen sizes
Compile the SuiteP theme and see that the top menu is now in alignment for all screen sizes
=> Fix Username alignment in all screen widths

modules/AOR_Reports/AOR_Report.php
=> Fix #8643 - Reports do not work related module custom fields

include/SubPanel/SubPanelTiles.php, include/TemplateHandler/TemplateHandler.php, service/JsonRPCServer/JsonRPCServer.php
Fix a few notices and warnings stemming from invalid array indexes and passing non-array values to `array_map`.
Also fixes an issue where a notice causes a returned JSON response to be invalid.
Different ways to trigger each of these.
Enable:
```
ini_set('display_errors', 1);
error_reporting(E_ALL);
```
1. Enable displaying all errors like above
2. As a non-admin user, create a report, then visit report detail view
3. Create a meeting, then try adding a User to the meeting via search function
=> Fix PHP notices & warnings

Api/Core/Config/ApiConfig.php, Api/V8/Config/services/middlewares.php, include/utils.php, install/install_utils.php, install/language/en_us.lang.php, install/performSetup.php, lib/Robo/Plugin/Commands/ApiCommands.php, modules/Administration/QuickRepairAndRebuild.php
Store the OAuth2 Encryption Key in `config.php` instead of `Api/Core/Config/ApiConfig.php`.
Currently this is done by changing/rewriting a core file
(`Api/Core/Config/ApiConfig.php`) in order to store the OAuth2 Encryption Key (ApiConfig::OAUTH2_ENCRYPTION_KEY).
Plus this is done in four different places - each one containing duplicated code.
IMHO it is much better to move this config value into the appropriate file
and also reduce duplicated code.
Another effect of this modification is that `Api/Core/Config/ApiConfig.php`
with a custom OAuth2 key won't accidently end up in a commit because the file has been changed.
E.g. run the CI tests.
=> FEATURE Move OAuth2 Encryption Key into config.php

data/SugarBean.php
Fix missing query offset in SugarBean::get_linked_beans().
Related (aka linked) Beans cannot be retrieved by using an offset + limit.
Sample code:
```
$BEANS_PER_REQUEST = 10;
$bean = new \Account();
$bean->retrieve("some-id");
$lnkRs = "contacts";
$bean->load_relationship($lnkRs);
for ($curIx = 0; ; $curIx += $BEANS_PER_REQUEST) {
$relatedBeanList = $bean->get_linked_beans($lnkRs, "", "", $curIx, $curIx + $BEANS_PER_REQUEST);
foreach ($relatedBeanList as $relatedBean) {
// do something with the related bean
}
if (count($relatedBeanList) != $BEANS_PER_REQUEST) {
break;
}
}
```
=> Fix missing query offset in SugarBean::get_linked_beans()

include/MVC/View/SugarView.php, include/globalControlLinks.php, themes/SuiteP/tpls/_headerModuleList.tpl
Fix for global support forum link.
1. Check that the link still takes you to community forums.
=> Fix user action menu support link

modules/AOR_Reports/AOR_Report.js
SuiteCRM 7.10.25
Multi `One of` condition not working on report due to incorrect checking of elements.
https://github.com/salesagility/SuiteCRM/issues/8645
=> AOR_Report - Fix Multi condition not working

modules/Contacts/Contact.php
DBManager::concat is not defined as static.
It generates a PHP error:
Call to undefined method Contact::quoted() in XXX/include/database/DBManager.php on line 1818
#8738 
Go to http://demo.suiteondemand.com
Open an Account
Click on Copy to copy account address to contacts
A blank popup opens.
The log shows: 
Call to undefined method Contact::quoted() in XXX/include/database/DBManager.php on line 1818
=> Fix #8738: Copy button in Account does not work

modules/UpgradeWizard/systemCheck.php, modules/UpgradeWizard/uw_utils.php
=> Fix #8637 - Upgrade Wizard fatal error after upgrade on windows

include/TimeDate.php
See issue #8757 
See issue #8757
=> Fix 8757 - time format preference  typo

include/SugarTinyMCE.php, modules/Cases/views/view.edit.php
Fix Case description field fails to save
Follow up to #8755
@QuickCRM & @ftoledo thanks for the quick feedback
=> fix Case description field fails to save

Api/Core/app.php
=> Fix V8 api delete cors issues

modules/AOR_Charts/AOR_Chart.php
This is a duplicate of #6636. 
In a Stacked Bar chart, the current code does not aggregate the chart totals properly. This PR fixes the issue by using the correct operator. 
Although we solved the problem independently, I appreciate @g-fantini for submitting a solution. It's a real shame that it wasn't merged in _years_ ago. 
Currently a Stacked bar chart only shows the value for the latest record in the set. 
While looping and organizing the data, the current code assigns a value that really should be summed. Because it's in a loop, only the last value is preserved and pushed to the chart. 
A common use case in CRM is to view Opportunities by Date (monthly or quarterly) and Status. You could do this with a report on the Opportunities module. You would group by Status. On the Chart, you …
=> Fixed #6427 - Stacked Bar chart totals incorrect

data/BeanFactory.php
=> Fix #8795 - Change log level to warn loading non existing Bean

README.md
Removing the old and removed CLA hub opting for a bot via PRs. Testing the success this.
Missing CLA agreement
Don't SuiteCRM team are on it. :+1:
=> removing old CLA url

modules/Emails/Save.php
Removes some dubious code which causes relationships to be deleted when saving an archived email
Fixes #8535
1. Navigate to an archived email with a To address (or create one first by composing a new email, for example from a subpanel)
2. Click Edit
3. Change nothing, click Save
4. See the To address is still visible
=> Fix Email To field being deleted on save

include/ListView/ListViewSubPanel.php, include/SubPanel/SubPanelTiles.php, include/SubPanel/tpls/SubPanelCheckbox.tpl, include/javascript/checkbox.js, modules/Contacts/metadata/subpanels/FP_events_subpanel_fp_events_contacts.php, modules/Delegates/metadata/subpaneldefs.php, modules/FP_events/metadata/subpaneldefs.php, modules/Leads/metadata/subpanels/FP_events_subpanel_fp_events_leads_1.php, modules/Prospects/metadata/subpanels/FP_events_subpanel_fp_events_prospects_1.php
Fixes an issue where the select all / select page checkbox doesn't work on Event Delegates subpanel.
Fixes #4560 
1. Create an Event
2. Add enough records to the Delegates subpanel so that it gets paginated into multiple pages
3. Use the checkbox to select all, or select this page
4. User Manage Delegates or Manage Acceptances to apply changes
5. See the changes are applied to all relevant records
=> Fix Delegates Select All

include/SubPanel/SubPanelDefinitions.php, modules/ACLRoles/EditView.php, modules/MySettings/StoreQuery.php
Fixes a few PHP notices
Removing PHP notices helps finding actual issues.
---
1. Enable PHP notices on your instance, set error reporting to `E_ALL`
---
2. Go to Admin, Role Management, Edit any Role
3. See no PHP notice
---
2. Go to User Profile, External Layouts tab
3. See no PHP notice
---
2. Go to any module Listview (Contacts)
3. Add a filter (name = abc)
4. Click on the small red cross to clear the filter
5. See no PHP notice
=> Fix PHP notices

.travis.yml
Travis fails on when using composer 2
=> Fix Travis fails on composer 2

data/Relationships/One2OneBeanRelationship.php
Report query fail as it build an invalid query when using a one 2 one relationship
=> Report Join fails when using one 2 one relationships 

modules/AOS_PDF_Templates/views/view.edit.php
Fix #4435 issue where Pagebreaks in TinyMCE simply did not work
See Issue
=> Fix #4435 TinyMCE pagebreaks

ModuleInstall/ModuleInstaller.php
Fix uninitialized variable $modules in ModuleInstaller::install_languages().
and ModuleInstaller::uninstall_languages().
Fix uninitialized variables $languages and $modules in ModuleInstaller::enable_languages().
Uninitialized variables are no good.
Install/Uninstall a module using the Module Loader.
=> Fix uninitialized variables in ModuleInstaller functions

include/Imap/ImapHandler.php
Office365 does not support charsets other than US-ASCII, PHP does not throw exception for BADCHARSET which means you will get no search results back at all but instead a literal FALSE.
- This patch will in that event check the last error message and switch to US-ASCII for the rest of the session.
=> Fix issues with IMAP InboundEmail

modules/AOR_Reports/aor_utils.php
=> Fix for #8391 Yesterday period option in reports show correct time

download.php
See issue #8918
Fixes regression caused by #8830. My apologies.
Add image fields to views and see if they display.
Possible variations for tests:
- core modules and custom modules
- core photo fields vs custom photo fields
- records that have non GUID ids which include underscores, one or more
- image field names that have underscores in them
=> Fix #8918 regression with image fields

modules/Employees/EmployeeStatus.php
Employee Status field is always empty on reports
1. Create a report based on Users
2. Add Last name, Status and Employee Status
3. The employee status is empty
=> Bug fix: Cannot report Employee Status

modules/Project/js/custom_project.js
Form Action is set to Delete even if the user click cancel when asked to confirm deletion
=> Form action should not be changed if delete is not confirmed

modules/Home/language/en_us.lang.php
Add missing labels to home module
Add missing labels to home module for dashlets and popup on record deletion 
See #8894
See #8894
=> Fix issue #8894 and similar issue with missing label calendar dashlet

modules/Home/language/en_us.lang.php
Adding on from Jack's fix -> https://github.com/salesagility/SuiteCRM/pull/9003
Add calendar dashlet to home screen .
Create task.
go back to home screen click on the task on the calendar dasklet and see there is a 'View task' button.
=> fix issue missing 'view task' label 

Api/V8/Service/ModuleService.php, modules/Documents/vardefs.php
Makes changes to the API to allow for similar functionality from notes to be used within documents.
Resolves Issue #8494 
Using postman attempt to post the following;
```
{
"data": {
"type": "Documents",
"attributes": {
"filename":"test.txt",
"document_name":"test.txt",
"filecontents": "VGhpcyBpcyBhIHRleHQgZmlsZQ=="
}
}
}
```
=> Update the V8 Api to allow for upload of documents similar to notes

modules/Administration/BusinessHours.php, modules/Administration/BusinessHours.tpl
Store days keys instead of days labels in business hours table.
Fix Issue #9034
=> Fix #9034 : Business Hours do not work in non-english language

composer.json, composer.lock
Change post install script of _google/apiclient_ library to use proposed script from library documentation: https://github.com/googleapis/google-api-php-client#composer
I spent half-day to understand, why Google Sheets doesn't connects to our-company СRM. I tried to do like write in library docs. And realized, that this action has white by simple commands.
All Google services should be deleted at library folder inside vendor.
=> Change config of "google/apiclient" dependency at composer.json

themes/SuiteP/css/suitep-base/navbar.scss, themes/SuiteP/tpls/_headerModuleList.tpl
Fixes the user menu alignment.
1. Rebuild SASS.
2. Check the user menu alignment changes.
3. Check in chrome and firefox.
=> Fix user menu alignment

Api/V8/BeanDecorator/BeanManager.php, Api/V8/Config/services/services.php, Api/V8/Controller/RelationshipController.php, Api/V8/JsonApi/Repository/Filter.php, Api/V8/Param/GetRelationshipParams.php, Api/V8/Param/Options/Filter.php, Api/V8/Param/Options/Sort.php, Api/V8/Service/RelationshipService.php
- Updated the core API to support pagination and filter in relationship calls
- Add Relationship Beans in V8 API Response
- Add filters in relationship API
- Add Additional API filter option `like`
*Note Added a small PHP 5.6 compatibility fix to remove the ```String``` type-hint on the ```getLinkedFieldBean``` method. Instead changing it to be ```string``` in the DocBloc. Otherwise, it will expect: ```Api\V8\BeanDecorator\String```.
- Using the V8 API, test filtering, relationships and the new API filter option `like`.
=> Implement additional API filtering

lib/Search/UI/SearchThrowableHandler.php
Fix misspelled errors for elasticsearch #8916.
Changed the Misspelled labels.
Allows users to see errors.
Closes #8916.
Run elasticsearch with a bad query, and you will see a valid message.
=> Fix misspelled elasticsearch labels

Api/V8/Helper/ModuleListProvider.php, ModuleInstall/PackageManager/ListViewPackages.php, ModuleInstall/PackageManager/PackageManagerDownloader.php, data/Link2.php, data/Relationships/EmailAddressRelationship.php, data/Relationships/M2MRelationship.php, data/Relationships/One2MBeanRelationship.php, data/Relationships/One2MRelationship.php, data/Relationships/One2OneBeanRelationship.php, data/Relationships/One2OneRelationship.php, data/Relationships/RelationshipFactory.php, data/Relationships/SugarRelationship.php, data/SugarBean.php, include/EditView/SubpanelQuickCreate.php, include/database/MssqlManager.php, include/database/MysqlManager.php, include/export_utils.php, include/externalAPI/Base/ExternalAPIBase.php, include/generic/SugarWidgets/SugarWidgetFieldcurrency.php, modules/Administration/Administration.php
The type should always go before the variable name and the variable name should start with a `$`.
Just cleaning up the code.
Review the code and make sure none of the changes look wrong.
Code cleanup.
=> Fix miscellaneous PHPDocs

modules/SecurityGroups/MassAssign.php, modules/SecurityGroups/language/en_us.lang.php
Make $_SESSION['export_where'] digest to be sending in request from "Security Groups: Mass Assign" panel.
Credit to @eapunk
When fixed, error message will be shown, group relationships will not be modified.
=> Prevent securitygroups mass assign damage

lib/Search/UI/SearchResultsController.php
- Fixed an issue where LangText was throwing an exception if there were any missing keys. As ElasticSearch is indexing potentially every module, there could be many missing keys that we need to log but not die on so the user can continue to see ElasticSearch results.
1. Index ElasticSearch
=> Fix LangText exception breaking ElasticSearch

modules/Administration/repairDatabase.php
- Updated quick repair and rebuild to check that ElasticSearch is enabled before running an index repair.
Previously elastic search was attempting to repair the index when running a general repair and rebuild. This was happening even with elastic search disabled which caused a fatal error.
Issue reference: #7772 
1. Disable elastic search, empty the config for elasticsearch
2. Have a database with a slightly different schema than defined in vardefs
3. Go to Quick repair&rebuild
4. When there is a SQL to execute at the end, press "execute"
5. Watch the error.log and suitecrm.log
=> Fix #7772 - Quick repair&rebuild, execute DB-Query gives Elastic search error

modules/AOD_Index/AOD_Index.php, modules/AOD_Index/AOD_Index_sugar.php, modules/AOD_Index/AOD_LogicHooks.php, modules/AOD_Index/LuceneUtils.php, modules/AOD_Index/PdfParser.php, modules/AOD_Index/controller.php, modules/AOD_Index/views/view.indexdata.php, modules/AOD_IndexEvent/AOD_IndexEvent.php, modules/AOD_IndexEvent/AOD_IndexEvent_sugar.php, modules/Schedulers/_AddJobsHere.php
- Deprecated ```AOD_Index``` and ```AOD_IndexEvent``` modules.
- Added a deprecation log that will trigger only on an index event (To avoid log spam).
- Deprecated ```PdfParser```, this is only used in one place by ```AOD_Index``` and there are other options to parse PDFs in core.
1. Enable AOD
2. Check that the index event logs a deprecation notice.
=> Deprecate AOD (Lucene)

include/utils.php
1. Check Travis
2. Sanity check commits.
=> Merge hotfix-7.10.x -> hotfix

Api/V8/JsonApi/Repository/Filter.php
Allow custom fields filter on API
Fixes bug https://github.com/salesagility/SuiteCRM/issues/7285
Fixing the bug
Use Get Modules API (V8) - with filter of non-custom fields and of custom fields (steps to reproduce found on the issue)
=> #7285: allow filter of custom fields on V8 API Get Modules

composer.json, composer.lock
- Bumped platform and require PHP version to 7.3.0
- A full regression test is required here.
=> Update minimum required PHP to v7.3.0

include/utils.php
Updated the install utils to include a few missing defaults, namely:
```
$sugar_config['default_module_favicon'] = false;
$sugar_config['dashlet_auto_refresh_min'] = '30';
$sugar_config['stack_trace_errors'] = false;
$sugar_config['developerMode'] = false;
$sugar_config['stackTrace'] = false;
```
These will now be included in the config for new installs instead of populating the ```config_override```.
1. Complete a fresh install.
2. See that the ```config_override.php``` file has been created but contains no values.
3. Go to the admin panel -> system settings and save.
4. See that the ```config_override.php``` still contains no values.
=> Fix missing default config values

modules/AOS_PDF_Templates/PDF_Lib/classes/bmp.php, modules/AOS_PDF_Templates/PDF_Lib/classes/cssmgr.php, modules/AOS_PDF_Templates/PDF_Lib/classes/directw.php, modules/AOS_PDF_Templates/PDF_Lib/classes/form.php, modules/AOS_PDF_Templates/PDF_Lib/classes/gif.php, modules/AOS_PDF_Templates/PDF_Lib/classes/grad.php, modules/AOS_PDF_Templates/PDF_Lib/classes/indic.php, modules/AOS_PDF_Templates/PDF_Lib/classes/svg.php, modules/AOS_PDF_Templates/PDF_Lib/classes/tocontents.php, modules/AOS_PDF_Templates/PDF_Lib/classes/ttfontsuni.php, modules/AOS_PDF_Templates/PDF_Lib/classes/wmf.php, modules/AOS_PDF_Templates/PDF_Lib/mpdf.php, modules/AOS_PDF_Templates/PDF_Lib/mpdfi/fpdi_pdf_parser.php, modules/AOS_PDF_Templates/PDF_Lib/mpdfi/pdf_context.php, modules/AOS_PDF_Templates/PDF_Lib/mpdfi/pdf_parser.php
- Fixed duplicate class properties and constructor syntax issues throughout PDF_Lib that were introduced by an old-style PHP constructor fix PR. I don't expect any of this PDF_Lib code to be in 7.12.x so this should be fairly low risk, we only really need these classes as a reference for building an interface.
1. Check that MPDF works as expected.
=> Fix PDF_Lib constructors

include/language/en_us.lang.php
It is impossible to search campaigns of type Survey
Add Survey in campaign types
=> Allow filtering Survey campaigns

.gitignore, lib/PDF/Exceptions/PDFEngineNotFoundException.php, lib/PDF/Exceptions/PDFException.php, lib/PDF/MPDF/MPDFEngine.php, lib/PDF/PDFEngine.php, lib/PDF/PDFWrapper.php, modules/AOR_Reports/controller.php, modules/AOS_PDF_Templates/formLetterPdf.php, modules/AOS_PDF_Templates/generatePdf.php, tests/unit/phpunit/lib/PDF/MPDF/MPDFEngineTest.php, tests/unit/phpunit/lib/PDF/PDFWrapperTest.php
- Branched from #9188.
- Implemented base PDF engine ```lib/PDF```.
- Refactored old mPDF calls to use new ```PDFWrapper```.
- Removed the old method of setting the ```error_reporting``` to 0 to avoid having PDFs show PHP errors in favor of using ```@``` when the mPDF lib is called directly, this should also fix the issues mentioned in #7111.
- Added autogenerated font files to ```.gitignore```.
- This is intended to be the minimum base required to complete further PDFEngine work (Adding new engines, engine selection, etc).
1. Fully regression test all MPDF functionality (Reports, bulk action pdf, quotes, etc).
=> Implement standard PDFEngines

modules/Users/tpls/EditViewFooter.tpl
- Fixed the user profile auto-filling the password fields on Chrome.
- https://developers.google.com/web/fundamentals/design-and-ux/input/forms#recommended_input_name_and_autocomplete_attribute_values
- https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill
- I've tried every possible combination to disable auto-fill mentioned in the docs and [stackoverflow](https://stackoverflow.com/questions/15738259/disabling-chrome-autofill). This is the only one that works with input fields on latest chrome.
1. On chrome go to user profile and save a password using the chrome password manager.
2. Check that on reload, the password is not auto-filled.
=> Fix #6997 - User profile password auto-fill

modules/ProspectLists/vardefs.php
=> Wrong spelling of ProspectLists module

include/SugarLogger/SugarLogger.php
Depending on the umask default for your system new files can be created with permissions that do not allow log files to be written to if they were created from a cron vs UI action.
ie. if cron runs and creates a log file I get `0644 / root / www-data` as my crons are running within a custom docker container which is root, but the UI will create them as `0644 / www-data / www-data`. The issue comes if the UI tries to write to log file originally created by the cron due to `0644` perms it will not write it but with `0664` it will.
Just set `0664` at the point the log file is created.
Also there is no need to do `file_exists` and `is_writable` when you are checking if the log file exists, a total of three checks are done and now ive reduced it to one, if its not writable it then checks if it …
=> Set default perms on new log file

include/SubPanel/SubPanelTiles.php, modules/AOR_Reports/AOR_Report.php, modules/AOR_Reports/aor_utils.php
SuiteCRM 7.10.25
PHP Notices fix on undef params
=> AOR_Reports generating php notices due to undef

include/SugarFolders/SugarFolders.php, tests/unit/phpunit/include/SugarFolders/SugarFolderTest.php
Replace subquery with JOIN for performance.
=> Fix Archive Folder Query

data/SugarBean.php
Prevent duplicate notification emails being sent.
When changing the assigned to user and the module has a workflow with a Calculate Fields action with a formula and the workflow Repeated Runs option is selected.
Add additional flag to set to true when the notification email has been sent.
Add additional check before sending the notification email.
One notification email sent.   
Two notification emails sent.  
Avoid duplicate notification emails being sent to assigned user.
Once Scheduler has been setup to process workflow tasks:
1. Create a workflow for a module.
2. Select "Repeated Runs" in the workflow.
3. Add a "Calculate Fields" action to the workflow.
4. Add a formula parameter to the "Calculate Fields" action of the workflow.
5. Go to Detail View of a record of the module used in …
=> Fix #9203 - Duplicate notification emails.

data/SugarBean.php
Prevent duplicate audit records being created in the module change log.
When changing the assigned to user and the module being audited has a workflow with a Calculate Fields action with a formula and the workflow Repeated Runs option is selected.
Add additional flag to set to true when the current module audit records have been created.
Add additional check before creating audit records.
One audit entry in the module change log.   
Two audit entries in the module change log.  
in `data/SugarBean.php`
Add additional flag to set to true when the current module audit records have been created.
Add additional check before creating audit records
Once Scheduler has been setup to process workflow tasks:
1. Create a workflow for a module.
2. Select "Repeated Runs" in the workflow.
3. Add a …
=> Fix #9205 - Duplicate audit records.

include/InlineEditing/InlineEditing.php
Issue #4145 Email Address - "invalid" and "opt_out" options are lost
=> Fix Issue #4145

modules/Project/Menu.php, modules/Project/Project.php, modules/Project/language/en_us.lang.php
- Add Import Projects label
- Add Import Projects menu
- Make bean importable
Projects cannot be imported
=> Make Projects importable

install/language/en_us.lang.php, modules/Users/authentication/SugarAuthenticate/FactorAuthEmailCode.tpl, modules/Users/language/en_us.lang.php, themes/SuiteP/tpls/login.tpl
=> https url fix

modules/InboundEmail/language/en_us.lang.php
Moving an actual comment next to the string
To be displayed to Crowdin translators a comment needs to be in the same line then the value
=> Moving comment next to the string

include/MVC/SugarApplication.php
See #8991
removed duplicate code
Removes duplicate code
login with redirect params
- [ x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
- [ x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> fix for #8991

modules/Contacts/ShowDuplicates.php
Display city and account name facilitates identification of real duplicates
Added account name and primary_address_city in query
Contacts duplicate identification is hard when you just display first name, last name and title.
Displaying account name and city makes it easier to find out if that contact is a real duplicate or not.
Duplicate a contact, or convert a lead when a contact already exists with the same name
=> Improve Contacts duplicates list

service/v3/SugarWebServiceImplv3.php
Retrieve SuiteCRM version in get_server_info v3/v4/v4_1 REST API
=> Retrieve SuiteCRM version in get_server_info

include/SugarPHPMailer.php, modules/Emails/Email.php, modules/Meetings/Meeting.php
use stream_resolve_include_path to get server path of file in upload dir
Used stream_resolve_include_path to get correct file path on server prior to adding attachment to email
Used stream_resolve_include_path to get correct file path for emails module, workflow module and meetings module
See #9236
Fixes issue where attachments are not added to an email 
Send emails from workflow, emails module and send invites on meetings module
=> Fix #9236 Fix issue with email attachments in emails not working

include/SugarPHPMailer.php, modules/Emails/Email.php, modules/Emails/metadata/detailviewdefs.php, modules/Meetings/Meeting.php
date_sent_received duplicated in two columns
=> Merges from hotfix into hotfix-7.10.x

lib/PDF/PDFConfigurator.php, lib/PDF/PDFWrapper.php, modules/Administration/PDF/Controller.php, modules/Administration/PDF/MVC/Controller.php, modules/Administration/PDF/MVC/View.php, modules/Administration/PDF/PDFView.php, modules/Administration/PDF/buttons.tpl, modules/Administration/PDF/view.tpl, modules/Administration/PDFSettings.php, modules/Administration/language/en_us.lang.php, modules/Administration/metadata/adminpaneldefs.php
- Initial Framework for PDF Engine selection (At the moment we only have the single Engine).
- Config generation will be handled on upgrade.
1. See new admin panel option "PDF Settings"
2. Check that saving correctly generates a config value: ```$sugar_config['pdf']['defaultEngine'] = 'MPDFEngine';```
=> PDF Engine Selection

composer.json, composer.lock
Composer google clean up task as was failing due to invalid config. This PR address this issue and ensure minimum required version is being met
- Run `composer install` 
- See that all non requires packages are now properly removed and vendor folder size is now much smaller
=> Fix #9161 - Composer google cleanup

data/SugarBean.php
- Bug fix: add undeclared $createdAuditRecords
- Throws an error when saving records in Suite 8. Reason: when trying to save the audit changes for the record there is an declared property.
- Try to save a record for a module that has audit configured. Logs should not have any undefined errors for `$createdAuditRecords`
=> Fix error on audit save

tests/unit/phpunit/includes/CleanCSVTest.php
Fixes return types in CleanCSVTest.php.
1. See Travis.
=> Fix CleanCSVTest return types

Api/V8/Config/services/middlewares.php
The original Fix #8420 missed one key reference and addtionally incorrect referenced the wrong key file 
This Pr addresses these issue to allow system running on windows to  Authenticate users without errors 
see that the API now Authenticates successfully when running on windows
=> V8 API Auth issues on windows

lib/PDF/PDFWrapper.php
- Fixes an extra dir traversal in mPDF class check.
=> Fix filepath for mPDF class

tests/_support/Step/Acceptance/Workflow.php, tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
Update acceptance test to use new workflow manager admin panel button.
1. See Travis.
=> Update workflow acceptance test

lib/Robo/Plugin/Commands/BuildCommands.php
pscss command incorrect causing rebuild to hang
=> Fix rebuild scss Robo command

modules/AOS_PDF_Templates/language/en_us.lang.php
Update the PDF Template Change Warning
Previous label was spelled incorrectly
1. Go to PDF Templates
2. Create a new record
3. Select a value from the Load Sample Dropdown
4. Select a new value from the Load Sample Dropdown
5. See Change
=> Update PDF template warning

include/language/en_us.lang.php
I noticed there is typo in word administrator, which I fixed.
=> Fix typo in word administrator

include/database/DBManager.php, include/database/MssqlManager.php, modules/Users/vardefs.php
- Fix sql index errors on install
- Related issues:
- [SuiteCRM 7.12.0 issue on MYSQL 5.6 #9356](https://github.com/salesagility/SuiteCRM/issues/9356)
- [Impossible to install SuiteCRM 7.11.20 #9217](https://github.com/salesagility/SuiteCRM/issues/9217)
- Gettting error when installing on some mysql versions and engine types
- Install on mysql versions with MyIsam. 
- Repair and rebuild on mysql versions with MyIsam. 
- Install on mysql versions with InnoDB
- Repair and rebuild on mysql versions with InnoDB. 
- Install on mssql
- Repair and rebuild on mssql
=> Fix sql index issues

lib/Search/ElasticSearch/ElasticSearchEngine.php
For Elastic Search 7 use wildcard rather than the defunct "_all" field
Elastic Search has deprecated the "_all" field which previously contained all fields. This means that the Suite elastic search now only checks name fields. This fix uses "*" to signify that Elastic Search should consider all fields.
Perform a search using the elastic search engine with Elastic Search v7 on a non-name field.
=> Use wildcard rather than the defunct "_all" field

modules/EmailMan/controller.php
When changing Campaign Email settings, Email settings are removed.
For example, if Users may send as themselves was checked, it becomes unchecked.
- Go to Email Settings.
- Check Users may send as themselves
- Save
- Go to Campaign Email Settings
- Make a change (for example, change Number of emails sent per batch)
- Save
- Go to Email Settings
- Users may send as themselves is now unchecked
=> Bug Fix: Campaign Email settings removes Email settings

Api/V8/Service/ModuleService.php
See #9378 
This fix allows users to search for leads by email1 through the API.
See #9378
=> Fix #9378 - Filter by Email1 Field Through the API

modules/AOW_WorkFlow/aow_utils.php
Add check on if value is array, if is array don't attempt date formatting
Fix workflow saving issue caused by PR #9238 
Fix issue  #9380 where workflow action with data type date/datetime/datetimecombo and parameter type date does not save.
When parameter type is date, $value is an array but passed into DB date conversion and null is returned, fixed by adding check if $value is an array
Fixes issue with date actions not being saved in workflow
Create a New workflow
Create a field that is Now + 1 day
Save the record
Re-open the workflow, you will see this does not in fact save.
=> Fix issue #9380 where date action in workflow fails to save

modules/ModuleBuilder/parsers/parser.dropdown.php, modules/Studio/DropDowns/DropDownHelper.php
Core Fix: Consistently store dropdowns in $app_list_strings rather than $GLOBALS
Update the save functionality of dropdowns to create and update dropdown lists using $app_list_strings rather than $GLOBALS['app_list_strings'].
Reduces chance of duplicating dropdowns if they are saved and changed outside of the dropdown editor.
Makes storing of dropdown lists more consistent across the system.
- Make a change to a dropdown in the Dropdown Editor in Admin.
- Check for the change in ```custom/include/language```.
=> Core Fix: Consistently store dropdowns in $app_list_strings

modules/ModuleBuilder/views/view.modulefields.php
https://community.suitecrm.com/t/creating-default-object-from-empty-value-using-php-7-4-22/81710
When using PHP 7.4 + it appears that when PHP WARNINGS are enabled users are unable to created fields in Module Builder / Studio.
**_Creating default object from empty value in /var/www/suitecrm/modules/ModuleBuilder/views/view.modulefields.php on line 109_**
https://community.suitecrm.com/uploads/default/optimized/2X/0/05bd70091fc64f6b7e5ef52286a67d64ab587abd_2_690x261.png
This is due to line: 
https://github.com/salesagility/SuiteCRM/blob/master/modules/ModuleBuilder/views/view.modulefields.php#L109
It looks like this was resolved in view.modulefield.php in previous versions. I've just adapted it to be used in this class.
https://github.com/salesagility/SuiteCRM/blob/master/modules/ModuleBuil …
=> Declaring object within StudioClass to remove Strict Warnings

tests/unit/phpunit/modules/Schedulers/SchedulerTest.php
Scheduler Test will fail if the 3rd of march falls on anything other than a wednesday.
Fix Scheduler Failing Test
Run Scheduler Unit Test and see that it's passing
=> Fix : Scheduler Test Failing

include/SugarEmailAddress/SugarEmailAddress.php
- Fix: https://github.com/salesagility/SuiteCRM/issues/7842
- Fixes issue in workflows, where email addresses where being removed.
-- this happened if record had more than 2 email addresses
- - Revert 41ee520
- Fixes issue https://github.com/salesagility/SuiteCRM/issues/7842
- See `Steps to reproduce` in https://github.com/salesagility/SuiteCRM/issues/7842
-  Also re-test https://github.com/salesagility/SuiteCRM/issues/5197
=> Fixed #7842 Do not reset email addresses list upon saving #9390

data/SugarBean.php, include/Services/NormalizeRecords/NormalizeRecords.php, include/database/DBManager.php, modules/DynamicFields/DynamicField.php
- Fix encoding repair tool.
- see: https://github.com/salesagility/SuiteCRM/issues/9482
- When saving some modules, the email addresses get removed because the emails weren't previously loaded
- see: https://github.com/salesagility/SuiteCRM/issues/9482
- Add several email addresses to a contact.
- Add a badly formated string to a field in that contact
- run the utf8 repair
- check that the contact's email addresses are all there
=> Fix #9482 - Only save update fields on utf encoding repair

lib/Search/UI/SearchResultsController.php
Add two getters to SearchResultsController in order to expose private attributes for extensibility.
SearchResultsController has two private attributes - $query and $results. Because these are private extending this controller to customise the instance is tricky. This change adds two getters for these attributes so that subclasses can use them.
This change shouldn't have any impact on functionality. Testing would be a case of testing the global search and confirming no issues have been introduced.
=> Add getters to SearchResultsController

modules/AOW_Conditions/conditionLines.js, modules/AOW_WorkFlow/aow_utils.php, modules/AOW_WorkFlow/controller.php
Fixes: #9435 
This fix builds on #9522.
When editing the workflow you are unable to save the "" value successfully.
See Issue for test details.
=> Fix #9435 - Dropdown doesn't return empty selected value

include/MVC/SugarApplication.php, include/SubPanel/SubPanelTiles.php, include/social/facebook/facebook_sdk/src/base_facebook.php, include/social/facebook/facebook_sdk/src/facebook.php, modules/UserPreferences/UserPreference.php, modules/Users/Logout.php, modules/Users/views/view.detail.php
- Change cookie_path handling
- in setCookie if no cookie_path value provided
- use session.cookie_path if defined
- Otherwise fallback to `/`
- Use application setCookie across the app
- Replace direct php setcookie calls with application setCookie
- see #9437 
- Cookie path set was not set to `/`
- see #9437 
- Go to app
- Clear all cookies
- Refresh. Check cookies and path
- Login. Check cookies and path
- Navigate through the app. Check cookies and path
=> Fix #9437 default cookie path

tests/acceptance/Core/ModuleBuilderFieldsCest.php, tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
Fix AOR Reports Tests
Run unit test
=> Fix AOR_Report unit tests

download.php, include/utils.php, modules/Documents/Document.php
- Check default allowed_preview config if not set on config.php
- Check default allowed_preview config if not set on config.php
- Prevent file upload error
- see #9530 
- see #9530
=> Fix #9530 Fallback to allowed_preview defaults

modules/AOR_Scheduled_Reports/emailRecipients.php
Fix #9636 Add styling of email recipient button
Fixes #9636
- Open scheduled reports
- Examine button
=> Fix #9636 Add styling of email recipient button

include/SugarFields/Fields/CronSchedule/SugarFieldCronSchedule.js
Fix #9634 and show the basic view of cron.
Fixes #9634
- Create a new Scheduled report
- Advanced checkbox should be disabled by default
=> Fix #9634 Add check on cron to show the basic view on first load

modules/AOR_Reports/aor_utils.php
This updates the AOR Utils Report Periods to include the users Timezone
This fixes issue #9551. Note that, although this does fix #9551 it does slightly change behaviour - different users will may see different results from a report depending on their Timezone.
- Create a report as described in #9551 - there should no longer be any records that fall outside the date period.
=> Fix #9551 - Update date period to include the users TZ.

modules/AOW_WorkFlow/AOW_WorkFlow.php, tests/unit/phpunit/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
Add fix for #9545. This quotes the link name to prevent reserved link names breaking the SQL.
Prevents broken SQL from being generated. In particular for the `case` link name in the Case Updates module.
Run through the steps in #9545 - create a new workflow on Case updates and create a condition to cases. When this runs in the scheduler there should no longer be an error.
=> Fix #9545 - Quote potential reserved name

lib/Search/UI/SearchResultsController.php, modules/DocumentRevisions/metadata/listviewdefs.php
Include DocumentRevisions listviewdefs.php.
Make changes to search functions that retrieve the listviewdefs file for modules so that it will handle null returns.
Include a new listviewdefs file for Document Revisions module.
Handling exception allows the global search to still work correctly even when some modules may have no listviewdefs.
The new listviewdefs for Documents Revisions allows the module to be searchable.
=> Fix issue with search where fail state was not handled when missing listviewdefs.php file.

modules/AOW_Actions/AOW_Action.php
Fix an issue where a workflow action of type "Field" is put through fixUpFormatting() and returns an incorrect value which is saved incorrectly. Only "Value" types should go through fixUpFormatting()
Related to issue https://github.com/salesagility/SuiteCRM/issues/9547 https://github.com/salesagility/SuiteCRM/issues/9336
Added in PR https://github.com/salesagility/SuiteCRM/pull/9238
May be able to revert this PR https://github.com/salesagility/SuiteCRM/pull/9401
Workflow Actions of type "Field" for checkbox/date/currency are not saving as they should
1. Create a Workflow on Opportunities module
2. Add an Action to create a record. 
3. Set record type to Opportunites
4. Add Field and set the values to "Amount" "Field" "Amount"
5. Save the record and open it again, the field will be set to …
=> Fix #9547 - Workflow actions not saving correctly for certain field types

lib/Search/ElasticSearch/ElasticSearchIndexer.php, tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchIndexerTest.php
When the elastic search logic hook is run after_save, the index argument is sent with via the $bean->module_name. This should be set to lowercase before sending as in other parts of the code.
Fix was proposed in https://github.com/salesagility/SuiteCRM/pull/9442 however the thread was closed before being accepted. the fix to set strtolower at the point I have should also not require the second fix.
Elastic Search Logic hooks fail to index changes made to records properly.
1. Enable elastic search on SuiteCRM 7.12.6 and set up a server for it
2. Perform a full index.
3. Ensure an elastic search scheduler is not running.
4. Make a change to a record i.e Accounts/Leads
5. in search_index.log in the base directory there should be an error 
```` …
```
=> Fix #9421 - Elastic search logic hooks fail to index properly

include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
When you saved an Email as a draft and related to a case, for example, when you went to the history subpanel to then open the email back up you would be taken to the Detail View for a email and not the Email Draft View where you can then edit or delete an Email Draft.
1. Go to Cases then to activities
2. Create an email and save it as a draft. Make sure the email is related to the case.
3. Next, reload the page and see that the email draft is marked as a draft in the history subpanel
4. Now, Click on the link to open the email and see that the `action` in the URL is now `action=DetailDraftView`
=> Draft Email Opens in Draft View From History Subpanel

include/SubPanel/SubPanelTiles.php
The `flat` flag on subpanels detailed here: https://docs.suitecrm.com/admin/advanced-configuration-options/#_sub_panels_replacing_the_drop_down_menu_with_buttons doesn't seem to work. The option seems to not be passed through. This fix makes sure the flat flag is passed to the action menu.
Allows selectively collapsing the action menu for subpanels.
- Add a flat flag as in the link above
- Do a QR&R, check the appropriate subpanel - in the old version there will be no change. In the new version it will be a flat menu.
Note: The compose button is duplicated when this option is selected but this is unrelated to this ticket - turning on the flat action menus in the settings also exposes this. A separate PR should be made to fix this. I will do this if I get a chance.
=> Respect the subpanel `flat` flag

modules/AOP_Case_Updates/Case_Updates.php, modules/Cases/language/en_us.lang.php
Removes an if statement that checks for a contact_id on the AOP_Case_Updates record so that it will always display the update. When the case update does not have a contact_id to pull a name for the update from, it will instead display it as from 'Unknown'.
This resolves an issue where Case Updates that come from 'Unknown' sources (the email doesn't match with a Contact/User in the CRM etc.) would not be displayed in the Case Updates Thread.
=> Fix #9511: Case Updates Thread now displays updates from 'Unknown' sources.

modules/Reminders/Reminder.php, modules/Users/UserViewHelper.php
See #9267 
See #9267 
1. Go to User Management.
2. Edit any user other than your own user.
3. Click on Advance Tab
4. Find Popup and Email Invitee Checkbox. Check both checkbox.
5. Change the value of both dropdowns under these checkboxes to 5 hours.
6. Now if you view this user detail view then it shows the checkbox as unchecked.
=> Fix #9267 - Fix for popup &email reminder options

modules/Notes/vardefs.php
See #9258 
See #9258 
1. Add the Date Modified field to the Advanced Search in the Notes module.
2. Go to the Notes Modules.
3. Open the Advanced filter and check that the operator input of the Date Modified filter is not working.
=> Fix #9258 - Fix for Notes module advanced date-modified search

modules/Administration/RepairESIndex.php
Fix Elastic Search repair values and return if user doesn't have it enabled
1. Disable ElasticSearch
2. See that the repair doesn't run
=> Fix #9736 - Elasticsearch still running repair in not enabled

modules/ModuleBuilder/views/view.resetmodule.php
=> Error resetting modules  #7827

include/language/en_us.lang.php
- Closes #9721 
This PR adds the year option to the aow_date_type_list. Adding the item to the list is enough to make it work. Cause the code will use the internal name as it is.
This small change will add improve functionality
1. Create a workflow based in Contacts
2. Select Birthdate field in conditions
3. Select Today, "+" and check it appears condition
4. Select the condition and trigger an action to test it.
=> Fix #9721 - Adding Years option to aow_date_type_list in Workflow ditions

include/MVC/View/SugarView.php, themes/SuiteP/tpls/_head.tpl
Use similar logic for the base browser title that the Ajax UI uses.
Fix #9688 
Same steps as #9688 after this fix the browser titles will be the same.
=> Fix #9688: Use the same browser title for the regular views

themes/SuiteP/include/ListView/ListViewPaginationBottom.tpl
- resolve #9672
The bug indicated in the issue is fixed. 
Fixed display bug on listview _Next_ button.
Check that the error shown in the issue is already corrected and the button is displayed correctly.
May be difficult to see due to poor button contrast
=> Fix #9672 - Bug in CSS class causes bad button display

modules/Users/Changenewpassword.php
- resolve #9668
File `modules/Users/changepassword.php` has been modified to use, if there is, a custom template for password change.
This change allows to customize the organization logo, as well as modify other aspects of appearance or content of the password change screen.
1. Clone template `modules/Users/Changenewpassword.tpl` to `custom/modules/Users/Changenewpassword.tpl`
2. Change some HTML element in the new template to verify what applies after the change.
3. Enable  _Forgot Password feature_ in admin área 
4. Logout & click in _Forgot Password?_ link.
5. Force a password change in Suitecrm to check the appearance of the password change screen and verify that the changes are applying.
=> Fix #9668 - It is not possible to use a custom template for password change

tests/unit/phpunit/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
Fix workflow unit tests
Run `./vendor/bin/robo tests:unit` in terminal and see that the test now passes.
=> Fix #9803 - Workflow test returns boolean

modules/Studio/parsers/StudioParser.php
Fix #9574 
Fixes #9574 
Open Admin
Got to “Rename Modules”
Attempt to switch the name of any core module
=> Fix #9574 - Update method to static for module renaming

lib/Search/ElasticSearch/ElasticSearchEngine.php, lib/Search/SearchQuery.php, lib/Search/UI/SearchResultsController.php, lib/Utility/ArrayMapper.php
Updates the Elasticsearch functionality to parse accented characters correctly when sending information to the Elasticsearch server in order to index records or search.
Fixes bugs when searching with a query that includes an accented character, including the string being returned encoded and not being able to find matching records.
1. Create a record that contains an accented character that will be indexed.
2. Run steps for full Elasticsearch indexing.
3. Search for previously created record via Elasticsearch engine.
=> Fix Elasticsearch indexing and searching using accented characters

modules/Administration/QuickRepairAndRebuild.php
Fix #9786
- Edit a field with Inline edit
- Change the field definition with Studio
- Edit the same field with Inline edit
- The new definition is not taken into account
=> Clear caches used by Inline Edition

modules/Users/tpls/EditViewFooter.tpl
- resolve #9670 
Fixed an error that processed the `receive_notifications` field differently from the rest of the checkboxes, and as a consequence, it did not save the value.
It is important to correctly save all settings in the user profile.
Look at the video in issue #9670. In the last step, the value of `receive_notifications` should be changed, as chosen by the user
=> Fix #9670 - Disabling the user profile option about notification of assignments does not work

include/EditView/EditView2.php, include/Imap/Imap2Handler.php, include/Popups/PopupSmarty.php, modules/InboundEmail/Save.php, modules/InboundEmail/vardefs.php
- There are php errors on InboundEmail when using php 8. See #9878 
- There are php errors on InboundEmail when using php 8. See #9878 
- On the "External Oauth Connection" Module -> the "Provider" Relate field Popup gives a FATAL
- When saving an "Inbound Mail Account" record, you get a FATAL whitescreen
- When editing an "Inbound Mail Account" record, the "External Oauth Connection" Relate field Popup gives FATAL
- The Compose->From field occasionally doesn't populate in PHP8, where it does in php7.4
=> Fix #9878 - Fix inbound email errors on php 8

include/Imap/ImapHandlerFactory.php
- Fix log level in ImapHandlerFactory
- See #9870 
- Fatal log level being used instead of debug
- See #9870 
- Configure Inbound Email Account
- Open Emails module
-  check the logs
=> Fix #9870 - Fix log level in ImapHandlerFactory

modules/AOW_Actions/actions/actionComputeField.php
Solves #9750 
As described in the issue, this PR adds the condition to format/translate dynamicenum related fields in Calculate Field WF Actions
The edit_display() function code is the same modification as PR #9622
This will allow to use dynamicenum in WF properly
1. Create a field of type dynamicenum in the Organizations module and add it to the editing and detail view. :
Name: subtype
Type: dynamicenum
Parent DropDown: account_type
Add DropDown List: subtype_list
Values:
- Item Name: Analyst_1 - Display Label: 1
- Item Name: Analyst_2 - Display Label: 2
- Item Name: Analyst_3 - Display Label: 3
2. Create an organization with Type = Analyst and subtype = 1
3. Create an Accounts-based workflow
Run:Always
Run On: All records
Action: Calculate Fields
Relationship Parameters:
- Accounts: …
=> Fix #9750 - Receive related parameters of type dynamicenum in workflow formulas

modules/AOP_Case_Updates/Case_Updates.php
Issue - https://github.com/salesagility/SuiteCRM/issues/9835
The case updates threaded save function hangs on the "performing task" dialog box when moved to a different panel than the default SuiteCRM panel
You should be able to move the case_updates_threaded field to another panel and have the save button work.
Case Updates do save but the crm hangs on "performing task" dialog box and doesn't perform the refresh/collapse of previous case updates etc.
1. In Studio, remove the panel called Case Updates for the Cases module.
2. Insert case_updates_threaded into the default panel or create a new panel 
3. Save the new detail view
4. In the Cases module, pick any record, write a case update and press save.
5. A dialog box saying "performing task" should pop up and the page won't refresh.
=> Fix #9835 - Case Updates save bug

modules/AOS_Products/AOS_Products.php
Error when creating product without uploading image
- see #9926  
Error when creating product without uploading image
- see #9926  
- Create product without uploading image
=> Fix #9926 - Add missing check on product image upload

modules/Campaigns/CampaignDiagnostic.php
Fix Campaign Parenthesis
1. Go to campaigns
=> Fix Campaigns parenthesis

modules/AOW_Actions/FormulaCalculator.php
- Closes #9902 
This PR adds the code to convert to DB format any value that arrive to the formula calculator function. It also converts to UTC if needed.
With this change any date calculation will work with any user format
1. Set the User date format in Profile Advance option to "23/12/2010"
2. Create a workflow with a Calculate field action (Contacts based)
3. Add a date field parameter as parameter (`birthdate`)
4. Add a formula to a text field. (Formula:  `{datediff({P0}; {now(Y-m-d)} ; months )}`  to `description` field)
5. Create a contact with 14/12/2020 in `birthdate`
6. Run the workflow on Scheduler and check it run successfully
=> Fix #9902 - Workflow - Some Date calculations fail with certain formats

include/utils.php
allowed_preview is defined twice in the array
removed one of the entries
There is no problem with that, but the second entry is useless
=> allowed_preview is defined twice in the array

modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
=> Fix #9828 - $mod_strings not in scope for line 395 of the same file

modules/CampaignTrackers/DetailView.html
=> Fix #9817 - Typo

modules/AOW_Actions/actions/actionComputeField.php
When using calculated field and using decimal values (e.g. 10,50 + 12,00) to calculate a decimal field, the result will not be correct (e.g. it will display 999,99 instead of 22,50).  The proposed change fixes this fault and renders the correct value. The issue only occured when one of the decimals is not equal to 0, fyi if you´re trying to reproduce it.
The change is required, because calculated fields should calculate correctly...
create three decimal fields; value A, value B and result C; 
Set one of the values to (e.g.) 12.50 and the other one to 10.00
Set up a workflow and calculate value A + value B by using  {add({P0};{P1})} or any other formula you wish
That´s it - the result will indicate 999,99
- [x ] My code follows the …
=> decimal numbers calculations fix

include/javascript/sugar_3.js, jssource/src_files/include/javascript/sugar_3.js
New User Group Popup. Popup does not show after creating a user
=> #9780 New User Group Popup. Popup does not show after creating a user

modules/Emails/EmailsController.php
From issue https://github.com/salesagility/SuiteCRM/issues/9764
When you hit "Reply To All" to an email in SuiteCRM, if the email has a second address in the "To" field, this address doesn't get added to the CC field.
Reply To All does not currently follow expected behaviour in regards to email addresses
1. Open up an email that has multiple "To" addresses
2. In the Action menu, hit "Reply To All"
3. Only the "From" address will be added to the new email and the additional "To" addresses will be ignored.
=> Fix #9764 - Add extra To addresses to CC field

modules/Charts/Dashlets/MyPipelineBySalesStageDashlet/MyPipelineBySalesStageDashlet.php, modules/Charts/Dashlets/OpportunitiesByLeadSourceByOutcomeDashlet/OpportunitiesByLeadSourceByOutcomeDashlet.php, modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php, modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.php, modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
This PR fixes an issue were old user preferences containing null values conflict with PHP 8
In SuiteCRM installations which were previously upgraded from SugarCRM the user preferences may contain null values for Dashlet preferences. When upgrading the PHP version to version 8, these null values become an issue as the php count() method throws an error when feeded with this null value.
This PR solves issues when migrating from PHP 7 to PHP 8 that have user preferences from earlier versions of Suite or SugarCRM.
- Install SuiteCRM 7 on a system with PHP 8.0
- On the Home page, click on "Actions", "Add Dashlet" and click on the tab "Charts"
- Add one or more of the following chart dashlets:
- All Opportunities By Lead Source By Outcome
- All Opportunities by Lead Source
- My Pipeline By …
=> Fix php 8 issue with old user preferences null values

include/Imap/Imap2Handler.php, include/ListView/ListViewGeneric.tpl, modules/InboundEmail/InboundEmail.php, themes/SuiteP/include/ListView/ListViewGeneric.tpl
=> Fix #10034 - Email Listview doesn't render, so no Emails are visible.

include/utils.php
Fix #10056: User bean value is_admin is unset on save()
=> Fix #10056: User bean value is_admin is unset on save()

include/SugarFolders/SugarFolders.php
PHP message: PHP Warning:  Attempt to read property "isgroup" on array in /var/www/sugar/include/SugarFolders/SugarFolders.php on line 790
=> Fix #9816 - $item is an array, no object

modules/ACL/remove_actions.php
When uninstalling a module, it will repeat the same string output over and over with no context to what is being removed.
During an uninstallation of a module it is repeatedly telling the user that the same thing is being uninstalled. This is confusing. It also does not tell you that it's ACLs that are being removed.
* Install a module
* Uninstall a module
* Look at the output in the UI
=> Add better description of what is being removed during module installation for ACLs

modules/AOW_WorkFlow/AOW_WorkFlow.php
Handle join to related module in query when run for relationships made in studio
Query fails for workflow when condition is based on a studio made relationship when run in scheduler
Query fails for workflow when condition is based on a studio made relationship when run in scheduler
Create a relation on Calls module with type one to many to Opportunities module
Go to Workflow module and create new Workflow on Opportunities module
Add condition on module Opportunities and field Calls to be equal to empty
Run scheduler
=> Fix #8682 -  Workflow fails with relationship condition

modules/Administration/AOPAdmin.php
Fix Case Module Settings not saving.
1. Go to Case Module Settings
2. See that it now saves
=> Fix AOP Config not saving

include/Imap/Imap2Handler.php, modules/InboundEmail/InboundEmail.php
=> Fix #10035 - Monitered Folders are not selectable for Basic Auth Accounts

include/SugarFields/Parsers/DetailViewMetaParser.php, include/SugarFields/Parsers/MetaParser.php, modules/ModuleBuilder/MB/MBPackage.php
Removes old sugar flavor references. Issue #6914 
As requested in Issues, and it's a good first issue :)
Install and run app.
=> Fix #9941 - Remove sugar pro flavor

modules/AOW_Actions/AOW_Action.php
- Closes #9725 
This PR adds code to retrieve the module name that contains the selected field value. Then it provides the module name to the function fixUpFormatting().
Format the value properly.
1. Create a Workflow based in Accounts
2. Add an action that modifies the record
3. Add the Birthdate field from the Contacts::Contacts relationship
4. Assign a value to the date field
5. Save the WF
6. Edit again de WF and check that the value stays.
=> Fix #9725 - Date field value isn't saved in a Workflow action related module

modules/Contacts/language/en_us.lang.php
Missed label: 
Avoiding using system labels in UI.
Go to: 
1) Admin -> Studio
2) Pick up Contacts
3) Layouts -> List view: check the missing label.
=> Fix #10020 - Issue with missing label on Contact Module

modules/Project/language/en_us.lang.php, modules/ProjectTask/language/en_us.lang.php, modules/ProspectLists/language/en_us.lang.php
Fix #9148 - Fix missing sorting labels.
Also works for this (it looks like the duplicated issue):
https://github.com/salesagility/SuiteCRM/issues/6880
According to https://github.com/salesagility/SuiteCRM/issues/9148 missing labels were added to language files of Project and ProspectList modules. 
Makes application cleaner + Project Tasks Module labels added.
1) Go to list view Projects 
2) Filter -> Advanced
3) Check that labels are missing:
=> Fix #9148- Fix missing sorting labels.

modules/AOW_Actions/actionLines.js
Issue is described here: 
https://github.com/salesagility/SuiteCRM/issues/3050
To make logic a bit consistent I'd like to offer implementation of the same function as presented in AOW_Conditions to remove condition lines from UI, if flow module has changed: 
This PR gives the same functionality to AOW_Actions - flow module changed, action lines removed simultaneously with condition lines.  
All the steps are fully described in the issue.
=> Fix #3050 - AOW: dropdown lists is not updating (calclulate field & modified record action)

themes/SuiteP/tpls/_headerModuleList.tpl
Issue fully described in here: 
https://github.com/salesagility/SuiteCRM/issues/2111
Labels have added to all 'title' attributes on anchor tags.  
It makes application cleaner. 
https://github.com/salesagility/SuiteCRM/issues/2111
=> Fix #2111 - Hover over favorites item, shows module name, not label

themes/SuiteP/modules/Users/tpls/DetailView-advanced-tab-content.tpl
The issue is in UI: 
1) Fields are duplicated;
2) Appropriate variable is not present:
This is slight improvement of template for User Profile. 
1) Go to Admin -> Profile;
2) Press Save of Cancel buttons in the header section (to get to the detail view);
3) Go to tab Advanced -> check section Locale Settings
=> Fix #10060 - User preferences detail-view template issues.

include/utils.php
Fix dropdowns not saving correctly when key and value were different types
1. Go to Business Hours
2. See that they now save with selected values
=> Fix dropdown keys not the same type

modules/Import/sources/ImportFile.php, modules/Import/views/view.confirm.php
Check value being count is an array before attempting to count in getFieldCount and remove "false" values from getSampleSet before returning array
Importer fails on step 2 when running php 8.0+
Add is_array check on value being counted before attempting to count to avoid fatal erorr
Also removed continue from foreach as it is not needed
Fixes issue where non array value is counted resulting in fatal errors #10129
Export task record
Re-import task as new record
See step 2 page load with no issues
=> Fix #10129 Fix issue with step 2 & 3 on the importer failing

modules/Surveys/Entry/Survey.php, modules/Surveys/language/en_us.lang.php, modules/Surveys/tpls/closeSurvey.tpl
Issue:
https://github.com/salesagility/SuiteCRM/issues/5385
[#4800](https://github.com/salesagility/SuiteCRM/issues/4800)
1. Added a src to use the same picture as if the Survey in status "Public".
2. Added a new label to language file to effectively substitute hard coded string. 
To make Suite Application cleaner (usage of labels instead raw strings + fix of broken image)
1. Create Survey;
3. Change status of created Survey to "Closed";
4. Try to access the Survey through EntryPoint with ID of your Survey as it described in the initial issue.
=> Fix #5385 - Fix Closed survey issues

modules/ModuleBuilder/parsers/ModuleBuilderParser.php, modules/ModuleBuilder/parsers/parser.label.php, modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php, modules/ModuleBuilder/parsers/views/DashletMetaDataParser.php
Replace usage of fclose with sugar_fclose to clear cache after writing to file
Replace fclose with sugar_fclose so that cache is rebuilt after a file has been written to so that layout changes are immediatly  reflected 
Fixes issue #9062 where 
Make layout changes to listview/dashlets in studio and see changes reflected immediatly
=> Fix #9062 - Studio layout changes not being reflected 

themes/SuiteP/css/suitep-base/studio.scss
Issue: https://github.com/salesagility/SuiteCRM/issues/3842
It's impossible to reach the UI content without vertical scroll bar.
Before fix: 
After fix:
=> Fix #3842 - Vertical scrollbar missing in Studio>Module>Layouts>

themes/SuiteP/css/suitep-base/editview.scss
Increase text area width to match description
When a text area is not named "description" the width set in studio is not respected on editview. See issue #10007 for screenshots
Fixes issue with text areas not spanning two columns
Create new text area filed
Add to edit view across two columns
See width not respected on editview
=> Fix #10007 - Text area cannot span two fields

modules/ExternalOAuthConnection/ExternalOAuthConnection.php, modules/ExternalOAuthConnection/controller.php, modules/ExternalOAuthProvider/ExternalOAuthProvider.php, modules/ExternalOAuthProvider/controller.php, modules/InboundEmail/InboundEmail.php, modules/InboundEmail/controller.php, modules/OutboundEmailAccounts/OutboundEmailAccounts.php, modules/OutboundEmailAccounts/controller.php
When logged in as a non-admin user
If you go to the Inbound Email Module, and click the "Outbound Email Account" relate field popup button
You can see your Outbound Accounts.
But they don't show as a link
1. Go to Inbound Emails as a non-admin user.
2. Select a Outbound Email Account
3. See that they now show as a link
=> Fix non-admin's outbound email link not showing

include/language/en_us.lang.php, modules/InboundEmail/InboundEmail.php, modules/InboundEmail/language/en_us.lang.php, modules/InboundEmail/metadata/detailviewdefs.php, modules/InboundEmail/metadata/editviewdefs.php, modules/InboundEmail/vardefs.php
Add options to change the way filtering is done for email body
1. Select an option from the dropdown within the Inbound Email Module
2. See that when filtering on listview that the option is respected and shows accordingly
=> Add Email Body Filtering Selection

modules/Accounts/metadata/SearchFields.php
See
https://github.com/salesagility/SuiteCRM/issues/10159
Make search more useful and consistent.
See 
https://github.com/salesagility/SuiteCRM/issues/10159
=> Fix #10159 - Accounts - Not able to search by fax on 'Any Phone' search field

install/ready.php
in the silent install informs incorrectly: "Upload File Size | error | Warning: Your PHP configuration should be changed to allow files of at least 6MB to be uploaded." but is set correctly to 6M, this is because of a strict comparison of ">" instead of a ">="
=> Update ready.php change checking of upload max filesize from > to >=

data/SugarBean.php
Currently this method is sending over the definition of the relationship in order to remove the relationship from the relationships db table.
The definition does not include the name and cannot be used.
During uninstalling a module, this method will throw a notice of Array to string conversion as well as not actually removing the relationship from the relationships table.
To correctly remove a module without notices and actually removing the relationships
* Install a module
* Uninstall the module.
* Check the logs
* Check the `relationships` table
=> Relationship::delete expects a string (the name of the relationship)

include/SearchForm/SearchForm2.php
When searching for "John Smith" in unified search, if someone puts characters in front of the first name so it is "_John Smith" in the database it doesn't show up in search results. This changes makes use of the utility method to put wildcard in front of the full name.
Certain results were not showing up in the search that should have been because of my intended change of search_wildcard_infront in the config.
Have a contact with other characters than your search query in front of the first + last name combination and verify it shows up in the results.
=> Respect wildcard in front when searching a full name in basic search

modules/OutboundEmailAccounts/smtpPreselection.tpl
Remove setting of html field values that don't exist on page
See issue #9456
See issue #9456
See issue #9456
=> Fix #9456 - choose email provider does not populate SMTP settings

modules/AOW_Actions/actions/actionSendEmail.php
Workflows always send html email as reported here https://community.suitecrm.com/t/workflow-send-email-send-text-only-always-sending-as-html/33987 this change fixes this issue allowing plain text emails to be sent if the template is selected to be plain text only.
Trying to send a plain text email with a workflow
Set up a workflow to send a email template that has plain text checked
=> Allow workflow to send plain text emails

modules/jjwg_Maps/controller.php
Fix the labels so results are shown properly
=> Fix #10252 Google Maps Geocoded Counts not displaying properly

include/MVC/SugarApplication.php
Fix error "invalid cookie domain".  See #9898 for details.
Port number is not allowed to be on cookie domain.  The `setCookie()` method was leaving port number on there.  This fix removes the port number, as it should, when setting the cookie's domain.
Install SuiteCRM on non-standard port, such as `8443`.
Very common to have ports when using docker and any other containers.
The application's URL will be something like `https://mysite.com:8443/index.php`
Look in browser console, you see `Invalid cookie domain` errors, for all cookies used by the application!  The app malfunctions because it depends on the cookies.
This is because `mysite.com:8443` in not allowed to be used as the cookie's domain.
Apply this code, and you get the acceptable cookie domain set on the app's cookies: …
=> Fix #9898 Invalid cookie domain when using non-standard HTTP Port.

modules/ProjectTask/views/view.list.php
See the issue: https://github.com/salesagility/SuiteCRM/issues/5392
See the issue: https://github.com/salesagility/SuiteCRM/issues/5392
=> Fix #5392 - My Filters doesn`t show up on Project Tasks

modules/AOW_WorkFlow/AOW_WorkFlow.php
When running the Workflow by scheduled Job, if there are any "Calculate Fields" or "Modify Record" actions on the Workflow alongside the "Send Email".
An additional Email is sent for each one of these actions.
1. Create WF with several actions - 2 or 3, one of them should send an email. 
2. Options to set: Run Always and Repeated runs. 
3. Run cron.
=> Fix #10296 - Add duplication logic check on run_when Always

include/Smarty/plugins/function.sugar_currency_format.php, include/utils.php, themes/SuiteP/include/Popups/tpls/PopupGeneric.tpl
https://github.com/salesagility/SuiteCRM/issues/5906
https://github.com/salesagility/SuiteCRM/issues/5906
=> Fix #5906 - Currency symbol for currency field in popup is always default

modules/InboundEmail/metadata/editviewdefs.php
The issue: 
https://github.com/salesagility/SuiteCRM-Core/issues/186
The issue: 
https://github.com/salesagility/SuiteCRM-Core/issues/186
=> Fix #10302 - IMAP INBOUND EMAIL error

modules/Administration/AOPAdmin.php, modules/Administration/AOPAdmin.tpl
https://github.com/salesagility/SuiteCRM/issues/9853
https://github.com/salesagility/SuiteCRM/issues/9853
=> Fix #9853 - 7.13.0 - The "Case Macro" field now appears empty by Default

modules/ExternalOAuthConnection/controller.php, modules/ExternalOAuthProvider/controller.php
When editing a Group External Connection/Provider record, the type changes from "Group" to "Personal"
Create an External OAuth Connection with the type group
Save
Edit the record and see that it no longer changes type
=> Fix Group External Connection Changing type on edit

modules/Administration/RepairFieldCasing.php
"Repair Non-Lowercase Fields" action was retunring a fatal error
* Run from the repair menu
* See that the error no longer shows
=> Remove unused line in repair

modules/ProspectLists/Delete.php
https://github.com/salesagility/SuiteCRM/issues/9144
https://github.com/salesagility/SuiteCRM/issues/9144
=> Fix #9144 - Popup error messages

modules/AOP_Case_Updates/util.php
https://github.com/salesagility/SuiteCRM/issues/9858
https://github.com/salesagility/SuiteCRM/issues/9858
=> Fix #9858 - "Distribution Method" is not retained on Editview Load

include/SugarFields/Fields/Parent/SearchView.tpl, modules/AOW_Processed/vardefs.php
See the issue:
https://github.com/salesagility/SuiteCRM/issues/2833
See the issue:
https://github.com/salesagility/SuiteCRM/issues/2833
=> Fix #2833 - Process Audit Advanced Search

include/SearchForm/SearchForm2.php
https://github.com/salesagility/SuiteCRM/issues/10093
https://github.com/salesagility/SuiteCRM/issues/10093
=> Fix #10093 - Results are not filtered in the Targets Module popup

modules/DynamicFields/templates/Fields/TemplateHTML.php, modules/DynamicFields/templates/Fields/TemplateParent.php, modules/DynamicFields/templates/Fields/TemplateRelatedTextField.php, modules/ModuleBuilder/tpls/resetModule.tpl, modules/ModuleBuilder/views/view.resetmodule.php
https://github.com/salesagility/SuiteCRM/issues/6397
https://github.com/salesagility/SuiteCRM/issues/6397
=> Fix #6397 - Studio: Reset Module: Remove Custom Fields

lib/Search/Index/IndexingSchedulerTrait.php, modules/Schedulers/_AddJobsHere.php
https://github.com/salesagility/SuiteCRM/issues/10207
https://github.com/salesagility/SuiteCRM/issues/10207
=> Fix #10207 - Problem running ElasticsearchIndexerScheduler from cron

modules/Administration/controller.php, modules/Administration/language/en_us.lang.php
Users could disable the language they have active
* Go to languages in the admin menu
* See you cannot disable your current language
=> Fix #10314 - disabling active languages

modules/InboundEmail/metadata/editviewdefs.php
When the user is creating an Inbound Mail Account, they are also able to configure Outbound info.
When the user links an Outbound Mail Account, the From Address/Name fields should autopopulate, for user convenience. 
1. Go to Admin -> Inbound Emails
2. Press New Inbound Email Account
3. Outbound configuration panel -> Choose Outbound email account.
=> Fix #10283 - When selecting an Outbound Email Account, From/Reply Information should autopopulate for user convenience

modules/Surveys/tpls/Reports/checkbox.tpl, modules/Surveys/tpls/Reports/matrix.tpl, modules/Surveys/tpls/Reports/option.tpl, modules/Surveys/tpls/reports.tpl
changes to styling options for checkbox, matrix and option graphs templates to improve legibility/prevent overlapping labels.
changes to reports.tpl to improve titles alignment/legibility, fix panel appearance, provide expand/contract functionality to panels
suggested improvement
Create Survey record
Provide responses
From survey detail view, view survey reports action
- [ x] New feature (non-breaking change which adds functionality)
- [ x] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
=> Fix #10310 Survey reports ui improvements

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md
Update github contributing page
- Contributing page was out of date
=> Update github contributing page

modules/AOW_Actions/actions/actionComputeField.php
- Closes #9895 
There was an error inside the function that goes through the array of the items of the multienum field. It should be using the "$val" argument provided by the array_walk function instead of the value of the whole field.
This is an error and should be fixed
1. Create  a Multienum field in Accounts module with a list that contains different internal values than label. (assign aor_date_options list)
2. Create a Workflow base in Accounts with an Calculate Field action that copies the Formatted values of the multiselect field to a Description field
3. Create an Account and check the description field was filled by the Formatted values of the multienum field
=> Fix #9895 - Workflow - Copying Formatted values of a multienum to another field

lib/Search/UI/SearchFormView.php
See: 
https://github.com/salesagility/SuiteCRM/issues/10182
See:
https://github.com/salesagility/SuiteCRM/issues/10182
=> Fix #10182 - Graphic Issue search view after 7.14 upgrade

modules/AOW_Processed/metadata/searchdefs.php
- Closes #9971
This PR adds the code to add new filters in quick and advanced search view:
- adds the Module, Record and Status fields to the quick search view.
- adds the above fields plus Date Created, Date Modified, Creator User, and Modifier User filters to the advanced search view
1. Access the AOW processed module and go to the search view
2. Check that offers the new filters in quick view and advanced view
=> Fix #9971 - Workflow - Add filters to quick and advanced search view in AOW Processed module

modules/Project/Project.php
I believe this line was added in the wrong place as part of:
https://github.com/salesagility/SuiteCRM/commit/9aff7071bb86df7e06e2cf56aa3060fc00e3978a
It appears in the final code in line 613 not 330.
This causes the array to re-initialize and then subsequently causing a 500 error because the date in the second iteration is blank in the array and cannot be converted to a date and returns boolean false.
This is necessary to fix because no projects can be created with templates with this bug.
Try to create a project with a template with more than one task and try to save it.  It will result in 500 error.
Make the fix and it will work as expected.
- [x ] My code follows the code style of this project found …
=> Fix# 10321 Creation of Project with Template Causes 500 Error

modules/Surveys/Entry/SurveySubmit.php
Adding assigned_user when creating a Survey Response after sending a Survey.
Adding assigned_user to Survey Response
An assigned_user is set in any Survey Response
1. Create a Survey and make it public
2. Open the Survey link and send a Survey response
3. Check that the Survey Response has the same assigned_user as the Survey
=> Fix #10327 - Survey Responses doesn't get assigned_user after sending Survey

data/SugarBean.php
Pressing the skip to last page button in subpanels would result in 9 results showing instead of the default configured ten. This only happens if disable_count_query in the config is set to true. This config option does not appear by default any more so this issue will almost never come up, but still can be found on google: https://community.suitecrm.com/t/slow-suitecrm-with-large-database/33848/3 The previous employee in my position had set this config option to true in a bad attempt to fix performance issues many years ago.
set disable_count_query=true in a config option
create contacts named test01 through test30 for an account
press skip to last page button on contacts subpanel in that account
notice that test30 is not present
spend hours tracking down this bug just to realize you …
=> fix skip to last page if disable_count_query=true

modules/AOS_PDF_Templates/templateParser.php
https://github.com/salesagility/SuiteCRM/issues/9213
https://github.com/salesagility/SuiteCRM/issues/9213
=> Fix #9213 - $discount_amount corrupted

.github/ISSUE_TEMPLATE/01_issueTemplate.yaml, .github/ISSUE_TEMPLATE/config.yml, .github/SECURITY.md, .github/workflows/add-comment.yml
=> Feature #10426 - new issue menu templates

modules/Users/User.php, modules/Users/vardefs.php
https://github.com/salesagility/SuiteCRM/issues/9177
https://github.com/salesagility/SuiteCRM/issues/9177
=> Fix #9177 - Cant use edit inline in UserType field

Api/V8/OAuth2/Repository/ClientRepository.php, lib/API/OAuth2/Repositories/ClientRepository.php
Kudos: Scott Miller @scottfrancismiller
original author: Scott Miller @scottfrancismiller
- Re-creating PR: https://github.com/salesagility/SuiteCRM/pull/10274
- See: https://github.com/salesagility/SuiteCRM/pull/10274
- See: https://github.com/salesagility/SuiteCRM/issues/10268
- See: https://github.com/salesagility/SuiteCRM/pull/10274
- See: https://github.com/salesagility/SuiteCRM/issues/10268
- See: https://github.com/salesagility/SuiteCRM/pull/10274
- See: https://github.com/salesagility/SuiteCRM/issues/10268
=> Fix #10268 - Access token wil not refresh for Oauth2 password clients

modules/Calendar/Calendar.php, modules/Calendar/Menu.php
See the issue:
https://github.com/salesagility/SuiteCRM/issues/10437
See the issue:
https://github.com/salesagility/SuiteCRM/issues/10437
=> Fix #10437 - Calendar - 'Today' left-hand side bar option loads the week

modules/AOS_PDF_Templates/templateParser.php
https://github.com/salesagility/SuiteCRM/issues/5653
https://github.com/salesagility/SuiteCRM/issues/5653
=> Fix #5653 - VAT Display in PDF Templates wrong when Currency Significant Digits set to 0

modules/Project/js/main_lib.js
https://github.com/salesagility/SuiteCRM/issues/2175
https://github.com/salesagility/SuiteCRM/issues/2175
=> Fix #2175 - No gif and shifted text after saving task in gants view

modules/AOS_Products/metadata/detailviewdefs.php, modules/AOS_Products/vardefs.php
When you view a Product record that contains a URL, the user is not able to click on the URL to be taken to the webpage.
Go to Product -> create one with URL field -> click on the URL field in the Detail Vew.
=> Fix #10390 - URL is not clickable

modules/Campaigns/SubPanelViewer.php
Fixes the wrong layout of several subpanels in the Campaign-module.
Change based on the code of the default "SubPanelViewer.php".
Open a Campaign in DetailView and check the subpanel layout.
=> Fix #7150 - Show subpanels correctly

include/MVC/View/SugarView.php, modules/Favorites/favorites.js, modules/Favorites/language/en_us.lang.php, modules/Spots/views/view.edit.php
https://github.com/salesagility/SuiteCRM/issues/9078
https://github.com/salesagility/SuiteCRM/issues/9078
=> Fix #9078 - Favorites adds record twice to the sidebar and to the db

modules/Calendar/Calendar.php
Implements html_entity_decode() for encoding the title of the activities.
The function html_entity_decode() has been implemented with ENT_QUOTES as the second parameter for encoding the title of the activities.
An assigned_user is set in any Survey Response
1. Create an event.
2. Put in the name of the event with quotation marks (single or double).
3. Verify that the title of the event appears with quotation marks already in the calendar.
4. Check also in the dashlet calendar.
=> Fix #10335 - Incorrect codification in the names of events displayed in the Calendar

Api/V8/BeanDecorator/BeanManager.php
SQL error when fetching beans by JSON v1 API with filter on custom filed.
Without filter on custom fields no error.
Fix issue https://github.com/salesagility/SuiteCRM/issues/10319 by added missing log message.
Fix error in Json v1 API.
More details and steps to reproduce here: https://github.com/salesagility/SuiteCRM/issues/10319
=> #10319 fix(JSON API v1) - SQL error when filtering by custom fields

modules/UpgradeWizard/SugarMerge/EditViewMerge.php
Recreation of https://github.com/salesagility/SuiteCRM/pull/9830
Credit to: [@FR-JS](https://github.com/FR-JS)
See  https://github.com/salesagility/SuiteCRM/pull/9830
See  https://github.com/salesagility/SuiteCRM/pull/9830
See  https://github.com/salesagility/SuiteCRM/pull/9830
=> Fix #9829 - Fatal error during upgrade to 7.12.8

include/SearchForm/SearchForm2.php
Fix #10467 
See #10467 
- [X ] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
=> Fix #10467 - Date range not working

modules/ExternalOAuthConnection/controller.php, modules/InboundEmail/Save.php, modules/InboundEmail/language/en_us.lang.php
Fix #9855 
Fix #9855
See #9855
=> Fix #9855 - Using a "Personal"-type Oauth Connection causes issues with "Group"-type Inbound Accounts

themes/SuiteP/css/suitep-base/editview.scss, themes/SuiteP/css/suitep-base/forms.scss
https://github.com/salesagility/SuiteCRM/issues/5287
https://github.com/salesagility/SuiteCRM/issues/5287
=> Fix #5287 - Change secret field is too short

modules/AOW_Actions/actions/actionComputeField.php
https://github.com/salesagility/SuiteCRM-Core/issues/507
https://github.com/salesagility/SuiteCRM-Core/issues/507
=> Fix #507 - Workflows - Calculated Fields - related field won't show up as parameter

modules/Calendar/CalendarActivity.php
https://github.com/salesagility/SuiteCRM/issues/10445
https://github.com/salesagility/SuiteCRM/issues/10445
- [ X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
=> Fix #10445 - Calendar: Calls still show even using Settings: 'Show Calls' = NO

themes/SuiteP/css/suitep-base/studio.scss
Fixes a regression which removed the independent scrollbars for the Toolbox and Layout elements within Layout Editor.
Scrolling in the layout editor has become troublesome.
It is no longer possible to scroll to the panel and field slot you want a field to appear in without the list of fields moving at the sametime.
This change makes it so that the list of fields and the field positions can be scrolled through independantly.
Open Studio and navigate through to the layout editor on a module with enough panels and fields to require scrollbars on both.
=> Add scrollbars for Toolbox and Layout | Studio

include/SuiteEditor/SuiteEditorConnector.php, modules/Campaigns/WizardMarketing.html
Use TinyMCE init function to set template body rather than triggering on page load
Suite7: #9737 
Suite8: https://github.com/salesagility/SuiteCRM-Core/issues/413
Currently in the Campaigns module the Email Template body is sometimes populated before the TinyMCE has finish initialising resulting in the Email Template being set to blank.
This fix moves the onEmailTemplateChange in WizardMarketing.html from being triggered on page load to being triggered on a post init hook in the TinyMCE config. This allows the TinyMCE to initialise before setting the body contents.
Fixes issue with Email Template being set to blank when on the Email Template step in the Campaign wizard.
Create a template and set a template
Relaunch the wizard and navigate to the Email Template step
See that the template …
=> Fix #9737 - Fix issue with campaigns displaying a blank email template

data/Relationships/M2MRelationship.php
Recreated: 
https://github.com/salesagility/SuiteCRM/pull/9036
See: 
https://github.com/salesagility/SuiteCRM/pull/9036
=> Fix #9036 - change log level according it message

modules/AOW_Actions/actions/actionCreateRecord.php
Workflow action Create Record works different from on screen save and CRON.
On cron run it set incorrect date values based on CRON user date time format
When save from screen - all works correct
https://github.com/salesagility/SuiteCRM/issues/10099
There is same workflow runs before and after fix with 3 different sets:
1. When workflow runs from trigger ON_SAVE system user date format not effect on the result 
2. When workflow runs from trigger In_Scheduler with system user date format DD/MM/YYYY+3
3. When workflow runs from trigger In_Scheduler with system user date format YYYY-MM-DD+3
When action "Create record" runs on bean saved from screen, the date in bean are not converted to the user date format, all dates are always in DB GMT format
On cron this action receive bean with **already …
=> #10099 Workflow action create record by Scheduler set incorrect date field values from related entity

include/HtmlSanitizer.php
https://github.com/salesagility/SuiteCRM/issues/10503
https://github.com/salesagility/SuiteCRM/issues/10503
=> Fix #10503 - Item label in dropdown list is not displayed if it contains '<' character

modules/ModuleBuilder/javascript/studio2.js
Recreated: 
https://github.com/salesagility/SuiteCRM/pull/10553
Credits to: [@MoeCond](https://github.com/MoeCondones)
In the Studio module, both the toolbox and layout appeared cropped. The issue was caused by incorrect height calculations in the resizeDivs function. The original calculation referenced Dom.getY('panels'), but changing this to Dom.getY('toolbox') resolves the issue, as the toolbox height needed to be accounted for.
See the issue:
https://github.com/salesagility/SuiteCRM/issues/10421
This fix ensures the layout and toolbox are properly resized in Studio, preventing visual cropping issues and enhancing user experience. This is especially critical for users who need full access to the design elements when configuring layouts in the Studio.
Navigate to the Studio module.
Open …
=> Fix #10421 - Studio | Layout Editor CSS broken

modules/Import/sources/ImportDataSource.php, modules/Import/tpls/last.tpl, modules/Import/tpls/listview.tpl, themes/SuiteP/css/suitep-base/listview.scss
Fix Import Error Styling
Fix the styling of the table that shows when an error occurs on import.
* Import records to any module that could cause an error (with the same ids etc...)
* See updated styling
=> Fix #10599 - Importing Error Styling

modules/AOR_Charts/AOR_Chart.php
=> Remove duplicate line

modules/AOS_PDF_Templates/templateParser.php
- resolve #9809 
This PR modifies the parsing of the PDF templates so that it does not discard values = 0
Values set to 0 in a field of type integer, or in a field of type dropdown with the internal value 0 should be displayed as-is, and are currently not displayed in documents generated using PDF templates.
1. In study create a field of type integer in the Accounts module and call it "amount"
2. Include the field in the edit view and modify a record set it to 0
3. Create a PDF template for the Accounts module including in the body of the template "$accounts_amount_c"
4. Generate the PDF document for the modified record and check that the value of the amount field is displayed correctly.
6. You can repeat the test using a dropdown list that has any of the values set to 0 and check that …
=> Fix #9809 - Incorrect parsing of 0 values in PDF templates

modules/Users/User.php
=> Fix #10661 - Fix preference on setting role

modules/UserPreferences/UserPreference.php
Fix #10637
Fix #10637
1. Enable LDAP
2. Login with a NON-LDAP user
=> Fix #10637 - Local users gets Profile wizard on each login

include/SearchForm/SearchForm2.php, include/SugarFields/Fields/Assigned_user_name/SearchView.tpl
Fixes #10264 
The `{php}` tag was removed from Smarty 3.1.
There was an omission in converting the Smarty code in this code to be compatible with current Smarty version used, in the current maintenance release 7.14.2.
Somehow, this `{php}` tag was left in this template file.  Smarty 3.1 has removed `{php}` tags.  It must be replaced with Smarty 3.1+ compatible code.
Replace old `{php}` tag code with new code that works with Smarty 3.1+.
The software will crash on this screen because `{php}` tag is no longer supported by current Smarty version used.
Run Suite 7.14.2 and go to this screen.  It should fail.
Apply this fix and go to this screen.  It should work.
=> Fix #10264 Error Assigned_user_name SearchView.tpl (`{php}` tag now crashes Smarty 4)

themes/SuiteP/css/suitep-base/yui.scss
Recreating : #9419 
See https://github.com/salesagility/SuiteCRM/pull/8343 for original fix.
Re-created for no action on the original PR.
This now shows all of the part number when autocompleting, in Quotes Line Items
1.  Clear Cache
2. Rebuild Theme
3. See that the autocomplete of the part number now shows the full part number.
=> Fix #8280 - Fix Autocomplete search in line items
