SuiteCRM/SuiteCRM

- include/SugarCache/SugarCache.php
- include/utils/file_utils.php
- include/utils/sugar_file_utils.php
OPcache causes some issues when writing .php files which are read shortly after: in this case the cached version of the file is read instead of the newly written file.
This change improves OPcache handling by
- reverting pull request https://github.com/salesagility/SuiteCRM/pull/339/commits/8833fae04cf9cc7fd2de9718446d56dba82bce77
- using the SugarCache object, which already has an implementation for APC for removing specific files from the cache and implementing OPcache cache refreshing in SugarCache::cleanFile
The refresh of the file cache of OPcache is implemented in a more central place: sugar_file_put_contents, as all write actions of SuiteCRM are processed by this method.
This change solves multiple problems concerning OPcache with SuiteCRM, especially editing layouts in Studio. …
> Fixed #2928 Fixed #341 - clear Zend OPcache when writing files

- modules/SecurityGroups/language/en_us.lang.php
Solved #6651 where a php notice appear in the SecurityGroups modules, in the User subpanel.
The problem was that the SubPanelDef is looking for the LBL_CHECKMARK in the SecurityGroup language file, and not in the User language file, that's where it is.
To avoid this, we added the LBL_CHECKMARK to SecurityGroup language file
> FIX #6651 - Added LBL_CHECKMARK to SecurityGruop language

- include/SubPanel/SubPanelTiles.js
- include/generic/SugarWidgets/SugarWidgetSubPanelEditSecurityGroupUserButton.php
- jssource/src_files/include/SubPanel/SubPanelTiles.js
In case the subpanel layout uses refresh_page=1 then showSubPanel() will start an
async request and after that reload the page. In many cases this will lead to the
just started request being aborted and the page gets reloaded without anything changing.
This was introduced in 829a06f5b8af where the previously sync call was replaced with an
async one.
This is most visible for me in the "Users" module were I can't remove security groups
through the subpanel and it just refreshes the page without removing the group.
Fix this my moving the page refresh check in the ajax callback so the page gets only reloaded
once the request is finished.
Make adding and removing security groups and roles in the Users module work
for example.
(Using Firefox, in case that makes a difference)
1) Admin -> User …
> Fixed #4872 - Fix some async subpanel actions failing if refresh_page=1

- modules/Campaigns/WizardMarketing.html
In 442af7f8539d99c2 the template editor was moved out of the main table to prevent
the table css affect the template editor content.
I missed that the content in the table is replaced in the wizard steps and by moving
the template editor out the editor is now being shown in all steps instead of only the
first one.
Fix this by tying the visiblity state of the editor to the first step panel.
Fixes the template editor being shown in all final steps of the campaign wizard
Create an email campaign, the template editor should only be shown in the template step.
> campaing wizard: fix template editor being shown in all steps

- include/Imap/ImapHandler.php
- include/Imap/ImapHandlerFactory.php
- include/SugarFolders/SugarFolders.php
- modules/Emails/include/ListView/ListViewSmartyEmails.php
- modules/InboundEmail/InboundEmail.php
- modules/Schedulers/_AddJobsHere.php
This PR will fix the importing of email issue.
This PR was created to fix the importing issue - #6440 Emails imported automatically won't allow to change the user assigned to.
To fix the issue (see Description)
1. Set up inbound email account with import emails automatically set
2. Email the inbound email account
3. Check the email address has imported correctly
4. Check that you can assign the email to a user
> fixed #6440 - Emails imported automatically won't allow to change the user assigned to

- modules/Emails/EmailUI.php
- modules/Users/User.php
This PR contains 3 commits, the first two are refactorings, the last one fixes
the issue.
----
In case the user had selected the external email client all email links would
not display any opt-in information (ticks). This is due to the ticks logic
being implemented in EmailUI which is only used in the sugar client case. The
external client path falls back to a simple mailto link.
This makes things always use EmailUI for rendering email links (including
ticks) and makes EmailUI use simple mailto links in case the user settings are
set to an external client.
Fixes #6485
Change the email client setting for the active user. The email links should always contain opt-in ticks.
> Fixed #6485 - Users: Display opt-in ticks also for external email clients

- modules/ACLRoles/EditAllBody.tpl
#6717 
When creating a role, when clicking on any item on the 'Delete' column the background is red and you are unable to read what is displayed in the drop-down menu.
1. Go to 'admin'
2. Then go to 'Role Management'
3. Create a Role and name it.
4. Check the data below and click on any item in the 'Delete' column.
> Fixed #6717 - Create Role - Delete column does not display properly

- modules/Emails/include/ListView/ListViewHeader.js
Small UI change to display the email account name on the folder button in order to make it easier to tell which account you are using.
1. Setup personal email in user profile.
2. View the email module list-view and check the button accurately displays the account name.
> Add email account name to inbox button

- modules/Emails/javascript/Email.js
In #6329 mozaik was set to a dummy object to make it work when not using
the mozaik editor. But the added variable declaration shadows the global
variable breaking the case where mozaik is actually used, setting it to
undefined.
This breaks inserting images into emails, the file gets uploaded but the
URL field stays empty.
Fix this by explicitly checking if we are using mozaik instead of using
a dummy object.
Fixes #6484 which is a regression introduced by #6329
* Use mozaik
* Insert > Insert/edit image
* Select a file and upload
* The "Source" field should contain a path to the added image file
> Fixed #6484 - Fix image insertion with mozaik

- tests/bootstrap.php
This makes sure that users running the test suite locally have the same error
reporting level that is used on travis-ci. For example the default error
level on Debian is "E_ALL & ~E_DEPRECATED & ~E_STRICT" and not E_ALL.
I was confused why travis-ci failed for #6503 while it worked locally.
Run the unit tests.
> unit tests: force enable E_ALL in bootstrap

- modules/Campaigns/WizardEmailSetup.php
Fixed the issue where a user could not set up emails in the campaign module.
Added in a requier_once function to pull in ImapHanderFactory.php file.
Issue reference - #6810
1. Go to the Campaigns module.
2. Click 'set up emails'.
3. The page should appear as normal.
> Fixed #6810 - Campaign page failure/imapfactory

- .travis.yml
Fixes #6759, removing the `composer.lock` has the side-effect of making tests less consistent. This PR changes the `.travis.yml` to make sure the lockfile isn't deleted.
We should always be testing on the same base of dependencies. As long as the commit is the same, we should always have the same dependencies whether it's 2019 or 2029. Deleting the lockfile lets composer essentially install whatever it wants.
Make sure Travis continues to pass.
> Don't delete the composer.lock when running tests on travis.

- modules/ModuleBuilder/javascript/SimpleList.js
Fixed #6786 
This fixes the issue of when adding a space in the drop-down editor it changes to "&20"
1. Go to Admin
2. Go to Dropdown Editor
3. Select a drop down and edit it
4. Put a space in the name
> Fixed #6786 -  Edit item list replace spaces with html entity "%20"

- include/SugarObjects/templates/company/Company.php
- include/SugarObjects/templates/person/Person.php
In some cases a NULL precondition is passed the WHERE results in WHERE (), which is invalid SQL and crashes the export.
Issue reference: #6468 
1. Create a new module using the company and person template.
2. Create some records.
3. Export these records from the list-view.
> Fixed #6468 - Wrong WHERE composition upon NULL precondition in Company

- include/SugarTheme/SugarTheme.php
Fix https://github.com/salesagility/SuiteCRM/issues/4361
Parameter $imageJSONEncode should also be used if returning sprites.
> Fix #4361 Use Parameter $imageJSONEncode if returning sprites, too

- composer.json
- composer.lock
- modules/EmailTemplates/EmailTemplate.php
- tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
When creating an email template with the editor and saving then SuiteCRM
will generate a text version automatically by stripping away tags and decoding
html entities (it also gets regenerated if the text field is cleared before saving)
This currently has the downside that many features of the email are lost,
like basic structure through headings/lists and, more importantly, links.
This patch adds the soundasleep/html2text library and uses it instead to generate the
initial text version. It also adjusts the regex for separating variables from surrounding
text to be less strict to allow using variables in HTML links (see the tests)
This for example makes the generated text from the included opt-in confirmation email usable
without having to manually fix it.
Also adds a few tests for common …
> EmailTemplates: Use html2text library for generating the text only body

- include/DetailView/DetailView.tpl
From commit 
https://github.com/salesagility/SuiteCRM/commit/223c407d9ce6622c11693a450b40493d47004ee2
This commit removes three lines from the `.tpl`. These lines set up a `{if}` that matches a similar block a few lines below. So when it's missing there will be a mismatch of opening and closing `ifs`.
This comes from a [thread in the Forums](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/21596-smarty-error-after-upgrade-7-8-20-7-8-25) and the user has confirmed the fix works.
The bug affects versions 7.8.25, theme SuiteR. It was introduced somewhere after 7.8.20, not sure exactly which.
Produced template files:
```
******************************************************
DetailView.tpl - Suitecrm 7.8.25 - NOT WORKING!
******************************************************
<td …
```
> WIP: Fix regression breaking Accounts detail view

- modules/AOR_Reports/AOR_Report.php
The 'params' value was changed from an array to a string in 6bdf937e9a07cd55e8
but not all usages fixed. This results in the "$att['params']['record_id']" assignment failing
and in lots of "Illegal string offset 'record_id'" errors when viewing a simple report.
This patch renames the 'params' key to 'format', because it's used only for the field format string
at this point, and creates a new $params array for passing the record_id to getModuleField().
From what I see the field format is checked everywhere because the reports module implements
its own date formatting and avoids calling into getModuleField() when a field has its own
a date format set.
This gets rid of the "Illegal string offset" errors and results in the correct record_id getting
passed to getModuleField().
Viewing a simple …
> Reports: fix "Illegal string offset 'record_id'" errors

- themes/SuiteP/tpls/_headerModuleList.tpl
Fixes #2117 - an issue where the more menu item within SuiteP is displayed regardless if the menu item has child elements or not.
This change resolves the 'More' menu item from displaying regardless if the menu item has child elements or not.
1. Login to SuiteCRM
2. Navigate to the user profile -> Advanced
3. Uncheck the 'Module Menu Filter' option
4. Observe the number of child list items in the 'More' item menu
5. Ensure that there is at least one child list item. If there is not, the 'More' menu item should not show
> Fixed #2117 - Redundant More Button in SuiteP

- modules/ACLRoles/EditAllBody.tpl
Fixed an issue where when changing the header of a column in Role Management, the entire column is not updated. This also fixes two other issues, one where the "Delete" column would have the css of a button and one where the css for the individual roles would vary depending on the column (E.g. "edit" doesn't fit in the box, "view" appears to be invisible.
Issue reference: #6778 
1. Go to roles -> Select value in header
2. Check that the style of each header is correct and updates all the items in the row.
> Fixed #6778 - Role Management - Header change doesn't update entire column

- modules/Emails/Email.php
Fixes a PHP error when trying to convert an object to a string.
Issue reference: #6916 
1. Enable confirm opt in.
2. Send a PDF by Email from Quote module
> Fixed #6916 - 7.11.1 Fatal: Object of class EmailAddress could not be converted to string

- modules/Emails/Email.php
```
`SugarPHPMailer encountered an error: Could not access file: upload://c2a5ebd1-5a6d-0f2f-eafe-5c6286a20e74`
```
Issue reference: #6932
1. Send an email with an attachment.
2. Send an email with a document attachment.
3. Sent an email with template attachments.
> Fixed #6932 - 7.11.1: Newer version of PHPMailer is not compatible with Email:email2Send method

- ModuleInstall/ModuleScanner.php
- data/SugarBean.php
- include/utils/file_utils.php
- modules/AOW_WorkFlow/aow_utils.php
This fixes two types or new errors/warnings in PHP 7.3:
(1) PHP Warning:  "continue" targeting switch is equivalent to "break".
Did you mean to use "continue 2"?
In all cases the continue was used as a break anyway, so just replace it
with the less confusing break statement.
(2) preg_replace(): Compilation failed: invalid range in character class at offset 4
Fix by properly escaping the "-" in the regex range.
This makes the unit tests pass with PHP 7.3 (the codeception tests still fail)
Debian has php 7.3 now and this allows me to run the tests there.
Run the unit tests with php 7.3
> unittests: Fixes for PHP 7.3

- include/globalControlLinks.php
Removes the "query=true" from the global employees link so that it doesn't reset the list-view query.
Issue reference: #6936 
1. Click on Employees.
2. Add a filter to the list.
3. Click again on Employees.
4. The query is not reset.
> Fixed #6936 - Global link Employees always reset list query

- tests/README.md
The documentation was linking to https://docs.suitecrm.com/developer/appendix-c---automated-testing when the actual URL is https://docs.suitecrm.com/developer/appendix-c-automated-testing
> Fix link to testing documentation. [ci-skip]

- modules/AOR_Reports/AOR_Report.php
Fixes an issue where downloaded CSV's in reports would always display an empty field.
Issue reference: #2531
1. Create a report that includes a checkbox field
2. Download a CSV of the report and see that the checkbox displays as 1
> Fixed #2531 - 7.10.4 - Report Writer - Boolean Field will not export to CSV

- modules/AOR_Reports/controller.php
Duplicate of PR #5706 
Issue reference: #5706 
1. Create a report that includes a checkbox field
2. Download a PDF of the report and see that the checkbox is visible
> Fixed #5706 - 7.10.4 - Checkboxes are missing in downloaded PDF from Reports

- modules/AOS_PDF_Templates/templateParser.php
Fix PDF templates from setting no value when 0.00 is entered (for 7.8.x)
1. Go to 'Product - Categories' and create a product category.
2. Then go to 'Products' and create a product.
3. Next, go to 'PDF - Templates' and create a template, make sure you put the variable in the body 
($aos_products_quotes_product_discount), and then save the template.
4. Then go to 'Quotes' and create a new quote.
5. Go to 'Line Items' and click 'Add group'. 
6. Add the product you just made and then change the 'Discount' price to "0.00" and save.
7. Once save, Click 'Print as PDF' and then open the PDF.
8. See that the value is now "0%" instead of  " ".
> Fix PDF templates from setting no value when 0.00 is entered

- themes/SuiteP/tpls/_headerModuleList.tpl
- themes/SuiteP/tpls/header.tpl
Currently I'm seeing a lot of notices in my install when show traces is on due to the index not being set in `$_COOKIE['sidebar']`.
I don't want to see warnings for unset indexes
Turn on traces.
Make sure you haven't previously set this cookie (e.g. clear your cookies)
> Give cookie a default value to stop from throwing notices

- include/SugarLogger/LoggerManager.php
This PR fixes #7032 
When implementing a new custom Logger class, there is no way to set the new entry in `$_levelMapping` in `LoggerManager.php`.
For example, if you create a custom logger class like this:
```php
require_once('include/SugarLogger/LoggerManager.php');
require_once('include/SugarLogger/LoggerTemplate.php');
/**
* SuiteCRM WS Logger
* @api
*/
class SuiteWSLogger implements LoggerTemplate
{
public function __construct()
{
$config = SugarConfig::getInstance();
$this->ext = $config->get('logger_ws.file.ext', $this->ext);
$this->logfile = $config->get('logger_ws.file.name', $this->logfile);
$this->dateFormat = $config->get('logger_ws.file.dateFormat', $this->dateFormat);
$this->logSize = $config->get('logger_ws.file.maxSize', $this->logSize);
$this->maxLogs = …
```
> FIX #7032 - Add setLevelMapping method

- modules/Contacts/metadata/SearchFields.php
fix: Any Phone search on Contacts module added missing field phone_home on SearchFields
I have added the **phone_home** field on the **Any Phone** search fields in the Contacts module no issue is referenced I found it and fix it right away
Any Phone search wasn't retrieving records with the searched phone if it only were stored on the phone_home field
Save only one phone number in any contact on the phone_home field then search for it the record won't be retrieved successfully 
Save any other phone number in any of the other phone fields (eg: phone_mobile) look out for the new number in the Any Phone search the record is retrieved successfully
> fix: Any Phone search on Contacts module added missing field phone_home on SearchFields

- tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
testaction_save() changes the DB and depending on the test order this resulted
in other tests failing.
Save and restore the "user_preferences" table in testaction_save() to fix this.
> Fix random unittest error in SugarControllerTest

- modules/EmailTemplates/EmailTemplate.php
- tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
addDomainToRelativeImagesSrc() is supposed to convert images elements of the form
"public/UUID.png" to absolute URLs including the site URL. The regex used here
didn't work because the mozaik editor includes a style attribute at the beginning resulting
in nothing getting replaced.
This makes the regex less strict to handle that case and adds some tests while at it.
Fixes #5662
* Create a email template
* Include an image
* Save
* In the preview check that the image URLs are not relative
> Fixed #5662 - EmailTemplate: Fix images URLs not being converted with mozaik

- themes/SuiteP/tpls/_headerModuleList.tpl
Fixes #6185 - an issue where, if the group tabs menu type is set within the users' profile, the drop down toggle option results in the drop down sub menu remaining on the page if the user clicks a list item within the top navigation such as 'Sales'.
This change resolves the drop down toggle option resulting in the drop down sub menu remaining on the page if the user clicks a list item within the top navigation such as 'Sales'.
1. Login to SuiteCRM
2. Navigate to the user profile -> Layout Options
3. Ensure the 'Module Menu Filter' option is checked
4. Click on a list item within the top navigation menu such as 'Sales'
5. Hover over the top menu list items
6. Observe that the child drop down of the list item that was clicked, does not retract/remove when there is no focus on that element
> Fixed #6185 - Top menu mouse out does not close sub

- themes/SuiteP/include/DetailView/DetailView.tpl
If you change tabs on a module (say from OVERVIEW to MORE INFORMATION or OTHER) while you have a QuickCreate form open on the Activities subpanel, the form disappears but leaves behind 2 sets of SAVE/CANCEL/FULL FORM buttons.
1. Open Studio, module Account, Detail View
2. Under first tab, add panel. Add more tabs (if there are none).
3. Save and Deploy
4. Panel is shown under each tab.
> Fixed issue with tab panel and quick create form

- install/ready.php
As discussed in chat with @Dillon-Brown and @willrennie
It seems our current minimum of 40Mb was letting some people down:
suitecrm.com/suitecrm/forum/installation-upgrade-help/22026-after-suitecrm-7-11-2-fresh-install-get-database-failure
1. Make your `memory_limit` in `php.ini` be 64Mb
2. Restart web server and verify that this took effect
3. Install SuiteCRM, it should install correctly and without any message about memory limits
Then
1. Make your `memory_limit` in `php.ini` be 63Mb
2. Restart web server and verify that this took effect
3. Try to install SuiteCRM, it should install give a message about memory limits
> Increase minimum recommended memory to 64Mb (for 7.8.x)

- install/ready.php
As discussed in chat with @Dillon-Brown and @willrennie
It seems our current minimum of 40Mb was letting some people down:
suitecrm.com/suitecrm/forum/installation-upgrade-help/22026-after-suitecrm-7-11-2-fresh-install-get-database-failure
1. Make your `memory_limit` in `php.ini` be 64Mb
2. Restart web server and verify that this took effect
3. Install SuiteCRM, it should install correctly and without any message about memory limits
Then
1. Make your `memory_limit` in `php.ini` be 63Mb
2. Restart web server and verify that this took effect
3. Try to install SuiteCRM, it should install give a message about memory limits
> Increase minimum recommended memory to 64Mb (for 7.10.x)

- modules/EmailTemplates/EditView.php
When a non-admin user creates a new template the "type" property isn't set resulting
in a PHP error.
Add a check to to prevent that and merge the two identical branches while at it.
1) Log in as a non-admin user
2) Go to Email Templates
3) Try creating a new template
4) Check PHP logs
> EmailTemplates: Fix undefined property error when creating a new template

- modules/AOR_Reports/AOR_Report.php
- modules/AOW_WorkFlow/aow_utils.php
The reports module already hides all fields (in the field list in the bottom left corner)
for modules not accessible to the user but still shows them in the "Module tree" and the
"Report Module" dropdown.
This leads to the users seeing lots of modules and potential relations which are not
usable in the end. To make this clearer also hide inaccessible modules in the module tree
and the module dropdown.
The call to load_report_beans() is moved to fill_in_additional_detail_fields() because
calling into ACLController in the constructor results in an infinite recursion as it
instantiates a AOR_Report itself.
* Users should not see modules they don't have access to.
* Might be a good enough solution for #5497
* Log in as a user that only has access to some modules
* Create a report
* Only the …
> Reports: Hide inaccessible modules in the reports editor

- modules/SugarFeed/SugarFeed.php
- tests/tests/modules/SugarFeed/SugarFeedTest.php
Fixes an issue with sugarfeed showing 0 seconds for all items.
Issue reference: #5918 
1. View "My sugarfeed Dashlet" on homepage.
2. See that the date does not display "0 seconds"
> Fixed #5918 - Activity Stream elapsed time calculation

- modules/ModuleBuilder/parsers/parser.label.php
references issue #551
Added a foreach loop which enumerates through the $labels array and populates the $mod_strings array. This is done so the new labels contained in the $labels array can be added to the labels already existing in the $mod_strings array. 
This foreach loop is added twice in the modules/ModuleBuilder/parsers/parser.label.php file. Once to save new labels in the custom/Extension/modules/Accounts/Ext/Language/en_us.file_name.php file and once to save new labels in the custom/modules/Accounts/Ext/Language/en_us.lang.ext.php file. 
Adding the above mentioned code allows to save new labels for relationships. Before this change Studio would not save new labels into the Extension framework, which caused them to wiped out after Quick Repair and Rebuild.
Field labels constantly …
> Fixed #551 add functionality to save new labels for relationships

- include/SugarObjects/templates/basic/Basic.php
```
PHP message: PHP Notice:  Undefined index: email_enable_confirm_opt_in in /srv/suitecrm/releases/20190314065822/include/SugarObjects/templates/basic/Basic.php on line 104
```
Notices are bad
Use system without `email_enable_confirm_opt_in` in the config file
> Use the provided method to make sure the index exists

- include/InlineEditing/InlineEditing.php
Fixes a PHP fatal causing inline edited date fields to appear blank when updated.
```
Fatal error:  Uncaught Error: Call to a member function format() on boolean in /XXXX/SuiteCRM/include/InlineEditing/InlineEditing.php:445
Stack trace:
#0 /XXXX/SuiteCRM/include/InlineEditing/InlineEditing.php(392): formatDisplayValue(Object(AOS_Contracts), '28/04/2019 00:0...', Array, 'save')
#1 /XXXX/SuiteCRM/include/InlineEditing/InlineEditing.php(370): getDisplayValue(Object(AOS_Contracts), 'start_date')
#2 /XXXX/SuiteCRM/modules/Home/controller.php(64): saveField('start_date', '7ede7c39-69a3-3...', 'AOS_Contracts', '28/04/2019', 'DetailView')
#3 /XXXX/SuiteCRM/include/MVC/Controller/SugarController.php(523): HomeController->action_saveHTMLField()
#4 …
```
> Fixed #7067 - InLine Date Edit bug - Call to a member function format() on boolean

- modules/EmailTemplates/views/view.classic.php
The EmailTemplates modules force enables the subpanels (security groups)
for every view, but the security group sub panel only works in the DetailView
and is broken in others (adding/removing groups doesn't do anything)
To fix this only enable it in the DetailView, like is the case with other modules.
Don't show buttons to users which are broken.
1) Create an email template and save
2) Edit it
3) See the security groups subpanel with non-working actions or see no subpanels with this patch
> EmailTemplates: Only show subpanels in the DetailView

- lib/Search/ElasticSearch/ElasticSearchHooks.php
Fixes an issue where the callback for save beans in the ElasticSearchHooks would trigger regardless of whether elasticsearch was enabled.
Issue reference: #6998 
1. Disable elasticsearch.
2. Refresh the homepage and check the log, you should no longer see elasticsearch errors.
> Fixed #6998 - cron.php fails because there is no check whether ElasticSearch is enabled

- include/SugarObjects/LanguageManager.php
Labels defined in the Extension framework (for example after exporting customizations from Studio and loading the module with Module Loader on another instance) can not be changed with Studio.
The change is properly saved in custom/modules/Calls/language/en_us.php
But it is overriden when LanguageManager loads custom/modules/Calls/Ext/Language/en_us.lang.ext.php which includes the original field label
Context : Any version of SuiteCRM.
Change order of loaded language files
- Add a field to Calls with Studio
- Export customizations
- Load the generated module in another instance
- Go to Studio and change the label of that field.
- The change is not taken into account.
Labels customization with Studio
> Fix priorities when loading language files

- modules/AOR_Reports/metadata/subpaneldefs.php
Adds a security groups subpanel at the bottom of a reports detail view.
Otherwise there is no way to change security groups for reports.
When I create new records I'd like to assign them to the security groups that
are going to use them.
* View a report
* See the security groups subpanel at the bottom of the page
> AOR Reports: Add a security groups subpanel

- modules/AOR_Reports/aor_utils.php
Fixes a typo in report utils when fetching the getPeriodDate.
Issue reference: #5968 
Create a report using a Last Quarter date period condition and check that the results are returned correctly when the current date is in the 4th quarter.
> Fixed #5968 - AOR Reports - incorrect start date calculated for LastQuarter period when in the 4th quarter

- modules/AOR_Reports/aor_utils.php
When the current date is in the last month of a quarter (i.e. March, June, September or December) then conditions based on date quarter periods do not work properly - causing incorrect results often returning no data rows when there should be.
Issue reference: #5967
Check that a report with conditions based on on date period This Quarter or Last Quarter returns the correct results.
> Fixed #5967 - AOR Reports - incorrect calculation for date quarter periods

- include/SugarTheme/SugarTheme.php
- include/SugarTheme/getImage.php
- tests/unit/phpunit/include/SugarTheme/SugarThemeTest.php
The getImage entry point only handled setting the correct mime type for
gif and png images. In case of svg images (for example the icon left of attachments in
the email template editor) the returned content type was text which made firefox
show an error and not display the image.
Fix this by adding mime types for all supported image extensions in SugarTheme
and using that in the getImage end point.
This also adds some basic tests for this new API.
In the email template editor the attachments had broken images
* Access `index.php?entryPoint=getImage&themeName=SuiteP&imageName=Accounts.svg`
* Check the returned content type
> Fix Content-Type header missing in some cases for the getImage entry point

- modules/AM_ProjectTemplates/css/style.css
From the forums:
https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/22160-add-new-task
Adding and editing Project Template tasks is broken.
1. Create Project Template, and add a task to it.
2. In the Template's detail view, try to a) add a task or b) edit an existing task
3. In the pop-up dialog box, there is a radio button to select between `Task` and `Milestone` which is hidden under the words (use browser console to figure it out), and therefore unusable.
My proposed change makes it visible and usable again.
I tried this on SuiteCRM 7.11.2.
> Fix obscured milestone radio buttons in Project Templates

- include/StateCheckerPHPUnitTestCaseAbstract.php
- tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
- tests/unit/phpunit/include/MVC/View/views/view.vcardTest.php
phpunit provides helpers for testing and redirecting test output but this is broken
by the added code in the test base class which prints test context during the tests
and gets treated as test output by phpunit.
To work around this write straight to STDOUT instead of going through the output buffer
for the test context.
This also adds some calls to setOutputCallback() and expectOutputRegex() to remove
the output/noise of some tests.
* Noisy output
* Not being able to use expectOutputRegex()/expectOutputString() etc.
* Run the test suite
> phpunit: Reduce test noise & make output test methods work

- jssource/src_files/include/javascript/EmailsComposeViewModal.js
- modules/Emails/EmailUI.php
Currently when a user has set their email client to internal (Mozaik) then the email's displayed with a link to some javascript for the popup. This means you can't simple right click on the link and "copy email address".
I would like it to be easier to copy the email address
* Set email client to Mozaik
** Click the link and see a pop-up of the internal email client
** Right click the link and see "Copy Email Address"
* Set email client to external
** Click the link and see that your operating system handles the email address
> Add href mailto for email links even when using internal email client

- modules/Campaigns/WebToPersonCapture.php
- modules/EmailMan/EmailMan.php
In case one uses "Send Confirm Opt In Email" in the "Actions" menu of a contact/lead etc
then action_sendConfirmOptInEmail() gets called which in turn calls EmailMan::sendOptInEmail().
This leads to the email being sent without any send/fail dates being recorded.
To fix this set the dates in EmailMan::sendOptInEmail() instead of leaving it to the caller.
Also remove the date set code from WebToPersonCapture because that's no longer needed now that
sendOptInEmail() handles it.
I have some logic which depends on the opt-in dates and while it works when adding a record through the web form it doesn't work when I manually add a contact and send an opt-in email through the actions menu.
* Create a record
* In the Actions menu send an opt-in email
* Look in the "email_addresses" table of the …
> Also set opt-in send/fail dates when sending emails through the action menu

- modules/Campaigns/WebToPersonCapture.php
- tests/unit/phpunit/include/UtilsTest.php
In case the the web form contains a multi select field the resulting value is
passed as an array. This was assigned as is to the newly created record and
probably thrown out at some later point because it wasn't a string.
To fix this use encodeMultienumValue() to convert the value list to the
expected internal format and assign that instead.
I've also noticed that encodeMultienumValue() doesn't have any tests, so I've
added some in a separate commit.
I have a form which uses multi select fields and want them to end up in the
created lead record.
I suspect that this fixes #3598
* Add a new multi select field to Leads
* Create a "Web to Person" form including the multi select
* Fill out the form and submit
* The selected values should show up in the CRM
> Fixed #3598 - WebToPersonCapture: Fix assignment of multi select values

- modules/InboundEmail/InboundEmail.php
- tests/unit/phpunit/data/SugarBeanTest.php
- tests/unit/phpunit/include/MVC/Controller/SugarControllerTest.php
- tests/unit/phpunit/include/MVC/View/SugarViewTest.php
- tests/unit/phpunit/include/SugarEmailAddress/SugarEmailAddressTest.php
- tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
- tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
- tests/unit/phpunit/modules/SchedulersJobs/SchedulersJobTest.php
This tries to improve the tests to be less dependent on the order they are run in.
Motivated by them failing a lot locally on my machine.
saveMailBoxValueOfInboundEmail: only used in the tests and failed due to wrong casing
and copy/paste errors (not sure why it worked on travis, maybe less strict mysql)
Properly save/restore User::field_defs. This made various tests later on fail because
User beans fetched from the DB were incomplete and only partially saved back, due to
the missing field defs.
Various state save/restore needed for passing with RUN_PER_TESTS.
The only remaining test class not passing with RUN_PER_TESTS is InboundEmailTest because
it depends on the test methods running in a specific order and fixing this would have
been too much code change. This adds a class level …
> phpunit: Various fixes for running with StateCheckerConfig::RUN_PER_TESTS

- jssource/src_files/include/javascript/sugar_3.js
Fixed #4297 - Error in Listview : Pagination - wrong "Selected" count
When I changed page in ListView, the "Selected" count didn't follow and the bulk action was not active.
Go to a ListView (like Campaigns for example), check many items and change page. See if the count is OK.
> Fixed #4297 - Error in Listview : Pagination - wrong "Selected" count

- modules/Tasks/metadata/subpanels/ForActivities.php
For the collection subpanel, date_due was aliased to date_start, while it should be displayed in the date_end field.
Fixes #6689 
1. Create Opportunity
2. Create Task with due date
3. Due date shows up in Subpanel
> Fix #6689 Task date_due not displaying in Activities subpanel

- modules/Campaigns/utils.php
- tests/unit/phpunit/modules/Campaigns/CampaignTest.php
While the functions are not exposed right now escaping things can't hurt.
I noticed that these functions weren't tested, so this adds some basic tests
for subscribing/unsubscribing a lead to/from a newsletter campaign.
I'd like to use these in an entry point.
Run the tests suite
> Campaigns: escape subscribe()/unsubscribe() IDs and add tests

- .travis.yml
This should significantly reduce the test output in CI by removing the debug flag (and removing some verbosity flags that were missed in #6907).
Per `./vendor/bin/codecept run --help`, the `-d` flag 'Shows debug and scenario output'. It should still give debug info if the test fails, it just won't print a bunch of logging for every successful test (which is essentially just noise).
~~I also turned off the `verbose` option in the phpunit XML config file, since that was the majority of the CI log once the debug flag was removed for the other test types.~~ This didn't fix the PHPUnit output. Unfortunately since we're on such an old version of PHPUnit and I'm not able to get the test suite to run locally, I'm not sure how to even improve the PHPUnit output. We can leave that for another PR. …
> Remove debug flags from codecept run commands in travis.yml

- Api/V8/JsonApi/Repository/Filter.php
- Api/V8/Param/Options/Filter.php
Fixes an issue where API filtering includes deleted records by default.
Adds a default filter parameter to use when no filters are specified.
Injects a deleted = 0 filter parameter when the list of filter parameters doesn't specifically include deleted records.
Most API operations are unaffected by this issue because we use a Bean function to actually retrieve records, so deleted records are filtered.
However, for the `[meta][total-pages]` a count query is run which does not include the deleted = 0 parameter, and thus returns a number of pages based on the total rows in the db, deleted or not.
1. Make sure your Accounts db table contains deleted records as well as non deleted records.
2. Do a call to `Accounts?fields[Account]=name,account_type&page[number]=1&page[size]=1`
3. Observe the …
> Fix API list total pages display

- Api/V8/Param/Options/Attributes.php
The `Attributes.php` parameter uses the `Fields.php` parameter's regex pattern to verify that attributes were formatted correctly. I've added a new regex to `Attributes.php` as the `fields` parameter validation shouldn't be re-used in the attributes class since while the `fields` parameter needs to restrict spaces and Unicode, attributes doesn't. 
I've also removed the ```Assert\NotBlank``` validation as we shouldn't need to exclude blank values.
It is currently impossible to create/edit a record with a space or Unicode character in any of the fields due to the attributes validation using ```REGEX_FIELD_PATTERN = '/[^\w-,]/'```.
Issue reference: #6452 
Issue reference: #6893 
```
POST SuiteCRM/Api/V8/module
BODY {
"data": {
"type": "Accounts",
"attributes": {
"name": "Cocacola company", …
```
> Fixed #6452 - Api/V8 create record does not support unicode and space in attributes

- Api/V8/JsonApi/Helper/RelationshipObjectHelper.php
Replace the lower case module names in the relationship links in API responses by the actual relationship identifiers.
Previously the response structure for records contained relationship links which were broken in those cases where the relationship identifier wasn't the same as the lower case module name.
Fixes #7121 
1. Make an API call to get a single record (example Contacts)
2. In the list of relationships, select one where the relationship identifier is NOT the same as the related module name (example FP_events, AM_ProjectTemplates - NOT Accounts)
3. Follow the link and make sure it returns a list of related records
> Fix API relationship links

- Api/V8/JsonApi/Helper/PaginationObjectHelper.php
- Api/V8/JsonApi/Helper/RelationshipObjectHelper.php
The new API states the base_uri should `https://crm.example.org/Api/`.
This means all links returned from the API need to be relative to this `base_uri`.
According to [Guzzle explanation of RFC 3986](http://docs.guzzlephp.org/en/stable/quickstart.html#making-a-request) the `base_uri` with a path should end with `/` and the relative link should start without a `/`.
Full Example usage of this would
```php
<?php
$client = new \GuzzleHttp\Client([
'base_uri' => 'https://crm.example.org/Api/',
]);
$url = 'V8/module/Notes?page[size]=20';
do {
$response = $client->request('GET', $url);
$body = json_decode((string)$response->getBody());
$data = $body->data;
// Do something with data
$url = property_exists($body, 'links')
&& property_exists($body->links, 'next')
&& !is_null($body->links->next) ? …
```
> Links returned in the API should be relative to the base_uri

- Api/V8/JsonApi/Repository/Filter.php
- Api/V8/JsonApi/Repository/Sort.php
Fix the check for existing fields in the filtering and sorting in the API.
Previously this was checking for the fields as properties on the bean. However custom fields are not explicitly defined as properties. Instead we check the field defs which is a more reliable indicator of whether or not a field exists.
Without this fix it is not possible to filter or sort on any custom field.
Calling the API with a custom field as a filter will fail before this fix and work as expected afterwards.
The related issue (https://github.com/salesagility/SuiteCRM/issues/6455) provides information.
> Fix custom fields in sort/filter in the API

- Api/V8/BeanDecorator/BeanListRequest.php
Use singleSelect for the underlying call to `SugarBean->get_list` from API get modules endpoint
When passing singleSelect = false to the `SugarBean->get_list` function, relate fields are not filled out correctly but padded with empty spaces.
Regular ListView in CRM passes singleSelect = true to this function, therefore the API should too.
Example json response diff:
1. Choose a module that has a relate field ( Example Contacts )
2. Do a getModules API call `/V8/module/Contacts`
3. In the result json, make sure the relate fields contain id and name of the related record
> Api - fix relate fields not populating on get_list

- Api/V8/JsonApi/Repository/Filter.php
- Api/V8/JsonApi/Repository/Sort.php
As custom fields are not explicitly defined as properties, you were unable to filter with them. With this fix, we use the field definitions instead of the properties.
Issue reference: #6455 
1. With the V8 API, check that using a custom field as a filter works as expected.
> Fixed #6455 - The V8 API does not allow filtering by custom fields

- service/v4_1/SugarWebServiceUtilv4_1.php
Using V4_1 API, get_relationships with ```$order_by = 'date_entered desc'``` causes the returned results to be in a random order instead of desc. 
Issue reference: #5746
1. Call get_relationships using V4_1 with $order_by = 'date_entered desc'.
2. Check that the returned results are correct.
> Fixed #5746 - Unable to order results descending on get_relationships API method

- service/v4_1/SugarWebServiceUtilv4_1.php
Improve `get_relationships` method of version 4_1 of the API, allowing descending sort of results.
Now you can call get_relationships and set order_by parameter like `date_entered desc`.
The change consists on pass `$order_by` to `getBeans()` params array on `getRelationshipResults()` method.
Actually is not possible to sort the results of `get_relationships` method descending.
Apply the changes and call `get_relationships()` using `$order_by = 'date_entered desc'` and see that results are ordered using `date_entered` field in a descending manner.
> Fix #5746 - Unable to order results descending on get_relationships API method

- include/SugarEmailAddress/SugarEmailAddress.php
When confirmed opt-in is enabled then converting a lead with a confirmed email
address to a contact makes the address lose its confirmation.
AddUpdateEmailAddress only gets a flag if opt-in is set or not, and when trying to update
the existing email record it replaces the COI_STAT_CONFIRMED_OPT_IN state with just
COI_STAT_OPT_IN because of that.
To fix this, in case the passed opt-in flag is 1 and the existing record has some kind
of opt-in state (!COI_STAT_DISABLED) we use that existing state to update the record instead
of forcing COI_STAT_OPT_IN.
In case of a lead conversion where nothing is changed this result in no DB update being
performed on the address.
I'd prefer if converting a lead wouldn't change the opt-in status of the
linked email address.
* Create a lead, set email and …
> Fix emails losing confirmed opt-in when converting a lead to a contact

- include/SugarObjects/templates/basic/metadata/detailviewdefs.php
- include/SugarObjects/templates/company/metadata/detailviewdefs.php
- include/SugarObjects/templates/file/metadata/detailviewdefs.php
- include/SugarObjects/templates/issue/metadata/detailviewdefs.php
- include/SugarObjects/templates/sale/metadata/detailviewdefs.php
add 'default' => to the panel name, so that changes to the view retain the "date by name" format. To reproduce bug, create any custom module, then edit the detail view and see that the "date by name" format is lost and it will instead just be the date field.
It solves the issue of custom modules not having the "date by name" format if you change the view at any point. There is caching issues with just having the date fields.
Create any module, use one of the templates which have been changed in the MR. Modify the detail view - see the bug as specified. Apply fix and retest and see that date by name format is there.
> Change default view on template to avoid date created/modified issues

- data/Relationships/M2MRelationship.php
Added conditions (module = 'Module' AND deleted = '0') to where clause for query that deletes from securitygroups_records and securitygroups_users.
securitygroups_records identifies record by `record_id` and `module` columns.
Also when querying just by securitygroup_id and record_id, indices not used. It is slow in big databases.
Remove group from some record. Watch query log.
Current example:
```sql
UPDATE securitygroups_records set deleted=1 , date_modified = 'x' WHERE securitygroup_id = 'x' AND record_id = 'x'
```
Fixed example:
```sql
UPDATE securitygroups_records set deleted=1 , date_modified = 'x' WHERE securitygroup_id = 'x' AND record_id = 'x' AND module = 'Opportunities' AND deleted = '0'
```
> Improve where clause when removing securitygroups relationships.

- modules/InboundEmail/InboundEmail.php
Fixes an issue where the email body of non-imported emails would appear to be blank when the email imap subtype was not html or plain.
Issue reference: #7166 
1. Setup inbound email.
2. Check the body of imported and non-imported emails is visible.
3. Check that the body is visible in emails with different IMAP types (HTML, PLAIN, etc)
> Fixed #7166 - Upgrade to 7.11.3 version email body is empty

- modules/AOR_Reports/AOR_Report_Before.js
The main report module is added to the module tree as well, but with an empty
module_path. When selecting related modules the module paths get concatenated
with the root module which is empty in this case and results in a wrong module
path being stored in the report.
This patch works around the issue by checking for an empty module_path before adding
the next module to the path.
Note that this wont fix existing reports that are broken because of this because
the wrong path is saved in the database and persists.
There is really no difference in the children of the first module and the other
toplevel nodes, so ideally the main module wouldn't have any child nodes in the first
place, but this would require more work and can be changed another time.
It's currently easy to create reports which …
> Fixed #6037 - Reports: Fix adding relations from the first tree node

- modules/AOW_WorkFlow/AOW_WorkFlow.php
If field value contains single quote, on each save CRM will treat this field as a changed and trigger all Worflows with condition AnyChange on this field
fix issue #6126
1. Create Account with single quote in name
1. Create Workflow with condition AnyChange on Account name field
3. Open and save Account without changes
4. Workflow should not be triggerd
> #6126 fix(Workflow AnyChange condition) - decode prev value before compare

- Api/V8/Config/services/beanAliases.php
- Api/V8/Param/Options/Attributes.php
Maps the EmailAddress class to EmailAddresses.
Issue reference: #7080 
Call with V8 API: ```{{suitecrm.url}}/V8/module/EmailAddress```
Before fix:
```
{
"errors": {
"status": 400,
"title": null,
"detail": "Module EmailAddress does not exist"
}
}
```
>  Fixed #7080 - API returns wrong module string address for email addresses

- Api/Core/Config/ApiConfig.php
- Api/V8/Config/services/middlewares.php
- composer.json
- composer.lock
- install/install_utils.php
- install/language/en_us.lang.php
- install/performSetup.php
- modules/Administration/QuickRepairAndRebuild.php
- Removes the hardcoded ```OAUTH2_ENCRYPTION_KEY``` from APIConfig and generates it if empty. 
- Generate ```OAUTH2_ENCRYPTION_KEY``` through Repair&Rebuild if empty.
- Generate ```OAUTH2_ENCRYPTION_KEY``` on install.
- Explicitly require [```paragonie/random_compat```](https://github.com/paragonie/random_compat) in composer. This allows us to use the PHP 7 functions ```random_bytes()``` and ```random_int()``` in PHP 5 and above. We are already using these functions in the v8 API with this lib being pulled down as a dependency of other libs, this just makes sure it won't get removed accidentally.
1. Call ```{{suitecrm.url}}/V8/module/Accounts/.```
2. Go to ```Api/Core/Config/ApiConfig.php``` -> ```const OAUTH2_ENCRYPTION_KEY``` and check that the value has been updated.
3. Replace …
> Remove hardcoded encryption key

- modules/InboundEmail/InboundEmail.php
Fixed ```PHP Notice: Undefined property: stdClass::$message_id ```.
Issue reference: #7221 
1. Check that you don't see any undefined ```$message_id``` notices when using the InboundEmail module.
> Fixed #7221 - stdClass::$message_id undefinded for IMAP

- include/SugarObjects/LanguageManager.php
Let the system has multiple languages installed, the system default language is different from the language of the current user and a language cache files has not yet been created. Let there is a custom module created on the Basic template using language files from the template. Then, during the initial creation of the cache for the user's language, the language files from the template will not be used.
This change solves the problem described above by taking check the creation of a cache for each system language separately.
To check it is necessary to repeat the sequence described above.
> Bug fix create language cache in multilanguage system

- Api/Core/app.php
- install/install_utils.php
- modules/Administration/UpgradeAccess.php
With apache+php-fpm the authorization header gets stripped and never
reaches the app. The .htaccess already includes some rules to pass them through
with an env var, but because of the rule order this is never applied.
Fix the rewrite rules by moving the env var rules before the rules marked as [L]ast.
Passing an env var with a rewrite rule results in apache prefixing the env
var with "REDIRECT_". To work around this copy REDIRECT_HTTP_AUTHORIZATION to
HTTP_AUTHORIZATION in case only the former is set.
I wanted to try the API, but it didn't work.
I also found similar issues in the forum (which inspired this patch):
* https://suitecrm.com/suitecrm/forum/installation-upgrade-help/21465-missing-authorization-header
* https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/19783-missing-au …
> Fix V8 API authorization header passing with apache+php-fpm

- install.php
Corrects syntax error in install.php:
SuiteCRM]$ php -l install.php 
PHP Parse error:  syntax error, unexpected '===' (T_IS_IDENTICAL), expecting ')' in install.php on line 269
Errors parsing install.php
> install.php: Syntax error upload logo

- modules/Campaigns/ProcessBouncedEmails.php
- modules/Emails/Email.php
- modules/InboundEmail/InboundEmail.php
- modules/Notes/Note.php
- tests/unit/phpunit/modules/Emails/EmailTest.php
Bounce handling is currently broken for multiple reasons:
(1) The imported bounce email is saved in the notes description field which is
marked as text and strips away all HTML on save(). This removes/mangles the
link containing the tracking ID so the attachment can't be linked to the
campaign log later on.
(2) SMTP servers usually return the original email as an attachment on a
bounce and include an addition attachment containing the delivery status (RFC
3464). Since this attachment wasn't saved, hard bounces weren't detected.
(3) In case the tracking ID makes it through and the email is considered a
hard bounce then marking the email as invalid failed because
markEmailAddressInvalid() was called with an email object but expected a
string.
To fix all these:
For (1) we don't save the …
> Fixed #6504 - Fix and implement proper bounce email handling

- .travis.yml
Currently all tests are running with Ubuntu 14.04 which includes MySQL 5.6
which is unlikely to be used by any newer setup.
Assuming that systems with a newer PHP version also use a newer MySQL switch the
PHP 7.x jobs to Ubuntu Xenial and thus to use MySQL 5.7 instead.
The unittests currently have problems with the default MySQL 5.7 configuration,
see #7107, so force unset the strict sql mode in the travis setup script for now.
This should make it easier to test the fix for #7107 and to prevent similar issues
in the future.
Make sure SuiteCRM works with MySQL 5.7 as advertised in the compatibility matrix.
Let travis-ci do its thing.
> travis-ci: Switch the PHP 7.x jobs to Ubuntu 16.04

- include/SubPanel/SubPanelDefinitions.php
Did not find at which point it was fixed for 7.10, but should be backportet to 7.8.x
https://github.com/salesagility/SuiteCRM/blob/1892b13ecfcd9a9e3cd575c8b4b3336188e86f28/include/SubPanel/SubPanelDefinitions.php#L432
> Add return to function

- modules/EmailMan/EmailManDelivery.php
When querying the emailman table the code didn't take deleted records and links into
account which could result in test emails being sent to persons no longer linked to
the campaign.
This adds deleted checks to the query.
Also adds a deleted check for the emailman entries for both test and non-test cases
while at it.
Fixes #6420 
Moving test lists around shouldn't result in weird email sending behavior.
* Create a newsletter campaign
* Add yourself to the test list
* Remove the test list from the campaign and add it back again
* Send a test mail
* The mail should only be sent once
> Fixed #6420 - Campaigns: don't send test emails to lists no longer linked to the campaign

- modules/Charts/Dashlets/OpportunitiesByLeadSourceDashlet/OpportunitiesByLeadSourceDashlet.php
- modules/Emails/EmailUI.php
- modules/Leads/views/view.convertlead.php
- modules/Project/Project.php
- modules/Project/chart.php
- modules/Project/controller.php
Fixes a lot of cases of the `$db` global variable from #7241.
See [this commit](https://github.com/salesagility/SuiteCRM/commit/98e8b6e5d8125f2b268a9975cf3d472edebbd98a#diff-3577c448a121183734986b4b6f848826) and [this PR](https://github.com/salesagility/SuiteCRM/pull/5718), where these were originally changed.
Make sure the test suite passes and that the queries I've changed still work.
> Replace $db global variable in a bunch of files

- modules/EmailTemplates/EmailTemplateData.php
- tests/bootstrap.php
- tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
Usually when creating a record where it's not possible to assign a user the current
user is assigned instead.
This didn't happen in the campaign wizard when copying or creating a new email template.
This assigns the current user and adds a unit test while at it.
Fixes #6445
* Create a new marketing entry in a campaign
* Copy any existing template or save a new one
* The new template should be assigned to you
> Fixed #6445 - Campaign Wizard: Assign current user when creating a new template

- include/StateSaver.php
- modules/EmailTemplates/EmailTemplate.php
- modules/EmailTemplates/Save.php
- tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
This contains three commits which should make including images in email
templates a bit less buggy:
1) Fix the unittest state saver so that the email_templates table can be
pushed/popped in tests.
2) Extend repairEntryPointImages() to handle all types of img tags, not just
some common mozaik ones.
3) When saving the template move images to public/ instead of depending
on repairEntryPointImages() to fix it later.
* Sometimes including images in mozaik will result in download entry point URLs
which are not public.
* I'm currently testing CKEditor which always triggered this because the img
tags have a different default attribute order there.
* Create an email template
* Upload an image and include it
* Save
* The image src should be an absolute URL using the public/ dir.
> EmailTemplates: Improve image url replacement

- service/core/SoapHelperWebService.php
Fixes an issue where strings with zero padding still have it when decrypted which causes issues when logging in via ldap.
To solve issues with logging in via api via ldap.
Login via api ensuring you are using a string which is zero padded. See that it will not work. Try again with fix applied
> Fix zero padding issue with openssl decryption

- .travis.yml
An alternative to #7087 to disable storing hash debug traces while running the tests but without removing the functionality altogether.
Run the unit tests.
> StateChecker: Don't save hash debug traces

- .gitignore
- lib/Robo/Plugin/Commands/BuildCommands.php
Removes old style sheets for sub-themes of SuiteP. Gets dynamic with searching the stock SuiteP dir and `/custom/them` dir.
fixes #7308
Removed the hardcoded sub-theme references and dynamically search the `theme/SuiteP/css/` directory for any possible directories that may contain any `style.css` or `style.scss` indicating they are a subtheme definition. If a `style.css` file is found remove it in prep for the new file to be compiled. This goes the same for the `custom/theme/` directory also. Theme directories are stored in variables so they can be updated later or possibly specified as params in the future.
Updated the `buildSuitePColorScheme()` function to accept an additional `$location` parameter with a default definition. This allows flexibility when directing what subthemes to …
> fixes #7308 - Sub-Theme changes don't always update

- include/InlineEditing/inlineEditing.js
Don't replace linebreaks on email fields when inline-editing.
Fixes #5173.
When inline-editing and then saving an email field, linebreaks (`\n`) inside the string returned by the backend were turned into `<br/>` elements, which caused the anchor tag to close early and display the HTML attributes as plaintext:
- Open the Contacts view
- Create a Contact with an email
- Go back to the Contacts list view
- Double click the email of the contact to inline-edit it
- Modify the email address
- Hit the checkmark to save
- Note that the email is rendered properly, instead of being rendered like the screenshot above.
You can also test inline-editing a field with linebreaks to verify that this change doesn't cause a regression to the problem described in #3136.
> Fix #5173 by disabling linebreak replacement on email fields during inline edit

- .travis.yml
- lib/Robo/Plugin/Commands/CodeCoverageCommands.php
- tests/bootstrap.php
- tests/unit/phpunit/lib/SuiteCRM/Robo/Commands/CodeCoverageCommandsTest.php
This changes the PHPUnit configuration to allow PHPUnit to be run from
outside the tests directory.
There's not really a good reason to require it be run from `./tests/`.
This changes the PHPUnit test suite to be runnable from the root directory instead of needing to be within the `tests/` directory. This is a backport from my GitLab CI PR.
Verify that Travis CI still works. Also verify that the code coverage in Travis CI still works. I'm not 100% sure on that one.
I don't know if this needs a documentation change?
> Run PHPUnit outside the tests directory

- tests/travis_config_si.php
The test suite gained new tests (callTest.php) which depend on the date format
being 'd/m/Y'.
This changes the date in travis_config_si.php so that test setups using
tests/testinstall.php continue to work as before.
a
> tests: change the test config default date format to match the unit tests

- cron.php
- include/utils.php
- modules/UpgradeWizard/systemCheck.php
- modules/UpgradeWizard/uw_ajax.php
- modules/UpgradeWizard/uw_utils.php
According to the previous discussion on #6344, I examined 8 places in the code and decided to update 5 of them, the others aren't necessary.
1. https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/systemCheck.php
2. https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/uw_ajax.php
3. https://github.com/salesagility/SuiteCRM/blob/master/modules/UpgradeWizard/uw_utils.php
These 3 instances are only using this to output a message to the user. I guarded the code for the case where `posix` functions are disabled, and made sure the output made sense.
4. https://github.com/salesagility/SuiteCRM/blob/master/cron.php
Added an if before the others, so that a proper message is logged.
5. https://github.com/salesagility/SuiteCRM/blob/master/install/performSet …
> Fix #6343 handling posix not allowed on some Linux systems

- modules/Home/index.php
Fixes an issue where a custom MySugar.tpl is never loaded due to a missing slash.
Issue reference: #7357 
1. Create the custom file ```custom/themes/' . $theme . '/include/MySugar/tpls/MySugar.tpl```.
2. Check that this file is loaded in home module index.
> Fixed #7357 - Home module index page loading bad MySugar file location

- tests/_support/Helper/WebDriverHelper.php
- tests/acceptance/lib/Search/ElasticsearchCest.php
The ElasticSearchCest had the hostname hard-coded to `localhost`. This was a problem I ran into with #7328, so I'm backporting it.
ElasticSearch didn't exist prior to 7.11.x, so it only needs to be merged into `hotfix`.
Make sure the Acceptance tests continue to pass in Travis.
> Configurable elasticsearch host in acceptance test

- .php_cs.dist
- composer.json
- lib/Robo/Plugin/Commands/CodingStandardCommands.php
Adds the php-cs-fixer package to the `composer.json` explicitly.
I'm opening this as a PR into hotfix because php-cs-fixer doesn't support PHP 5.5, which SuiteCRM 7.8.x and 7.10.x both still support.
The `composer.json` didn't specify php-cs-fixer despite the fact that we use it for the Robo style check command. This commit adds it explicitly to the `composer.json` so it will be installed by default for developers and so everyone will be able to use the same version of the package.
Run `composer install` and run the phpcsfixer Robo task with `./vendor/bin/robo style:phpcsfixer`, if it lints files and fixes any issues, it works.
I guess this is a bug fix?
> Add php-cs-fixer to composer.json as a dev dependency.

- .travis.yml
- include/StateCheckerConfig.php
- include/StateCheckerTrait.php
* Makes save_traces default to false
* Print stacktraces always
* Remove the travis config override which is no longer needed now
This is a better version of #7087
I couldn't run the full test suite on my local machine because they needed too much
memory (>16GB)
Run the unit tests.
> StateChecker: disable save_traces by default

- .travis.yml
- include/database/MysqliManager.php
STRICT_TRANS_TABLES is enabled by default with MySQL 5.7 and some tests
fail with it due to missing values in SQL insert/update statements.
Given that our test coverage isn't that high there might be more issues
not covered by the tests, so better disable STRICT_TRANS_TABLES to get the same
behavior as with MySQL 5.6 for now.
Fixes #7107
Make the test suite pass with MySQL 5.7
Run the test suite (see travis-ci)
> Fixed #7107 - MysqliManager: always remove STRICT_TRANS_TABLES from sql_mode

- tests/_envs/travis-ci-hub.yml
- tests/_support/AcceptanceTester.php
- tests/acceptance/Core/BasicModuleCest.php
- tests/acceptance/Core/CompanyModuleCest.php
- tests/acceptance/Core/FileModuleCest.php
- tests/acceptance/Core/IssueModuleCest.php
- tests/acceptance/Core/ModuleBuilderFieldsCest.php
- tests/acceptance/Core/PersonModuleCest.php
- tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
This PR has two major changes that are done to reduce test suite flakiness at the cost of speed:
- Remove login snapshots
- Clear cookies between tests
This adds somewhere between 1 and 3 minutes to the length of the acceptance suite, but it should significantly reduce the amount of times we need to re-run the tests in CI due to flaky test failures. I think that's an acceptable trade-off.
It removes a bunch of conditional logic that assumed logins could be skipped in certain situations (the cookie clearing causes these to no longer work). It also disables an AOW_Workflow test that was dependent on the state of a previous test, since I didn't want to deal with fixing that problem right now.
Note for reviewers: Disable showing whitespace changes in the diffs to make them a bit easier to …
> Fix flaky tests

- tests/_support/Step/Acceptance/Calls.php
- tests/_support/Step/Acceptance/Dashboard.php
- tests/_support/Step/Acceptance/DetailView.php
- tests/_support/Step/Acceptance/EditView.php
- tests/_support/Step/Acceptance/ListView.php
- tests/_support/Step/Acceptance/Meetings.php
- tests/_support/Step/Acceptance/ModuleBuilder.php
- tests/_support/Step/Acceptance/NavigationBar.php
- tests/_support/Step/Acceptance/Workflow.php
- tests/acceptance/Core/ModuleBuilderFieldsCest.php
- tests/acceptance/modules/Accounts/AccountsCest.php
- tests/acceptance/modules/Activities/ActivitiesCest.php
- tests/acceptance/modules/History/HistoryCest.php
Part of #7344.
This removes explicit timeouts from all calls to waitForElementVisible in the acceptance test suite. If a page failed to load, the test would wait for the entire timeout before failing. This made running the test suite locally pretty painful, especially when a test would fail. It would also make the test suite take significantly longer than normal when a change introduced failures.
Generally, most of these should never take more than the default 10 second timeout, so they're unnecessary.
Make sure Travis passes.
> Remove explicit timeouts in acceptance tests.

- data/SugarBean.php
Fix an elusive bug which sporadically causes incomplete beans to be cached by BeanFactory, resulting in variables not pulling through to email templates, pdf templates, and generally causing malfunctions.
While filling relationship fields during SugarBean->retrieve, a check is in place to avoid infinite recursion.
Only top level beans are fully retrieved, while the beans we retrieve to fill out the top level relationship fields don't have their own relationship fields filled out.
1. Load an Account bean
2. `Account->retrieve` calls `Account->fill_in_relationship_fields`
3. `Account->fill_in_relationship_fields` calls `Contact->retrieve` to set any relate fields there might be
4. `Contact->retrieve` calls `Contact->fill_in_relationship_fields`, but since it's nested the check kicks in and …
> Avoid caching incomplete beans in during SugarBean->fill_in_relationship_fields

- download.php
Change the headers being sent for file downloads.
Previous downloaded files could get cached by browsers (or other intermediaries) due to the cache headers not being strict enough.
Fixes #4116 
This issue only appear on some browsers. I haven't been able to reproduce the issue myself, but the person who brought the issue to my attention followed these steps (Which are the same as were reported in #4116 ):
1. Clear browser cache
2. Go to import records into any module
3. Make sure your import.csv contains at least one error
4. Do the import
5. Download the error.csv
6. Change your import import.csv so it triggers different errors
7. Do the import of the updated csv
8. Download the error.csv
9. See the downloaded error.csv contains the errors from the second import instead of the first, so …
> Fix #4116 Prevent download files from being cached

- tests/acceptance.suite.yml
- tests/install.suite.yml
These are unnecessary since they're handled by the travis config.
The only problem this would cause is if a custom env isn't used, but the acceptance and install suites using different settings by default when run locally is also bad. I'd say this is probably better than the current situation, and #7433 will help with this as well.
> Simplify the acceptance and install suite configs.

- modules/AOR_Reports/aor_utils.php
- modules/AOW_WorkFlow/aow_utils.php
If a timezone is set in the users profile to negative GMT - America/New York (GMT -4:00) for example, when saving a report with a date condition, the condition is saved as the previous day.
See #7370 
Set user profile time zone to America/New York
Create a report with a date field condition set to: Equal to -> Value -> 15/05/2019
Save report
Records returned will be for the 14/05/2019
> Fix issue #7370

- include/Imap/ImapHandlerFactory.php
- tests/unit/phpunit/include/Imap/ImapHandlerFactoryTest.php
The ImapTestSettings.txt file wasn't properly disposed-of, which caused testGetImapHandlerOk to fail.
The file was created by a function in `testGetImapHandlerOk` and it caused the test to fail because a file at `include/Imap/ImapTestSettings.txt` to not be deleted.
This solves one of the state-related failures in the PHPUnit suite.
Run the PHPUnit tests locally with the developerMode enabled and make sure the IMAP tests pass.
> IMAP StateSaver test fix

- .travis.yml
This should speed up CI a bit. This is a backport from hotfix.
Original PR was #6834. There was also #6833 but it was closed, I'm not really sure why? @Dillon-Brown
It makes Travis CI runs slightly faster. You can see it in action if you look at a job for a commit on hotfix vs. one for hotfix-7.10.x:
- hotfix: https://travis-ci.org/salesagility/SuiteCRM/jobs/548726541 (8 seconds spent on `composer install`, all dependencies pulled from cache)
- hotfix-7.10.x: https://travis-ci.org/salesagility/SuiteCRM/jobs/548779265 (40 seconds spent on `composer install`, needed to install all the dependencies)
I think we just forgot to backport it before? 🤷‍♂ 
As long as Travis passes we should be good, it's the exact same change as the PRs mentioned above and those work fine.
> Cache Composer files in Travis. (hotfix-7.10.x PR)

- .travis.yml
This adds a job to Travis that validates that the `composer.json` and `composer.lock` are in sync.
I forgot to update the `composer.lock` when adding php-cs-fixer and had to fix it in #7450. This job shouldn't take very long to run and would fix this problem.
Make sure Travis passes.
> Add composer validate job in Travis.

- tests/unit/phpunit/data/SugarBeanTest.php
- tests/unit/phpunit/include/MVC/SugarApplicationTest.php
- tests/unit/phpunit/include/MVC/View/views/view.ajaxuiTest.php
- tests/unit/phpunit/include/MVC/View/views/view.classicTest.php
- tests/unit/phpunit/include/MVC/View/views/view.detailTest.php
- tests/unit/phpunit/include/MVC/View/views/view.editTest.php
- tests/unit/phpunit/include/MVC/View/views/view.importvcardsaveTest.php
- tests/unit/phpunit/include/MVC/View/views/view.sugarpdfTest.php
- tests/unit/phpunit/lib/SuiteCRM/Exception/ExceptionTest.php
- tests/unit/phpunit/lib/SuiteCRM/Utility/CurrentLanguageTest.php
- tests/unit/phpunit/lib/SuiteCRM/Utility/ModuleLanguageTest.php
- tests/unit/phpunit/lib/SuiteCRM/Utility/PathsTest.php
- tests/unit/phpunit/lib/SuiteCRM/Utility/StringValidatorTest.php
- tests/unit/phpunit/lib/SuiteCRM/Utility/SuiteLoggerTest.php
- tests/unit/phpunit/modules/ACLActions/ACLActionTest.php
- tests/unit/phpunit/modules/ACLRoles/ACLRoleTest.php
- tests/unit/phpunit/modules/AOD_Index/AOD_IndexTest.php
- tests/unit/phpunit/modules/AOP_Case_Updates/AOP_Case_UpdatesTest.php
- tests/unit/phpunit/modules/AOR_Charts/AOR_ChartTest.php
- tests/unit/phpunit/modules/AOR_Conditions/AOR_ConditionTest.php
- tests/unit/phpunit/modules/AOR_Reports/AOR_ReportTest.php
- tests/unit/phpunit/modules/AOR_Scheduled_Reports/AOR_Scheduled_ReportsTest.php
- tests/unit/phpunit/modules/AOS_Contracts/AOS_ContractsTest.php
- tests/unit/phpunit/modules/AOS_Invoices/AOS_InvoicesTest.php
- tests/unit/phpunit/modules/AOS_Line_Item_Groups/AOS_Line_Item_GroupsTest.php
- tests/unit/phpunit/modules/AOS_PDF_Templates/AOS_PDF_TemplatesTest.php
- tests/unit/phpunit/modules/AOS_Products/AOS_ProductsTest.php
- tests/unit/phpunit/modules/Accounts/AccountTest.php
- tests/unit/phpunit/modules/Alerts/AlertTest.php
- Remove incomplete tests for SugarBean, incomplete tests cause the test suite to run significantly slower when the state checker runs with `RUN_PER_TEST` for no real reason. They're replaced by a comment listing all the functions that still need tests.
- Formatting fixes that remove excessive whitespace, and a few typo fixes.
- Remove unnecessary StateChecker invocations in a few tests where they aren't used.
Improve unit suite speed when using the state checker, and also formatting and readability of tests.
Honestly the PHP CodeSniffer should just be backported to 7.10 and added to CI, but that's a whole other thing.
Make sure the tests still pass on Travis and make sure the formatting changes look acceptable.
> Remove some incomplete tests and miscellaneous formatting fixes for the unit test suite

- tests/_support/Step/Acceptance/Calls.php
- tests/_support/Step/Acceptance/Campaigns.php
- tests/_support/Step/Acceptance/EditView.php
- tests/_support/Step/Acceptance/ListView.php
- tests/_support/Step/Acceptance/ModuleBuilder.php
- tests/_support/Step/Acceptance/NavigationBar.php
- tests/acceptance/Core/ModuleBuilderFieldsCest.php
- tests/acceptance/Core/PersonModuleCest.php
- tests/acceptance/modules/Activities/ActivitiesCest.php
- tests/acceptance/modules/History/HistoryCest.php
- tests/acceptance/modules/Home/HomeCest.php
- tests/acceptance/modules/Meetings/MeetingsCest.php
- tests/acceptance/modules/Users/UsersCest.php
- tests/acceptance/modules/jjwg_Maps/jjwg_MapsCest.php
Part of #7344.
This makes the tests faster by removing a lot of usages of `$I->wait(x)` with `$I->waitForElementVisible(x)` or `$I->waitForText(x)`. Essentially, the problem with using `$I->wait` is that it waits for the full x number of seconds even if the page loads in the mean time.
```php
// Waits 10 seconds no matter what.
$I->wait(10);
$I->click('button');
// Will wait up to 10 seconds if necessary, otherwise it will skip to the click as soon as the element is visible. 
$I->waitForElementVisible('button');
$I->click('button');
```
Individually, these usually only add a few seconds each. Once you add two dozen or more, though, it can unnecessarily add over a minute to the test suite.
It also introduces potential flakiness if the tests take longer on another machine than on Travis, …
> Replace most instances of $I->wait(n) with waitForX. 

- modules/Users/User.php
This updated user password hashing to use the new php password_hash implementation. This is greatly increase the security of user password stored in the database. It is fully backward compatible with previous password hashing, used in SuiteCRM, so should not cause any issues with users already using previous implementations of password hashing.
1. See that you can login to the application, api(s) using the existing password standard and backward compatible standards.
3. Update your password and see that it stored using the more secure hash and test that you can still login in all places.
> Update password hash to use php password_hash by default

- tests/phpunit.xml.dist
We use these options explicitly in Travis, and they make running the tests without stopOnFailure/Error enabled unnecessarily difficult.
Also, note that this is essentially a backport from #7374. If that's merged before this, this PR won't really be necessary.
I want to run the PHPUnit suite to completion and it's not possible to do so locally without changing this file, which is annoying to do whenever I switch branches. Plus, we explicitly use the flags in CI so there's not really a reason to set them in the PHPUnit config.
Run PHPUnit locally without `--stop-on-error` or `--stop-on-failure` and see if it stops on either of those cases occurring.
This is technically a breaking change because people could have relied on the old behavior in scripts they'd written?
> Disable stopOnFailure and stopOnError in PHPUnit config.

- jssource/src_files/include/javascript/jsclass_async.js
Fixes the meetings scheduler displaying the wrong time.
The meeting scheduler was displaying created meetings shifted along to the right by 1 hour regardless of the users set timezone.
Issue reference: #1840
1.  Rebuild Minified JS Files
2. Clear cache + hard reload
3. Create a meeting.
4. Open the meeting and check the scheduler is at the right time.
> Fixed #1840 - Meetings in scheduler shifted by one hour

- composer.json
- composer.lock
I failed to update the lockfile when I added php-cs-fixer to the `composer.json` in #7206. Whoops. It needed to be added with `composer require friendsofphp/php-cs-fixer` to prevent other packages from being updated at the same time.
@Dillon-Brown Note that #7441 also fixes this problem, so if that's merged before this, this PR can be closed. Alternatively, if this is merged you'll probably need to rebase that, sorry 🙇 
This caused the PHP CS Fixer Robo tasks to fail (not that they worked before, since there were no packages in the `composer.json` anyway).
Run `composer install` locally and make sure it works and doesn't mention that the `composer.lock` is out of date with `composer.json`.
You can also try `./vendor/bin/robo style:phpcsfixer-dry-run` to make sure it runs (it doesn't …
> Update composer.lock to include php-cs-fixer.

- tests/acceptance/modules/Home/HomeCest.php
It seems like we may just need to wait for the text to be visible before sending the click.
This is meant to fix the flaky test described in https://github.com/salesagility/SuiteCRM/issues/7272#issuecomment-505589148
Check if Travis passes. It may also be worth re-running the test jobs in CI to see make sure it doesn't re-occur, since it doesn't seem to happen often enough for 6 test runs to be sufficient
> Try to fix a flaky test in HomeCest.

- lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
This resolves one of the problems in #7344.
The Robo task will now automatically install the latest version of ChromeDriver instead of installing a static version.
Also improves wording/grammar in various places.
The ChromeDriver Robo task was stuck at an older version of ChromeDriver, `2.38`. This isn't compatible with the latest release of Chrome, so it doesn't work unless you're on an older version of Chrome.
The `LATEST_RELEASE` URL system is based on how [the webdrivers gem](https://github.com/titusfortner/webdrivers) installs ChromeDriver, and also based on the ChromeDriver documentation.
Install ChromeDriver with the Robo task (`./vendor/bin/robo chromedriver:install`) and then make sure it runs properly (`./vendor/bin/robo chromedriver:run`). It should install ChromeDriver 75. …
> Get ChromeDriver's latest release in Robo task.

- modules/ModuleBuilder/javascript/ModuleBuilder.js
When saving chaned labels in Studio, or when hovering over an event in the Calendar, a popup appears. This popup doesn't automatically disappear when expected.
https://github.com/salesagility/SuiteCRM/issues/3756
Studio popups
1. Go to Labels of a module.
2. Make a change and click save.
> FIXED #3756 - Popup Studio and Calendar don't auto-close

- modules/Meetings/metadata/subpanels/ForHistory.php
Fixed a database error with the history subpanel.
Issue reference: #7267 
1. Create a lead.
2. Add a note to the history subpanel.
3. Add a task to the activities subpanel.
4. Edit the task and save. Upon redirection, you should be taken back to the lead detail-view and the due date of the task should be visible with no database errors.
> Fixed #7267 - Database Failure after upgrading to Version 7.11.4

- modules/InboundEmail/InboundEmail.php
Fixed an issue with email auto-reply not sending attachments.
Issue reference: #5552 
1. Create a group email account. 
2. Set Auto-reply template with attachment.
3. Send an email to the group email account.
4. Check that the auto-reply email has the attachment.
> Fixed #5552 - Inbound Email Auto-reply send email without Attachments

- lib/Robo/Plugin/Commands/TestEnvironmentCommands.php
- tests/_envs/custom.dist.yml
Some follow-up fixes/improvements to the custom codecept config:
- Set the 'smart wait' time to 0 in the custom codecept config, to match CI.
- Add an optional ChromeDriver background process to the custom config. This can be used to run ChromeDriver whenever the tests are run, instead of needing to run it in a separate terminal window whenever you want to run the test suites.
- Fix the command suggested when installing ChromeDriver.
Backported from #7374.
Shouldn't really require testing, just make sure the changes make sense.
> Misc automated testing improvements.

- modules/AOR_Scheduled_Reports/metadata/subpaneldefs.php
- modules/AOR_Scheduled_Reports/vardefs.php
- tests/unit/phpunit/modules/SecurityGroups/SecurityGroupTest.php
Without security groups when a user creates a new scheduled report then no
other user in the same security group can see/edit the record.
This adds security group support to the module and also adds a security groups
subpanel in the detail view so the group relations can be edited.
I'd like to use scheduled reports in combination with security groups.
* (Run a repair to adjust the relations)
* Create a scheduled report with a user that is in a security group
* Log in as a different user in the same group and see/edit the scheduled report
> Scheduled Reports: Enable security groups support and add the subpanel

- include/MVC/SugarApplication.php
Fixed an issue where the session path would be set to "/" and ignore changes made to session.cookie_path.
Issue reference: #6935
1. Install suitecrm inside a folder (/alpha)
2. Add the following to .htaccess: ```php_value session.cookie_path /alpha```
3. Login and check path for cookies
>  Fixed #6935 - Cookie path is not respected if globally set

- data/Relationships/One2MBeanRelationship.php
If you call `getQuery` method on One2Many relationship using custom fields on `order_by` or `where` optional parameters you've got the following error:
```
Query Failed: SELECT id FROM tasks WHERE tasks.contact_id = '62f50b22-c255-ccc9-a2e2-5a871e7b989' AND tasks.deleted=0 AND tasks_cstm.tipo_tarea_c = 'tipo1' LIMIT 0,10: MySQL error 1054: Unknown column 'tasks_cstm.tipo_tarea_c' in 'where clause'
```
This is caused due missing JOIN with cstm table.
See issue #5754 
This is `7.10.x` version of #5755
If optional `order_by` or `where` parameter is specified on `getQuery` method of One2Many relationship do a JOIN with custom table of module (if has custom table).
I'm trying to get related records of a bean filtering by a custom field.
1. Call `getQuery` method on One2Many relationship using …
> Fix #5754 - Error with custom fields on getQuery from One2Many relationships (7.10.x)

- tests/acceptance/modules/Home/HomeCest.php
This wait is necessary right now because the chartCategory button isn't necessarily clickable immediately, which can cause flaky failures.
I previously tried fixing it with #7473, but that didn't fix the problem and it was pretty much just a guess since I didn't think I could reproduce the failures locally. This time, I ran the test repeatedly locally and was able to reproduce it somewhere around 1 in every 5 or so test runs.
With this change, I've run it 30 times now and I haven't seen it fail, so I'm fairly certain this fixes the problem.
You can see my description of the flaky test here: https://github.com/salesagility/SuiteCRM/issues/7272#issuecomment-505589148
Solves a source of test flakiness that was really annoying me, since I kept hitting it on my PRs. I'd prefer to not use …
> Add wait to HomeCest so it won't flake.

- lib/Robo/Plugin/Commands/TestRunCommands.php
Part of #7344. This adds Robo tasks for easily running the four different test suites in a consistent way. 
- `./vendor/bin/robo tests:install`
- `./vendor/bin/robo tests:acceptance`
- `./vendor/bin/robo tests:api`
- `./vendor/bin/robo tests:unit`
The test commands are pretty long and annoying to type, and also hard to discover. This PR makes Robo commands that make running the tests simple and consistent.
I intend to update the automated testing documentation to incorporate these changes and simplify the general process of a developer running the test suite locally.
You'll need to set up the `tests/_envs/custom.yml` codeception config file (see https://docs.suitecrm.com/developer/automatedtesting/). You'll also need to either uncomment the part of the config with the background …
> Robo test-running commands

- data/SugarBean.php
- include/MVC/SugarApplication.php
- include/utils.php
- modules/Activities/EmailReminder.php
- modules/Emails/EmailUI.php
- modules/Home/QuickSearch.php
- modules/Home/sitemap.php
- modules/Users/authentication/EmailAuthenticate/EmailAuthenticateUser.php
- service/JsonRPCServer/JsonRPCServer.php
- service/JsonRPCServer/JsonRPCServerCalls.php
- tests/unit/phpunit/include/UtilsTest.php
- vCard.php
This can be used instead of accessing the global "current_language" variable.
Replace various accesses to the "authenticated_user_language" session var
with a call to get_current_language().
Adds some basic unit tests.
@gymad suggested not accessing the global "current_language" in another PR, so I looked into providing a function for this instead and found lots of duplicated code that could be replaced with it.
Run the unit tests.
> Add a get_current_language() helper function

- modules/Emails/metadata/detailviewdefs.php
- modules/Emails/metadata/nonimporteddetailviewdefs.php
Unified the imported and non-imported email detail-views:
- Added Date Sent/Received to non-imported and imported emails.
- Fixed the date_entered on imported emails.
Issue reference: #6973 
Issue reference: #4881 
Check the detail-view of imported and non-imported emails.
> Fixed #4881 - Detail view of no imported email is different as imported + missing time unit + attachments

- include/language/en_us.lang.php
Added AOS modules in record_tpye_* drop downs. It is usefull, that at least Calls can have Contract/Quote/Invoice as parent.
Added selection of AOS_ modules as related to: fields in en_US.lang.php
Added selection of AOS_ modules as related to: fields in en_US.lang.php
To be able to select Contracts, etc in related to field in Activities (Calls, Meetings, ...)
Crete Call. Select Contract as related to: field
- [ X] My code follows the code style of this project found [here](https://docs.suitecrm.com/community/contributing-code/coding-standards/).
> FIX issue #7567: Missing Contracts from selection of Related to: field

- tests/_support/Step/Acceptance/Accounts.php
- tests/acceptance/_bootstrap.php
- tests/acceptance/modules/Accounts/AccountsCest.php
- tests/acceptance/modules/Users/UsersCest.php
It now uses a database call instead of inputting values via a form.
This is based on how it's done in the API tests. It should make the tests faster.
See #7484.
The contents of the `createAccount` method were moved to the AccountsCest file, where the accounts are created as part of a test. That's the only place this should be used.
Make sure the tests continue to pass :)
Also, when this PR is merged it'll need a bit of work to be merged into hotfix, see https://github.com/salesagility/SuiteCRM/commit/30d2076bf0be6bde71814130719ccd3d4078d3b2. I'm pretty sure you can just take the changes I have here and apply them to AccountsTester.
> Replace the createAccount method

- include/InlineEditing/inlineEditing.js
When you edit inline a fields, click outside the field you get an alert. This is cool and good, but even if I dont make any change to the fields I get the alert.
https://github.com/salesagility/SuiteCRM/issues/7209
1. Inline edit a field.
2. Click outside the field.
> FIXED #7209 - Inline Edit alert Even if I dont make a change.

- include/ListView/ListView.php
Fixes PHP notice ```A non-numeric value encountered at ListViewSubPanel.php, line 323```.
Issue reference: #7608 
1. Reports -> Schedule Report subpanel.
2. Check for PHP errors.
> Fixed #7608 - A non-numeric value encountered at ListViewSubPanel.php

- modules/AOP_Case_Updates/CaseUpdatesHook.php
Prevents a blank email being sent by AOP when 'User Email Template' is set to 'None'.
Issue reference: #7599 
1. Set all AOP template choice dropdowns to 'None'
2. Process an inbound email
> Fixed #7599 - Unwanted email generated in case creation & update

- tests/acceptance/Core/BasicModuleCest.php
- tests/acceptance/Core/CompanyModuleCest.php
- tests/acceptance/Core/FileModuleCest.php
- tests/acceptance/Core/IssueModuleCest.php
- tests/acceptance/Core/ModuleBuilderFieldsCest.php
- tests/acceptance/Core/PersonModuleCest.php
- tests/acceptance/modules/AOW_Workflow/AOW_WorkflowCest.php
These were made unnecessary by #7417, and I hadn't gotten around to cleaning them up until now. They were used to do certain things depending on the previous test that was run, but this introduced non-determinism into the tests and caused them to flake, so removing these shouldn't impact anything. I doubt this'll cause any problems for the hotfix merge, but it might be worth keeping in mind just in case any tests had a `lastView` declaration added between 7.10 and 7.11.
It's dead code.
Make sure Travis passes.
> Remove lastView variables from tests.

- tests/_support/Helper/Acceptance.php
Fixes #7419! Now the acceptance tests can be run as many times as you want, without needing to worry about the files that are left behind by previous test runs.
This doesn't take very long, so it shouldn't add any noticeable runtime to the acceptance suite.
Unfortunately, there are still two files modified by the acceptance tests, which I didn't fix: `Api/Core/Config/ApiConfig.php` and `custom/modules/unified_search_modules_display.php`. The former is modified to include an `OAUTH2_ENCRYPTION_KEY` (can we make that an environment variable or something?) and the latter is just some spacing changes (should I just commit the changed version of this file so it doesn't get changed every time we run the tests?).
This allows me to run the acceptance tests locally without worrying about the …
> Cleanup files created by acceptance tests between test runs

- include/utils.php
Fix #6996
Avoid adding quotes on already quoted parameters by using already existing `quote` method instead of concatenating quotes with php dot operator.
Improve the way values are quoted when replacing parameters in `SELECT` clauses, for only adding quotes if needed.
Fixes #6996 
See #6996
1. Browse ListView of any module that uses "My favorites" filter, for example: Projects.
2. Set "My Favorites" checkbox to checked.
3. Click Search button.
4. The query should be generated properly without throwing errors.
> Avoid adding quotes on already quoted parameters.

- include/SugarPHPMailer.php
(SugarPHPMailer.php)
This is a continuation of https://github.com/salesagility/SuiteCRM/issues/6932 which in Suitecrm 7.11.3 is still not fixed. The bug should be reopened.
Check original https://github.com/salesagility/SuiteCRM/issues/6932 . Basically in our scenario campaigns are sent without attachments.
Try to send a campaign with an attachment and monitor suitecrm.log.
A message like:
```
SugarPHPMailer encountered an error: Could not access file: upload://63534f9e-c81e-b9ff-1f52-5ca76adc945e
```
> Fixes SugarPHPMailer encountered an error: Could not access file

- include/InlineEditing/inlineEditing.js
This uses [prettier](https://prettier.io) and some minor manual tweaking to improve the readability/consistency of `InlineEditing.js`.
The JavaScript file was inconsistent and pretty messy, I wanted to fix that.
It doesn't seem like there's a minified version of InlineEditing.js in the repo? Please correct me if I'm wrong, the minification/concatenation in the admin panel didn't seem to change any relevant files.
Make sure inline editing still works, see that the tests pass.
Code cleanup.
> Format InlineEditing.js with prettier.

- modules/ACLRoles/ACLRole.php
This was causing my editor to highlight uses of getUserRoleNames as an error when it was used as an array.
Doesn't really need tests, just review the change.
> Add a proper return type to getUserRoleNames()

- modules/Campaigns/ProcessBouncedEmails.php
Make sure the scan for the header is case insensitive to make it more robust. Some SMTP services convert "X-CampTrackID" to lowercase, making it "x-camptrackid".
SuiteCRM identifies the bounce either by the opt-out link or the e-mail header. In case an email is bounced and the contents of the email are in base64 format, SuiteCRM checks this header.
Some SMTP Services like outlook.com convert headers to lowercase. In this case, "x-camptrackid" is not identified accordingly.
This change adds robustness for SMTP services that change the case of email headers.
See https://github.com/salesagility/SuiteCRM/issues/7712
> Fixed #7712 - case insensitive detection of header X-CampTrackID

- .github/config.yml
Config file for SuiteBot, a GitHub application to help manage our GitHub workflow.
Current features:
- Automatic creation of the "Sprint Planning" issue.
- Automatic creation of the "Current Sprint" issue, populated with stats from the previous sprint.
- Auto label PRs made to invalid or EOL branches.
- Auto comment PRs made to invalid or EOL branches.
- Auto label of "Community Contributed" PRs to help with metrics.
- Auto label issues that don't follow the template.
- Auto comment issues that don't follow the template.
- Slash command functionality to add labels (Can easily be extended).
- Auto label of "WIP" PRs
- Adds a check to "WIP" which fails until "WIP" is removed.
- Adds a check to "Requires Review".
Any suggestions for more functionality welcome! I'll look at making a repo for …
> SuiteBot config.yml

- modules/Users/User.php
Creating a new user does not generate a new password for the user and does not send a new account email. This started happening to me when I upgraded from 7.10.2 to 7.10.13
https://github.com/salesagility/SuiteCRM/issues/6982
1. Go to create new user page
2. Create new user
3. No password generated and no email sent to the new user
> FIXED #6982 - New user password not being generated.

- lib/Robo/Plugin/Commands/TestRunCommands.php
The robo command always quit with a 0 return status which makes it not usable
in a CI environment.
Fordward the comman result to make the robo command fail when tests fail.
I'd like to run the tests in CI
* `./vendor/bin/robo test:unit`
* It should return != 0 in case test fail
> Make "robo test" commands fail if tests fail

- .travis.yml
- lib/Robo/Plugin/Commands/CodeCoverageCommands.php
Removes an unncessary limitation of the robo code coverage command so that it now allows a non-ci envionment get code coverage.
Issue reference: #7622 
1. Check Travis.
2. Run ```./vendor/bin/robo code:coverage``` and retrieve code covage info.
3. Run ```./vendor/bin/robo code:coverage --ci``` and it should fail with no ci detected.
> Fixed #7622 - Make the code:coverage Robo command work outside of CI

- modules/Alerts/templates/default.tpl
Previously, any modules that were plural (most of them) were getting an `s` appended to their names in order to load the image for that module, leading to the CRM trying to load images like `Leadss.gif`, which does not exist. This only applies the `s` when the module name isn't already plural (this is done by just checking if the module name ends with an `s`, which isn't perfect but better than before). This also changes the icons from `.gif` files to html tags that render the icon font, since most other static image icons have been replaced already by #5273 and #5457.
Fixes #6264 (which should not be closed)
Before:
Now it looks like this:
Icons weren't loading.
~~Ideally, this would be fixed by replacing the gif with a `span` using the new icon font, as I mentioned in my comment on …
> Fix icons not rendering properly in Alerts.

- lib/Robo/Plugin/Commands/BuildCommands.php
Read #7781
Read #7781
Run:
```bash
$ ./vendor/bin/robo build:suite-p --color_scheme Dawn 
```
And verify that only Dawn color_scheme is compiled
> FIX #7781 - Now we can compile SuiteP only one color_scheme

- modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
- modules/SugarFeed/SugarFeed.php
See the commits for details:
* Fixes creating feed entries for non-english users
* Fix php error log spam
* Fix delete links not being shown for feed entries and replies
* Make things work like in 7.10.18
* As a non-english user try to create a feed entry
* Create a feed entry and try to delete it again
* Create a reply to an entry of a different user and try to delete it again
> SugarFeed: Various fixes for 7.10.19/20 regressions

- include/ListView/ListViewSubPanel.php
Removing an item from subpanel should only require the item edit access right
Removing an item from subpanel should only require the item edit access right
Currently the code look for Delete access right in order to remove an item from subpanel. This should not be needed. We are not removing the item. We are just removing the item relationship with another item - in other words - editing it.
Create a lead with another login. Login as another user. Create an account.  Add relationship between the account and the lead. With the change, the user with edit right to the lead should be able to remove the lead from Account Lead subpanel
> Removing an item from subpanel should only require the item edit access right

- lib/Robo/Plugin/Commands/TestRunCommands.php
This allows one to run only one specific test method of a test class, which is
helpful when you implement a new test or want to investigate a specific failing one.
The --filter option is passed as is to phpunit, see https://phpunit.readthedocs.io/en/latest/textui.html
for details.
* ``./vendor/bin/robo tests:unit --filter testdeleteFavorite ./tests/unit/phpunit/modules/Favorites/FavoritesTest.php``
> Robo: Add a --filter option to tests:unit for filtering tests

- lib/Robo/Plugin/Commands/BuildCommands.php
Read #7836
Many times it is very useful to have a custom theme (based in SuitP) to modify things in a safe upgrade mode. With this PR we can compile the css of that theme.
```bash
./vendor/bin/robo build:theme --theme=BCCL                                                                         
➜  Compile BCCL Theme (SASS)
➜  Found style.css for Dusk, Removing
➜  Found style.scss for Dusk, Compiling
[Exec] Running ./vendor/bin/pscss -f compressed themes/BCCL/css/Dusk/style.scss > themes/BCCL/css/Dusk/style.css
[Exec] Done in 18.49s
➜  Found style.css for Night, Removing
➜  Found style.scss for Night, Compiling
[Exec] Running ./vendor/bin/pscss -f compressed themes/BCCL/css/Night/style.scss > themes/BCCL/css/Night/style.css
[Exec] Done in 18.618s
➜  Found style.css for Dawn, Removing
➜ …
```
> FIX #7836 - Robo task to compile css in a custom theme

- include/database/DBManager.php
- include/database/MysqlManager.php
- include/utils.php
- include/utils/array_utils.php
- tests/unit/phpunit/include/utils/arrayUtilsTest.php
This PR fixes #7675
See #7675
1. Go to on admin
2. Click on quick repair and rebuild
3. Verify that (if you have already created in DB) the following index it is not created again:
```sql
ALTER TABLE users DROP INDEX idx_user_name, ADD INDEX idx_user_name (user_name,is_group,status,last_name (30),first_name (30),id);
```
> FIX #7675 - Add a function to compare properly indices definitios

- download.php
- include/SugarFields/Fields/File/SugarFieldFile.php
Fixed undefined index in document upload and download.
Issue reference: #7838
```
Tested in 7.10.20:
[Mon Sep  9 19:17:47 2019] PHP Notice:  Undefined index: docType in /home/jose/trabajos/SuiteCRM/include/SugarFields/Fields/File/SugarFieldFile.php on line 158
[Mon Sep  9 19:17:47 2019] PHP Stack trace:
[Mon Sep  9 19:17:47 2019] PHP   1. {main}() /home/jose/trabajos/SuiteCRM/index.php:0
[Mon Sep  9 19:17:47 2019] PHP   2. SugarApplication->execute() /home/jose/trabajos/SuiteCRM/index.php:52
[Mon Sep  9 19:17:47 2019] PHP   3. NotesController->execute() /home/jose/trabajos/SuiteCRM/include/MVC/SugarApplication.php:113
[Mon Sep  9 19:17:47 2019] PHP   4. NotesController->process() /home/jose/trabajos/SuiteCRM/include/MVC/Controller/SugarController.php:373
[Mon Sep  9 19:17:47 2019] PHP …
```
> Fixed #7838 - 'Undefined index: docType' PHP notice

- modules/Connectors/connectors/sources/ext/rest/twitter/config.php
modules/Connectors/connectors/sources/ext/rest/twitter/config.php produces PHP Fatal error: 
```Uncaught Error: Cannot use string offset as an array when hitting CRM home.```
Simply initialise the config array before assignments.
Check for PHP fatals on the homepage.
> Fixed #7779 - PHP Fatal error in modules/Connectors

- include/Smarty/plugins/function.suite_check_access.php
- themes/SuiteP/tpls/_headerModuleList.tpl
Read #7810
1. Create a Contact with a non admin user.
2. Login with admin user
3. Create a new Role and let that role to edit only owned records
4. Assign another user (different from step 1) to the new Role
5. Login with that user.
6. Go to the DetailView of the Contact created in step 1.
7. Verify there is pencil in Top Menu only for records you can edit
> FIX #7810 - Pencil present in Top Menu for users with non editing permission

- modules/Emails/Email.php
- modules/Emails/EmailsController.php
- modules/Emails/include/ComposeView/ComposeView.tpl
- modules/Emails/include/ComposeView/EmailsComposeView.js
- modules/Emails/views/view.compose.php
Change the behavior when selecting a template in Email compose view, so that current attachments are not removed.
#5520 
1. Compose e-mail
2. Add attachment
3. Select template
4. Attachment still exists, together with any template attachments
> Fix #5520 Do not clear existing attachments when loading a template

- modules/EmailTemplates/EmailTemplateParser.php
- tests/unit/phpunit/modules/EmailTemplates/EmailTemplateTest.php
This was removed in #5337, reverted in #5397 and then re-removed in #5425.
The original template code does more things, but this should at least make
the basics work again and adds some tests.
Fixes #6535
Sending emails with templates to leads
* Create a campaign
* Add a lead to the test list
* Include a lead variable (like name)
* Send a test email
* The variable should be replaced
> Fixed #6535 - Replace contact_xxx in templates also for leads/prospects/users

- modules/Emails/Email.php
When emails were being sent from 'system' and the 'allow sending as user' toggle wasn't enabled, the email was being sent as 'Root User' instead of the name configured in the Email Settings.
The fix was suggested here: https://github.com/salesagility/SuiteCRM/pull/6017#issuecomment-444086825
I essentially used the same code, but I refactored it because having multi-line assignment looks really ugly to me.
This fully fixes the issue described in #6012.
1. Set up the CRM with the following:
- Have an 'Outbound Email' configured as 'system', with a Name set (e.g. 'Custom Name').
- In the Admin page 'Email Settings', make sure 'Users may send as themselves' is turned off.
1. Go to a Lead.
1. Click 'Compose Email' in the Activities subpanel.
1. Set the "To" address to your own email.
1. Send a …
> Fix emails being sent from 'Root User'.

- modules/AOR_Reports/AOR_Report.php
Refixed #7393 without breaking headers for non-pulldown fields (which
> AOR_Report Group Headers: Fixing #7393 and #7644, replacing #7645

- include/SugarObjects/templates/company/Company.php
- include/SugarObjects/templates/person/Person.php
Save email addresses before saving company/person
Save email addresses before saving company/person
I found that the company/person updated email addresses are not available when company/person after_save logic hook was called. This is an issue if the after_save logic hook expect latest company/person email addresses.
Create a after_save logic hook for accounts. In the after_save logic hook print out the email addresses:
$emails = $bean->get_linked_beans('email_addresses', 'EmailAddresses');
foreach($emails as $email) {
// print $email
}
> Save email addresses before saving company/person

- modules/AOS_Products/AOS_Products.php
Fix database failure in quote purchases subpanel
Fix database failure in quote purchases subpanel
The quote purchases subpanel expansion lead to a database failure 
MySQL error 1055: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'suitecrm.aos_quotes.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
Create a product. Create a quote that include the product as a line item. Select an account. Save the quote. Go to the product page and expand the Purchases subpanel
> Fix a sql query bug for quote purchase subpanel

- include/javascript/sugar_3.js
- jssource/src_files/include/javascript/sugar_3.js
Fix #7626 and #7244.
It solves a JavaScript undefined variable error that could happen a few hundred times.
- Pull down this branch
- Go to Leads list view (you'll need to create a lead if you don't have any)
- Open your browser console
- Click on a Lead to open it.
- Wait for the page to load
- Look at the browser console and make sure there aren't any errors that say something about a TypeError and an undefined variable, and point to code in `sugar_grp1.js` (`sugar_3.js` in the actual source).
Essentially, try to reproduce #7626 and make sure you're unable to.
> Update sugar_3.js to fix a MassUpdate undefined error.

- include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
Read #7875
Make SuiteCRM looks cuter ;-)
1. Open a search form with a DateRange widget
2. Select Between option
3. Verify the how is rendered
> FIX #7875 - Wrong render in DateRangeInput using "Between" Option

- tests/unit/phpunit/modules/InboundEmail/InboundEmailTest.php
The test methods in InboundEmailTest depended on the test order to run correctly and
failed if the state checker was run per test instead of per class.
This patch makes the tests not depend on each other and restores the state so that the state checker
is happy.
* Move some imap cache setup in a setDummyCacheValue() method
* Use a temp file instead of creating a "fakeImapResource" file in the source dir
* Save/Restore more things between tests
See #7480
* Run the tests outside of travis-ci
* Run the test suite with `StateCheckerConfig::RUN_PER_TESTS`
> InboundEmailTest: Make tests independent to make them work with the state checker

- modules/AOR_Reports/AOR_Report.php
Added missing initialization of variable used in building of SQL query.
https://github.com/salesagility/SuiteCRM/issues/7552
Solves reports returning no records if accessed by a non system administrator
Loading a report which contains linked modules ( e.g. displaying contacts in an accounts report) resulted in a failed SQL query and no records were displayed.
With this bugfix the SQL query is not failing anymore and the records will be displayed.
> Fixed #7552 - AOR Reports - Mysqli_query failed when execute Report as normal User

- modules/AOR_Reports/AOR_Report.php
This prevents PHP notices like "PHP Notice:  Undefined index: leads_id" when running reports.
Fixes #7868.
It was causing a lot of notices in our error logs.
1. Be on `hotfix-7.10.x`.
2. Run a report by viewing a Report DetailView page.
- It seems easiest to reproduce this with a report on Leads, but I'm sure it happens elsewhere too.
3. Check your PHP error logs and see that there are a bunch of errors like `PHP Notice:  Undefined index: leads_id` that reference `modules/AOR_Reports/AOR_Report.php`.
4. Switch to this branch.
5. Run the report again.
6. Check your PHP error logs again and see that the error is gone, make sure the report continues to return the same result as before.
> Fix 'Undefined index: leads_id' notices in AOR_Report.php

- modules/Users/views/view.detail.php
Delete option is not visible when actions are displayed in menus
Add title to Delete menu.
Users cannot be deleted when actions are displayed in menus.
> Enable Delete button in Actions menu

- include/ListView/ListViewSmarty.php
These changes fix issue https://github.com/salesagility/SuiteCRM/issues/7926
The OAuth clients/tokens page has no widths defined, resulting in the totalWidth being 0, and so does the adjustment. The quickfix is to prevent dividing by the variable in such case, avoiding division by 0. When adjustment is 0, we just set the final value in displayColumn to 0.
These changes also refactor the check on adjustment with the first condition. This is probably easier to read and maintain, rather than having two separates conditions resulting to the exact same code (eg setting the value in displayColumn to 0).
1. Go to the Admin panel.
2. Go to "OAuth clients and tokens".
3. You're now at the page that should have the issue.
4. Make sure you don't see the following warning:
> PHP Warning: Division by …
> Hotfix: Do not divide by adjustment if it equals 0

- modules/MergeRecords/Step3.php
Added global variable for field check in show_field() function and add bool to eligible fields for merge
Checkboxes don't display on merge
See #7942
> Fix #7942 add bool to eligible fields for merging

- themes/SuiteP/include/SubPanel/tpls/SubPanelDynamic.tpl
Read #7923
Now the Smarty code is 'transformed' into a php file in `cache/smarty/templates_c` with
```php
<?php if (is_array ( $this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']] ) && count($this->_tpl_vars['ROWS_BUTTONS'][$this->_tpl_vars['rowHeader']]) > 0): ?>
```
As we can see if the variable is not an array, we do not count it, avoiding Warnings
1. Run SuiteCRM with PHP 7.3
2. Load a DetailView with subpanels
3. Reload a Subpanle
4. Check this Warning is not in PHP error log
> FIX #7923 - Verify the variable is an array

- include/generic/SugarWidgets/SugarWidgetField.php
Read #7912
Avoid annoying PHP Notices in php log
1. Define a Float field in a subpanel
2. Check for Notices in PHP log
> FIX #7912 - Avoid PHP Notices in getVardefs() method

- include/Smarty/plugins/function.suite_check_access.php
> Verify if $bean is_subclass_of SugarBean so we can check access

- modules/AOW_WorkFlow/aow_utils.php
Prevents warnings like `PHP Warning:  Illegal string offset ''` by making sure the enum has an 'options' array to append a new value to in `aow_utils.php`.
Fixes #7869.
It causes a bunch of warnings when running reports.
1. Be on `hotfix-7.10.x`.
2. Create a report (probably needs to involve an enum field? I'm not entirely sure, honestly).
3. Run the report.
4. Check PHP error logs and see that there are warnings like `PHP Warning:  Illegal string offset ''`.
5. Switch to this branch.
6. Run the report again.
7. Check the error logs and see that the warning no longer shows up. Also make sure the reports continue to work fine.
> Protect against illegal string offset warnings in aow_utils.

- modules/Users/views/view.edit.php
Fixes an issue where hitting the enter button wouldn't save a user and instead re-directs you to the users list-view.
Issue reference: #321 
1. Admin -> user management -> new user.
2. Fill out the username, last name, email and password fields.
3. Hit enter.
> Fixed #321 Hitting enter in the password input saves the user but not the password

- .gitignore
- lib/Robo/Traits/CliRunnerTrait.php
- tests/bootstrap.php
- tests/config.test.dist.php
Issue reference: #7621 
1. Check Travis
2. Add a ```tests/config.test.php``` file and then give it a custom value like so: 
```
$testConfig = [
'imap_test' => true,
];
```
3. Check that the custom config only runs during the test suite execution and overrides the ```config.php``` and ```config_override.php``` values.
> Fixed #7621 - Add support for config_override.test.php

- include/MVC/Controller/entry_point_registry.php
- modules/Users/authentication/SAML2Authenticate/SAML2Authenticate.php
- modules/Users/authentication/SAML2Authenticate/SAML2Metadata.php
- tests/unit/phpunit/modules/Users/SAML2AuthenticateTest.php
This adds a new endpoint which returns the XML metadata for the SAML2
integration. The output can be used to register the service with the identity
provider.
The endpoint can be reached through "index.php?entryPoint=SAML2Metadata"
Based on the php-saml example: https://github.com/onelogin/php-saml/blob/master/demo1/metadata.php
This makes it easy to to register SuiteCRM with the IDP as you don't have to
build the XML/configuration manually.
It also makes it easier to configure the SuiteCRM SAML2 config as one can
compare the metadata to the metadata of an already existing/registered
service.
Given a working SAML2 configuration visit "index.php?entryPoint=SAML2Metadata".
It should return XMl similar to: https://en.wikipedia.org/wiki/SAML_2.0#Service_Provider_Metadata
> Add a SAML2 metadata endpoint

- include/utils.php
This replaces a deprecated means of accessing elements in an array. This is a fix to make PHP 7.4 work properly (or, more properly). See also #7974.
PHP 7.4 deprecates accessing the index of an array with `$array{1}`, we should always use `$array[1]`.
https://wiki.php.net/rfc/deprecate_curly_braces_array_access
> Replace deprecated array index accessors.

- .github/config.yml
Pull requests to this branch should be going to hotfix-7.10.x instead.
This includes 7.10.x as an invalid branch so that SuiteBot will tell users to rebase to hotfix-7.10.x.
No real way to test until this ends up in the master branch.
> Update config.yml to include 7.10.x branch

- modules/Administration/RebuildConfig.php
- modules/Administration/templates/RebuildConfig.tpl
This renders the RebuildConfig page using Smarty instead of XTemplate.
See also #8016.
XTemplate is old, outdated, probably insecure, and we should really remove it from the CRM. This is a step toward that.
1. Go to the Administration module.
2. Go to Repair.
3. Choose "Rebuild Config"
4. Make sure it looks and works the same as it did before this change.
Technical debt :)
> Move RebuildConfig.php from using XTemplate to using Smarty.

- include/Localization/Localization.php
- include/SugarFields/Fields/Relate/SugarFieldRelate.php
- include/TimeDate.php
- jssource/minify_utils.php
- modules/Calendar/CalendarDisplay.php
- modules/EmailMan/EmailMan.php
- modules/SugarFeed/SugarFeed.php
- modules/SugarFeed/linkHandlers/Link.php
- modules/UpgradeWizard/uw_utils.php
- modules/Users/User.php
Accessing array indices with curly braces is deprecated as of PHP 7.4, this replaces a few more uses of the old syntax.
Pretty much the same as #7976.
https://wiki.php.net/rfc/deprecate_curly_braces_array_access
> Fix more PHP 7.4 array accessor deprecations

- data/BeanFactory.php
- tests/unit/phpunit/data/SugarBeanTest.php
In case a bean is retrieved, deleted and then fetched again the bean factory
would return it despite the bean being deleted. This means the bahviour is different
depending on whether the bean is cached or not.
Avoid this by not returning a cached bean if it is marked deleted and the delete
filter isn't disabled by the caller.
I was writing a test and was confused why deleted beans got still returned.
See the unit test.
> BeanFactory: Don't return deleted beans from the cache

- modules/AOW_WorkFlow/AOW_WorkFlow.php
- tests/unit/phpunit/modules/AOW_WorkFlow/AOW_WorkFlowTest.php
The workflow is the sole owner of them, so they should be deleted when the workflow is.
Otherwise only the relation is deleted which means the workflow field of the related beans
is deleted and the actions, conditions stay in the DB forever.
Deleting things should delete it from the DB.
1) Create a workflow
2) Add some conditions/actions
3) Delete the workflow
4) The conditions and actions shouldn't be in the DB anymore
> AOW_WorkFlow: Delete all related beans when deleting a workflow

- modules/EmailMarketing/vardefs.php
- tests/unit/phpunit/modules/SecurityGroups/SecurityGroupTest.php
When a user of a security group creates a marketing entry then no
other user in the same group can see/edit it.
This adds the security group relation so that new records are associated with
the right group and other users in the same group can access the marketing email
record.
See above
* Two users in the same security group
* Create a newsletter with one, and create a marketing entry (just follow the wizard)
* Log in with the other user
* When viewing the campaign the marketing entry should be visible in the subpanel
> EmailMarketing: Add security groups support

- lib/Search/ElasticSearch/ElasticSearchHooks.php
This is the same as https://github.com/salesagility/SuiteCRM/pull/7020 but for deletes.
Please see  [the Forum thread](https://suitecrm.com/suitecrm/forum/suitecrm-7-0-discussion/27476-error-data-in-log-file) for more details, but here is the exact error message:
```
Mon Sep 23 16:58:17 2019 [6672][1][FATAL] [ERROR] Failed to remove bean to index
Mon Sep 23 16:58:17 2019 [6672][1][FATAL] [ERROR] SuiteCRM\Search\Exceptions\SearchException: Elasticsearch trying to re-indexing a bean but indexer is disabled in configuration. in C:\xampp\htdocs\SuiteCRM\lib\Search\ElasticSearch\ElasticSearchHooks.php:123
Stack trace:
#0 C:\xampp\htdocs\SuiteCRM\lib\Search\ElasticSearch\ElasticSearchHooks.php(105): SuiteCRM\Search\ElasticSearch\ElasticSearchHooks->reIndex(Object(Reminder_Invitee))
#1 …
```
> Complete previous fix when ElasticSearch disabled

- include/phpmailer/class.phpmailer.php
Decode email address before being sent out
Decoded HTML as email address is encoded on save but no decoded
Fixes issue with emails not being sent when apostrophe is in email address, See #7962
See #7962
> Fix 7962 issue with sending emails with apostrophe in email address

- .codecov.yml
This now matches the coverage tracking in hotfix.
Make sure this passes CI, obviously, and make sure it's valid and makes sense.
Here's the file on hotfix for comparison: https://github.com/salesagility/SuiteCRM/blob/hotfix/.codecov.yml
> Ignore vendored library files in .codecov.yml

- include/OutboundEmail/OutboundEmail.php
- install/installConfig.php
- modules/AOR_Charts/AOR_Chart.php
- modules/ModuleBuilder/views/view.layoutview.php
Part of #8057. This fixes usages of `implode()` where the arguments are reversed. PHP 7.4 deprecates the ability to use `implode($parts, $glue)` in favor of only supporting `implode($glue, $parts)`.
This PR fixes a few of these deprecates uses.
> Fix deprecated usages of implode

- include/SubPanel/SubPanelTiles.php
join is an alias of implode. PHP 7.4 deprecates using the delimiter as the second argument.
Part of #8057. See also #8058.
> Fix a deprecated usage of join.

- modules/InboundEmail/InboundEmail.php
- modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php
This fixes these three deprecation warnings from PHP 7.4:
```
Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /home/travis/build/salesagility/SuiteCRM/modules/InboundEmail/InboundEmail.php on line 1817
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` in /home/travis/build/salesagility/SuiteCRM/modules/InboundEmail/InboundEmail.php on line 4366
Deprecated: The behavior of unparenthesized expressions containing both '.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence in /home/travis/build/salesagility/SuiteCRM/modules/Users/authentication/SugarAuthenticate/SugarAuthenticate.php on line 404
``` …
> Fix misc PHP 7.4 deprecations

- themes/SuiteP/include/DetailView/tab_panel_content.tpl
- themes/SuiteP/include/EditView/tab_panel_content.tpl
- themes/SuiteP/tpls/header.tpl
The present commit adds a "data-module" tag to the SuiteP pagecontent div and "data-field" tags in the edit and detail views. 
The SuiteP theme does currently not allow to differentiate between different modules in the html code. This is not necessary for the standard SuiteP layout (not a bug). However, it would allow for tiny customization with css here and there. These additions allows developers to easily customize the appearance of individual views by simply adding custom css code, e.g.:
`
div#pagecontent[data-module='Accounts'] .edit-view-row-item[data-field='assigned_user_name'] .label {  
color: red;  
}
`
You can add the above css code into custom/themes/SuiteP/css/Dawn/style.css and should see the color change.
> SuiteP: Add html data tags to allow module and field identification

- data/SugarBean.php
Read #8063
The users couldn't go to the DetailView of the Notes they were creating.
1. Create and Role and assign an user to this Role.
2. Set the followings permissions to the module Notes for this Role:
```
access: 89
delete: -99
edit: 75
export: -99
import: -99
list: 75
view: 75
```
3. Login with this user
4. Create a Note
5. Verify you can go to the DetailView.
> FIX #8063 - Change isset() to !empty()

- lib/Robo/Plugin/Commands/RepairCommands.php
This PR fixes #7828 
Sometimes it is very useful to perform some actions in SuiteCRM through the command line.
With the passage of time we have been adding habitual tasks to an immense Makefile. But since SuiteCRM has RoboTask, we can migrate those tasks to RoboTask.
The tasks that we add in this PR, are the first ones that we have migrated from our Makefile to Robo.
We added 3 tasks:
This task synchronize database with vardefs
```bash
$ ./vendor/bin/robo repair:database  
➜  Repairing database...
➜  Database synchronized with vardefs!
➜  Executed queries: 3
```
You can use the argument no-execute to not execute and show the queries in stdout
```bash
$ ./vendor/bin/robo repair:database --no-execute                                                                  
➜  Repairing database... …
```
> FIX #7828 - Robo tasks for common actions that are performed in Repair Administration module

- modules/AOW_Actions/actions/actionCreateRecord.php
There is currently no action for deleting a record, only for modifying one.
The only way atm is to set the "deleted" field during the workflow action which
seems to work but leaves tangling relations in the DB and not all code handles that
properly, leading to weird errors/states and a bloated DB
Improves the current way by checking if the delete field was set during the action
and properly delete the record after the action is done, including relations etc.
Searching for how to delete with a workflow leads to descriptions pointing to set the deleted field, but that's not working right currently.
* Delete a record with a workflow, all relations should be marked as deleted as well.
> Workflow: Properly delete records which are marked as deleted

- modules/jjwg_Maps/views/view.map_markers.php
Remove scheme to avoid mixed content error
Site served over HTTPS got a mixed content error, this change is to avoid the error.
This is a quick fix as according to https://datatables.net/extensions/tabletools/ TableTools are retired... 
Fix #7128 for HacktoberFest
> Fixed #7128 - Remove scheme to avoid mixed content error

- include/utils.php
- install.php
- service/example/Rest_Proxy.php
This doesn't touch the vendored HTMLPurifier, which does still use this function.
[It always returns `FALSE` since PHP 5.4](https://www.php.net/manual/en/function.get-magic-quotes-gpc.php), and 7.4 deprecates it entirely. This PR removes those branches of code that never get touched.
Part of #8057.
`get_magic_quotes_runtime` is also deprecated, but it's only used in vendored libraries, so I haven't touched them.
> Remove all uses of get_magic_quotes_gpc.

- lib/Search/SearchQuery.php
This PR addresses #7953 
It changes the SearchQuery class to check the config before falling back to a default search size. 
This is important for situations where a CRM has a minimum pagination size greater or less than 10. 
I also took the liberty of adding a dedicated setting for the default query size. 
This PR gives developers the ability to set and potentially raise the default Elasticsearch query size. This can be especially helpful if there are 'cluttered' results (like if you're searching for a specfic Account and for whatever reason a bunch of Notes rank higher). 
1. Enable Elasticsearch and Index your records
2. Perform a generic search from the Navbar - you should get 10 results
3. Add the following to your config: `$sugar_config['search']['pagination']['min'] = 5`
4. Repeat …
> Fixed #7953 - Elasticsearch default size setting

- .codecov.yml
The old v8 API is deprecated and we don't run any of the tests for it in Travis anymore. 
1. See Travis.
> Added the deprecated lowercase v8 API to codecov ignore list

- include/SugarEmailAddress/SugarEmailAddress.php
- tests/unit/phpunit/include/SugarEmailAddress/SugarEmailAddressTest.php
`getBeansByEmailAddress` now checks the deleted flag on the `email_address` and when loading the related bean the result is checked and not add it to the result list
The unit test is pretty comprehensive, but basically have a contact with an email address then mark the contact as deleted, using `getBeansByEmailAddress` will now not return an empty contact in the results, the results will be an empty array
> Fixed #1504 - check deleted flag on email_addresses and related bean

- modules/Calls/metadata/subpanels/ForActivities.php
- modules/Calls/metadata/subpanels/ForHistory.php
- modules/Emails/metadata/subpanels/ForHistory.php
- modules/Emails/metadata/subpanels/ForUnlinkedEmailHistory.php
- modules/Emails/subpanels/ForHistory.php
- modules/Meetings/metadata/subpanels/ForActivities.php
- modules/Meetings/metadata/subpanels/ForHistory.php
- modules/Notes/metadata/subpanels/ForHistory.php
- modules/Tasks/metadata/subpanels/ForActivities.php
- modules/Tasks/metadata/subpanels/ForHistory.php
Fix aliasing for `date_end`/`date_due` fields so that the columns from each of the three modules (Calls, Meetings and Tasks) match consistently in the UNION ALL queries.
- Calls and Meetings should use the `date_end` field aliased to `date_due` (or whatever as long as it's consistent everywhere which has been the issue thus far).
- Task should use the `date_due` field with an inverse alias of `date_end` oddly.
Inconsistency in aliases across UNION table columns caused queries to intermittently failed under certain circumstances such as having at least one of each type of history record in the subpanel etc.
- Create any record and relate at least one task, meeting and call in both the Activities and History subpanels. 
- Load the detail view of that record and it should no longer die.
- …
> Fix Activities and History Queries

- include/SugarDateTime.php
This has been deprecated for a long time and is unused.
Part of #7744.
> Remove get_day_by_index_this_year from SugarDateTime.

- modules/Accounts/Account.php
- tests/unit/phpunit/modules/Accounts/AccountTest.php
This code doesn't do anything and hasn't been used for a long time.
Also removes the test for it.
Part of #7744.
Make sure tests pass and Accounts views work.
> Remove remove_redundant_http() from Account.

- include/JSON.php
- modules/Home/QuickSearch.php
These have been deprecated for over six years now.
There was only one use of `encodeReal`, so I've replaced it.
Part of #7744.
Make sure Quick Search works and that the tests continue to pass.
> Remove deprecated JSON functions encodeReal() and decodeReal()

- modules/Users/User.php
- tests/unit/phpunit/modules/Users/UserTest.php
It's not used anywhere else in the codebase besides the test suite, so it should be safe to remove.
Part of #7744.
Make sure logging in/out works, and maybe also try changing your password to make sure it encrypts it properly? Also make sure the tests pass, obviously.
> Remove deprecated encrypt_password function for User.

- include/Smarty/Config_File.class.php
- include/Smarty/Smarty.class.php
- include/Smarty/Smarty_Compiler.class.php
- include/Smarty/internals/core.assemble_plugin_filepath.php
- include/Smarty/internals/core.assign_smarty_interface.php
- include/Smarty/internals/core.create_dir_structure.php
- include/Smarty/internals/core.display_debug_console.php
- include/Smarty/internals/core.get_include_path.php
- include/Smarty/internals/core.get_microtime.php
- include/Smarty/internals/core.get_php_resource.php
- include/Smarty/internals/core.is_secure.php
- include/Smarty/internals/core.is_trusted.php
- include/Smarty/internals/core.load_plugins.php
- include/Smarty/internals/core.load_resource_plugin.php
- include/Smarty/internals/core.process_cached_inserts.php
- include/Smarty/internals/core.process_compiled_include.php
- include/Smarty/internals/core.read_cache_file.php
- include/Smarty/internals/core.rm_auto.php
- include/Smarty/internals/core.rmdir.php
- include/Smarty/internals/core.run_insert_handler.php
- include/Smarty/internals/core.smarty_include_php.php
- include/Smarty/internals/core.write_cache_file.php
- include/Smarty/internals/core.write_compiled_include.php
- include/Smarty/internals/core.write_compiled_resource.php
- include/Smarty/internals/core.write_file.php
Smarty is included via Composer now (#7591, #7729), so these files can be removed. If anyone is requiring these files in their custom code, they should make sure to remove those requires.
All Smarty plugins remain as-is.
> Remove all deprecated Smarty files.

- composer.json
- composer.lock
This fixes various deprecation warnings when using HTMLPurifier with PHP 7.4.
Part of #8057.
See also #8137 and the htmlpurifier NEWS file: https://github.com/ezyang/htmlpurifier/blob/v4.12.0/NEWS.
Deprecated code shouldn't be used :)
The test suite should pretty much cover anything this'd break, feel free to also try booting the CRM to make sure it works.
> Update html-purifier to 4.12

- tests/unit/phpunit/modules/FP_events/FP_eventsTest.php
Updating FPEvent unit test to use correct array.
Fixing the unit test to use the correct array value as this no longer exists as per https://github.com/salesagility/SuiteCRM/pull/8151.
Running the unit test.
> Updating FPEvent unit test to use correct array.

- export.php
- include/Localization/Localization.php
- include/export_utils.php
- modules/AOR_Reports/AOR_Report.php
- tests/unit/phpunit/include/Localization/LocalizationTest.php
Excel on Windows/macOS when simply opening a CSV file will try to guess the
CSV dialect (encoding, delimiter, etc) and just go with the first guess.
It's still possible to do an explicit import with Excel where you can select the
dialect, but that's not very obvious.
The most common wrong guess is that mostly ASCII utf-8 will get detected as latin-1.
I've tested various encodings with Excel (2019) and codepoints from latin-1:
* utf-8: win/macOS use latin-1
* utf-8+bom: win/macOS correctly use utf-8
* utf-16le: win uses utf-16le, macOS garbled text
* utf-16le+bom: win/macOS fail to detect CSV and load it as one text block
thus utf-8+bom is the preferred mode.
This patch makes the "export_excel_compatible" mode use utf-8+bom for the CSV encoding.
In addition this removes the hardcoded …
> export: Update export_excel_compatible to work with all Excel versions

- modules/Meetings/Meeting.php
PHP 7.4 logs a warning if you attempt to access a boolean, null value, float, etc. as an array. e.g. `$booleanVariable[0]` causes a warning. This PR fixes one such case where this was happening.
Part of #8057.
Make sure the tests pass and the Meetings module continues to work.
> Fix a PHP warning in Meeting.php.

- modules/AOW_Actions/actionLines.php
Fix to workflow actions.
Try to create or edit a workflow with actions saved. Ensure those actions persist when opening the workflow again.
> Fix #8173 - Workflow actions missing in edit and detail view

- modules/ACLActions/ACLAction.php
Fixes an issue with ACL roles allowing users to see records they don't have ownership of.
Issue reference: #8178 
1. Setup your ACL role the same as the screenshot in #8178.
2. Check that your user has the correct level of access.
> Fixed #8178 - 7.11.9 Employee role control is lost, invalid

- .travis.yml
- composer.json
- composer.lock
Run it on PHP 7.3 so it completes faster and remove a reference to the state checker.
The removal of the state checker seems to have caused the tests to take quite a bit longer on older versions of PHP (not sure what that's about). It's quite fast on PHP 7.3, so this updates the coverage job to use PHP 7.3, to save time.
It also removes a duplicate instance of phpunit/phpunit from `composer.json`.
Make sure the tests pass and the coverage job continues to work.
> Update the Travis Code Coverage job.

- include/TimeDate.php
- modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
- modules/iCals/iCal.php
PHP 5.3 has been EOL for years, and SuiteCRM doesn't support it at all anymore, so I looked around and found a few hacks related to PHP 5.3 that shouldn't be necessary anymore.
We don't support PHP 5.3, so this shouldn't change the actual behavior of the CRM at all.
Cleaning up old, dead code.
> Remove some old code referencing PHP 5.3.

- include/utils.php
The following functions are deprecated by this PR:
- `add_http`
- `getSWFPath`
- `getSQLDate`
- `clone_history`
- `values_to_keys`
- `getCurrentURL`
- `mark_delete_components`
- `checkLoginUserStatus`
- `returnPhpJsonStatus`
- `add_quotes`
- `add_squotes`
- `array_depth`
- `ajaxInit`
- `getVersionStatus`
- `getMajorMinorVersion`
- `getFTSBoostOptions`
- `utf8_recursive_encode`
- `get_help_url`
- `getDuplicateRelationListWithTitle`
- `suite_substr`
- `suite_strtoupper`
- `suite_strtolower`
- `suite_strpos`
- `suite_strrpos`
- `chartColors`
- `chartStyle`
- `format_number_display`
- `return_theme_language`
- `get_all_languages (only used in a test)`
- `get_language_display (only used in a test)`
- `return_name`
- `make_not_writable`
- `sugar_config_union`
This is all dead code, it's not …
> Deprecate various utils functions that are unused.

- include/utils.php
- tests/unit/phpunit/include/UtilsTest.php
This PR adds tests for the `check_php_version` function in utils.php.
Needed to modify the way the min/recommended versions are defined in order to make it testable, but that doesn't matter for the existing uses of the function.
I did this because I wanted to see why the version check was failing in #7987, but this didn't really give me anything to work with. I'm still stumped as to why it's failing on 7.4.0.
Adds some tests.
> Add tests for check_php_version.

- include/utils.php
Remove `get_admin_modules_for_user`, `get_theme_display`, `get_themes`, and `isValidId`.
These are all deprecated and unused.
Part of #7744.
Make sure tests pass.
Technical debt
> Remove deprecated functions from utils.php.

- include/utils.php
It's been deprecated since SuiteCRM's initial commit and a grep for load_menu doesn't return anything, so it doesn't seem to be used anywhere.
Part of #7744.
Make sure the tests pass and the function isn't used anywhere.
Technical debt
> Remove the deprecated load_menu() function in utils.php

- include/utils.php
- tests/unit/phpunit/include/UtilsTest.php
Title pretty much says everything.
This function was pretty useful for something I was doing, so I figured I'd document it for others.
I see that the code also handles the case where the multienum is already an array, and will just return that. So I made the parameter type `string|string[]`. I also added a unit test for that case :)
Make sure the `unencodeMultienum` function docs make sense. Make sure the tests continue to pass.
Documentation :)
> Add a PHPDoc comment and test to unencodeMultienum()

- include/utils.php
When exit() is called during tests the test suite will stop without returning an error.
To avoid that add our own exit() wrapper which throws an exception instead when
tests are running. There are many more calls to exit() in the code base, this just changes the
common path through sugar_cleanup()
Make tests fail when they fail.
> tests: throw an error in case exit() is called during testing

- include/database/DBManager.php
- tests/unit/phpunit/include/database/DBManagerTest.php
Fixes #7720 and adds tests for some basic pQuery functionality, to prevent it from regressing.
A query like `SELECT foo FROM bar WHERE baz != '?';` would have failed when passed to pQuery because the `!` isn't handled in any special way when it precedes an `=`.
`!` can be used as a token, but it shouldn't conflict with valid SQL queries.
It changes the way pQuery works, by renaming `executePreparedQuery` to `createPreparedQuery` and instead handle the execution of the queries in pQuery itself. `executePreparedQuery` was only used in the `pQuery` function. The point of this change is to make pQuery easier to test. I wanted to make sure the queries were returned by a function as strings, since the results of the queries aren't relevant to me and would just add complexity to the tests.
Make …
> Fix "!" in pQuery and add tests

- modules/Administration/templates/RepairDatabase.tpl
So it's Friday night and I decided to do something I've been postponing for too long.
When admins run a `Quick Repair and Rebuild`, sometimes there is an important message to inform them they have a mismatch between the database and the vardefs, and it offers to run an SQL query to fix it.
People don't see the notice unless they remember to scroll down. I waste significant time in the Forums telling people to go check this, and I must have done it a hundred times.
I chose a solution that is not very fancy, but has excellent browser compatibility.
1. Run a QR&R with no vardefs unsynced, to confirm that everything works as normal, as it always did.
2. Now make a change to your vardefs, to trigger the message (to facilitate, I suggest a change below)
3. Check that the browser scrolls to show …
> Scroll QR&R to see the 'sync with vardefs' part

- include/Dashlets/Dashlet.php
Some Dashlets (iFrame, AOR_Reports, for example) don't define `seedBean` and produce a PHP Notice that shows on the Homepage if you have `display_errors` turned on. 
```php
PHP Notice:  Undefined property: iFrameDashlet::$seedBean in /var/www/html/include/Dashlets/Dashlet.php on line 253
PHP Stack trace:
PHP   1. {main}() /var/www/html/index.php:0
PHP   2. SugarApplication->execute() /var/www/html/index.php:52
PHP   3. HomeController->execute() /var/www/html/include/MVC/SugarApplication.php:113
PHP   4. HomeController->process() /var/www/html/include/MVC/Controller/SugarController.php:373
PHP   5. HomeController->handleEntryPoint() /var/www/html/include/MVC/Controller/SugarController.php:468
PHP   6. require_once() /var/www/html/include/MVC/Controller/SugarController.php:1020
PHP   7. …
```
> Clear PHP notice on Home page, improve suitecrm.log message

- include/utils.php
- tests/unit/phpunit/include/UtilsTest.php
Continuing my spelunking through utils.php for functions that are unused or untested, this one has a few uses throughout the codebase so I've added tests for it.
Test coverage :)
The values are for memory, which I guess is measured in kibi/mebi/gibibytes? I was under the impression is was kilo/mega/gigabytes, but apparently not according to this function.
Also this function should maybe be updated to include support for tibibytes ;)
Adding tests and PHPDocs :)
> Add tests and PHPDocs for return_bytes function

- include/ListView/ListViewGeneric.tpl
- themes/SuiteP/include/ListView/ListViewGeneric.tpl
Show correct sorting icon when sorting data in ListViews: when sorting == `ASC` use class `suitepicon-action-sorting-ascending`, else use class `suitepicon-action-sorting-descending`.
Fixes #8295 
1. Open any Listview.
2. Click search button.
3. When data shows, click to order records by some field.
4. The data is shown in the correct order. Also, hovering the sorting icons shows the correct description of the sorting (Ascendant / Descendant)
5. The sorting icon that shows highlighted is the correct one.
> Fix #8295 - Fix sorting icons showing counterwise

- data/Relationships/M2MRelationship.php
- data/Relationships/One2MRelationship.php
- include/ListView/ListViewDisplay.php
- include/SearchForm/SearchForm2.php
- modules/Emails/Email.php
- modules/Leads/Lead.php
- modules/jjwg_Areas/jjwg_Areas.php
- modules/jjwg_Maps/jjwg_Maps.php
Backporting a bunch of fixes from #7987.
Mostly related to accessing booleans, integers, or null values as arrays. This causes errors in PHP 7.4, so we need to have these fixed before PHP 7.4 is released.
Part of #8057.
PHP 7.4 support :)
Make sure the CRM still works and the tests pass.
> Backport various PHP 7.4 fixes

- themes/SuiteP/css/suitep-base/navbar.scss
Change auto fill font colour to standard search font colour
See #8180
See #8180
> Fix issue #8180 where font colour is the same as the search bar bg

- include/Sugar_Smarty.php
- themes/SuiteP/tpls/header.tpl
Fixed #7874 - Unable to use custom _head.tpl file
Adds lookup for custom tpls in Sugar_Smarty.php, so that any {{include file='abc'}} automatically looks for a custom version of that file in custom/abc.
As discussed in the issue #7874 this might be a more general solution to the issue.
Because PR #8028 has already been merged, this PR revokes the changes made to the header.tpl, because the modification is not required any more.
> Fixed #7874 - Unable to use custom _head.tpl file (alternative fix)

- tests/unit/phpunit/include/UtilsTest.php
- tests/unit/phpunit/include/utils/arrayUtilsTest.php
Fix the parameter order for asserts in tests.
The expected value is supposed to go first, followed by the actual value. This swaps them in a few places that used the wrong order.
This is important because PHPUnit depends on this when showing diffs on test failure, so it can cause the output from PHPUnit to be confusing.
See [the docs for `assertEquals`](https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertEquals).
Make sure CI passes.
> Fix parameter order for asserts in unit tests.

- modules/Schedulers/views/view.list.php
Try this first without the fix, to see the problem
1. Open Admin / Schedulers
1. Enter the Filters dialog pop-up
1. Click the tabs (switch from `Quick Filter` to `Advanced filter` or vice-versa) until a new request is generated into the server, producing the cron instructions inside the dialog
> Remove Schedulers cron instructions from filter pop-up

- modules/UpgradeWizard/silentUpgrade_step1.php
This was failing due to a dependency in a logic hook - the direct save to the DB will bypass this. A larger fix should be to split step 1 of the silent upgrade process into two seperate steps - with one being an extendable way of adding files/dependencies before the upgrade process begins at all.
The silent upgrade process would fail during the saving of upgrade history. This will allow for the upgrade process to complete successfully.
As the new silentUpgrade_step1.php file will be copied over during the actual upgrade, it would not work for the first upgrade (therefore requiring a composer update prior). However, for testing purposes this file should be copied over and then the silent upgrade process followed (add the upgrade file to the correct directory and run ./vendor/bin/robo …
> Adding fix to silent upgrade's upgrade history save.

- data/SugarBean.php
- include/SearchForm/SearchForm2.php
- modules/AOW_WorkFlow/AOW_WorkFlow.php
- modules/Cases/Case.php
- modules/InboundEmail/InboundEmail.php
- modules/Meetings/Meeting.php
- modules/ProjectTask/updateDependencies.php
- modules/jjwg_Areas/jjwg_Areas.php
- modules/jjwg_Maps/jjwg_Maps.php
Backporting some fixes from #7987, this is a follow-up on #8233.
This avoids cherrypicking any changes involving `$mod_strings`, since IMO we should figure out a proper fix for that ever being `null`, rather than spending the time to figure out how to protect it from being `null` throughout the codebase.
PHP 7.4 comes out on November 28th so we should try to be ready for it :)
Make sure the tests pass and the general changes make sense.
> Backport more PHP 7.4 fixes

- modules/Reminders/Reminder.php
Removed lines 306 and 307 in Reminders.php:
```
$dateTimeNow = $db->convert($db->quoted($dateTimeNow), 'datetime');
$dateTimeMax = $db->convert($db->quoted($dateTimeMax), 'datetime');
```
Issue https://github.com/salesagility/SuiteCRM/issues/6000
Popup Notifications not working when using MSSQL database
Stepping through the code, the issue is cased due to the $db->convert function. Wen using a MSSQL this results in the $dateTimeMax and $dateTimeNow variables not being formatted correctly. This means the WHERE clause on line 328 is incorrect and therefore getBean fails.
Tested on version 7.11.6
Fixes notifications 
Using a MSSQL db, test popup notifications for new meetings etc
- [x ] I have read the [**How to …
> Fix #6000 for notifications not working when using mssql

- include/utils.php
This removes a 'buggy version check' from the PHP version check function in `utils.php`. This has been a huge thorn in my side for #7987.
For some reason this breaks on PHP 7.4, and we don't actually use it for anything, so I'm just removing it.
I genuinely have no idea why this happens, but the code is hitting this part on 7.4 for some reason and causing issues like #8419, even though the buggy versions array is _empty_. It makes no sense, but it's the only explanation I have.
I tried reproducing this locally with a PHP script but it didn't have the same problem. I have absolutely no clue why this causes problems. I've already spent far too long on this issue, all I know is that this fixes it, and that's all I really care about at the moment.
Make sure the tests pass in CI.
> Remove 'buggy version check' from php version checker.

- themes/SuiteP/tpls/footer.tpl
For some reason there is some JS in the footer template to move #step1_uploader, which is
only used in the campaign wizard.
This resulted in the attachment box being shifted down quite a lot. Just remove it so it's right
below the template editor again.
* Create a newsletter campaign
* Got to the template step
* See the attachment box right below the template editor
> Campaign Wizard: Fix the attachment box being shifted down in the template editor

- include/javascript/sugar_3.js
- jssource/src_files/include/javascript/sugar_3.js
Returning a value here produces a blank page when double clicking the anchor element that calls the function (the sort actions in the listview). 
Also, the return value seems to not be used anywhere and it can be safely removed.
Fixes #8323
See #8323
1. Browse a ListView.
2. Click search button.
3. When data is shown, double click on sort action in any field.
4. Data is ordered in the correct way and no blank page is shown.
> Fix #8323 - Avoid to return a value on function that is used within href attr in anchor elements

- modules/Configurator/UploadFileCheck.php
When uploading a logo image, the temp file gets copied to the cache/images directory so that it can be displayed in the GUI as a preview. Currently this breaks if the target directory has not already been created by other functionality, resulting in a broken image link and lang string displayed as the image source path does not exist.
1. Go to admin -> system settings.
1. Upload a logo image.
1. See the broken image link and lang string.
1. Apply fix and try again.
> Create images directory in cache if not exists

- modules/Campaigns/Subscriptions.php
In the "Manage Subscriptions" view pressing save just reloaded the page and didn't return
the user to the previous module. The only way was to click save and then cancel which is confusing.
This changes things to make it redirect to the source module after saving.
It should be easy to change the subscription of a lead/contact.
* Go to a lead
* Action menu -> Manage Subscriptions
* Click "Save"
* You should be back at the lead
> Campaigns: Return to the previous view when clicking "Save" in "Manage Subscriptions"

- modules/Campaigns/Charts.php
- modules/Charts/Dashlets/CampaignROIChartDashlet/CampaignROIChartDashlet.php
- modules/Charts/Dashlets/MyPipelineBySalesStageDashlet/MyPipelineBySalesStageDashlet.php
- modules/Charts/Dashlets/OutcomeByMonthDashlet/OutcomeByMonthDashlet.php
- modules/Charts/Dashlets/PipelineBySalesStageDashlet/PipelineBySalesStageDashlet.php
- modules/Charts/PredefinedChart.php
- modules/Charts/code/Chart_my_pipeline_by_sales_stage.php
- modules/Charts/code/Chart_outcome_by_month.php
- modules/Charts/code/Chart_pipeline_by_sales_stage.php
- modules/Schedulers/_AddJobsHere.php
- service/v4_1/SugarWebServiceImplv4_1.php
- soap/SoapData.php
- soap/SoapPortalUsers.php
- soap/SoapRelationshipHelper.php
#8129 introduced a direct call to an abstract database function, this PR correct it to call the function on the instantiated db object, addressing multiple issue introduced in 7.10.24/7.11.12
See home page charts, trimTracker Scheduled Task and everywhere else that uses this function now works as expected
> Fix db convert directly calling abstract function

- modules/UpgradeWizard/cancel.php
- modules/UpgradeWizard/preflight.php
- modules/UpgradeWizard/systemCheck.php
- modules/UpgradeWizard/uw_utils.php
Fixes many Upgrader problems caused by the increase of our upgrade packages size, and aggravated each time the upgrade didn't finish correctly.
See the Issue #8261 for symptoms and diagnosis tools. Also #7242.
The functions [`uwfindAllFiles`](https://github.com/salesagility/SuiteCRM/search?q=uwFindAllFiles&unscoped_q=uwFindAllFiles) and [`findAllFiles`](https://github.com/salesagility/SuiteCRM/search?q=findAllFiles&unscoped_q=findAllFiles) should be dropped entirely, and the places that use them should be refactored so that they use Iterators and don't build huge arrays in memory before acting on the files.
Exceptions to this can be made if you're sure the place where the function is used will never have to iterate over a large set of files.
**Warning**: if you just pull these changes …
> Fix #8261, Fix #7242 - Handling of temp files during Upgrades

- modules/AOR_Reports/AOR_Report.php
Business hours will only work in certain situation in report queries
This is add the only possible case  in the current implementation i.e where it being compared with now,
1. setup Business hours in the admin panel
Create a report using business hours, using now +/- business hours, and see that is now correct based on defined business hours
> Add missing business hours calculation to reports

- modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php
```
PHP Warning: in_array() expects parameter 2 to be array, string given in /var/www/suitecrm/modules/Users/authentication/LDAPAuthenticate/LDAPAuthenticateUser.php on line 124
```
Issue reference: #3911
See http://php.net/manual/en/function.in-array.php
> Fixed #3911 - LDAPAutheticate warnings in log

- metadata/prospect_lists_prospectsMetaData.php
Adds `deleted` field to middle table index
The actual query the CRM performs to retrieve the relationship looks somewhat like this:
```
SELECT * FROM prospect_lists_prospects WHERE prospect_list_id='ba00d2c7-1940-ee63-f256-5d93484c97a8' AND deleted = '0';
```
Without including `deleted` in the index, the query uses both the index and a where, which is slow on large tables.
1. Run an explain query on the DB: `EXPLAIN SELECT * FROM prospect_lists_prospects WHERE prospect_list_id='ba00d2c7-1940-ee63-f256-5d93484c97a8' AND deleted = '0';`
2. See it uses only the index, doesn't use where.
> Update the index on the target list - targets middle table

- include/SugarCache/SugarCacheRedis.php
Replace usage of Redis::delete() with Redis::del()
The function Redis::delete() is deprecated.
Enable Redis caching. E.g. in `config_override.php`:
```
$sugar_config['external_cache_disabled_redis'] = false;
$sugar_config['external_cache']['redis']['host'] = 'redis';
$sugar_config['external_cache']['redis']['port'] = '6379';
```
Use SuiteCRM a bit. Key/Values should be stored and get deleted as usual.
> Fix usage of deprecated Redis::delete() function

- install/installConfig.php
This should complete a previous PR #5112 fixing Issue #5012 
The problem showed up on the Forums [here](https://community.suitecrm.com/t/doesnt-accept-db-user-db-name-stuck-at-step-one/71092/14)
> Remove maxLength from user name in DB config

- themes/SuiteP/css/suitep-base/editview.scss
Added CSS to make case updates textfield re-sizeable
See #8549
See #8549
> Fix resize #8549

- modules/AOR_Reports/AOR_Report.php
Report page navigation does not display correctly
Create a report with multiple pages and see that the navigation now displays correctly, the same as it does in others list views
> Fix Report navigation display

- modules/AOR_Reports/AOR_Report.php
The main report group by field in reports needlessly requires the field in the report to be grouped to function correctly, which is not clear in the UI and can cause duplicate sub grouped reports to appear if you do which to group the field within the report 
Create a report e.g on Accounts, 
add field e.g assigned user and some other fields
set assigned user as the main group by feild, but not grouped in the report
see tat you now only get one group for each user, where previously you would have gotten a duplicate group by the number of time the assign user appears
> Fix #5487 - Report groups repeat for each record

- Api/V8/OAuth2/Entity/UserEntity.php
- Api/V8/OAuth2/Repository/AccessTokenRepository.php
- Api/V8/OAuth2/Repository/UserRepository.php
Issue reference: #8499 
Implemented UserIdentifier for OAuth2 password grant.
Fix needed to way of working with with user identifier represented by the access token.
1. Create password grant oauth2 client. 
2. Request an access token:
```bash
curl -v \
-H 'Content-type: application/vnd.api+json' \
-H 'Accept: application/vnd.api+json' \
--data '{"grant_type":"password","client_id":"[UUID]","client_secret":"[SECRET]","username":"[username]","password":"[password]"}' \
http://[SUITECRM_INSTANCE]/Api/access_token
```
> Fixed #8499 - API V8 issues for password grants SuiteCRM 7.10.22

- install/install_utils.php
- modules/Administration/QuickRepairAndRebuild.php
Address some minor warning when running upgrade via cli
in_array() expects parameter 2 to be array, null given in rebuild
Undefined index: SERVER_SOFTWARE in install_utils.php
Run the upgrade via cli and see that these warning no longer trigger
> Fix warnings when running upgrade via cli

- modules/AOR_Reports/AOR_Report.php
Remove useless recalculation:
getModuleField is called twice successively with the same parameters when exporting a report
Large reports can't be exported as too many resources are consumed
> Reports: Remove useless recalculation

- include/utils.php
- modules/UpgradeWizard/silentUpgrade_dce_step1.php
- modules/UpgradeWizard/silentUpgrade_dce_step2.php
- modules/UpgradeWizard/silentUpgrade_step1.php
- modules/UpgradeWizard/silentUpgrade_step2.php
special_query_modules is still referencing the SugarCRM Reports module.
It should set AOR_Reports instead
Allow larger reports to be displayed or exported
> special_query_modules: AOR_Reports and not SugarCRM Reports module

- modules/jjwg_Maps/views/view.map_markers.php
language files in modules/jjwg_Maps/DataTables/media/language/ are named fr_FR.js and de_DE.js 
These files are not found because the file loaded is strtolower($GLOBALS['current_language']) .js
That might happen for all other languages where language contains capital letters.
removes strtolower
- Connect to SuiteCRM in french or german
- Display a map for selected accounts
- The table is not display and the browser console shows:
modules/jjwg_Maps/DataTables/media/language/fr_fr.js not found
Table is not displayed under maps
> Bug fix: Display Data table under maps in French or German

- modules/AOS_Products/tpls/EditViewHeader.tpl
It solves issue #8489 
In `EditViewHeader.tpl` file of `AOS_Products` module,  element `form_id` was missing.
With this change, on click of header `Save` button, form will validate properly.
1. Go to `Products` module.
2. Create new record.
3. Click on 'Save' button available on header section without filling any mandatory fields and check whether you gets an error or not.
> Fixed #8489 - No validation when using header save button in AOS_Products

- include/OutboundEmail/OutboundEmail.php
SuiteCRM 7.10.25
If you happen to delete default system outbound email account it creates a second one but the SQL query does not check only for non-deleted accounts.
> Fix pulling deleted system outbound SMTP account

- composer.json
Google composer package "google/apiclient" come in a one package fit all and include everything google under the sun. Thus, makes the package sizes unnecessary large as only one part of the package is actually used "Calendar"
Reduce the size of upgrade packages
Run `composer install`
See that everything still works as normal especially the google calendar integration
> Remove unused google service from the vendor directory

- data/SugarBean.php
SugarBean fixUpFormatting wrongly log a depreciation log, despite be used constantly within the core code base. This changes Depreciation log to more appropriate Info log
1. Enable deprecation logs
2. Edit and save in a few modules
3. See that the logs no longer appear
4. Enable Info logs
5. See that a more generic log now appears
> Fix #7766 - Invalid depreciated log in SugarBean fixUpFormatting

- modules/Schedulers/_AddJobsHere.php
Add database check for jobs that are running before starting new job
#8680 
When the cron is run on every minute it schedules a job for the scheduled reports
When the report is generated for a long time the scheduler continues to schedule the report on next minute and a while you have multiple cronjobs running and every of them creating the same report
Multiple large report running at the same time can cause high useage/overload
Create large reports
Set up cron to run every minute
See scheduled reports start to overlap due to large report
> Fix issue 8680 where scheduled reports overlap in cron

- include/SugarTinyMCE.php
Cases Update text fails to save on edit view when using html variation of the field field(currently the default), as tinymce is not loading correctly when multiple fields are using it, this pr changes TinyMCE to be instance specific when loading, to prevent conflicts.
Fix #7152 
Try to update an exsiting case from edit view when using the html field
> Fix #7152 - Cases Update text not saving when using html field

- include/InlineEditing/InlineEditing.php
Fixes my attempt to fix issue #5526
The inline editing of date fields was still not displaying a value after an edit. 
I believe the cause was php datetime format function would incur a fatal error when attempting to format a date value with a datetime string.  So I split the formatting depending on the field type.
Use inline editing for any date or datetime field and see if the correct value displays after saving.
> Changes for inline edit date/datetime #5526

- modules/EmailTemplates/EmailTemplate.php
Replicates a previous fix for AOW templates: #5842
When newly created beans are saved in the BeanFactory cache, they may contain incomplete data such as dates or auto increment fields. Those fields only contain the correct data after a retrieve operation. By busting the cache and forcing a retrieve operation the template can access the correct data.
Fixes #3468 (closed but not fixed)
1. Set up an email template containing a date field for any module (example Leads)
2. Ensure your profile date settings are not YYYY-MM-DD
3. Set up either a workflow or a logic hook which fires on Lead record creation
4. Set up that workflow or logic hook to send the previous email template
5. See the parsed date is in your profile format and not YYYY-MM-DD
> Fix BeanFactory serving incomplete cached beans for Email Templates

- install/suite_install/Projects.php
Fixes module name from `Projects` to `Project` to install the logic_hook to the correct location. Fixes #8816
> Fixes module name on logic_hook install

- modules/EmailMan/EmailMan.php
Problems customizing EmailMan class with a custom class.
Create custom class in `custom/modules/EmailMan/CustomEmailMan.php`with something like this...
```php
require_once 'modules/EmailMan/EmailMan.php';
class CustomEmailMan extends EmailMan {
public function sendEmail(SugarPHPMailer $mail, $save_emails = 1, $testmode = false, $previewmode = false) {
[... code copied from original function, using function $this->shouldBlockEmail() ....]
}
}
```
You get a PHP error:
``` 
Sun Aug  9 18:47:59 2020 [1183][1][PHP S] [E_ERROR] 
'Uncaught Error: Call to private method EmailMan::shouldBlockEmail() 
from context 'CustomEmailMan' 
in custom/modules/EmailMan/CustomEmailMan.php:126
```
This is wrong because this class is meant to be overridable, so these functions should be either `public` or …
> Turn privates to protecteds to fix EmailMan overrides

- include/OutboundEmail/OutboundEmail.php
Checks only non-deleted rows of type 'system' to correctly update the outbound email settings.
Changes the query on line 546 to include a "deleted = 0" clause to filter only the "active" row of outbound email settings. Fix #8819
> Update OutboundEmail.php to handle deleted rows

- install.php
Hi.
You miss a bracket in line 263 file install.php.
Now:
echo "<script>window.top.window.uploadLogoCallback" . json_encode($result) . ");</script>";
Need:
echo "<script>window.top.window.uploadLogoCallback(" . json_encode($result) . ");</script>";
Without this bracket browther throw error:
Uncaught SyntaxError: Unexpected token '{'
and can't finish upload process.
Best regards, Aleksandr. ;)
> Fix #8785 - Incorrect Syntax in install.php

- ModuleInstall/ModuleInstaller.php
fixes #8888
See notes in issue #8888
Just trying to fix a bug.
```php
$dyField = BeanFactory::newBean('DynamicFields');
$GLOBALS['log']->fatal("dyField: " . print_r($dyField, true)); // empty. bad. 
$dyField = new DynamicField();
$GLOBALS['log']->fatal("dyField: " . print_r($dyField, true)); // not empty. good.
```
> Fixes DynamicField reference

- include/SugarFields/SugarFieldHandler.php
We can create custom SugarFields classes in `custom/include/SugarFields/Fields/`.
But if the class we're overriding is the `Base` class, in `custom/include/SugarFields/Fields/Base/SugarFieldBase.php`, it gets picked up for some fields, but not for others:
This is because there are actually two ways for the base class to get loaded:
A - no class is found for that field type, so the default is loaded here https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/include/SugarFields/SugarFieldHandler.php#L123 (doesn't pick up the custom class, and this is what my PR fixes)
B - the field type is `varchar`, so it gets changed to `base` in function `fixupFieldType`. This new name will cause the custom class to get loaded here https://github.com/salesagility/SuiteCRM/blob/hotfix-7.10.x/include/ …
> Fix incongruent SugarFieldBase class customization

- include/ListView/ListView.php
This started with #3576, continued with #7608, leading to a fix #7612.
But the ghastly `getOffset` function handles all kinds of values and types, like 0, 10, '', or 'end', and the fix doesn't take that into account.
https://community.suitecrm.com/t/campaign-module-sub-panel-navigation-is-not-working/71790
So it breaks the "end" navigation in _all_ subpanels. So I am fixing _that_ by moving back to a code that is closer to the original, and fixes the first bug in a less impacting manner... so that I can hope I am not breaking something else. 🤷‍♂️ 
- to facilitate testing, set a low subpanel limit by adding something like `$sugar_config['list_max_entries_per_subpanel'] = '3';` to `config_override.php`
- get any subpanel to show excessive items, so that a second page is needed.
- click the …
> Fix getOffset recession from #7608, subpanel "end" navigation

- include/formbase.php
Add to target list doesn't work in Campaign results
Changed verification of parent_module visibility
- On campaign results page, click Add to target list on any subpanel (clicked links, read messages, ...) and select a target list
- Nothing is added to the target list
> Fix Add to target list in Campaign results

- include/generic/SugarWidgets/SugarWidgetSubPanelTopComposeEmailButton.php
Fixes an issue which causes the Compose Email modal to fire twice when clicking the Activities subpanel button.
Fixes #8730 
Fixes #6601
1. Navigate to a Lead or Contact
2. Open Activities subpanel, click "Compose Email"
3. See a single dialogue opens.
> Fix duplicate Compose Email Modal from Activities subpanel

- install/install_utils.php
Issue reference: #7306
Issue reference: #8251
This PR fixes the process of rewriting the `.htaccess` file in two ways:
- when rewriting the `.htaccess` file any custom content before the
"# BEGIN SUITECRM RESTRICTIONS" marker and after the
"# END SUITECRM RESTRICTIONS" marker are written to the
new file at their original positions.
Before all custom content was placed before the BEGIN marker and the
BEGIN marker was written twice to the new file.
- remove paths after 'Api/index.php' in generated `.htaccess` file to allow
proper URL rewriting for API V8 calls
Accessing the API V8 was only possible by using the URL path "Api/index.php/V8/*"
and rewriting the `/.htaccess` when it contained custom content after the END marker
resulted in malformed output (options/commands out of order). …
> Fixed #7306 - API v8 not working on php-fcgid - Missing /api/.htaccess

- modules/Campaigns/ProcessBouncedEmails.php
Depending on email provider or other factors sometimes bounce emails from email Campaign are not recognised despite being valid bounce emails. This appear to be being caused by mine type being not an exact match for what it is expecting
> Fix Campaign Bounce Handling mine type recognition

- modules/AOS_Invoices/vardefs.php
- modules/AOS_Line_Item_Groups/vardefs.php
- modules/AOS_PDF_Templates/vardefs.php
- modules/AOS_Products/vardefs.php
- modules/AOS_Products_Quotes/vardefs.php
- modules/AOS_Quotes/vardefs.php
- modules/OptimisticLock/LockResolve.php
- modules/SecurityGroups/vardefs.php
- modules/SugarFeed/vardefs.php
Optimistic locking can display false positive as it doesn't work correctly with dates checkbox or html encoded fields
Addtiknaly somne moduels such as Quotes and Invoices have the optimistice locking definition incorrectly set so optimistic locking does not trigger on these modules
> Optimistic locking false positives

- download.php
From Forums topic: photo files with extra underscores weren't downloading correctly.
https://community.suitecrm.com/t/broken-photo-for-id-like-zcrm-12345/74087/21?u=pgr
The code in `download.php` is using a simplistic method to extract the ending in `_photo` or `photo_c` used by image fields. It assumes the filename has no additional underscores, which is not always the case.
- Studio: Add Photo field to detail views in Contacts module (which has an existing `photo` field by default, it just needs adding to view)
- Studio: Add Photo field Products module (which does not have an existing `photo` field by default) and add it to Detail view
- QR & R
- add a couple of photos in records from both modules
- check that the detail view displays the uploaded photos correctly in both modules
- try …
> Fix handling of file names with underscores in download.php

- modules/AOR_Reports/controller.php
Add 'Contains' operator to AOR multienum field
SuiteCRM save multi enumeration in database as string separated by commas. In AOR, 'Equal To' and 'Not Equal To' operator is not likely to match a string with multiple selections. 'Contains' is a more appropriate operator.
Create some records in a table with multienum field. Create a report with a condition for the multienum field.
> Add 'Contains' as valid opp for multinum

- include/SugarFields/Fields/Wysiwyg/SugarFieldWysiwyg.php
- themes/SuiteP/tpls/_head.tpl
Email compose body field missing due to invalid ref to tinymce
> Fix #8913 - Email compose body field missing

- include/export_utils.php
- include/utils.php
- modules/AOR_Reports/AOR_Report.php
see issues #8934 and #8936
see that +/- are not strippped from test and role sand reports main group work as expected
> Fix Saving strips +/- value from start of strings

- modules/AOR_Fields/fieldLines.js
After upgrading to 7.10.28 7.11.16/17 you cannot longer delete fields from reports
See  that you can not delete fields from reports
> Fix #8941 - Cannot delete reports fields

- modules/Emails/include/ComposeView/EmailsComposeView.js
Changed CSS Class for Fixing Bug
WYSIWYG wasn`t applied for correct textarea field ("description") because there is a field with the same ID in detail view.
So I`ve changed the CSS id, so that it  applies correctly.
WYSIWYG wasn`t applied for correct textarea field ("description") because there is a field with the same ID in detail view.
So I`ve changed the CSS id, so that it  applies correctly.
Please test WYSIWYG in detail view by clicking on email field with email. In modal window for writing email the field description should be shown up as WYSIWYG. It should also work in list view.
Changes in CSS id in javascript code
> Fixed #8956 - Email compose body not shown up in detail views

- modules/Schedulers/language/en_us.lang.php
> Add missing scheduler label for trimSugarFeeds

- modules/AOR_Scheduled_Reports/AOR_Scheduled_Reports.php
Fixes #8676 
If a Scheduled Report is created and it is not immediately eligible to run (for example, it's scheduled to run at midnight and it's currently the afternoon), then a Fatal PHP error is thrown**. 
This error could likely prevent _other_ scheduled reports from running - this is especially relevant if you have other reports scheduled at different times.
This PR fixes the issue by filling in a reasonable value for the `$lastRun` variable. This allows us to have the correct type for the `handleTimeZone()` function. 
** The Fatal error was caused by providing a `false` value to the `handleTimeZone(DateTime $date)` function.
Thanks @afernandez2000 for providing a recommended fix.
This allows you to create Scheduled Reports in a system that may have multiple. It will not break the …
> Fixed #8676: New Scheduled Reports does not run

- data/BeanFactory.php
- data/SugarBean.php
Fixes issues resulting from #8387 
#8387 addresses an issue where BeanFactory can cache beans which are not complete - missing fields as a result of how the SugarBean `fill_in_relationship_fields` method works.
However, the solution in #8387 can cause its own set of problems in installations which have large numbers of `after_retrieve` logic hooks and/or calculated fields, causing a significant performance drop.
The solution proposed in this PR solves both the original issue of incomplete beans being cached by BeanFactory, and also the performance issue by keeping a register of "shallow" beans which are only used to compute relate fields.
Performance issues will appear when an installation has a large number of relate fields, expanded subpanels, after_retrieve logic hooks and/or functions …
> Improved solution for BeanFactory caching incomplete beans

- data/Link2.php
When removing related ids, if a bean fails to load, place this id in the failures array and continue.
If bean fails to load/not instanceof SugarBean, track the failed id in the $failure array.
This has also required creating a new variable in order to track both the id and the bean (as failing to load the bean was overwriting the id itself with null)
Proposed fix for issue #9075
> Fix #9075 - Removing deleted related beans via link

- modules/AOR_Reports/AOR_Report.js
Use updateTimeDateFields as fieldInput is undefined when using dates
Use function updateTimeDateFields to deal with undefined dates when using date params on reports 
May also fix issue: #7618 & #8070
Solves issue with date params on reports
See: #8182
> Fix reports date issue #8182

- modules/Import/Importer.php
Check if fetched_row is an array before relying upon it for the condition.
Prevents notice in PHP7.4
PHP Notice error thrown when $focus->fetched_row is not an array.
1) PHP version > 7.4
2) PHP Error level include Notice
3) Import new record
> Prevent Notice Error During Import

- modules/Calls/language/en_us.lang.php
- modules/Calls/reschedule_history.php
> Fix Hardcoded 'by' label in calls history (issue #8999)

- modules/ModuleBuilder/tpls/labels.tpl
- modules/ModuleBuilder/views/view.modulelabels.php
Fixes display of module labels in Modulebuilder
Opening Module Builder and clicking on "Labels" for a module doesn't list any labels, see #6051
Solves the display of labels in the ModuleBuilder editing function. This function was broken by #5519, which fixed an issue for labels editing in Studio.
It also hides the dropdown for "frequently used labels" / "all labels" when it is not populated with values (in modulebuilder).
1. Open Module Builder
2. Create a new Package
3. Create a new Module of type "Basic"
4. Click on "Labels" on the navigation tree on the left
> Fix modulebuilder labels edit fixes #6051

- themes/SuiteP/css/suitep-base/editview.scss
- when the text option in a drop down exceeded the width of the div containing it, the drop down would overflow. This limits the size of the drop down to be 100% of the container width.
Drop down was overflowing, issue described in 9067. The fix I am suggesting limits drop down width do that it will not exceed the length of the text input fields
When trying to customise the software I have added drop down options that are too long for the container, it makes the view harder to read as the overflow can cover labels and hide information.
- go to drop down editor
- choose a drop down
- add option to drop down with very long text vaue
- view drop down on edit view and ensure that the drop down does not exceed the length of the text inputs
> 9067 - Fix the drop down width

- ModuleInstall/ModuleInstaller.php
- include/DetailView/DetailView2.php
- include/EditView/EditView2.php
- include/SubPanel/SubPanel.php
- include/SugarCache/SugarCache.php
- include/connectors/sources/default/source.php
- include/dir_inc.php
- include/utils/logic_utils.php
- include/utils/php_zip_utils.php
- include/utils/sugar_file_utils.php
- include/utils/zip_utils.php
- install/performSetup.php
- modules/AOP_Case_Updates/AOPAssignManager.php
- modules/Administration/Common.php
- modules/Administration/SugarSpriteBuilder.php
- modules/Administration/undoupdateclass.php
- modules/Administration/updateclass.php
- modules/Administration/upgrade_custom_relationships.php
- modules/Configurator/Configurator.php
- modules/Configurator/controller.php
- modules/ModuleBuilder/MB/MBLanguage.php
- modules/ModuleBuilder/MB/MBModule.php
- modules/ModuleBuilder/MB/MBPackage.php
- modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php
- modules/Studio/parsers/StudioParser.php
- modules/UpgradeWizard/silentUpgrade_step1.php
- modules/UpgradeWizard/upgradeMetaHelper.php
- modules/UpgradeWizard/uw_utils.php
This pull request makes sure that all modifications of php files are notified to OPcache by SuiteCRM core methods that save and close php files.
OPcache is an opcode cache for PHP and was included in PHP since PHP version 5.5 and is enabled by default in many distributions.
OPcache led to multiple issues in the past and still causes issues. This is caused by the dynamic nature of SuiteCRM: it writes php code and then includes these files directly after writing, which causes OPcache to not detect these modifications in time. The webserver then runs a previously cached version. It would require the dreaded "Quick Repair and Rebuild" to re-align the cache.
The changes in this pull request effectively remediate these issues by making sure that OPcache always is notified of potential …
> Fixed #8461 fixed #8462 : Implement effective opcache file clearing

- install/suite_install/Search.php
- lib/Search/ElasticSearch/ElasticSearchEngine.php
- lib/Search/ElasticSearch/ElasticSearchIndexer.php
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchEngineTest.php
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchIndexerTest.php
Set the Elasitcsearch Index key to be either a configured value or the Instance's unique key. 
This allows one Elasticsearch server to hold multiple CRM instances without collisions.
Added an additional Elasticsearch config setting so that existing instances can continue to use the 'main' index if needed (though not recommended)
Currently if you have multiple instances of CRM and a single Elasticsearch server, they will all share the same 'index' - like dropping all the data in a big pot. This makes a complete mess of the elastic search results. 
This PR foregoes the generic 'main' index name and uses the CRM's unique key instead. 
1. Spin up a CRM instance and connect to Elasticsearch. Sync records
2. Spin up a second CRM instance and connect to the same Elasticsearch server. Sync …
> Fixed #6800 - Elasticsearch: Elastic index name is hardcoded

- modules/Users/metadata/detailviewdefs.php
The Detailviewdefs for Users contain an entry for useTabs and tabDefs twice, once correctly under "templateMeta" and once in the wrong place of the definition hierarchy, probably caused by a merge failure.
Cleans up the detailviewdefs to remove the stray useTabs and tabDefs
It doesn't solve any problem, for this reason no issue was created.
- Click on Admin / User Management
- Click on a user
-> the details of the user should be displayed, as they did before
> Cleanup detailviewdefs for module Users

- include/generic/SugarWidgets/SugarWidgetSubPanelEditRoleButton.php
Opening an Opportunity issues the following entry in the webserver error log:
```Declaration of SugarWidgetSubPanelEditRoleButton::displayList($layout_def) should be compatible with SugarWidgetField::displayList(&$layout_def)```
This PR makes the method SugarWidgetSubPanelEditRoleButton::displayList compatible to it's parent class SugarWidgetField, it follows up on PR  #5635.
Open an opportunity, check the error log file of the webserver to see if a new entry like above appears.
> Incompatible method SugarWidgetSubPanelEditRoleButton::displayList - fixes #5624

- install/suite_install/Search.php
- lib/Search/ElasticSearch/ElasticSearchEngine.php
- lib/Search/SearchResults.php
- tests/unit/phpunit/lib/SuiteCRM/Search/ElasticSearch/ElasticSearchEngineTest.php
Issue reference: #8472
Issue reference: #7742
This PR adds support for the config values
$GLOBALS['sugar_config']['search_wildcard_char']
and
$GLOBALS['sugar_config']['search_wildcard_infront']
to ElasticSearchEngine::createSearchParams().
And it fixes resolving related bean IDs in SearchResults::getRelatedId() when
there is more than one level of relationships.
Using the ElasticSearchEngine can cause fatal PHP errors (and therefor resulting
in incomplete search results) and
search results returned by the ElasticSearchEngine can appear incomplete
when one expects the default search wildcard character '%' to work as it would
when using filters (SQL) or the legacy 'Advanced Search' engine.
1. Search Engine configuration: put the following config values in the `config_override.php`:
``` …
```
> Fixed #8472 - No or not complete Searchresults using elasticsearch engine

- include/utils.php
Issue reference: #9106
Re-adds functionality that was removed from the ```securexss``` method which was causing different encoded values to be returned.
1. Check Travis 
(This has been tested internally).
> Fix #9106 - Update securexss for backwards compatibility

- modules/AOW_Actions/AOW_Action.php
- modules/AOW_WorkFlow/aow_utils.php
Fix #9237 where dates in aow actions & conditions are not saved or displayed correctly
Use fixUpFormatting in actions and only display as datetime if field type is datetime else use date
Use fixUpFormatting in actions the same way its used for condtions
Use to_display_date when field type is date instead of defaulting to to_display_date_time
See #9237
See #9237
> Fix #9237 where dates in aow actions & conditions are not saved or displayed correctly

- themes/SuiteP/css/suitep-base/listview.scss
Fix labels in module filters using long text overflowing into the next element.
Remove attribute "white-space: nowrap;"
Add attribute "line-height: $line-height-base;" to
element "#search_form label".
Avoid labels overflowing into the next element.
Rebuild sass
> Fixed #9201 - Filter form label styling.

- modules/MySettings/TabController.php
- modules/UpgradeWizard/silentUpgrade_dce_step2.php
- modules/UpgradeWizard/uw_utils.php
Declare the function TabController::get_key_array() as static function since
it is intended to be used as such and fix calls to this function that
assumed that it was a non-static function.
Statically calling non-static functions is deprecated.
1. In `php.ini` change the `error_reporting` setting from something like
```
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
```
to
```
error_reporting = E_ALL & ~E_STRICT
```
2. Restart Apache (e.g. `service apache2 reload`) or PHP-FPM (e.g. `service php7.1-fpm restart`)
3. In SuiteCRM's Admin panel navigate to "Display Modules and Subpanels"
4. Check Apache error log for messages like
```
PHP Deprecated:  Non-static method TabController::get_key_array() should not be
called statically in …
```
> Fix function declaration of TabController::get_key_array()

- modules/Emails/metadata/detailviewdefs.php
date_sent_received duplicated in two columns
Having the date sent/received is also more important to have a the top rather than the bottom.
SuiteCRM 7.10.25
> Correct layout of date fields

- modules/AOS_Products_Quotes/AOS_Utils.php
Patch only init Currency class once when saving products as its attached to focus object which does not change per loop.
> Only init Currency once when saving 

- modules/Emails/Email.php
Cases parent_type to be pulled for Email Template
> Add cases to email object_arr

- modules/AOR_Charts/AOR_Chart.php
Replaced substr with mb_substr
Changes to be committed:
modified:   AOR_Chart.php
Fix for issue #9179
substr sometimes cuts string with utf8 characters in a way, that json_encode can't encode it.
Display graphs with labels contianing utf8 characters.
Described in issue #9179
> Fix for: #9179 AOR_Charts getShortenedLabel fails on utf8 characters

- include/InlineEditing/InlineEditing.php
In Studio, enter a help containing a quote text in a field
When inline editing that field, all text after the quote is removed
> Inline Edit: Help text containing quotes is not correctly displayed

- modules/SecurityGroups/metadata/detailviewdefs.php
This fix adds the Overview label to the tab header in the Security Groups detailview
1. Go to Security Groups detailview
2. See the change
> Add the `Overview` label to Security Groups detailview

- data/SugarBean.php
- tests/unit/phpunit/modules/Cases/CaseTest.php
- tests/unit/phpunit/modules/Meetings/MeetingTest.php
When creating a meeting in the meetings module, the invite notification emails are only going to the first invited user/contact/lead.
All invitees should receive a meeting invite email
1 invitee is emailed.
Check against an array of user ids rather than a boolean when preventing duplicate emails caused by workflow hooks
1. Create a meeting in the meetings module
2. Invite more than 1 user
3. Hit Save and send invites
4. Check logs or mailcatcher if set up
Need to make sure all meeting invitees receive an invitation email.
https://github.com/salesagility/SuiteCRM/issues/9358
* SuiteCRM Version used: 7.12.0
* Browser name and version: Firefox Version 94.0 (64-bit))
* Environment name and version: PHP 7.4
* Operating System and version: Ubuntu 20.04.3 LTS
> Fixed #9358 - Meeting invite notification emails are not sending to all invitees.

- include/SugarFolders/SugarFolders.php
Fixes a bug when importing emails and using the Sugar Folders module where it would add an identical relationship between Sugar Folders and Inbound Email accounts.
Stops duplicating data in the database for each email imported.
If the folders_rel table is empty, when importing emails, the Inbound Email account in use should create a new relationship between itself and a Sugar Folder.
Once that relationship exists, it should be the only one of it's kind in the folders_rel table, even after importing more emails with the same Inbound Email account.
> Fix Issue #9192: Fix duplication of folders_rel table entries.

- modules/Activities/EmailReminder.php
- modules/Users/User.php
Email reminders for Meetings and Calls are sent to users, even if their account has been disabled.
This checks to see if the user is enabled before adding them to the recipients of an outbound reminder email.
Added a new function isEnabled() to the user bean to provide a standardised way to check if a user is active.
Email reminders getRecipients() calls this new user function to check the user is still a current user.
Once a user has been set to Inactive, Terminated or Leave of Absence it's unlikely we should be sending them emails.
Login as test user
Create a meeting or call with a reminder in the near future.
Switch to another user with admin rights
Disable the test user, either by setting the user status to Inactive or the employee status to Terminated or Leave of Absence.
The …
> Prevent Email Reminders for Disabled User

- modules/AOW_WorkFlow/AOW_WorkFlow.php
- modules/AOW_WorkFlow/language/en_us.lang.php
- modules/AOW_WorkFlow/metadata/detailviewdefs.php
- modules/AOW_WorkFlow/metadata/editviewdefs.php
- modules/AOW_WorkFlow/vardefs.php
Added checkbox to workflows, allowing users to enable them to trigger when importing records.
- Create a workflow for a specific module, ticking the run on import field
- Import records to that module & ensure the workflow has triggered
> Fix #9376 - allow workflows on import

- modules/Emails/include/ComposeView/EmailsComposeView.js
Added text color plugin and  forecolor/backcolor buttons
These buttons used to be available in older versions of SuiteCRM and disappeared when the compose view was restructured
> Allow changing text colors when composing an email

- modules/OAuth2Clients/metadata/detailcredentialsviewdefs.php
- modules/OAuth2Clients/metadata/detailpasswordviewdefs.php
- modules/OAuth2Clients/metadata/detailviewdefs.php
- modules/OAuth2Clients/metadata/editcredentialsviewdefs.php
- modules/OAuth2Clients/metadata/editpasswordviewdefs.php
- modules/OAuth2Clients/metadata/editviewdefs.php
see #9374
See you can now create an  OAuth2 password in php8+
> Fix #9374 - OAuth password creation Unsupported operand types fatal in php8

- modules/OutboundEmailAccounts/metadata/detailviewdefs.php
- modules/OutboundEmailAccounts/metadata/editviewdefs.php
see #9382
See you can now edit an Outbound Email in php8+
> Fix #9382 - Outbound Emails editview Unsupported operand types fatal in php 8

- modules/ModuleBuilder/parsers/relationships/AbstractRelationships.php
- modules/ModuleBuilder/views/view.relationship.php
The changes fix the unsupported each() function in PHP8.x
- The fix applied to fix the existing code using each() function
- The fix uses PHP8.x polyfill for the removed each() function
=> Setup PHP8 as your project environment:
1) If you are not using a docker environment:
Upgrade your PHP Version to 8.0 or above as applicable to your System/PHP environment setting.
2) If you are using a docker environment:
Pull down the PHP8 Container by following these steps:-
a) Specify the PHP8 docker image entry inside your docker-compose.yaml file
A sample entry:
```
php8:
image: <docker image url>
container_name: php8
restart: unless-stopped
ports:
- <port_number>:80
volumes:
- $LOCAL_DIRECTORY: <project document root e.g. /var/www>
environment:
IDE_KEY: $IDE_KEY
networks:
local_docker: …
```
> Fix #9383 unsupported each function in php8

- include/InlineEditing/InlineEditing.php
Clsoes #9408 
As described in the Issue, Emails can't be deleted from inline edit of a Detail or ListView
In this PR we add the condition in the Inline Edit file to be able to delete emails from the Inline edit functionality
Any user should be able to Delete an Email.
Check that emails can be deleted from Inline edit and make sure everything works alright inside inline edit functions.
> Fixed #9408 - Emails can't be deleted from inline edit

- include/SugarQueue/SugarCronJobs.php
- include/SugarQueue/SugarJobQueue.php
- modules/SchedulersJobs/metadata/subpanels/default.php
Improvements to scheduler processing to delete historic scheduled tasks from the job_queue table.
Historic jobs from the job_queue table are never removed.
If a job fails in a certain condition, the schedulers may no longer run
The subpanel doesn't display the actual job status, only the overall status
Check that scheduled tasks older than the ['sugar_config']['jobs']['success_lifetime'] and ['sugar_config']['jobs']['failure_lifetime'] values are deleted. 
Check that running jobs that exceed ['sugar_config']['jobs']['timeout'] are correctly marked as failed
> Clean Historic and Failed Schedulers

- include/ListView/ListViewDisplay.php
Similar to proposed fix https://github.com/salesagility/SuiteCRM/pull/8600 . Please close this one if you want me to continue dialogue in the other thread.
Fix https://github.com/salesagility/SuiteCRM/issues/8525 & https://github.com/salesagility/SuiteCRM/issues/8309
Bulk Action button is not showing for users without delete access. Delete button is still showing for users without delete access.
Provide continuity between different roles in the list view and fix for what I assume was the original design intent.
Login with a user without delete access for a module and go to the list view of that module. Check Bulk Action menu, notice that it shows 'email' rather than Bulk Action.
> Fix #8525 #8309 Bulk Action button missing and delete button showing for users with no delete access

- modules/ProjectTask/Menu.php
- modules/ProjectTask/ProjectTask.php
- modules/ProjectTask/language/en_us.lang.php
Make Project Tasks Importable
Fix #8948 
Go to Project Tasks.
See that you can now import.
> Fix #8948 - Make Project Tasks Importable

- include/Popups/PopupSmarty.php
- include/Popups/tpls/header.tpl
custom viewdef when set when opening a module popup, gets reset to the default popup def when the list is filtered, as the metadata value is not stored
See the viewdef overrides on popup don't get overwritten
> Fix #9455 - Popup metadata override removed when filtered

- lib/Search/BasicSearch/BasicSearchEngine.php
When record is linked with multiple activities / history records the basic search results get duplicated.
This is due to a known issue with `ListViewData` search, it requires the `filter_fields` in order to avoid the duplicates.
To fix this we are calculating the `filter_fields` for each module and passing those to the `ListViewData` search
When record is linked with multiple activities / history records the basic search results get duplicated.
1. Link several activities / history entries to Leads, Contacts, etc records you are going to search for
2. Open global Search. Search for those records that have the activities attached.
3. There should be no duplicate lines in the results of each module. Meaning a same record should not display twice
> Fix duplicate results in basic search

- modules/Studio/DropDowns/DropDownHelper.php
This address a issue where the statically called saveDropDown function, used not static references and therefore caused a 500 error when called and affect thing like renaming modules
See you can now save dropdowns and change modules name without an error
> Fix #9496 - Cannot save dropdown values

- ModuleInstall/ExtensionManager.php
- include/SugarObjects/LanguageManager.php
- include/utils/file_utils.php
- modules/ModuleBuilder/parsers/parser.label.php
Provides static method for compiling extension files with filenames prefixed with _override from Studio taking priority. 
Intended to replace https://github.com/salesagility/SuiteCRM/pull/8081
Allows for EXT files to be compiled without using ModuleInstaller::merge_files which is encumbered by the DB and fails on initial install when there is no DB present.
1. Apply this PR.
2. Make some non-studio language changes in the extensions frame work.
3. Make some studio language changes.
4. Run a Repair & Rebuild.
5. Do a fresh install ensuring the compiled `.ext` files do not exist.
> Statically Compile EXT Files & Studio Override Precedence 

- themes/SuiteP/include/Dashlets/DashletHeader.tpl
The reload icon in every dashlet was reloading all the dashboard.
With my fix it reloads just the dashlet requested as in previous versions of suiteCRM.
My code just replace the onclick function in the themes/SuiteP/include/Dashlets/DashletHeader.tpl
User use to have a lot of dashlets in their dashboards and performance in big databeses is penalized. By other hand users has no way to understand which of their dashlets are slow. Reloading dinamicaly just the targeted dashlet they can experiment to remove slow and not so useful dashlets.
> Fixed #2857 - No dynamic refreshing in dashboard

- include/SugarObjects/templates/basic/metadata/metafiles.php
- include/SugarObjects/templates/basic/metadata/subpaneldefs.php
- include/SugarObjects/templates/company/metadata/metafiles.php
- include/SugarObjects/templates/company/metadata/subpaneldefs.php
- include/SugarObjects/templates/file/metadata/metafiles.php
- include/SugarObjects/templates/file/metadata/subpaneldefs.php
- include/SugarObjects/templates/issue/metadata/metafiles.php
- include/SugarObjects/templates/issue/metadata/subpaneldefs.php
- include/SugarObjects/templates/person/metadata/metafiles.php
- include/SugarObjects/templates/person/metadata/subpaneldefs.php
- include/SugarObjects/templates/sale/metadata/metafiles.php
- include/SugarObjects/templates/sale/metadata/subpaneldefs.php
Rebased branch to hotfix from #9469 
Closes #9468
As the Issue describes, newly created custom modules don't have the Security Suite subpanels by default, they need to be added manually in their modules' code.
This PR adds the necessary code to the SugarObjects templates for the different module types that will be later used by the ModuleBuilder when creating the modules. Basically, it adds the definition of the Security Suite subpanels in the same way that the rest of the metadata definition is added.
With this change, newly created modules will have the Security Suite subpanel by default
1. Create a module in the ModuleBuilder
2. Deploy the module
3. Create a record and check that the SS subpanel appear in their DetailView.
> Fix #9468 - Adding Security Suite subpanels to new custom modules

- Api/V8/JsonApi/Repository/Filter.php
Issue reference: #8366 
Grouped out filter params for query.
Without grouping we fail to apply OR filter.
Example of generated query:
```sql
contacts.phone_mobile = '...' OR contacts.phone_work = '...' OR contacts.deleted = '0'
```
Should be:
```sql
(contacts.phone_mobile = '...' OR contacts.phone_work = '...') AND contacts.deleted = '0'
```
* Create a Contact and set Phone Work and Phone Mobile for some values.
* Apply OR filter to GET modules API call, targeting Contacts.
```
/V8/module/Contacts?filter[operator]=or&filter[phone_mobile][eq]=some_value&filter[phone_work][eq]=some_value
```
* Run some more tests with varying filter value.
> Fixed #8366 - V8 API Filtering W/ OR Operator Chained Conditions

- modules/ModuleBuilder/javascript/ModuleBuilder.js
- tests/_support/Step/Acceptance/ModuleBuilder.php
- tests/acceptance/Core/ModuleBuilderFieldsCest.php
Auto-close annoying success message boxes in Module Builder.
When working with the Module Builder every 2nd click a success message box
pops up which then requires clicking on the tiny "close" link.
This makes working with the Module Builder an unnerving task.
Create a new package + module in Module Builder, create some fields, etc.
> Auto-close success message boxes in ModuleBuilder

- modules/ModuleBuilder/views/view.modulefield.php
Rebased branch to hotfix from #9439 
Closes #9438 
As described in the issue, the keyword 'action' shouldn't be allowed for field name creation.
This can cause problem to users that aren't aware.
1- Go to Module builder
2- Try adding a field called "action" to any module
> Fix #9438 - Adding Action keyword to fieldname exception

- include/entryPoint.php
- include/utils.php
- Enable php session_gc by default
- Add config to not enable it
- Add config to set values for gc_probability and gc_divisor
- When using custom `session_dir`, the session files aren't cleaned up.
- see #3157 
- on config.php, change `session_dir` to something different from the default
- Login in the app
- Check that session files were added to the directory defined in `session_dir`
- logout from the session
- check if some of the session files were removed. You may need to refresh the page some times. (the session garbage collector is done randomly with a probability of 1/100)
- In config.php, change the value of `enable_session_gc` to false.
- Check that after login in and logging out the session files aren't removed 
- see #3157
> Fix #3157 - Add default option to enable session_gc

- modules/AOP_Case_Updates/Case_Updates.php
Case updates from contacts are run through nl2br which adds unexpected whitespace and causes #9594. This fix removes the call.
Fixes #9594
- Create a case update as in #9594. Alternatively update the DB for a case contact to add some HTML that has newlines.
- Open the threaded case updates view.
> Fix #9594 - Don't convert nl to BR for contact updates 

- include/Imap/ImapHandler.php
The test functionality of InboundEmail cycles through multiple imap connection stings to find the optimum. See InboundEmail.php findOptimumSettings() In doing so, it triggers multiple errors, which may be better represented as warnings. As this is by design, changing the level of these errors to warn will prevent unnecessary errors being logged.
Minimises logged errors
From Admin -> Email -> Inbound Email , run the test functionality on an IMAP mailbox. Multiple errors should now be suppressed such as:
* ImapHandler trying to use a non valid resource stream.
* ImapHandler trying to set a non valid resource az stream.
> Change the logger level in setStream and getStream functions to prevent excessive log errors

- themes/SuiteP/include/SubPanel/tpls/SubPanelTiles.tpl
From https://github.com/salesagility/SuiteCRM/issues/9663
Suite will auto collapse Subpanels on screens below "Large"(less than 1130 pixels). This code also collapses regular panels on the detail view.  This seems to be an unintended side effect.
Large screen:
Small screen(requires a reload):
Subpanels should be collapsed but panels with information on them from the current record should remain expanded if that is the default state.
1. Open a Case record in detail view on a large screen greater than 1130 pixels, the "Case Updates" should be expanded.
2. Resize the window so that it is less than 1130px width
3. Reload the page
4. The "Case Updates" panel will start collapsed
> Fix #9663 - Smaller screens automatically collapse non-subpanel panels

- modules/ModuleBuilder/MB/MBPackage.php
From issue https://github.com/salesagility/SuiteCRM/issues/9660
Imported module customizations via the module loader copy files to the "custom/working" directory. This directory is used to store studio changes that have been saved but not deployed.
All metadata is copied to this directory, except for listviewdefs.php, regardless if it is in the custom/working directory of the exported module.
This causes an issue where Studio loads in this working metadata file for dashletviewdefs and never overwrites or deletes it because the working directory is only used for detail view, edit view and quickcreate view.
Imported customizations cause Studio to load the wrong dashlet views.
1. Go to Studio and make a customization to cases->layouts->defaults->SuiteCRM Dashlet->SuiteCRM Dashlet Search to …
> Fix #9660 - Copy only select files to custom/working directory

- include/Sugar_Smarty.php
Fix for https://github.com/salesagility/SuiteCRM/issues/9627
Has been an issue since https://github.com/salesagility/SuiteCRM/pull/8514
Studio changes such as changes to a field or layout are not getting picked up by the CRM until a server restart under certain conditions.
When opcache.validate_timestamps is set to 0 on the server, the smarty template cache does not get cleared from opcache, this causes old templates to load.
Studio changes require a server restart to show up when validate_timestamps is set to 0 on a server
1.  Ensure xdebug isn't active on the container/server
2.  Set opcache.validate_timestamps to 0 in server's php.ini
3.  Perform a server restart to clear cache
4.  Load the cases detail view to load it into cache/opcache
5.  Go to Studio and make a change to the layout …
> Fix #9627 - Studio changes not picked up by CRM when opcache.validate_timestamps=0

- lib/Search/UI/SearchResultsController.php
Pagination total was previously determined using a count on the hits returned.
Basic and advanced search return all results from a query, making the count an effective solution. Elasticsearch results are limited by the query size parameter rendering this previous solution unsuitable.
This change uses the getTotal value from the SearchResults class which contains the true total.
Tested for backwards compatibility with all three search types.
Pagination is missing on the search results page when using Elasticsearch engine
Perform a search which returns a multi page result and ensure pagination is available. 
It may be worth testing with Basic, Advanced and Elasticsearch.
> Fix missing pagination on Elasticsearch results page

- include/utils.php
- modules/Administration/repairDatabase.php
Update config defaults to include allowed_preview value.
Removes Elasticsearch references and indexing during QR+R, adds ```allowed_preview``` to default config function.
Improves performance of QR+R by avoiding Elasticsearch indexing when unnecessary. Including ```allowed_preview``` in config defaults allows Elasticsearch indexing to complete without errors when indexing the Documents module.
1. Run Quick Repair & Rebuild to confirm performance.
2. Manually run Elasticsearch indexing in terminal to return and view errors. Documents should now complete without error.
> Fix bug with Elasticsearch indexing unnecessarily during QR+R.

- modules/Administration/Administration.php
- modules/Emails/EmailUIAjax.php
- modules/OutboundEmailAccounts/OutboundEmailAccounts.php
Solves #9753 
As described in the issue, the PR adds the trim() function before saving the data related to the SMTP connection and it does so in the 3 different ways to store this information: Email Settings, Outbound Email and Outgoing SMTP Mail Servers in user configuration
The CRM allows you to enter blank spaces in the fields related to SMTP connections causing subsequent failures due to these blank spaces. In this way, the CRM allows you to enter data that does not generate errors.
1. Create an SMTP account, from Email Settings, Outbound Email and Outgoing SMTP Mail Servers in user configuration, whose fields have spaces before or after them from the different parts of the CRM where they can be created.
2. Edit the registry again and check that the spaces have disappeared
> Fix #9753 - Do not save white spaces in SMTP data

- modules/InboundEmail/InboundEmail.php
- modules/Schedulers/_AddJobsHere.php
… from AOPInboundEmail.php
Trying to run cron.php with PHP 8 fails with a fatal error (see [issue salesagility/SuiteCRM-Core#143](https://github.com/salesagility/SuiteCRM-Core/issues/143)):
PHP Fatal error:  Declaration of AOPInboundEmail::handleCreateCase(Email $email, $userId) must be compatible with InboundEmail::handleCreateCase($email, $userId)
This allows cron.php to succeed on a system with PHP 8.
The fix was suggested by pgr on forum team: "it’s a known issue that was aggravated in PHP 8 because it used to be a warning, now it’s FATAL"
Run cron.php with PHP 8
(Note: for the script to fully succeed, PR salesagility/SuiteCRM#9731 for Issue salesagility/SuiteCRM#9730 must also be applied)
> Fix #9728 - cron.php fails with "must be compatible" error

- modules/Import/Importer.php
Solves https://github.com/salesagility/SuiteCRM/issues/9674
The PR deletes the condition indicated in the issue.
The PR deletes the condition indicated in the issue to be able to import, with the create and update option, files with record IDs deleted at the database level
1. Create a contact, opportunity, or other record and export it
2. Delete the record from the CRM interface
3. Import the file exported in step 1 through the Update and Create option.
4. Check that the import was successful
> Fix #9674 - Error when importing (creating and updating) a record with ID already deleted in the database

- include/MySugar/tpls/dashletsSearchResults.tpl
Solves #9658
The PR modifies the properties of the HTML element returned by the dashlet filter to be the same as the element that is displayed when no filter is applied, so that only one dashlet is added.
Avoid having to remove a dashlet when the dashlet filter has been used
1. Access the Home view
2. Filter to add a dashlet from any module
3. Check that only one dashlet are added.
> Fix #9658 - SuiteCRM add duplicate dashlet when filter is used

- modules/Calendar/views/view.savesettings.php
Closes #9650 
As described in the issue, this PR update the call to the deprecated constructor method.
Update the call to the deprecated constructor method.
It is a very simple change and it can see it by reviewing the code
> Fix #9650 - Deprecated constructor method is being called in Calendar

- modules/AOW_Actions/actions/actionSendEmail.php
Problems creating custom AOW_Action by subclassing it from **actionSendMail** which calls this private function...
Create custom AOW_Action with something like this...
```php
class actionSendMyCustomEmail extends actionSendEmail
{
public function run_action(SugarBean $bean, $params = array(), $in_save = false)
{
[... code copied from original function, using function $this->getEmailsFromParams() ....]
}
}
```
You get a PHP error: `Uncaught Error: Call to private method getEmailsFromParams() `
This is wrong because this class is meant to be overridable, so these functions should be either `public` or `protected`.
> Turn private to protected to fix SendMail AOW_Action overrides

- modules/EmailTemplates/EmailTemplate.php
Problems customizing EmailTemplate class with a custom class.
Create custom class in `custom/modules/EmailTemplates/CustomEmailTemplate.php`with something like this...
```php
<?php
if (!defined('sugarEntry') || !sugarEntry) {
die('Not A Valid Entry Point');
}
require_once 'modules/EmailTemplates/EmailTemplate.php';
class CustomEmailTemplate extends EmailTemplate
{
public function retrieve($id = -1, $encode = true, $deleted = true)
{
[... code copied from original function, using function $this->repairMozaikClears() and  $this->repairEntryPointImages....]
}
```
You get a PHP error: `Uncaught Error: Call to private method`
This is wrong because this class is meant to be overridable, so these functions should be either `public` or `protected`.
> Turn privates to protecteds to fix Emailtemplate overrides

- include/CleanCSV.php
If a cell is empty then there is no need to escape the cell, so just return the empty string
Description of Issue in  #9556 (https://github.com/salesagility/SuiteCRM/issues/9556)
As above
As above
> fix escapeField where $cell string is empty

- modules/DynamicFields/language/en_us.lang.php
Fix #6756
Add `LBL_INSERT_FIELDS` to Dynamic Enum Language file
Go to the page shown in #6756, see that the label now shows as expected.
> Fix #6756 - Add Label to Dynamic Fields

- modules/Administration/Diagnostic.tpl
Checkboxes are automatically checked in the diagnostic tools section in admin. Having them unchecked is quicker and easier for users just checking what they want as it is rare that users need all of them. 
1. go to adamin->diagnostic tools
2. see that all checkboxes are not checked
> fix #9802 - Diagnostic checkboxes

- include/EditView/EditView2.php
- Closes #9717 
This PR adds the condition "$_REQUEST['isDuplicate'] == true" when testing if the record is newly created.
With this change, the Security Suite Group Selector will appear in any duplication form.
1. Create several Security Suite Groups
2. Add those Groups to a User
3. Enable de Security Suite Setting "Use Creator Group Select"
4. Create a record with that user and check that the Group selector appears
5. Duplicate a record and check that the Group selector appears.
> Fix #9717 - Security Suite Record Group selector doesn't appear when duplicating records

- data/SugarBean.php
- include/DetailView/DetailView.php
- include/export_utils.php
- include/utils.php
- include/utils/LogicHook.php
- modules/AOR_Reports/AOR_Report.php
- modules/Campaigns/utils.php
- modules/Emails/EmailUI.php
- modules/MergeRecords/MergeRecord.php
- modules/ProspectLists/TargetListUpdate.php
- modules/Spots/controller.php
- service/v3_1/SugarWebServiceUtilv3_1.php
- soap/SoapSugarUsers.php
This PR add 2 new Logic Hooks:-
- before_acl_query
- before_acl_check
That allow you to extend and override access rights. To achieve this there was slight extension to the logic hook logic to allow it too return a value which was require in both cases, along side the general use of access logic being simplified through the CRM so it consistent and easily extendable via the new hooks.
The change should fully backward compatible and documentation to follow
> Feature - Add ACL Access Logic Hooks

- include/SugarTinyMCE.php
Closes #9646 
As described in the issue, this PR will display the TinyMCE editor in step 4 of the form generation process
Retrieve a feature that the CRM had to be able to edit the form from the TinyMCE editor
1. Go to the campaign menu and create a Person form
2. Skip ahead to step 4 and check that the TinyMCE editor is displayed
> Fix #9646 - Display TinyMCE in step 4 of the campaigns form wizard

- modules/Surveys/Menu.php
Resolve #9499 
In this PR, the menu item "View Survey Responses" is added to the Surveys module
In this way users will be able to access the Survey Responses ListView easily.
1- Go to Surveys module
2- Check that the Menu item "View Survey Responses" appears
> Fix #9499 - Add View Survey Responses Menu item

- include/language/en_us.lang.php
Closes #9473
As described in the Issue, there is missing an item in the campainglog_activity_type_dom list.
This PR adds the missing item to the language file.
With this change, the item will appear correctly
1. Create a Survey
2. Create a Campaign Survey Type
3. Send the campaign
4. Answer the Survey
5. Check the Campaign log for the activity Type.
> Fix #9473 - Missing item "Survey" in campainglog_activity_type_dom

- lib/Search/ElasticSearch/ElasticSearchIndexer.php
Previously, the ElasticSearch Indexing would assume that if there were errors in a batch that all items in the batch had an error.  This fix only logs errors when an item actually has an error present.
Previously, the sendBatch() function did not check if $item[$action]['error']) was set before trying to access indices within.  This would cause errors when indexing if there was a batch that included an item that had an error but others items within the batch did not.
My database previously included some items that had some errors.  I've since fixed those errors so I can't immediately reproduce the issue currently.
> ElasticSearch Indexing batch error handling

- include/database/MysqliManager.php
Add a check on the MYSQL version and ignore int lengths in versions >= 8.0.19
This fixes #9568 - namely some DB changes always appearing in the QR&R log due to MySQL ignoring int lengths. https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-19.html
- Run a QR&R on an instance using MySQL > 8.0.19. Plenty of changes should appear (add an int field with a length in studio if not
- Run the DB changes - note that this has no effect on the QR&R results
- Apply fix - run QR&R and the changes will be gone
> Fix #99568: Ignore int len when comparing vardefs in newer MySQL versions

- themes/SuiteP/include/DetailView/DetailView.tpl
FIX #9344 
Found that the name of the function selectTabOnError has been declared twice at the theme SuiteP
If I change the definition of the function from let to var it does not throws the error on the javascript console.
When create a new record with quickcreate view form subpanel it throws an error console of javascript. 
1. Add a panel in the QuickCreate view of the Accounts module
2. After saving the view, change the "Panel" to "Tab" configuration
3. Go to the Quickcreateview of Accounts (Inside an Account, the Member Organization subpanel)
4. Open the browser console and see the error
> FIX #9344 Error in Browsers console after adding tabs to Quickcreate: function selectTabOnError

- include/ListView/ListViewData.php
Corrected typo mistake 
Count bracket is closed after relational operator it must be typo mistake done years ago
before PHP 8.0 count() use to yield a warning but after PHP 8.0 count() will throw TypeError if countable types parameter is not passed, in this case Boolean value was feeding to count so it was throwing TypeError in PHP 8.0+
This issue will throw TypeError in PHP 8.0 and may stop execution on all listing page
Use PHP 8.0 + version and search on any listing page with some conditions selected in dropdown in basic search
Click on Campaigns -> View Email Template -> click on filter -> in Quick filter enter some name and select type as email -> click on search you will see following error
```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type …
```
> Closing count bracket before relational operator PHP 8.0 count throwing TypeError

- include/SugarCache/SugarCache.php
- include/utils/file_utils.php
Fixes compatibility with PHP 8.0 for Plesk users
PHP configurations which have the following configured in php.ini
`disable_functions = opcache_get_status`
will not be able to install or use SuiteCRM from 8.0 as disabled functions now trigger a fatal error
https://php.watch/versions/8.0/disable_functions-redeclare
The code for SugarCache uses a check which uses the function opcache_get_status to retrieve detailed information on the current opcache configuration
Plesk users have the above php.ini configuration as default are are not able to install SuiteCRM with the default configuration with php 8.0
This change provides a graceful degradation for installations which have opcache_get_status disabled by checking the opcache configuration using the more archaic function "ini_get" to retrieve …
> Fix #9873 - Plesk php.ini disable_functions = opcache_get_status

- modules/Users/language/en_us.lang.php
- resolve #9871
This PR adds the `LBL_LAST_ADMIN_NOTICE` label that must be displayed when trying to update all users massively, if you try to modify the _is_admin_ or _status_ fields.
This prevents the message with the text undefined from being displayed
An erroneous message that does not offer any information to the user is avoided
1) In the list view of the users module, select all the records (not the current page, but all the records)
2) By mass update, try to modify the _is_admin_ or _status_ fields and check how the correct message is displayed
(It would be nice to specify in the documentation that the inheritance of security groups is applied exclusively at record creation time.)
> Fix #9871 -  Javascript message error when bulk updating all user records

- metadata/securitygroups_recordsMetaData.php
resolve #9883
It has been found that the problem is caused by the _module_ field in the _securitygroups_records_ table being defined as _char(36)_, so the name of the module will be truncated in the database when a record is created in this table, that is, when any Security group is assigned to a record of the same. In this PR, the type of the module field is changed to _varchar(100)_ in the _securitygroups_records_ table, so that longer module names are stored correctly. It has been considered that setting the limit of the field at 100 is sufficient for any reasonable module name.
It is common to use module names that, along with the prefix, exceed 36 characters and this must be corrected.
1. Remove or rename the securitygroups_record table and quick repair. The table should be created …
> Fix #9883 -  Security Groups do not work with modules whose name exceeds 36 characters.

- modules/DynamicFields/templates/Fields/Forms/dynamicenum.php
- modules/DynamicFields/templates/Fields/Forms/enum2.php
- Closes #9909 
This PR adds a default empty item to the list of Drop Down lists available. Therefore, if the user doesn't choose or select a list, no list will be assigned.
No list should be chosen by default
- Create a Dropdown field
- Check an empty option item appears in the Dropdown List field.
> Fix #9909 - Default empty item when creating a new Dropdown field

- themes/SuiteP/css/suitep-base/dashboard.scss
Prior to this change, overflow of the dashlet options popup div were set to hidden.  Now they are set to auto to allow scrollbars when content overflows.
In my SuiteCRM instance, the Save and Clear buttons were not accessible in the 'My Open Cases : Options' popup when configuring the dashlet.
Overflow of the div containing the options in the popup was set to hidden and the max-height was insufficient to display all of the options plus the buttons.  Rather than change the max-height (which may need to be readjusted in the future), I figured that allowing the div to vertically scroll was a better solution.
Rebuild sass
> Fix #9914 - Update dashboard.scss for dashlet options overflow

- modules/AOW_WorkFlow/AOW_WorkFlow.php
- Closes #9900 
This PR adds the code that decode the HTML value of a text field in a Workflow condition. Therefore any character set can be used in condition
Condition should work with any special character.
1. Create a workflow that compares "aña" with last_name of a Contact
2. Add any action
3. Create a Contact with last_name "aña" and check the the Workflow run successfully.
> Fix #9900 - Conditions doesn't recognize some of the characters set

- modules/ExternalOAuthConnection/controller.php
- modules/ExternalOAuthProvider/controller.php
Fix OAuth External Provider and OAuth External Connection saving with no type.
1. When creating a OAuth External Provider record remove the `type=xxx` from the url.
2. Fill in required fields and save
3. See that it defaults to personal.
4. Do the same with a OAuth External Connection record and see the same result
> Fix Email OAuth Saving with no type

- modules/ProspectLists/Save.php
The ```$focus->save()``` call inside ```\modules\ProspectLists\Save.php``` on line 79  is unnecessary.  
If there are any after_save logic hooks present on the Prospect List (Target List) module, it will trigger them twice for a target list that is being duplicated, causing undesired results.
This fix is related to this issue:  [https://github.com/salesagility/SuiteCRM/issues/9602](url)
When a Target List is duplicated there's a check on the ```\modules\ProspectLists\Save.php``` that handles adding related records to the Target List being duplicated.   
On line 79 of the ```Save.php``` there's a call that is redundant to the save method of the focus bean. This causes any after_save logic hook to be triggered twice which is undesirable.
This solves redundant after_save logic hooks being …
> Fix #9602 - ProspectLists save function has a duplication issue

- include/SuiteEditor/SuiteEditorConnector.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
Solves https://github.com/salesagility/SuiteCRM/issues/9768
As described in the issue, the PR adds the necessary configuration in TinyMCE to disable convert the URL when creating a link.
Being able to link to CRM content in emails.
1. Create a campaign and go to the Templates step.
2. Open the popup view and insert a link to the site's URL in the body of the email.
3. Open the popup view of the newly created link and verify that the scheme and domain have not been removed.
>  Fix #9768 - Do not convert link URLs in TinyMCE 

- modules/AOW_Actions/actions/actionComputeField.php
- Closes #9621 
As described in the issue, this PR adds the condition to format/translate dynamicenum fields in Calculate Field WF Actions
This will allow to use dynamicenum in WF properly
1. Create a WF with Calculate Field action
2. Assign a DynamicField Formatted value to a Text field
3. Run the WF and check that the copied value is properly formatted/translated
> Fix #9621 - Workflows Calculate Field Actions don't translate dynamicenum fields

- include/MassUpdate.php
- include/SugarFields/Fields/Datetimecombo/RangeSearchForm.tpl
Closes #9470
As described in the issue, the calendar popup doesn't display the user defined first day of the week for the Massupdate date selector fields and range search.
This PR adds the logic to return the user fdow defined parameter and set it in the Calendar setup of the affected templates.
With this change, the calendar will always display the user defined fdow.
1. Set Monday as First day of the Week
2. Go to Contact Mass update view
3. Open the Calendar of the date field
4. Check that the first day of the week is Sunday
> Fix #9470 - Set fdow in Calendar popup date selector for range search and MassUpdate

- include/export_utils.php
Closes: https://github.com/salesagility/SuiteCRM/issues/9153
When exporting a record for any module that contains a DynamicDropdown field, the content isn't exported properly.
When using the function export of a record of any module that contains a DynamicDropdown field, it exports the keys of the field, instead of the label assigned to that key.
I feel this is an important functionality for any user working with export.
1. Add a dynamicdropdown field in a EditView of any module
2. Create a record in that module filling the DynamicDropdown field
3. Export that record and see that the value of the field isn't the expected one
> Fix #9153 - Adding dynamicenum case option for export

- .env.dist
- codeception.dist.yml
- tests/SuiteCRM/Test/Driver/WebDriver.php
- tests/acceptance.suite.yml
- tests/acceptance/_bootstrap.php
- tests/api/_bootstrap.php
- tests/install.suite.yml
- tests/unit.suite.yml
- tests/unit/_bootstrap.php
The current implementation of Codeception will load environment variables from your operating system as described here: https://docs.suitecrm.com/developer/automatedtesting/
This PR includes changes to the codeception yaml files to also attempt to load environment variables from the `.env.test` file, if it exists.
Doing so simplifies the testing setup process, removing the need to run `./vendor/bin/robo configure:tests` and change the environment itself. Most common configuration can be applied in the `.env.test` file
In addition the browser and webdriver can now be fully configured using environment variables and some unused code is removed from test/driver/WebDriver.php
Finally the bootstrap files for each test module have been adjusted to use the appropriate working directory. This …
> Codeception testing compatibility changes

- lib/Search/SearchResults.php
getRelatedId is supposed to return a string but returns null in some conditions. Return an empty string instead
Fix issue #9516 
Global Search can fail with an error message:
An unknown error has occurred while performing the search. Contact an administrator if the problem persists. More information available in the logs.
Return value of SuiteCRM\Search\SearchResults::getRelatedId() must be of the type string, null returned in /var/www/crm/sractivities/lib/Search/SearchResults.php:227
> Fix issue #9516

- include/database/DBManager.php
Call fixUpFormatting before comparing values for change/audit log
Call fixUpFormatting before comparing values for change/audit log
getDataChanges(include/database/DBManager.php) will not fix formatting before comparing values.
Depending on functionality that could be added in save hook getDataChanges can potentially be comparing values with different formats. e.g. Save hook uses retrieve: $contact->retrieve($contact->id);
Dates returned using retrieve are set in user pref format: 22-07-2022
When passed into getDataChanges the date is compared against DB format: 2022-07-22
Although date are the same the change log believes they are different: 22-07-2022 !== 2022-07-22
Create aftersave hook
Set user pref date format to non-db format
Use retrieve on bean you are saving: …
> Fix #9654 - Fix issue with different date formats being compared for change log

- modules/AOW_Actions/actions/actionSendEmail.php
The `$array` parameter passed to `implode($separator, $array)` was `null`. 
Previously in PHP 7 and less, this gave only a `Notice` or `Warning` error.
In PHP 8+ passing a null array parameter to implode now gives a `FATAL` error and PHP exits because the call matches a different overloaded function signature, expecting an `array` in first position, but it gets the `separator` which is a `string`.
Fixes bug #10033 when running on PHP 8+
PHP 7 and below only emitted a `Notice` or `Warning` to the log when you call `implode` with a `NULL` for the `$array`.
PHP 8 and above now will throw an `Exception` and exit PHP because the call signature matches a different overload and the `$separator` is passed in where it expects the `$array`.
See issue.
Basic code example proving this is `FATAL` on …
> Fix #10033 PHP Fatal error Uncaught TypeError PHP8

- modules/AOW_WorkFlow/aow_utils.php
https://github.com/salesagility/SuiteCRM/issues/9548
Issue is fully described in ticket + after analysis code base doesn’t use always default_currency_signifacant_digits, it uses user preferences.  
Make one of workflow's actions working properly with decimals. 
See https://github.com/salesagility/SuiteCRM/issues/9548
- [] Breaking change (fix or feature that would cause existing functionality to change)
> Fix #9548 - Wrong decimal precision returned in a Modify Record workflow action

- modules/AOR_Conditions/AOR_Condition.php
Fix for issue #9601 where parenthesis pairs in Report Conditions would not save the pairing data correctly. 
As part of the deployment, if admins have pre-existing reports with parentheses that they do not wish to recreate, they can run the following SQL in order to reset the necessary information on parentheses:
```
UPDATE aor_conditions SET parenthesis = 'END'
WHERE parenthesis != 'START' AND parenthesis IS NOT NULL
```
Once the above has been run, re-saving the reports with parentheses will update the conditions with the correct data. If the above SQL is not run, then the incorrect data will still be there after saving. This fix will only affect new conditions otherwise.
This solves a bug when deleting parentheses from the report conditions, where if the pairs do not match up, then the …
> Fix #9601 - Fix bug where report conditions parenthesis pairs would not save correctly.

- data/Link2.php
When adding or removing multiple relationships the beans are loaded and stored within the tempBeans array in data/Link2.php file.
When performing lots of changes at once, for example when performing bulk actions or updating target lists this leads to runaway memory usage.
This fix unsets the bean from the temporary array as it is no longer necessary to remain in storage.
Has potentially wide ranging impacts when record numbers and bulk actions increase.
1. Prepare demo data with a reasonably large number of account records (e.g. 2000)
2. Create an empty Target List
3. Attempt to bulk assign all 2000 accounts to the target list
4. Monitor the php memory usage, it should now remain at very low levels.
> Fix #9937 - Resolve high memory usage when performing bulk relationship changes

- themes/SuiteP/include/EditView/tab_panel_content.tpl
This change returns the $col variable as an integer. This is needed for the following problem:
```
Fatal error: Uncaught TypeError: Unsupported operand types: string % int
```
This change is required for people who are using the email import function. There is an issue related to this problem.
This change solves a problem with the email import function.
The current code interprets the $col variable as a string.
Set up SCRM like me:
SCRM 8.2.1
PHP 8.0.26
First, add your E-Mail to your profile. Then go into the Email menu and select any mail. After that press on "Bulk actions" and select "import".
For me: No window comes up just a message saying "An error occurred" with an HTTP 500 response.
> #9807 - Email import fix

- modules/AOR_Reports/AOR_Report.php
- modules/AOR_Reports/aor_utils.php
- modules/AOW_WorkFlow/aow_utils.php
See https://github.com/salesagility/SuiteCRM/issues/9805
When a User has set a different timezone and they attempt to report on Date fields, the CRM queries the database using a datetime value with an offset for the timezone. This provides incorrect results as the query will assume a date type has a midnight timestamp.
Users with custom timezones may have incorrect report results.
1. Set your timezone to America/Chicago in your profile.
2. Create a date field in Contacts
3. Create a Contacts record with the newly created date field set to today.
4. Create a Report on Contacts with a condition on the newly created date field equal to the period "Today"
5. The Contacts record will not be returned in the report
> Fix #9805 - Use timezone offset for datetime only

- modules/Users/User.php
Fix #10184 
Fix timezone not being set when running through silent install/ cli install
> Fix #10184 - Timezone not set on silent install

- include/SugarFields/Fields/Text/SugarFieldText.php
Fix for bug https://github.com/salesagility/SuiteCRM/issues/10139
Text fields using html editors are loading an older version of tinyMCE, this can prevent new WYSIWIG fields from displaying due to conflicts.
This is most notable on the Cases description field that is set to use an html editor by default
1. In Studio, create a WYSIWIG field for the Cases module.
2. Add the WYSIWIG field to the edit view.
3. Go to a Cases edit view.
4. The WYSIWIG field will fail to load the editor.
> Fix #10139 - HTML Text Field tinyMCE version

- include/utils/sugar_file_utils.php
Use filemode set in config when setting permissions on files
When setting file permissions 755 is applied by default and the filemode set in the config is not used.
This fix applied the filemode set in the config and if not set default back to 755.
Fixes #10131
Set file mode in config.php
Delete cache
See file permissions applied to files after they are rebuilt
> Fix #10131 - Fix issue with file mode changes not being applied on cache rebuild

- modules/AOW_WorkFlow/AOW_WorkFlow.php
Code correction.
There is no such static method present (AOW_Workflow -> Basic -> SugarBean).
Issue: https://github.com/salesagility/SuiteCRM/issues/8939
-
-
> Fix #8939 - Fix Static call to non-static method in AOW_WorkFlow

- themes/SuiteP/modules/Users/tpls/DetailView-advanced-tab-content.tpl
Changes to .tpl file for Users module
Same label is used for different fields in one of DetailView templates: 
To see the issue:
1) Go to Users list view;
2) Choose user -> Detail view -> Tab Advanced
3) Check that labels are the same for different fields: 
Fixes the issue: 
https://github.com/salesagility/SuiteCRM/issues/9021
To use correct labels in the application.
Check that correct label is in use.
> Fix #9021 - User Preferences Wrong Label.

- modules/Studio/SaveTabs.php
With Php 8 static calls require static methods.
When pressing save in the Configure Module Menu Filters editor the following fatal error has shown up:
```
[30-Mar-2023 07:54:05 UTC] PHP Fatal error:  Uncaught Error: Non-static method TabGroupHelper::saveTabGroups() cannot be called statically in /bitnami/suitecrm/modules/Studio/SaveTabs.php:48
Stack trace:
#0 /bitnami/suitecrm/include/MVC/View/SugarView.php(824): include_once()
#1 /bitnami/suitecrm/include/MVC/View/views/view.classic.php(72): SugarView->includeClassicFile()
#2 /bitnami/suitecrm/include/MVC/View/SugarView.php(210): ViewClassic->display()
#3 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(432): SugarView->process()
#4 /bitnami/suitecrm/include/MVC/Controller/SugarController.php(363): …
```
> Fix #9574 - Avoid calling method in a static way

- modules/Surveys/Lines/Lines.php
Fixes issue #5390
https://github.com/salesagility/SuiteCRM/issues/5390
We check through global request weather data comes from duplication button or not. It helps to show message where it's necessary and avoid where it is not.  
All the detail are given in the issue description.
> Fix #5390 - Redundant message when duplicating a survey

- modules/AOS_Contracts/AOS_Contracts.php
- modules/AOS_Contracts/language/en_us.lang.php
Additional label added for language pack purposes ('LBL_RENEWAL_REMINDER'). 
Function createReminder() slightly changed to use label instead plain string.
The link to an actual issue:
https://github.com/salesagility/SuiteCRM/issues/8359
For language packs purposes.
Issue has a brief description.
> Fix #8359 - Fix Contract renewal reminder title is hardcoded.

- modules/ModuleBuilder/parsers/relationships/ActivitiesRelationship.php
Solution for the issue #10205
Changed ActivitiesRelationship#buildLabels and ActivitiesRelationship#getLinkFieldDefinition parameter to match parent class parameters to avoid exceptions when using PHP8
The child class methods should contain the same parameters as the parent class. Without those changes the CRM throws an error when you try to deploy a package with a module related to Activities.
1. Create a new package in the module builder
2. Add a new custom module in the package
3. Add a relationship between the new custom module and Activities (One-To-Many)
4. Deploy the package.
The package should be deployed correctly without any failure.
> Fix #10205. Compatibility hotfix for PHP 8 in ActivitiesRelationship.php

- include/utils.php
After all the recent work done to make email configuration in SuiteCRM less of a problem, this bug is totally killing the experience. Again. A fix has been around for months, but people keep stumbling on this, comes up in the forums every week.
Please see Issue #9950 for details.
To see the bug happening, before the fix:
1. In **Admin / Email settings**, set up an SMTP account that uses TLS.
2. Check DB, value is saved in `outbound_email`, system account, field `mail_smtpssl` with value 2.
3. Open the **Admin / Email settings** screen again. Note that the dropdown changed to `None`.
4. Click Save.
5. Check DB, field is now 0.
With the fix, the dropdown should show the saved value, and saving should keep that value every time.
> Fix #9950 editing Email settings drops TLS SSL selection

- modules/AOP_Case_Updates/Case_Updates.php
Fix for issue https://github.com/salesagility/SuiteCRM/issues/10141
When a Cases record with Notes related to it is deleted, the orphaned notes will be loaded into the Case Attachements field when creating a new Cases record.
This causes a display bug when creating a Case
1. Create a Cases record
2. Add/relate a Notes record to the Cases record
3. Delete the Case
4. Click on Create Case
5. The Case Attachments field will contain the orphaned Note
> Fix #10141 - Orphaned Case Attachments bug

- modules/AOW_WorkFlow/controller.php
Added a check for when request id is set but set to blank.
Currently when trying to set up a workflow with a calculate field action under PHP the form doesnt not generate, 
1) Create a new workflow
2) Choose a module
3) Add an Action
4) Choose Calculate Field
5) The form to fill in does not appear when using PHP8
Fixes broken code under PHP8
1) Create a new workflow
2) Choose a module
3) Add an Action
4) Choose Calculate Field
5) The form to fill will appear after the fix is applied
> Fix 10115 - Wokflow Calculate Action broken under PHP8

- include/TimeDate.php
Another alternative would be to change this function
```
/**
* Format DateTime object as user time
* Note: by default does not convert TZ!
*
* @param DateTime $date
* @param boolean $tz Perform TZ conversion?
* @param User $user
* @return string
*/
public function asUserTime(DateTime $date, $tz = false, User $user = null)
{
if ($tz) {
$this->tzUser($date, $user);
}
return $date->format($this->get_time_format($user));
}
``Σ
> Fix parameter userTime method in class TimeDate

- download.php
BeanFiles global provides the path to the overwritten class for customizations.
See #8980 
Cannot download files if extending Documents Bean.
See how to reproduce in #8980 
- [ x] I have read the [**How to Contribute**](https://docs.suitecrm.com/community/contributing-code/) guidelines.
> Fix #8980 - Check beanFiles for class path

- include/SugarFields/Fields/Currency/SugarFieldCurrency.php
resolve #9880
If the decimal separator is set to a comma "," in the user's settings, an error occurs when importing currency fields that include decimals because the decimal separator is removed and the result is the value of the field multiplied by 100.
The error was caused by the filter set for importing currency fields being incorrect, as it passes the same filter as float fields, when a currency field, after the currency symbol is removed, should follow the same treatment as a decimal field. This is what has been implemented in the solution.
Prevent errors when importing currency fields with different types of decimal separators.
1. Set the decimal separator to a comma “,” in the user's settings.
2. Import a record from the Opportunities module with the Opportunity Amount set to a …
> Fix #9880 -  Error when importing currency fields with a decimal separator

- include/InlineEditing/inlineEditing.js
Closes #9412 
Adding false to the second parameter when calling the function setValueClose(). Replacing line breaks in email field isn't necessary and it produces error.
Setting this parameter, it avoids displayed a wrong value
Follow the steps defined in the issue #9412
> Fix #9412 - Wrong email value displayed when aborting an inline edition

- modules/AOW_WorkFlow/aow_utils.php
Rebased branch to hotfix from #9436
Closes #9435 
As described in the issue, the editview of a workflow is built using a Smarty template. When editing an existing workflow with an action that sets to blank an enum field which has a not blank default value, the template does not show the blank value (as expected) but the default value. 
In order to properly show the expected blank value, we hack the vardef definition overriding default value with blank value when the stored workflow value (now in $value) is blank.
This can be confusing for the users and it needs to be fixed.
1. Set any item as a default value for the dropdown Category in Documents
2. Create a Workflow based in Documents
3. Add condition of the field Category selecting the empty value
4. Save and open the workflow, check …
> Fix #9435 - Dropdown doesn't return empty selected value

- include/SugarFields/Fields/Html/DetailView.tpl
https://github.com/salesagility/SuiteCRM/issues/9563
https://github.com/salesagility/SuiteCRM/issues/9563
> Fix #9563 - HTML Type field doesn't populate

- include/TemplateHandler/TemplateHandler.php
TemplateHandler.php `buildTemplate` now gets module name via `BeanFactory` instead of directly checking `$beanList`
Validation broken on extended core beans
Extend core surveys bean & delete surveys EditView.tpl file from cache
Quick repair and rebuild
Navigate to surveys editview & save without populating any mandatory fields
> Fix #10307 retrieve object name via beanfactory

- modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php
The reports dashlet allows you to add reports to your homescreen.
If you delete a report which is used in a reports dashlet, the home screen fails to load and throws a 500 error.
Uncaught Error: Attempt to assign property "user_parameters" on bool in /var/www/modules/AOR_Reports/Dashlets/AORReportsDashlet/AORReportsDashlet.php:44
When this happens, the main workarounds are to clear user preferences or restore the deleted report.
This fix prevents the unrecoverable error and allows the user to interact with the dashlet as normal.
1. Create a test report
2. Add a reports dashlet to your dashboard
3. Assign the test report to your new reports dashlet
4. Confirm the home screen loads
5. Delete the report
6. Confirm the home screen fails to load, with the error shown above in the logs
> Fix #10410  - Check report has been loaded before setting user params

- modules/Calls/Call.php
date_end of calls is stored equals to date_start in the database if duration_hours is 0 or duration_minutes is 0
Fix issue #9985 
if the duration is, for example 0 hours 15minutes or 1 hour 0 minute, it is not taken into account to compute date_end when saving
Create a call with duration = 15mn
Look at that call in the database
date_end is equal to date_start
Create a call with duration = 15mn
Look at that call in the database
date_end is now date_start + 15 minute
> Fix issue #9985

- modules/UpgradeWizard/index.php
This PR fixes an issue that "commit" is called twice when runing the upgradewizard caused by changes in:
https://github.com/salesagility/SuiteCRM/commit/890e5997a02666b925623cd53b99a81609fa481d#diff-7c5c0ada659df5cc72d508d4b597f1882ede2ee19a4a243010a84b9a3a8b4213
The changes in the said commit introduce the variable $additionalStep in modules/Upgradewizard/index.php
This variable is initalized in line 509, but already used before in line 297 without initialization. This causes the commit.php to be executed twice.
As commit.php is secured to not run its logic twice, this bug does not have any implications for now, however future changes might cause an issue here.
- install SuiteCRM 7.14.2
- upgrade to SuiteCRM 7.14.3
**Expected result**
commit.php is only called once
**Observed behaviour** …
> Fix #10375 - Upgradewizard double commit

- modules/Administration/UpgradeHistory.php
https://github.com/salesagility/SuiteCRM/issues/1872
https://github.com/salesagility/SuiteCRM/issues/1872
> Fix #1872 - Admin - Install Module - "Back to Module Loader" shows page with header only

- metadata/emails_beansMetaData.php
The fromaddr and reply_to_addr fields in emails_text vardefs are set to 250 when they should be 255. This has caused an issue where repair and rebuild keeps trying to recreate the index on the fromaddr field in some situations.
https://github.com/salesagility/SuiteCRM/issues/10443
This looks to have been unintentionally changed in a previous MR:
https://github.com/salesagility/SuiteCRM/pull/7798
> Fix #10443 - Incorrect lengths in emails_text vardefs

- data/SugarBean.php
- Closes #10339 
This Pull Request addresses issue [#10339](https://github.com/salesagility/SuiteCRM/issues) by implementing improvements in the `cleanBean()` function in `data/SugarBean.php`. It now executes `trim` on all "name" and "varchar" type fields during save operations. A check has been added to avoid using `trim` when the field value is `null` to prevent errors in PHP.
This change is necessary to improve data consistency and cleanliness in text fields where unnecessary spaces can impact data quality and search efficiency.
1. Create or edit a record in SuiteCRM with additional spaces in "name" or "varchar" type fields in various modules, including modules created using the Module Builder and through Web forms.
2. Save these records and verify that the additional spaces have been …
> Fix #10339 - Inconsistent application of trim function on name & varchar fields

- modules/AOS_Products_Quotes/Line_Items.php
When the user sets their Significant Digits to 0 (via their Profile)
When viewing the Quotes detailview, any "0" values are stripped, leading to displaying errors
ie:
"0%" becomes "%"
"20%" becomes "2%"
1. Set sign digits to 0 in settings: Profile -> Advanced Tab -> . 
2. Go to Quotes module -> Create quote -> add service line
3. Check tax column on DetailView:
> Fix # - VAT Values display incorrectly on Quotes->Service Line Items, if Significant Figures = 0

- modules/Currencies/ListCurrency.php
If the user changes the currency on a Quote/Invoice, the generated Group Discount is not always correct.
This can be most noted when changing the Discount Amount/Percentage, the Group amount will become wildly incorrect
1. Set another currency. 
2. Create a record in the Quotes/Invoice module.
3. On Edit View try to change the currency and check the result of the Group Discount field.
> Fix #10520 - Discount Calculation incorrect when changing Currency

- modules/Emails/language/en_us.lang.php
https://github.com/salesagility/SuiteCRM/issues/8332
https://github.com/salesagility/SuiteCRM/issues/8332
> Fix #8332 - Recipient Type [Language]

- include/utils.php
- modules/AOS_PDF_Templates/templateParser.php
- modules/EmailTemplates/EmailTemplateParser.php
This PR fixes the decimal separator symbol for a decimal or float value obtained from a database not being parsed correctly when incorporated into an email template or PDF template.
To do this, a generic function is created in the PR with a parameter where you can indicate which configuration to use: the system configuration (configured by default) or the user configuration. This function will be used in the operation of parsing the PDF template or the email template.
Our proposal is to use the system configuration for sending emails and the user configuration for using the PDF template.
- #9261
- We have found that this also happens when sending an email from a workflow. Here is a video with the three use cases of incorrect behavior.
1. Create a decimal and a float fields in a contact …
> Fix #9261 - Use decimal symbol configured in system and user

- ModuleInstall/ModuleInstaller.php
Add empty check to avoid 500 error when deploying module from module loader
Add empty check after loading user preferences to avoid 500 when running php8+ 
PHP Fatal error: Uncaught TypeError: array_key_exists(): Argument https://github.com/salesagility/SuiteCRM/issues/2 ($array) must be of type array, null given
Fixes potential 500 error when deploying module from module loader if user has no global search preference set
1. Reset User Preferences
2. Avoid using functionality that will set global search user preferences e.g. global search
3. Attempt to deploy module changes from module loader
4. See 500 error in logs and module deploy fail to complete
> Fix #10450 - Add check for empty value before searching array

- modules/Surveys/Entry/Thanks.php
- modules/Surveys/language/en_us.lang.php
Fixing https://github.com/salesagility/SuiteCRM/issues/10564
Completing a survey redirects to a page where the message is only in English “Thanks for completing this survey”. The message should be displayed in the default language of the CRM.
Solution implemented:
The string have been implemented with the message that appeared at the beginning in English, therefore a variable has been created with the translate() function to collect these strings according to the language selected in the login.
Motivation: The message should be displayed in the default language of the instance.
1. Go to Surveys and create a survey with a question.
2. Send the survey and check that the message appears in the language selected in the login or the default language of the CRM.
> Fix #10564 - Thank you message in Surveys only in English

- cron.php
- modules/ModuleBuilder/parsers/views/AbstractMetaDataImplementation.php
In this PR all calls to the warning() method of the LoggerManager are located and changed to call the warn method
1. Comment out the following code to be able to call cron.php from the URL (https://github.com/salesagility/SuiteCRM/blob/hotfix/cron.php#L50C1-L53C2) 
```bash
$sapi_type = php_sapi_name();
if (substr($sapi_type, 0, 3) != 'cli') {
sugar_die("cron.php is CLI only.");
}
```
and change the following line to cause it to enter the logger:
`$cronUser = getRunningUser(); `   -->    `$cronUser = '';`
2. Set warn as log level
3. Call _cron.php_ from the browser and check that the error message is displayed in suitecrm.log
> [WARN] cron.php: can't determine running user is displayed. No cron user checks will occur
4. Configure fatal, error or other log level more restricted than _warn_ …
> Fix #10479 - Call LoggerManager's warn() method instead of warning()

- lib/Search/SearchResults.php
When a search results contain records which have related links in them; the link to the related record does not contain the correct related record id. This causes the link to go to a page with an error message of `Error retrieving record. This record may be deleted or you may not be authorized to view it.`
*NOTE* This bug is documented in Pull Request #9823 which seems to only have not been merged due to the formatting of the Pull Request itself.
This issue affects all previous versions of 7.12.x - 7.14.x
* Spin up a new SuiteCrm installation
* Go to Administration > Module Builder
* Create a new Package and Module
* Add a One-to-Many relation of your new module to Accounts
* Deploy the package
* Go to Administration > Search Settings and add your new module
* Go to the new module
* …
> Correctly find the id of related objects in search results

- include/generic/SugarWidgets/SugarWidgetSubPanelDetailViewLink.php
This PR fixes an issue where subpanels weren't correctly displaying links to related records when the user's role had "Group" view permissions. Previously, when viewing a record's subpanel, related records would show only as plain text instead of clickable links if the user had Group-level view permissions, even when they had access to those records.
The fix adds specific user permission checking logic in the subpanel code to properly evaluate the "View" permission column value, ensuring links are displayed according to the user's actual permissions.
Related issue: #10611 
This change is required to ensure proper functionality of subpanels when working with security groups and role-based permissions. The previous behavior was inconsistent with how direct relationships were handled and …
> Fix - #10611 Subpanels don't show related records links when view permission is set to "group"

- themes/SuiteP/tpls/_headerModuleList.tpl
Previously, the tooltip would only show the module name regardless of cursor position, which made it difficult to identify specific records when their names were truncated due to space constraints. This change enhances user experience by:
1. Maintaining the ability to identify record types via module name tooltip
2. Adding the ability to see full record names when they are truncated in the display
3. Making the tooltip behavior more intuitive by showing contextually relevant information based on cursor position
1. Test Recently Viewed Items:
- Navigate through different modules to populate the Recently Viewed list
- Verify module name tooltip appears when hovering over module icons
- Verify full record name tooltip appears when hovering over truncated record names
2. Test Favorites:
- Add …
> Fix #10606 - Recently viewed items tooltip shows module name instead of full record name

- modules/Surveys/Entry/Survey.php
As described in #10624 , survey response forms allowed multiple identical submissions when users repeatedly clicked the "submit" button before the usual redirection occurred.
This issue has been resolved by modifying the survey response form code. The "submit" button is now disabled upon the first activation (submission) to prevent additional clicks.
This change is required to ensure data integrity and avoid multiple identical responses from a single user. By disabling the "submit" button immediately after submission, it eliminates the possibility of repeated actions before redirection, improving the reliability of survey results.
1. Create a survey and make it public.
2. Access the survey link, respond to the survey, and try pressing the "submit" button repeatedly.
3. Verify that it is …
> Fix #10624 - Prevent Multiple Submissions on Survey Forms

- modules/ModuleBuilder/parsers/StandardField.php
Studio was not saving field properties correctly. This bug has been there for years...
1. Enter Studio
1. Enter a module (such as `Cases`)
1. Click `Fields`
1. Enter a field  (such as `Description`) to see its properties:
5. Change one of the properties, 
6. Save
7. Exit that screen to the field list
8. Enter the same field again
9. Change a different property
10. Save
11. Exit and go back in
12. Both properties should be retained, instead of the first one you changed being reverted to a default.
The bug caused each subsequent save to throw away the previously saved non-default properties. I guess for a long time people work around this by just changing one property, or repeating the saves when they were mysteriously throw away...
During tests, it might be helpful to keep separate …
> Fix #10243 - studio not saving field properties correctly

- modules/Import/views/ImportListView.php
Not my issue, see this forum thread for details:
https://community.suitecrm.com/t/php-fatal-error-uncaught-typeerror-count-argument-1-value-must-be-of-type-countable-after-upgrade-to-suite-7-14/91224
```php
[Thu Dec 14 19:43:01.002817 2023] [php:error] [pid 35371] [client 127.0.0.1:45634] 
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in modules/Import/views/ImportListView.php:131
Stack trace:
#0 modules/Import/views/view.last.php(189): ImportListView->display()
#1 modules/Import/views/view.last.php(141): ImportViewLast->getListViewTableFromFile()
#2 include/MVC/View/SugarView.php(210): ImportViewLast->display()
#3 include/MVC/Controller/SugarController.php(432): SugarView->process()
#4 …
```
> Fix non-countable error when importing CSV

- modules/DynamicFields/templates/Fields/TemplateDatetimecombo.php
Fixing https://github.com/salesagility/SuiteCRM/issues/10616
This PR solves two issues.
1. The first one, as described in the issue, it was detected that in the creation/edition view of Studio fields, for fields of type DateTime, the default values to be selected are not shown in the different languages, but always in English.
2. In the second one, it was detected that if the default value “first day of next month” is selected for a field of type “DateTime”, of any module, the instance gives an error that makes it unusable.
1. The constructor function has been added next to `$app_strings` where the labels of the dropdown are collected. Generating the dropdown.
2. Fixed the value “first of next month” that was generating problem, for “first day of next month”.
1. Go to Studio, to any …
> Fix #10616 - Default values of DateTime always in English and value “first day of next month” gives an error

- Api/V8/Service/MetaService.php
https://github.com/salesagility/SuiteCRM/issues/8632
_'Include field labels into field description'_
1. Without field labels, API consumers must manually map field names to their corresponding labels, making development more difficult. 
2. There's a slight typo, which makes additional information not available: 
- there is no such key as 'comments' 
Updated: 
Thanks!
https://github.com/salesagility/SuiteCRM/issues/8632
> Fix #8632 - API V8 /meta/fields/{moduleName} endpoint output without field labels

- Api/Core/app.php
enables the ability to update CRM Records from the V8 API
The CRM is sending CORS headers.
The CRM does not allow the PATCH method which prevents users from updating existing records within the CRM
It is not possible to update records over the API without this change,
or it is required to fix the headers upstream within a reverse proxy web server.
run a PATCH method request
> Allow End Users to use the PATCH method for the V8 API

- include/generic/SugarWidgets/SugarWidgetSubPanelRemoveButton.php
Fixing bug #10543 
Remove Security Group button was being displayed or hidden depending on permission on list and not edit.
The behavior between the remove button in the subpanel and removing groups from list view was not consistent.
1.Create a user U1
2.Create a security group SG1
3.Create a Role R1 and assign group permission on every action of every module
4.Assign SG1 and R1 to U1
5.Login with user U1 and check that it can not see the remove button on the subpanels
6. Change permission for R1 on Edit Security Groups and check that now the button is shown.
> Fix #10543 - Remove Security Groups button on subpanelsbased on EditView

- include/Sugar_Smarty.php
Fixes #10147, #10396 - Smarty unregistered function deprecated notice
Reduce unnecessary logging
See that there are no longer any deprecation notices logged on PHP functions used with smarty template files
> Fix #10147, #10396 - Smarty unregistered function deprecated notice

- modules/Emails/EmailsControllerActionGetFromFields.php
- modules/Emails/EmailsDataAddressCollector.php
- modules/Emails/include/ComposeView/EmailsComposeView.js
Email signatures will sometimes remove the email thread when replying to an email. 
Email signatures elements that are on an email thread will also be replaced by the users email signature.
Email signatures will occasionally not be added to the email if the From fields have not been fully loaded in.
From fields can fail to load due to php82 fatal errors
```
PHP Fatal error:  Uncaught TypeError: EmailsDataAddressCollector::getFillDataAddressArray(): Argument #7 ($prependSignature) must be of type bool, null given, called in /var/www/SuiteCRM/modules/Emails/EmailsDataAddressCollector.php on line 673 and defined in /var/www/SuiteCRM/modules/Emails/EmailsDataAddressCollector.php:753
PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, bool given in …
```
> Fix #10570 - Email Signature Compose View Issues
